swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector Policy Management Certificates API
schemes:
- https
tags:
- name: Policy Management Certificates
paths:
  /certificates:
    get:
      tags:
      - Policy Management Certificates
      summary: Microsoft Azure Retrieves The Set Of Certificates Used To Express Policy For The Current Tenant
      operationId: microsoftAzurePolicycertificatesGet
      parameters:
      - $ref: '#/parameters/ApiVersionParameter'
      responses:
        '200':
          description: An RFC7519 JSON Web Token structure containing an RFC7517 JsonWebKeySet which contains the certificates used to validate policy changes
          schema:
            $ref: '#/definitions/PolicyCertificatesResponse'
        default:
          description: Error response describing why the operation failed
          schema:
            $ref: '#/definitions/CloudError'
      x-ms-examples:
        Get PolicyCertificates:
          $ref: ./examples/Get_PolicyCertificates.json
      description: Needs a more full description created.
  /certificates:add:
    post:
      tags:
      - Policy Management Certificates
      summary: Microsoft Azure Adds A New Attestation Policy Certificate To The Set Of Policy Management Certificates
      operationId: microsoftAzurePolicycertificatesAdd
      parameters:
      - $ref: '#/parameters/ApiVersionParameter'
      - name: policyCertificateToAdd
        in: body
        description: An RFC7519 JSON Web Token whose body is an RFC7517 JSON Web Key object. The RFC7519 JWT must be signed with one of the existing signing certificates
        required: true
        schema:
          $ref: '#/definitions/JsonWebToken'
      responses:
        '200':
          description: An RFC7519 JSON Web Token structure containing an RFC7517 JsonWebKeySet which contains the certificates used to validate policy changes
          schema:
            $ref: '#/definitions/PolicyCertificatesModifyResponse'
        default:
          description: Error response describing why the operation failed
          schema:
            $ref: '#/definitions/CloudError'
      x-ms-examples:
        Add PolicyCertificate:
          $ref: ./examples/Add_PolicyCertificate.json
      description: Needs a more full description created.
  /certificates:remove:
    post:
      tags:
      - Policy Management Certificates
      summary: Microsoft Azure Removes The Specified Policy Management Certificate Note That The Final Policy Management Certificate Cannot Be Removed
      operationId: microsoftAzurePolicycertificatesRemove
      parameters:
      - $ref: '#/parameters/ApiVersionParameter'
      - name: policyCertificateToRemove
        in: body
        description: An RFC7519 JSON Web Token whose body is an AttestationCertificateManagementBody object. The RFC7519 JWT must be signed with one of the existing signing certificates
        required: true
        schema:
          $ref: '#/definitions/JsonWebToken'
      responses:
        '200':
          description: An RFC7519 JSON Web Token structure containing an RFC7517 JsonWebKeySet which contains the certificates used to validate policy changes
          schema:
            $ref: '#/definitions/PolicyCertificatesModifyResponse'
        default:
          description: Error response describing why the operation failed
          schema:
            $ref: '#/definitions/CloudError'
      x-ms-examples:
        Remove PolicyCertificate:
          $ref: ./examples/Remove_PolicyCertificate.json
      description: Needs a more full description created.
definitions:
  PolicyCertificatesResponse:
    type: object
    description: The response to an attestation policy management API
    properties:
      token:
        description: An RFC7519 JSON Web Token structure containing a PolicyCertificatesResults object which contains the certificates used to validate policy changes
        $ref: '#/definitions/JsonWebToken'
  CloudError:
    x-ms-external: true
    properties:
      error:
        $ref: '#/definitions/CloudErrorBody'
    description: An error response from Attestation.
  CloudErrorBody:
    x-ms-external: true
    properties:
      code:
        type: string
        description: An identifier for the error. Codes are invariant and are intended to be consumed programmatically.
      message:
        type: string
        description: A message describing the error, intended to be suitable for displaying in a user interface.
    description: An error response from Attestation.
  PolicyCertificatesModifyResponse:
    type: object
    description: The response to an attestation policy management API
    properties:
      token:
        description: An RFC7519 JSON Web Token structure whose body is a PolicyCertificatesModificationResult object.
        $ref: '#/definitions/JsonWebToken'
  JsonWebToken:
    description: An RFC 7519 Json Web Token
    type: string
    pattern: '[A-Za-z0-9_-]+\.[A-Za-z0-9_-]*\.[A-Za-z0-9_-]*'
    externalDocs:
      description: JSON Web Token RFC
      url: https://tools.ietf.org/html/rfc7519
parameters:
  ApiVersionParameter:
    name: api-version
    in: query
    required: true
    type: string
    description: Client API version. Current version is 2022-09-01-preview
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
