swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector GuestAgents API
schemes:
- https
tags:
- name: GuestAgents
paths:
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ConnectedVMwarevSphere/virtualMachines/{virtualMachineName}/guestAgents/{name}
  : put:
      tags:
      - GuestAgents
      operationId: microsoftAzureGuestagentsCreate
      description: Create Or Update GuestAgent.
      summary: Microsoft Azure Implements Guestagent Put Method
      x-ms-examples:
        CreateGuestAgent:
          $ref: ./examples/CreateGuestAgent.json
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/subscriptionId'
      - $ref: '#/parameters/resourceGroupName'
      - in: path
        name: virtualMachineName
        required: true
        type: string
        description: Name of the vm.
      - in: path
        name: name
        required: true
        type: string
        description: Name of the guestAgents.
      - $ref: '#/parameters/api-version'
      - in: body
        name: body
        description: Request payload.
        schema:
          $ref: '#/definitions/GuestAgent'
      responses:
        '200':
          description: Arm resource update successful.
          schema:
            $ref: '#/definitions/GuestAgent'
        '201':
          description: Created
          schema:
            $ref: '#/definitions/GuestAgent'
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: ../../../../../common-types/resource-management/v3/types.json#/definitions/ErrorResponse
      x-ms-long-running-operation: true
      x-ms-long-running-operation-options:
        final-state-via: azure-async-operation
    get:
      tags:
      - GuestAgents
      operationId: microsoftAzureGuestagentsGet
      summary: Microsoft Azure Gets Guestagent
      description: Implements GuestAgent GET method.
      x-ms-examples:
        GetGuestAgent:
          $ref: ./examples/GetGuestAgent.json
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/subscriptionId'
      - $ref: '#/parameters/resourceGroupName'
      - in: path
        name: virtualMachineName
        required: true
        type: string
        description: Name of the vm.
      - in: path
        name: name
        required: true
        type: string
        description: Name of the GuestAgent.
      - $ref: '#/parameters/api-version'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/GuestAgent'
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: ../../../../../common-types/resource-management/v3/types.json#/definitions/ErrorResponse
    delete:
      tags:
      - GuestAgents
      operationId: microsoftAzureGuestagentsDelete
      summary: Microsoft Azure Deletes An Guestagent
      description: Implements GuestAgent DELETE method.
      x-ms-examples:
        DeleteGuestAgent:
          $ref: ./examples/DeleteGuestAgent.json
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/subscriptionId'
      - $ref: '#/parameters/resourceGroupName'
      - in: path
        name: virtualMachineName
        required: true
        type: string
        description: Name of the vm.
      - in: path
        name: name
        required: true
        type: string
        description: Name of the GuestAgent.
      - $ref: '#/parameters/api-version'
      responses:
        '200':
          description: Success
        '202':
          description: Accepted
          headers:
            Location:
              type: string
        '204':
          description: No Content
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: ../../../../../common-types/resource-management/v3/types.json#/definitions/ErrorResponse
      x-ms-long-running-operation: true
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ConnectedVMwarevSphere/virtualMachines/{virtualMachineName}/guestAgents
  : get:
      tags:
      - GuestAgents
      operationId: microsoftAzureGuestagentsList
      summary: Microsoft Azure Implements Get Guestagent In A Vm
      description: Returns the list of GuestAgent of the given vm.
      x-ms-examples:
        GuestAgentListByVm:
          $ref: ./examples/GuestAgent_ListByVm.json
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/subscriptionId'
      - $ref: '#/parameters/resourceGroupName'
      - in: path
        name: virtualMachineName
        required: true
        type: string
        description: Name of the vm.
      - $ref: '#/parameters/api-version'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/GuestAgentList'
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: ../../../../../common-types/resource-management/v3/types.json#/definitions/ErrorResponse
      x-ms-pageable:
        nextLinkName: nextLink
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ScVmm/virtualMachines/{virtualMachineName}/guestAgents/{guestAgentName}
  : put:
      tags:
      - GuestAgents
      operationId: microsoftAzureGuestagentsCreate
      description: Create Or Update GuestAgent.
      summary: Microsoft Azure Implements Guestagent Put Method
      x-ms-examples:
        CreateGuestAgent:
          $ref: ./examples/CreateGuestAgent.json
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/SubscriptionIdParameter'
      - $ref: '#/parameters/ResourceGroupNameParameter'
      - in: path
        name: virtualMachineName
        required: true
        type: string
        description: Name of the vm.
      - in: path
        name: guestAgentName
        required: true
        type: string
        description: Name of the guestAgents.
      - $ref: '#/parameters/ApiVersionParameter'
      - in: body
        name: body
        description: Request payload.
        schema:
          $ref: '#/definitions/GuestAgent_2'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/GuestAgent_2'
        '201':
          description: Created
          schema:
            $ref: '#/definitions/GuestAgent_2'
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: '#/definitions/ErrorResponse'
      x-ms-long-running-operation: true
      x-ms-long-running-operation-options:
        final-state-via: azure-async-operation
    get:
      tags:
      - GuestAgents
      operationId: microsoftAzureGuestagentsGet
      summary: Microsoft Azure Gets Guestagent
      description: Implements GuestAgent GET method.
      x-ms-examples:
        GetGuestAgent:
          $ref: ./examples/GetGuestAgent.json
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/SubscriptionIdParameter'
      - $ref: '#/parameters/ResourceGroupNameParameter'
      - in: path
        name: virtualMachineName
        required: true
        type: string
        description: Name of the vm.
      - in: path
        name: guestAgentName
        required: true
        type: string
        description: Name of the GuestAgent.
      - $ref: '#/parameters/ApiVersionParameter'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/GuestAgent_2'
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: '#/definitions/ErrorResponse'
    delete:
      tags:
      - GuestAgents
      operationId: microsoftAzureGuestagentsDelete
      summary: Microsoft Azure Deletes An Guestagent
      description: Implements GuestAgent DELETE method.
      x-ms-examples:
        DeleteGuestAgent:
          $ref: ./examples/DeleteGuestAgent.json
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/SubscriptionIdParameter'
      - $ref: '#/parameters/ResourceGroupNameParameter'
      - in: path
        name: virtualMachineName
        required: true
        type: string
        description: Name of the vm.
      - in: path
        name: guestAgentName
        required: true
        type: string
        description: Name of the GuestAgent.
      - $ref: '#/parameters/ApiVersionParameter'
      responses:
        '200':
          description: Success
        '202':
          description: Accepted
        '204':
          description: No Content
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: '#/definitions/ErrorResponse'
      x-ms-long-running-operation: true
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ScVmm/virtualMachines/{virtualMachineName}/guestAgents
  : get:
      tags:
      - GuestAgents
      operationId: microsoftAzureGuestagentsListbyvm
      summary: Microsoft Azure Implements Get Guestagent In A Vm
      description: Returns the list of GuestAgent of the given vm.
      x-ms-examples:
        GuestAgentListByVm:
          $ref: ./examples/GuestAgent_ListByVm.json
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/SubscriptionIdParameter'
      - $ref: '#/parameters/ResourceGroupNameParameter'
      - in: path
        name: virtualMachineName
        required: true
        type: string
        description: Name of the vm.
      - $ref: '#/parameters/ApiVersionParameter'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/GuestAgentList'
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: '#/definitions/ErrorResponse'
      x-ms-pageable:
        nextLinkName: nextLink
definitions:
  ErrorDefinition:
    description: Error definition.
    type: object
    properties:
      code:
        description: Service specific error code which serves as the substatus for the HTTP error code.
        type: string
        readOnly: true
      message:
        description: Description of the error.
        type: string
        readOnly: true
      details:
        description: Internal error details.
        type: array
        items:
          $ref: '#/definitions/ErrorDefinition'
        x-ms-identifiers: []
        readOnly: true
  ErrorResponse:
    description: Error response.
    type: object
    properties:
      error:
        $ref: '#/definitions/ErrorDefinition'
        description: The error details.
  GuestAgentProperties:
    description: Describes the properties of a Virtual Machine Guest Agent.
    type: object
    properties:
      uuid:
        description: Gets or sets a unique identifier for this resource.
        type: string
        readOnly: true
      credentials:
        description: Username / Password Credentials to provision guest agent.
        $ref: '#/definitions/GuestCredential'
      privateLinkScopeResourceId:
        type: string
        format: arm-id
        description: The resource id of the private link scope this machine is assigned to, if any.
      httpProxyConfig:
        description: HTTP Proxy configuration for the VM.
        $ref: '#/definitions/HttpProxyConfiguration'
      provisioningAction:
        description: Gets or sets the guest agent provisioning action.
        $ref: '#/definitions/ProvisioningAction'
        type: string
      status:
        description: Gets or sets the guest agent status.
        type: string
        readOnly: true
      customResourceName:
        description: Gets the name of the corresponding resource in Kubernetes.
        type: string
        readOnly: true
      statuses:
        description: The resource status information.
        readOnly: true
        type: array
        items:
          $ref: '#/definitions/ResourceStatus'
        x-ms-identifiers:
        - type
      provisioningState:
        $ref: '#/definitions/ResourceProvisioningState'
        description: Gets the provisioning state.
        readOnly: true
  ResourceProvisioningState:
    type: string
    description: The current deployment state of resource.
    enum:
    - Succeeded
    - Failed
    - Canceled
    - Provisioning
    - Updating
    - Deleting
    - Accepted
    - Created
    x-ms-enum:
      name: ProvisioningState
      modelAsString: true
  HttpProxyConfiguration:
    description: HTTP Proxy configuration for the VM.
    type: object
    properties:
      httpsProxy:
        description: Gets or sets httpsProxy url.
        type: string
  ProvisioningAction:
    description: Defines the different types of operations for guest agent.
    enum:
    - install
    - uninstall
    - repair
    type: string
    x-ms-enum:
      modelAsString: true
      name: ProvisioningAction
  ResourceStatus:
    description: The resource status information.
    type: object
    properties:
      type:
        description: The type of the condition.
        type: string
        readOnly: true
      status:
        description: Status of the condition.
        type: string
        readOnly: true
      reason:
        description: The reason for the condition's status.
        type: string
        readOnly: true
      message:
        description: A human readable message indicating details about the status.
        type: string
        readOnly: true
      severity:
        description: Severity with which to treat failures of this type of condition.
        type: string
        readOnly: true
      lastUpdatedAt:
        description: The last update time for this condition.
        type: string
        format: date-time
        readOnly: true
  GuestAgent_2:
    description: Defines the GuestAgent.
    required:
    - properties
    type: object
    allOf:
    - $ref: ../../../../../common-types/resource-management/v3/types.json#/definitions/ProxyResource
      description: The resource model definition for an Azure Resource Manager proxy resource. It will have everything other than required location and tags.
    properties:
      properties:
        x-ms-client-flatten: true
        description: Resource properties.
        $ref: '#/definitions/GuestAgentProperties_2'
    x-ms-azure-resource: true
  GuestAgentProperties_2:
    description: Defines the resource properties.
    type: object
    properties:
      uuid:
        description: Gets or sets a unique identifier for this resource.
        type: string
        readOnly: true
      credentials:
        description: Username / Password Credentials to provision guest agent.
        $ref: '#/definitions/GuestCredential'
      httpProxyConfig:
        description: HTTP Proxy configuration for the VM.
        $ref: '#/definitions/HttpProxyConfiguration'
      provisioningAction:
        description: Gets or sets the guest agent provisioning action.
        $ref: '#/definitions/ProvisioningAction'
        type: string
      status:
        description: Gets or sets the guest agent status.
        type: string
        readOnly: true
      customResourceName:
        description: Gets the name of the corresponding resource in Kubernetes.
        type: string
        readOnly: true
      provisioningState:
        description: Gets or sets the provisioning state.
        type: string
        readOnly: true
  GuestAgentList:
    description: List of GuestAgent.
    type: object
    properties:
      nextLink:
        description: Url to follow for getting next page of GuestAgent.
        type: string
      value:
        description: Array of GuestAgent
        type: array
        items:
          $ref: '#/definitions/GuestAgent'
    required:
    - value
  GuestCredential:
    description: Username / Password Credentials to connect to guest.
    type: object
    properties:
      username:
        description: Gets or sets username to connect with the guest.
        type: string
      password:
        description: Gets or sets the password to connect with the guest.
        type: string
        x-ms-mutability:
        - create
        - update
        x-ms-secret: true
  GuestAgent:
    description: Defines the GuestAgent.
    required:
    - properties
    type: object
    allOf:
    - $ref: ../../../../../common-types/resource-management/v5/types.json#/definitions/ProxyResource
      description: The resource model definition for an Azure Resource Manager proxy resource. It will have everything other than required location and tags.
    properties:
      properties:
        x-ms-client-flatten: true
        description: Resource properties.
        $ref: '#/definitions/GuestAgentProperties'
    x-ms-azure-resource: true
parameters:
  ApiVersionParameter:
    name: api-version
    in: query
    required: true
    type: string
    description: The API version to be used with the HTTP request (e.g. YYYY-MM-DD).
  resourceGroupName:
    in: path
    name: resourceGroupName
    description: The Resource Group Name.
    required: true
    type: string
    x-ms-parameter-location: method
  SubscriptionIdParameter:
    name: subscriptionId
    in: path
    required: true
    type: string
    description: The Azure subscription ID. This is a GUID-formatted string (e.g. 00000000-0000-0000-0000-000000000000).
  subscriptionId:
    in: path
    name: subscriptionId
    description: The Subscription ID.
    required: true
    type: string
  api-version:
    in: query
    name: api-version
    description: Client Api Version.
    required: true
    type: string
  ResourceGroupNameParameter:
    name: resourceGroupName
    in: path
    required: true
    type: string
    description: The name of the resource group.
    x-ms-parameter-location: method
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
