openapi: 3.2.0
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector Nsp Access Rules Reconcile API
tags:
- name: NspAccessRulesReconcile
paths:
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/networkSecurityPerimeters/{networkSecurityPerimeterName}/profiles/{profileName}/accessRules/{accessRuleName}/reconcile
  : parameters:
    - $ref: ./network.json#/parameters/SubscriptionIdParameter
    - $ref: '#/components/parameters/ResourceGroupNameParameter'
    - $ref: '#/components/parameters/NetworkSecurityPerimeterNameParameter'
    - $ref: '#/components/parameters/ProfileNameParameter'
    - $ref: '#/components/parameters/AccessRuleNameParameter'
    - $ref: ./network.json#/parameters/ApiVersionParameter
    post:
      tags:
      - NspAccessRulesReconcile
      operationId: microsoftAzureNspaccessrulesreconcilePost
      description: Reconcile NSP access rules
      responses:
        '200':
          description: Reconcile NSP access rule.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NspAccessRuleReconcile'
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                $ref: ./network.json#/definitions/CloudError
      x-ms-examples:
        NspAccessRuleReconcile:
          $ref: ./examples/NspAccessRuleReconcile.json
      summary: Microsoft Azure Post Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Network Networksecurityperimeters Networksecurityperimetername Profiles Profilename Accessrules Accessrulename Reconcile
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NspAccessRuleReconcile'
        description: Parameters for NSP access rule reconcile
        required: true
components:
  parameters:
    ProfileNameParameter:
      name: profileName
      in: path
      required: true
      description: The name of the NSP profile.
      x-ms-parameter-location: method
      schema:
        type: string
    NetworkSecurityPerimeterNameParameter:
      name: networkSecurityPerimeterName
      in: path
      required: true
      description: The name of the network security perimeter.
      x-ms-parameter-location: method
      schema:
        type: string
    ResourceGroupNameParameter:
      name: resourceGroupName
      in: path
      required: true
      description: The name of the resource group.
      x-ms-parameter-location: method
      schema:
        type: string
    AccessRuleNameParameter:
      name: accessRuleName
      in: path
      required: true
      description: The name of the NSP access rule.
      x-ms-parameter-location: method
      schema:
        type: string
  schemas:
    NspAccessRuleReconcile:
      type: object
      properties: {}
      description: Request object for NSP reconcile.
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/components/parameters/Endpoint'
