swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector SentShare API
schemes:
- https
tags:
- name: SentShare
paths:
  /sentShares:
    get:
      tags:
      - SentShare
      summary: Microsoft Azure Get A List Of Sent Shares
      description: List sent shares
      operationId: microsoftAzureSentsharesList
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/referenceName'
      - $ref: '#/parameters/api-version'
      - $ref: '#/parameters/filter'
      - $ref: '#/parameters/orderby'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/SentShareList'
        default:
          description: Default error response.
          schema:
            $ref: '#/definitions/PurviewShareError'
          headers:
            x-ms-error-code:
              description: The error code
              type: string
      x-ms-examples:
        SentShares_List:
          $ref: ./examples/SentShares_List.json
      x-ms-pageable:
        nextLinkName: nextLink
  /sentShares/{sentShareId}:
    get:
      tags:
      - SentShare
      summary: Microsoft Azure Get A Sent Share By Guid
      description: Get a sent share
      operationId: microsoftAzureSentsharesGet
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/sentShareId'
      - $ref: '#/parameters/api-version'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/SentShare'
        default:
          description: Default error response.
          schema:
            $ref: '#/definitions/PurviewShareError'
          headers:
            x-ms-error-code:
              description: The error code
              type: string
      x-ms-examples:
        SentShares_Get:
          $ref: ./examples/SentShares_Get.json
        SentShares_GetAdlsGen2Account:
          $ref: ./examples/SentShares_GetAdlsGen2Account.json
        SentShares_GetBlobAccount:
          $ref: ./examples/SentShares_GetBlobAccount.json
    put:
      tags:
      - SentShare
      summary: Microsoft Azure Create Or Replace A Sent Share
      description: Create or replace a sent share
      operationId: microsoftAzureSentsharesCreateorreplace
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/sentShareId'
      - $ref: '#/parameters/api-version'
      - in: body
        name: sentShare
        description: The sent share to create or replace.
        required: true
        schema:
          $ref: '#/definitions/SentShare'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/SentShare'
          headers:
            Operation-Location:
              description: The URL to track the status of the long running operation.
              type: string
        '201':
          description: Success
          schema:
            $ref: '#/definitions/SentShare'
          headers:
            Operation-Location:
              description: The URL to track the status of the long running operation.
              type: string
        default:
          description: Default error response.
          schema:
            $ref: '#/definitions/PurviewShareError'
          headers:
            x-ms-error-code:
              description: The error code
              type: string
      x-ms-examples:
        SentShares_CreateOrReplace:
          $ref: ./examples/SentShares_CreateOrReplace.json
        SentShares_CreateOrReplaceAdlsGen2Account:
          $ref: ./examples/SentShares_CreateOrReplaceAdlsGen2Account.json
        SentShares_CreateOrReplaceBlobAccount:
          $ref: ./examples/SentShares_CreateOrReplaceBlobAccount.json
      x-ms-long-running-operation: true
    delete:
      tags:
      - SentShare
      summary: Microsoft Azure Deletes A Sent Share
      description: Delete a sent share
      operationId: microsoftAzureSentsharesDelete
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/sentShareId'
      - $ref: '#/parameters/api-version'
      responses:
        '202':
          description: Accepted
          schema:
            $ref: '#/definitions/OperationResponse'
          headers:
            Operation-Location:
              description: The URL to track the status of the long running operation.
              type: string
        default:
          description: Default error response.
          schema:
            $ref: '#/definitions/PurviewShareError'
          headers:
            x-ms-error-code:
              description: The error code
              type: string
      x-ms-examples:
        SentShares_Delete:
          $ref: ./examples/SentShares_Delete.json
      x-ms-long-running-operation: true
definitions:
  PurviewShareError:
    description: The purview share error model.
    required:
    - error
    type: object
    properties:
      error:
        $ref: '#/definitions/PurviewShareErrorInfo'
  OperationStatus:
    description: States for long running operations.
    enum:
    - Running
    - TransientFailure
    - Succeeded
    - Failed
    - NotStarted
    type: string
    x-ms-enum:
      name: OperationStatus
      modelAsString: true
      values:
      - value: Running
        description: The long running operation is in 'Running' state
        name: Long running operation state is 'Running'
      - value: TransientFailure
        description: The long running operation hit a transient failure
        name: Long running operation state is 'TransientFailure'
      - value: Succeeded
        description: The long running operation is in 'Succeeded' state
        name: Long running operation state is 'Succeeded'
      - value: Failed
        description: The long running operation is in 'Failed' state
        name: Long running operation state is 'Failed'
      - value: NotStarted
        description: The long running operation has not started
        name: Long running operation state is 'NotStarted'
  ProxyResource:
    description: Base data transfer object implementation for proxy resources.
    type: object
    properties:
      id:
        description: The unique id of the resource.
        type: string
        readOnly: true
      type:
        description: Type of the resource.
        type: string
        readOnly: true
  ShareKind:
    description: Defines the supported types for share.
    enum:
    - InPlace
    type: string
    x-ms-enum:
      name: ShareKind
      modelAsString: true
      values:
      - value: InPlace
        description: The type of share is in-place sharing
        name: In place share kind
  SentShareList:
    description: List of sent shares.
    required:
    - value
    type: object
    properties:
      nextLink:
        format: url
        description: The Url of next result page.
        type: string
      value:
        description: Collection of items of type SentShare
        type: array
        items:
          $ref: '#/definitions/SentShare'
  SentShare:
    description: A sent share data transfer object.
    required:
    - shareKind
    type: object
    allOf:
    - $ref: '#/definitions/ProxyResource'
    properties:
      shareKind:
        $ref: '#/definitions/ShareKind'
    discriminator: shareKind
  PurviewShareErrorInfo:
    description: The purview share error body model.
    required:
    - code
    - message
    type: object
    properties:
      code:
        description: Code of the error
        type: string
      details:
        description: Nested details of the error model
        type: array
        items:
          $ref: '#/definitions/PurviewShareErrorInfo'
      message:
        description: Message of the error
        type: string
      target:
        description: Target of the error
        type: string
  OperationResponse:
    description: Response for long running operation.
    required:
    - status
    type: object
    properties:
      endTime:
        format: date-time
        description: End time of the long running operation. Represented in the standard date-time format as defined by [RFC 3339](https://www.rfc-editor.org/rfc/rfc3339)
        type: string
      error:
        $ref: '#/definitions/PurviewShareErrorInfo'
      id:
        description: Job id of the long running operation
        type: string
      startTime:
        format: date-time
        description: Start time of the long running operation. Represented in the standard date-time format as defined by [RFC 3339](https://www.rfc-editor.org/rfc/rfc3339)
        type: string
      status:
        $ref: '#/definitions/OperationStatus'
parameters:
  referenceName:
    in: query
    name: referenceName
    description: A name that references a data store.
    required: true
    type: string
    x-ms-parameter-location: method
  sentShareId:
    in: path
    name: sentShareId
    description: Id of the sent share
    required: true
    type: string
    maxLength: 36
    pattern: ^(?:\{{0,1}(?:[0-9a-fA-F]){8}-(?:[0-9a-fA-F]){4}-(?:[0-9a-fA-F]){4}-(?:[0-9a-fA-F]){4}-(?:[0-9a-fA-F]){12}\}{0,1})$
    x-ms-parameter-location: method
  orderby:
    in: query
    name: orderby
    description: Sorts the results using OData syntax
    type: string
    x-ms-parameter-location: method
  filter:
    in: query
    name: filter
    description: Filters the results using OData syntax
    type: string
    x-ms-parameter-location: method
  api-version:
    in: query
    name: api-version
    description: The api version to use
    required: true
    type: string
    x-ms-parameter-location: client
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
