swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector ScanResult API
schemes:
- https
tags:
- name: ScanResult
paths:
  /datasources/{dataSourceName}/scans/{scanName}/runs/{runId}:
    put:
      tags:
      - ScanResult
      description: Runs the scan
      operationId: microsoftAzureScanresultRunscan
      produces:
      - application/json
      parameters:
      - in: path
        name: dataSourceName
        required: true
        type: string
      - in: path
        name: scanName
        required: true
        type: string
      - in: path
        name: runId
        required: true
        type: string
      - in: query
        name: scanLevel
        type: string
        enum:
        - Full
        - Incremental
        x-ms-enum:
          name: ScanLevelType
          modelAsString: true
      - $ref: '#/parameters/api-version'
      responses:
        '202':
          description: Success
          schema:
            $ref: '#/definitions/OperationResponse'
        default:
          description: An error response received from the Scanning Service
          schema:
            $ref: '#/definitions/ErrorResponseModel'
      x-ms-examples:
        ScanResult_RunScan:
          $ref: ./examples/ScanResult_RunScan.json
      summary: Microsoft Azure Put Datasources Datasourcename Scans Scanname Runs Runid
  /datasources/{dataSourceName}/scans/{scanName}/runs/{runId}/:cancel:
    post:
      tags:
      - ScanResult
      description: Cancels a scan
      operationId: microsoftAzureScanresultCancelscan
      produces:
      - application/json
      parameters:
      - in: path
        name: dataSourceName
        required: true
        type: string
      - in: path
        name: scanName
        required: true
        type: string
      - in: path
        name: runId
        required: true
        type: string
      - $ref: '#/parameters/api-version'
      responses:
        '202':
          description: Success
          schema:
            $ref: '#/definitions/OperationResponse'
        default:
          description: An error response received from the Scanning Service
          schema:
            $ref: '#/definitions/ErrorResponseModel'
      x-ms-examples:
        ScanResult_CancelScan:
          $ref: ./examples/ScanResult_CancelScan.json
      summary: Microsoft Azure Post Datasources Datasourcename Scans Scanname Runs Runid :cancel
  /datasources/{dataSourceName}/scans/{scanName}/runs:
    get:
      tags:
      - ScanResult
      description: Lists the scan history of a scan
      operationId: microsoftAzureScanresultListscanhistory
      produces:
      - application/json
      parameters:
      - in: path
        name: dataSourceName
        required: true
        type: string
      - in: path
        name: scanName
        required: true
        type: string
      - $ref: '#/parameters/api-version'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/ScanHistoryList'
        default:
          description: An error response received from the Scanning Service
          schema:
            $ref: '#/definitions/ErrorResponseModel'
      x-ms-examples:
        ScanResult_ListScanHistory:
          $ref: ./examples/ScanResult_ListScanHistory.json
      x-ms-pageable:
        nextLinkName: nextLink
      summary: Microsoft Azure Get Datasources Datasourcename Scans Scanname Runs
definitions:
  ErrorInfo:
    type: object
    properties:
      code:
        type: string
      message:
        type: string
      target:
        type: string
      details:
        type: array
        items:
          $ref: '#/definitions/ErrorInfo'
  ScanDiagnostics:
    type: object
    properties:
      notifications:
        type: array
        items:
          $ref: '#/definitions/Notification'
      exceptionCountMap:
        type: object
        additionalProperties:
          format: int32
          type: integer
        readOnly: true
  ErrorResponseModel:
    type: object
    properties:
      error:
        allOf:
        - $ref: '#/definitions/ErrorModel'
  ErrorModel:
    type: object
    properties:
      code:
        type: string
      message:
        type: string
      target:
        type: string
      details:
        type: array
        items:
          $ref: '#/definitions/ErrorModel'
  ScanHistoryList:
    required:
    - value
    type: object
    properties:
      value:
        type: array
        items:
          $ref: '#/definitions/ScanResult'
      nextLink:
        type: string
      count:
        format: int64
        type: integer
  Notification:
    type: object
    properties:
      message:
        type: string
      code:
        format: int32
        type: integer
  ScanResult:
    type: object
    properties:
      parentId:
        type: string
        readOnly: true
      id:
        type: string
        readOnly: true
      resourceId:
        type: string
        readOnly: true
      status:
        type: string
        readOnly: true
      assetsDiscovered:
        format: int64
        type: integer
        readOnly: true
      assetsClassified:
        format: int64
        type: integer
        readOnly: true
      diagnostics:
        allOf:
        - $ref: '#/definitions/ScanDiagnostics'
        readOnly: true
      startTime:
        format: date-time
        type: string
        readOnly: true
      queuedTime:
        format: date-time
        type: string
        readOnly: true
      pipelineStartTime:
        format: date-time
        type: string
        readOnly: true
      endTime:
        format: date-time
        type: string
        readOnly: true
      scanRulesetVersion:
        format: int32
        type: integer
        readOnly: true
      scanRulesetType:
        enum:
        - Custom
        - System
        type: string
        readOnly: true
        x-ms-enum:
          name: ScanRulesetType
          modelAsString: true
      scanLevelType:
        enum:
        - Full
        - Incremental
        type: string
        readOnly: true
        x-ms-enum:
          name: ScanLevelType
          modelAsString: true
      errorMessage:
        type: string
        readOnly: true
      error:
        allOf:
        - $ref: '#/definitions/ErrorModel'
        readOnly: true
      runType:
        type: string
        readOnly: true
      dataSourceType:
        enum:
        - None
        - AzureSubscription
        - AzureResourceGroup
        - AzureSynapseWorkspace
        - AzureSynapse
        - AdlsGen1
        - AdlsGen2
        - AmazonAccount
        - AmazonS3
        - AmazonSql
        - AzureCosmosDb
        - AzureDataExplorer
        - AzureFileService
        - AzureSqlDatabase
        - AmazonPostgreSql
        - AzurePostgreSql
        - SqlServerDatabase
        - AzureSqlDatabaseManagedInstance
        - AzureSqlDataWarehouse
        - AzureMySql
        - AzureStorage
        - Teradata
        - Oracle
        - SapS4Hana
        - SapEcc
        - PowerBI
        type: string
        readOnly: true
        x-ms-enum:
          name: DataSourceType
          modelAsString: true
  OperationResponse:
    type: object
    properties:
      scanResultId:
        format: uuid
        type: string
      startTime:
        format: date-time
        type: string
      endTime:
        format: date-time
        type: string
      status:
        enum:
        - Accepted
        - InProgress
        - TransientFailure
        - Succeeded
        - Failed
        - Canceled
        type: string
        x-ms-enum:
          name: OperationStatus
          modelAsString: true
      error:
        allOf:
        - $ref: '#/definitions/ErrorInfo'
parameters:
  api-version:
    in: query
    name: api-version
    description: The api version to use.
    required: true
    type: string
    x-ms-client-name: ApiVersion
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
