swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector DnsForwardingRulesets API
schemes:
- https
tags:
- name: DnsForwardingRulesets
paths:
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/dnsForwardingRulesets/{dnsForwardingRulesetName}
  : put:
      tags:
      - DnsForwardingRulesets
      operationId: microsoftAzureDnsforwardingrulesetsCreateorupdate
      description: Creates or updates a DNS forwarding ruleset.
      parameters:
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/ResourceGroupNameParameter
      - $ref: '#/parameters/DnsForwardingRulesetNameParameter'
      - name: parameters
        in: body
        required: true
        schema:
          $ref: '#/definitions/DnsForwardingRuleset'
        description: Parameters supplied to the CreateOrUpdate operation.
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/ApiVersionParameter
      - $ref: '#/parameters/IfMatchParameter'
      - $ref: '#/parameters/IfNoneMatchParameter'
      responses:
        '200':
          description: The DNS forwarding ruleset has been updated.
          schema:
            $ref: '#/definitions/DnsForwardingRuleset'
        '201':
          description: The DNS forwarding ruleset has been created.
          schema:
            $ref: '#/definitions/DnsForwardingRuleset'
        '202':
          description: The operation to upsert DNS forwarding ruleset has been accepted and will complete asynchronously.
        default:
          description: Default response. It will be deserialized as per the Error definition.
          schema:
            $ref: '#/definitions/CloudError'
      x-ms-long-running-operation: true
      x-ms-examples:
        Upsert DNS forwarding ruleset:
          $ref: ./examples/DnsForwardingRuleset_Put.json
      summary: Microsoft Azure Put Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Network Dnsforwardingrulesets Dnsforwardingrulesetname
    patch:
      tags:
      - DnsForwardingRulesets
      operationId: microsoftAzureDnsforwardingrulesetsUpdate
      description: Updates a DNS forwarding ruleset.
      parameters:
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/ResourceGroupNameParameter
      - $ref: '#/parameters/DnsForwardingRulesetNameParameter'
      - name: parameters
        in: body
        required: true
        schema:
          $ref: '#/definitions/DnsForwardingRulesetPatch'
        description: Parameters supplied to the Update operation.
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/ApiVersionParameter
      - $ref: '#/parameters/IfMatchParameter'
      responses:
        '200':
          description: The DNS forwarding ruleset has been updated.
          schema:
            $ref: '#/definitions/DnsForwardingRuleset'
        '202':
          description: The operation to update DNS forwarding ruleset has been accepted and will complete asynchronously.
        default:
          description: Default response. It will be deserialized as per the Error definition.
          schema:
            $ref: '#/definitions/CloudError'
      x-ms-long-running-operation: true
      x-ms-examples:
        Update DNS forwarding ruleset:
          $ref: ./examples/DnsForwardingRuleset_Patch.json
      summary: Microsoft Azure Patch Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Network Dnsforwardingrulesets Dnsforwardingrulesetname
    delete:
      tags:
      - DnsForwardingRulesets
      operationId: microsoftAzureDnsforwardingrulesetsDelete
      description: 'Deletes a DNS forwarding ruleset. WARNING: This operation cannot be undone. All forwarding rules within the ruleset will be deleted.'
      parameters:
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/ResourceGroupNameParameter
      - $ref: '#/parameters/DnsForwardingRulesetNameParameter'
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/ApiVersionParameter
      - $ref: '#/parameters/IfMatchParameter'
      responses:
        '200':
          description: The DNS forwarding ruleset has been deleted.
        '202':
          description: The operation to delete DNS forwarding ruleset has been accepted and will complete asynchronously.
        '204':
          description: The DNS forwarding ruleset was not found.
        default:
          description: Default response. It will be deserialized as per the Error definition.
          schema:
            $ref: '#/definitions/CloudError'
      x-ms-long-running-operation: true
      x-ms-examples:
        Delete DNS forwarding ruleset:
          $ref: ./examples/DnsForwardingRuleset_Delete.json
      summary: Microsoft Azure Delete Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Network Dnsforwardingrulesets Dnsforwardingrulesetname
    get:
      tags:
      - DnsForwardingRulesets
      operationId: microsoftAzureDnsforwardingrulesetsGet
      description: Gets a DNS forwarding ruleset properties.
      parameters:
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/ResourceGroupNameParameter
      - $ref: '#/parameters/DnsForwardingRulesetNameParameter'
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/ApiVersionParameter
      responses:
        '200':
          description: The DNS forwarding ruleset was found.
          schema:
            $ref: '#/definitions/DnsForwardingRuleset'
        default:
          description: Default response. It will be deserialized as per the Error definition.
          schema:
            $ref: '#/definitions/CloudError'
      x-ms-examples:
        Retrieve DNS forwarding ruleset:
          $ref: ./examples/DnsForwardingRuleset_Get.json
      summary: Microsoft Azure Get Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Network Dnsforwardingrulesets Dnsforwardingrulesetname
  /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/dnsForwardingRulesets:
    get:
      tags:
      - DnsForwardingRulesets
      operationId: microsoftAzureDnsforwardingrulesetsListbyresourcegroup
      description: Lists DNS forwarding rulesets within a resource group.
      parameters:
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/ResourceGroupNameParameter
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/ApiVersionParameter
      - $ref: '#/parameters/TopParameter'
      responses:
        '200':
          description: List of DNS forwarding rulesets in the resource group.
          schema:
            $ref: '#/definitions/DnsForwardingRulesetListResult'
        default:
          description: Default response. It will be deserialized as per the Error definition.
          schema:
            $ref: '#/definitions/CloudError'
      x-ms-pageable:
        nextLinkName: nextLink
      x-ms-examples:
        List DNS forwarding rulesets by resource group:
          $ref: ./examples/DnsForwardingRuleset_ListByResourceGroup.json
      summary: Microsoft Azure Get Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Network Dnsforwardingrulesets
  /subscriptions/{subscriptionId}/providers/Microsoft.Network/dnsForwardingRulesets:
    get:
      tags:
      - DnsForwardingRulesets
      operationId: microsoftAzureDnsforwardingrulesetsList
      description: Lists DNS forwarding rulesets in all resource groups of a subscription.
      parameters:
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/ApiVersionParameter
      - $ref: '#/parameters/TopParameter'
      responses:
        '200':
          description: List of DNS forwarding rulesets in the subscription.
          schema:
            $ref: '#/definitions/DnsForwardingRulesetListResult'
        default:
          description: Default response. It will be deserialized as per the Error definition.
          schema:
            $ref: '#/definitions/CloudError'
      x-ms-pageable:
        nextLinkName: nextLink
      x-ms-examples:
        List DNS forwarding rulesets by subscription:
          $ref: ./examples/DnsForwardingRuleset_ListBySubscription.json
      summary: Microsoft Azure Get Subscriptions Subscriptionid Providers Microsoft Network Dnsforwardingrulesets
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/virtualNetworks/{virtualNetworkName}/listDnsForwardingRulesets
  : post:
      tags:
      - DnsForwardingRulesets
      operationId: microsoftAzureDnsforwardingrulesetsListbyvirtualnetwork
      description: Lists DNS forwarding ruleset resource IDs attached to a virtual network.
      parameters:
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/ResourceGroupNameParameter
      - $ref: '#/parameters/VirtualNetworkNameParameter'
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/ApiVersionParameter
      - $ref: '#/parameters/TopParameter'
      responses:
        '200':
          description: List of DNS forwarding ruleset resource IDs and virtual network link resource IDs attached to the virtual network.
          schema:
            $ref: '#/definitions/VirtualNetworkDnsForwardingRulesetListResult'
        default:
          description: Default response. It will be deserialized as per the Error definition.
          schema:
            $ref: '#/definitions/CloudError'
      x-ms-pageable:
        nextLinkName: nextLink
      x-ms-examples:
        List DNS forwarding rulesets by virtual network:
          $ref: ./examples/DnsForwardingRuleset_ListByVirtualNetwork.json
      summary: Microsoft Azure Post Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Network Virtualnetworks Virtualnetworkname Listdnsforwardingrulesets
definitions:
  VirtualNetworkLinkSubResourceProperties:
    description: The reference to the virtual network link that associates between the DNS forwarding ruleset and virtual network.
    type: object
    properties:
      virtualNetworkLink:
        description: The reference to the virtual network link.
        $ref: '#/definitions/SubResource'
  VirtualNetworkDnsForwardingRuleset:
    description: Reference to DNS forwarding ruleset and associated virtual network link.
    type: object
    properties:
      id:
        type: string
        description: DNS Forwarding Ruleset Resource ID.
      properties:
        description: Properties of the virtual network link sub-resource reference.
        $ref: '#/definitions/VirtualNetworkLinkSubResourceProperties'
        x-ms-client-flatten: true
  DnsForwardingRuleset:
    description: Describes a DNS forwarding ruleset.
    type: object
    properties:
      etag:
        description: ETag of the DNS forwarding ruleset.
        type: string
        readOnly: true
      properties:
        description: Properties of the DNS forwarding ruleset.
        $ref: '#/definitions/DnsForwardingRulesetProperties'
        x-ms-client-flatten: true
      systemData:
        $ref: ../../../../../common-types/resource-management/v2/types.json#/definitions/systemData
        description: Metadata pertaining to creation and last modification of the resource.
        readOnly: true
    allOf:
    - $ref: ../../../../../common-types/resource-management/v2/types.json#/definitions/TrackedResource
  CloudError:
    description: An error message
    type: object
    properties:
      error:
        description: The error message body
        $ref: '#/definitions/CloudErrorBody'
    x-ms-external: true
  SubResource:
    description: Reference to another ARM resource.
    type: object
    properties:
      id:
        type: string
        description: Resource ID.
    x-ms-azure-resource: true
  ProvisioningState:
    description: The current provisioning state of the resource.
    type: string
    enum:
    - Creating
    - Updating
    - Deleting
    - Succeeded
    - Failed
    - Canceled
    x-ms-enum:
      name: ProvisioningState
      modelAsString: true
  VirtualNetworkDnsForwardingRulesetListResult:
    description: The response to an enumeration operation on Virtual Network DNS Forwarding Ruleset.
    type: object
    properties:
      value:
        description: Enumeration of the Virtual Network DNS Forwarding Ruleset.
        type: array
        items:
          $ref: '#/definitions/VirtualNetworkDnsForwardingRuleset'
      nextLink:
        description: The continuation token for the next page of results.
        type: string
        readOnly: true
  CloudErrorBody:
    description: The body of an error message
    type: object
    properties:
      code:
        description: The error code
        type: string
      message:
        description: A description of what caused the error
        type: string
      target:
        description: The target resource of the error message
        type: string
      details:
        description: Extra error information
        type: array
        items:
          $ref: '#/definitions/CloudErrorBody'
        x-ms-identifiers: []
    x-ms-external: true
  DnsForwardingRulesetListResult:
    description: The response to an enumeration operation on DNS forwarding rulesets.
    type: object
    properties:
      value:
        description: Enumeration of the DNS forwarding rulesets.
        type: array
        items:
          $ref: '#/definitions/DnsForwardingRuleset'
      nextLink:
        description: The continuation token for the next page of results.
        type: string
        readOnly: true
  DnsForwardingRulesetPatch:
    description: Describes a DNS forwarding ruleset PATCH operation.
    type: object
    properties:
      tags:
        type: object
        additionalProperties:
          type: string
        x-ms-mutability:
        - read
        - create
        - update
        description: Tags for DNS Resolver.
  DnsForwardingRulesetProperties:
    description: Represents the properties of a DNS forwarding ruleset.
    type: object
    properties:
      dnsResolverOutboundEndpoints:
        description: The reference to the DNS resolver outbound endpoints that are used to route DNS queries matching the forwarding rules in the ruleset to the target DNS servers.
        type: array
        items:
          $ref: '#/definitions/SubResource'
      provisioningState:
        description: The current provisioning state of the DNS forwarding ruleset. This is a read-only property and any attempt to set this value will be ignored.
        $ref: '#/definitions/ProvisioningState'
        readOnly: true
      resourceGuid:
        description: The resourceGuid for the DNS forwarding ruleset.
        type: string
        readOnly: true
parameters:
  IfNoneMatchParameter:
    name: If-None-Match
    in: header
    required: false
    type: string
    x-ms-client-name: IfNoneMatch
    description: Set to '*' to allow a new resource to be created, but to prevent updating an existing resource. Other values will be ignored.
    x-ms-parameter-location: method
  IfMatchParameter:
    name: If-Match
    in: header
    required: false
    type: string
    x-ms-client-name: IfMatch
    description: ETag of the resource. Omit this value to always overwrite the current resource. Specify the last-seen ETag value to prevent accidentally overwriting any concurrent changes.
    x-ms-parameter-location: method
  VirtualNetworkNameParameter:
    name: virtualNetworkName
    in: path
    required: true
    type: string
    description: The name of the virtual network.
    x-ms-parameter-location: method
  TopParameter:
    name: $top
    in: query
    required: false
    type: integer
    format: int32
    description: The maximum number of results to return. If not specified, returns up to 100 results.
    x-ms-parameter-location: method
  DnsForwardingRulesetNameParameter:
    name: dnsForwardingRulesetName
    in: path
    required: true
    type: string
    description: The name of the DNS forwarding ruleset.
    x-ms-parameter-location: method
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
