openapi: 3.2.0
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector Service Principal App Role Assigned To API
tags:
- name: ServicePrincipalAppRoleAssignedTo
paths:
  /{tenantID}/servicePrincipals/{objectId}/appRoleAssignedTo:
    get:
      tags:
      - ServicePrincipalAppRoleAssignedTo
      operationId: microsoftAzureServiceprincipalsListapproleassignedto
      summary: Microsoft Azure Principals Users, Groups, And Service Principals That Are Assigned To This Service Principal
      parameters:
      - name: objectId
        in: path
        required: true
        description: The object ID of the service principal for which to get owners.
        schema:
          type: string
      - $ref: '#/components/parameters/ApiVersionParameter'
      - $ref: '#/components/parameters/tenantIDInPath'
      responses:
        '200':
          description: OK. The operation was successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppRoleAssignmentListResult'
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GraphError'
      x-ms-pageable:
        nextLinkName: odata.nextLink
      description: Needs a more full description created.
components:
  schemas:
    OdataError:
      type: object
      properties:
        code:
          type: string
          description: Error code.
        message:
          type: object
          x-ms-client-flatten: true
          $ref: '#/components/schemas/ErrorMessage'
          description: Error Message.
      description: Active Directory OData error information.
    AppRoleAssignment:
      type: object
      allOf:
      - $ref: '#/components/schemas/DirectoryObject'
      properties:
        id:
          type: string
          description: The role id that was assigned to the principal. This role must be declared by the target resource application resourceId in its appRoles property.
        principalDisplayName:
          type: string
          description: The display name of the principal that was granted the access.
        principalId:
          type: string
          description: The unique identifier (objectId) for the principal being granted the access.
        principalType:
          type: string
          description: The type of principal. This can either be "User", "Group" or "ServicePrincipal".
        resourceDisplayName:
          type: string
          description: The display name of the resource to which the assignment was made.
        resourceId:
          type: string
          description: The unique identifier (objectId) for the target resource (service principal) for which the assignment was made.
      x-ms-discriminator-value: AppRoleAssignment
      description: AppRoleAssignment information.
    ErrorMessage:
      type: object
      properties:
        value:
          type: string
          x-ms-client-name: message
          description: Error message value.
      description: Active Directory error message.
    AppRoleAssignmentListResult:
      type: object
      properties:
        value:
          type: array
          items:
            $ref: '#/components/schemas/AppRoleAssignment'
          description: A collection of AppRoleAssignment.
        odata.nextLink:
          type: string
          description: The URL to get the next set of results.
      description: AppRoleAssignment list operation result.
    DirectoryObject:
      type: object
      discriminator:
        propertyName: objectType
      properties:
        objectId:
          type: string
          description: The object ID.
          readOnly: true
        objectType:
          type: string
          description: The object type.
        deletionTimestamp:
          type:
          - string
          - 'null'
          format: date-time
          description: The time at which the directory object was deleted.
          readOnly: true
      required:
      - objectType
      additionalProperties:
        type: object
      description: Represents an Azure Active Directory object.
    GraphError:
      type: object
      properties:
        odata.error:
          type: object
          x-ms-client-flatten: true
          $ref: '#/components/schemas/OdataError'
          description: A Graph API error.
      description: Active Directory error information.
  parameters:
    tenantIDInPath:
      name: tenantID
      in: path
      required: true
      description: The tenant ID.
      x-ms-parameter-location: client
      schema:
        type: string
    ApiVersionParameter:
      name: api-version
      in: query
      required: true
      description: Client API version.
      schema:
        type: string
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/components/parameters/Endpoint'
