swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector PrivateEndpointConnection Resource API
schemes:
- https
tags:
- name: PrivateEndpointConnection Resource
paths:
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.StorageSync/storageSyncServices/{storageSyncServiceName}/privateEndpointConnections
  : get:
      parameters:
      - $ref: ../../../../../common-types/resource-management/v5/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../common-types/resource-management/v5/types.json#/parameters/ResourceGroupNameParameter
      - $ref: ../../../../../common-types/resource-management/v5/types.json#/parameters/ApiVersionParameter
      - name: storageSyncServiceName
        in: path
        description: Name of Storage Sync Service resource.
        required: true
        type: string
      tags:
      - PrivateEndpointConnection Resource
      operationId: microsoftAzurePrivateendpointconnectionsListbystoragesyncservice
      description: Get a PrivateEndpointConnection List.
      x-ms-examples:
        PrivateEndpointConnections_ListByStorageSyncService:
          $ref: ./examples/PrivateEndpointConnections_ListByStorageSyncService.json
      responses:
        '200':
          description: Array of Sync Group resources in Storage Sync Service
          schema:
            $ref: ../../../../../common-types/resource-management/v5/privatelinks.json#/definitions/PrivateEndpointConnectionListResult
          headers:
            x-ms-request-id:
              description: request id.
              type: string
            x-ms-correlation-request-id:
              description: correlation request id.
              type: string
        default:
          description: Error message indicating why the operation failed.
          schema:
            $ref: '#/definitions/StorageSyncError'
      x-ms-pageable:
        nextLinkName: null
      summary: Microsoft Azure Get Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Storagesync Storagesyncservices Storagesyncservicename Privateendpointconnections
definitions:
  StorageSyncError:
    type: object
    description: Error type
    properties:
      error:
        $ref: '#/definitions/StorageSyncApiError'
        description: Error details of the given entry.
      innererror:
        $ref: '#/definitions/StorageSyncApiError'
        description: Error details of the given entry.
  StorageSyncErrorDetails:
    type: object
    description: Error Details object.
    properties:
      code:
        type: string
        description: Error code of the given entry.
      message:
        type: string
        description: Error message of the given entry.
      target:
        type: string
        description: Target of the given entry.
      requestUri:
        type: string
        description: Request URI of the given entry.
      exceptionType:
        type: string
        description: Exception type of the given entry.
      httpMethod:
        type: string
        description: HTTP method of the given entry.
      hashedMessage:
        type: string
        description: Hashed message of the given entry.
      httpErrorCode:
        type: string
        description: HTTP error code of the given entry.
  StorageSyncInnerErrorDetails:
    type: object
    description: Error Details object.
    properties:
      callStack:
        type: string
        description: Call stack of the error.
      message:
        type: string
        description: Error message of the error.
      innerException:
        type: string
        description: Exception of the inner error.
      innerExceptionCallStack:
        type: string
        description: Call stack of the inner error.
  StorageSyncApiError:
    type: object
    description: Error type
    properties:
      code:
        type: string
        description: Error code of the given entry.
      message:
        type: string
        description: Error message of the given entry.
      target:
        type: string
        description: Target of the given error entry.
      details:
        $ref: '#/definitions/StorageSyncErrorDetails'
        description: Error details of the given entry.
      innererror:
        $ref: '#/definitions/StorageSyncInnerErrorDetails'
        description: Inner error details of the given entry.
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
