swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector Managed APIs API
schemes:
- https
tags:
- name: Managed APIs
paths:
  /subscriptions/{subscriptionId}/providers/Microsoft.Web/locations/{location}/managedApis:
    get:
      tags:
      - Managed APIs
      summary: Microsoft Azure Lists Managed Apis
      operationId: microsoftAzureManagedapisList
      description: Gets a list of managed APIs
      x-ms-examples:
        List all managed APIs:
          $ref: ./examples/managedApisList.json
      parameters:
      - $ref: '#/parameters/locationParameter'
      - $ref: '#/parameters/subscriptionIdParameter'
      - $ref: '#/parameters/apiVersionParameter'
      responses:
        '200':
          description: A list of managed APIs
          schema:
            $ref: '#/definitions/ManagedApiDefinitionCollection'
  /subscriptions/{subscriptionId}/providers/Microsoft.Web/locations/{location}/managedApis/{apiName}:
    get:
      tags:
      - Managed APIs
      summary: Microsoft Azure Gets Managed Api
      operationId: microsoftAzureManagedapisGet
      description: Gets a managed API
      x-ms-examples:
        Get a managed API:
          $ref: ./examples/managedApisGet.json
      parameters:
      - $ref: '#/parameters/subscriptionIdParameter'
      - $ref: '#/parameters/locationParameter'
      - $ref: '#/parameters/apiNameParameter'
      - $ref: '#/parameters/apiVersionParameter'
      responses:
        '200':
          description: A managed API definition
          schema:
            $ref: '#/definitions/ManagedApiDefinition'
definitions:
  ApiResourceBackendService:
    type: object
    description: The API backend service
    additionalProperties: false
    properties:
      serviceUrl:
        type: string
        description: The service URL
  WsdlService:
    type: object
    description: The service with name and endpoint names
    additionalProperties: false
    required:
    - qualifiedName
    properties:
      qualifiedName:
        description: The service's qualified name
        type: string
      endpointQualifiedNames:
        type: array
        description: List of the endpoints' qualified names
        items:
          type: string
  ManagedApiDefinitionCollection:
    description: A list of managed API definitions
    type: object
    properties:
      value:
        description: Collection of managed APIs
        type: array
        items:
          $ref: '#/definitions/ManagedApiDefinition'
  TagsDictionary:
    type: object
    description: Resource tags
    additionalProperties:
      type: string
    example:
      SampleTagName: SampleTagValue
  ResourceDefinition:
    description: A resource
    type: object
    additionalProperties: false
    properties:
      id:
        description: Resource id
        type: string
        readOnly: true
      name:
        description: Resource name
        type: string
        readOnly: true
      type:
        description: Resource type
        type: string
        readOnly: true
      location:
        description: Resource location
        type: string
      etag:
        description: Resource ETag
        type: string
      tags:
        $ref: '#/definitions/TagsDictionary'
    x-ms-azure-resource: true
  ApiResourceProperties:
    type: object
    description: API resource properties
    additionalProperties: false
    properties:
      name:
        type: string
      connectionParameters:
        description: Connection parameters
        type: object
        additionalProperties:
          $ref: '#/definitions/ConnectionParameter'
      metadata:
        $ref: '#/definitions/ApiResourceMetadata'
      runtimeUrls:
        type: array
        description: Runtime URLs
        items:
          type: string
      generalInformation:
        $ref: '#/definitions/ApiResourceGeneralInformation'
      capabilities:
        type: array
        description: The managed API capabilities
        items:
          type: string
      swagger:
        type: object
        description: The JSON representation of the swagger
      backendService:
        $ref: '#/definitions/ApiResourceBackendService'
      policies:
        $ref: '#/definitions/ApiResourcePolicies'
      apiDefinitionUrl:
        type: string
        description: URL where the swagger can be downloaded from
      apiDefinitions:
        $ref: '#/definitions/ApiResourceDefinitions'
  WsdlImportMethod:
    type: string
    description: The WSDL import method
    enum:
    - NotSpecified
    - SoapToRest
    - SoapPassThrough
    x-ms-enum:
      name: WsdlImportMethod
      modelAsString: true
  ApiResourcePolicies:
    type: object
    description: Describes the API policies either as embedded content or as a link to uploaded content
    additionalProperties: false
    properties:
      content:
        type: string
        description: API level policies as XML
      contentLink:
        type: string
        description: Link to the JSON of the policies
  ManagedApiDefinition:
    type: object
    description: A managed API definition
    additionalProperties: false
    properties:
      properties:
        $ref: '#/definitions/ApiResourceProperties'
    allOf:
    - $ref: '#/definitions/ResourceDefinition'
  ConnectionParameter:
    description: Connection provider parameters
    type: object
    properties:
      type:
        description: Type of the parameter
        enum:
        - string
        - securestring
        - secureobject
        - int
        - bool
        - object
        - array
        - oauthSetting
        - connection
        type: string
        x-ms-enum:
          name: ConnectionParameterType
          modelAsString: false
      oAuthSettings:
        $ref: '#/definitions/ApiOAuthSettings'
  ApiOAuthSettings:
    description: OAuth settings for the connection provider
    type: object
    properties:
      identityProvider:
        description: Identity provider
        type: string
      clientId:
        description: Resource provider client id
        type: string
      clientSecret:
        description: Client Secret needed for OAuth
        type: string
      scopes:
        description: OAuth scopes
        type: array
        items:
          type: string
      redirectUrl:
        description: Url
        type: string
      properties:
        type: object
        description: Read only properties for this oauth setting.
      customParameters:
        description: OAuth parameters key is the name of parameter
        type: object
        additionalProperties:
          $ref: '#/definitions/ApiOAuthSettingsParameter'
  ApiResourceGeneralInformation:
    type: object
    description: General information about the API
    additionalProperties: false
    properties:
      iconUrl:
        type: string
        description: The icon URL
      displayName:
        type: string
        description: Display name
      description:
        type: string
        description: The API description
      termsOfUseUrl:
        type: string
        description: URL to the Terms of Use
      releaseTag:
        type: string
        description: Release tag
  ApiResourceDefinitions:
    type: object
    description: API Definitions
    additionalProperties: false
    properties:
      originalSwaggerUrl:
        type: string
        description: The original swagger URL
      modifiedSwaggerUrl:
        type: string
        description: The modified swagger URL
  ApiType:
    type: string
    description: The API type
    enum:
    - NotSpecified
    - Rest
    - Soap
    x-ms-enum:
      name: ApiType
      modelAsString: true
  ApiOAuthSettingsParameter:
    description: OAuth settings for the API
    type: object
    properties:
      value:
        description: Value of the setting
        type: string
      options:
        type: object
        description: Options available to this parameter
      uiDefinition:
        type: object
        description: UI definitions per culture as caller can specify the culture
  ApiResourceMetadata:
    type: object
    additionalProperties: false
    properties:
      source:
        type: string
        description: The source
      brandColor:
        type: string
        description: Brand color
      hideKey:
        type: string
        description: Hide key
      tags:
        $ref: '#/definitions/TagsDictionary'
      apiType:
        $ref: '#/definitions/ApiType'
      wsdlService:
        $ref: '#/definitions/WsdlService'
      wsdlImportMethod:
        $ref: '#/definitions/WsdlImportMethod'
      connectionType:
        type: string
        description: The connection type
parameters:
  locationParameter:
    name: location
    description: The location
    in: path
    required: true
    type: string
    x-ms-parameter-location: method
  apiNameParameter:
    type: string
    name: apiName
    description: API name
    in: path
    required: true
    x-ms-parameter-location: method
  apiVersionParameter:
    name: api-version
    in: query
    description: API Version
    required: true
    type: string
    x-ms-parameter-location: method
  subscriptionIdParameter:
    name: subscriptionId
    in: path
    description: Subscription Id
    required: true
    type: string
    x-ms-parameter-location: method
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
