openapi: 3.2.0
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector Patch Schedules API
tags:
- name: PatchSchedules
paths:
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Cache/Redis/{cacheName}/patchSchedules
  : get:
      tags:
      - PatchSchedules
      operationId: microsoftAzurePatchschedulesListbyredisresource
      description: Gets all patch schedules in the specified redis cache (there is only one).
      x-ms-examples:
        RedisCachePatchSchedulesList:
          $ref: ./examples/RedisCachePatchSchedulesList.json
      parameters:
      - $ref: '#/components/parameters/ApiVersionParameter'
      - $ref: '#/components/parameters/SubscriptionIdParameter'
      - name: resourceGroupName
        in: path
        required: true
        description: The name of the resource group.
        schema:
          type: string
      - name: cacheName
        in: path
        required: true
        description: The name of the Redis cache.
        schema:
          type: string
      responses:
        '200':
          description: Successfully got the current patch schedules
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RedisPatchScheduleListResult'
      x-ms-pageable:
        nextLinkName: nextLink
      summary: Microsoft Azure Get Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Cache Redis Cachename Patchschedules
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Cache/Redis/{name}/patchSchedules/{default}
  : put:
      tags:
      - PatchSchedules
      operationId: microsoftAzurePatchschedulesCreateorupdate
      x-ms-examples:
        RedisCachePatchSchedulesCreateOrUpdate:
          $ref: ./examples/RedisCachePatchSchedulesCreateOrUpdate.json
      description: Create or replace the patching schedule for Redis cache (requires Premium SKU).
      parameters:
      - name: resourceGroupName
        in: path
        required: true
        description: The name of the resource group.
        schema:
          type: string
      - name: name
        in: path
        required: true
        description: The name of the Redis cache.
        schema:
          type: string
      - name: default
        in: path
        required: true
        description: Default string modeled as parameter for auto generation to work correctly.
        x-ms-enum:
          name: defaultName
          modelAsString: true
        schema:
          type: string
          enum:
          - default
      - $ref: '#/components/parameters/ApiVersionParameter'
      - $ref: '#/components/parameters/SubscriptionIdParameter'
      responses:
        '200':
          description: The patch schedule was successfully updated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RedisPatchSchedule'
        '201':
          description: The patch schedule was successfully created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RedisPatchSchedule'
      summary: Microsoft Azure Put Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Cache Redis Name Patchschedules Default
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RedisPatchSchedule'
        description: Parameters to set the patching schedule for Redis cache.
        required: true
    delete:
      tags:
      - PatchSchedules
      operationId: microsoftAzurePatchschedulesDelete
      x-ms-examples:
        RedisCachePatchSchedulesDelete:
          $ref: ./examples/RedisCachePatchSchedulesDelete.json
      description: Deletes the patching schedule of a redis cache (requires Premium SKU).
      parameters:
      - name: resourceGroupName
        in: path
        required: true
        description: The name of the resource group.
        schema:
          type: string
      - name: name
        in: path
        required: true
        description: The name of the redis cache.
        schema:
          type: string
      - name: default
        in: path
        required: true
        description: Default string modeled as parameter for auto generation to work correctly.
        x-ms-enum:
          name: defaultName
          modelAsString: true
        schema:
          type: string
          enum:
          - default
      - $ref: '#/components/parameters/ApiVersionParameter'
      - $ref: '#/components/parameters/SubscriptionIdParameter'
      responses:
        '200':
          description: Success.
        '204':
          description: Success.
      summary: Microsoft Azure Delete Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Cache Redis Name Patchschedules Default
    get:
      tags:
      - PatchSchedules
      operationId: microsoftAzurePatchschedulesGet
      x-ms-examples:
        RedisCachePatchSchedulesGet:
          $ref: ./examples/RedisCachePatchSchedulesGet.json
      description: Gets the patching schedule of a redis cache (requires Premium SKU).
      parameters:
      - name: resourceGroupName
        in: path
        required: true
        description: The name of the resource group.
        schema:
          type: string
      - name: name
        in: path
        required: true
        description: The name of the redis cache.
        schema:
          type: string
      - name: default
        in: path
        required: true
        description: Default string modeled as parameter for auto generation to work correctly.
        x-ms-enum:
          name: defaultName
          modelAsString: true
        schema:
          type: string
          enum:
          - default
      - $ref: '#/components/parameters/ApiVersionParameter'
      - $ref: '#/components/parameters/SubscriptionIdParameter'
      responses:
        '200':
          description: Response of get patch schedules.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RedisPatchSchedule'
      summary: Microsoft Azure Get Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Cache Redis Name Patchschedules Default
components:
  schemas:
    ScheduleEntries:
      properties:
        scheduleEntries:
          x-ms-client-name: ScheduleEntries
          type: array
          items:
            $ref: '#/components/schemas/ScheduleEntry'
          description: List of patch schedules for a Redis cache.
      required:
      - scheduleEntries
      description: List of patch schedules for a Redis cache.
    RedisPatchSchedule:
      properties:
        properties:
          x-ms-client-flatten: true
          $ref: '#/components/schemas/ScheduleEntries'
          description: List of patch schedules for a Redis cache.
      required:
      - properties
      allOf:
      - $ref: '#/components/schemas/ProxyResource'
      description: Response to put/get patch schedules for Redis cache.
    RedisPatchScheduleListResult:
      properties:
        value:
          type: array
          items:
            $ref: '#/components/schemas/RedisPatchSchedule'
          description: Results of the list patch schedules operation.
        nextLink:
          type: string
          readOnly: true
          description: Link for next page of results.
      description: The response of list patch schedules Redis operation.
    Resource:
      description: The Resource definition.
      properties:
        id:
          readOnly: true
          type: string
          description: Resource ID.
        name:
          readOnly: true
          type: string
          description: Resource name.
        type:
          readOnly: true
          type: string
          description: Resource type.
      x-ms-azure-resource: true
    ScheduleEntry:
      properties:
        dayOfWeek:
          type: string
          description: Day of the week when a cache can be patched.
          enum:
          - Monday
          - Tuesday
          - Wednesday
          - Thursday
          - Friday
          - Saturday
          - Sunday
          - Everyday
          - Weekend
          x-ms-enum:
            name: DayOfWeek
            modelAsString: false
        startHourUtc:
          type: integer
          format: int32
          description: Start hour after which cache patching can start.
        maintenanceWindow:
          type: string
          format: duration
          description: 'ISO8601 timespan specifying how much time cache patching can take. '
      required:
      - dayOfWeek
      - startHourUtc
      description: Patch schedule entry for a Premium Redis Cache.
    ProxyResource:
      description: The resource model definition for a ARM proxy resource. It will have everything other than required location and tags
      allOf:
      - $ref: '#/components/schemas/Resource'
  parameters:
    ApiVersionParameter:
      name: api-version
      in: query
      required: true
      description: Client Api Version.
      schema:
        type: string
    SubscriptionIdParameter:
      name: subscriptionId
      in: path
      required: true
      description: Gets subscription credentials which uniquely identify the Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.
      schema:
        type: string
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/components/parameters/Endpoint'
