swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector ServiceRunners API
schemes:
- https
tags:
- name: ServiceRunners
paths:
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DevTestLab/labs/{labName}/servicerunners/{name}
  : get:
      tags:
      - ServiceRunners
      description: Get service runner.
      operationId: microsoftAzureServicerunnersGet
      parameters:
      - $ref: '#/parameters/subscriptionId'
      - $ref: '#/parameters/resourceGroupName'
      - name: labName
        in: path
        description: The name of the lab.
        required: true
        type: string
      - name: name
        in: path
        description: The name of the service runner.
        required: true
        type: string
      - $ref: '#/parameters/api-version'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ServiceRunner'
        default:
          description: BadRequest
          schema:
            $ref: '#/definitions/CloudError'
      x-ms-examples:
        ServiceRunners_Get:
          $ref: ./examples/ServiceRunners_Get.json
      summary: Microsoft Azure Get Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Devtestlab Labs Labname Servicerunners Name
    put:
      tags:
      - ServiceRunners
      description: Create or replace an existing service runner.
      operationId: microsoftAzureServicerunnersCreateorupdate
      parameters:
      - $ref: '#/parameters/subscriptionId'
      - $ref: '#/parameters/resourceGroupName'
      - name: labName
        in: path
        description: The name of the lab.
        required: true
        type: string
      - name: name
        in: path
        description: The name of the service runner.
        required: true
        type: string
      - name: serviceRunner
        in: body
        description: A container for a managed identity to execute DevTest lab services.
        required: true
        schema:
          $ref: '#/definitions/ServiceRunner'
      - $ref: '#/parameters/api-version'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ServiceRunner'
        '201':
          description: Created
          schema:
            $ref: '#/definitions/ServiceRunner'
        default:
          description: BadRequest
          schema:
            $ref: '#/definitions/CloudError'
      x-ms-examples:
        ServiceRunners_CreateOrUpdate:
          $ref: ./examples/ServiceRunners_CreateOrUpdate.json
      summary: Microsoft Azure Put Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Devtestlab Labs Labname Servicerunners Name
    delete:
      tags:
      - ServiceRunners
      description: Delete service runner.
      operationId: microsoftAzureServicerunnersDelete
      parameters:
      - $ref: '#/parameters/subscriptionId'
      - $ref: '#/parameters/resourceGroupName'
      - name: labName
        in: path
        description: The name of the lab.
        required: true
        type: string
      - name: name
        in: path
        description: The name of the service runner.
        required: true
        type: string
      - $ref: '#/parameters/api-version'
      responses:
        '200':
          description: OK
        '204':
          description: No Content
        default:
          description: BadRequest
          schema:
            $ref: '#/definitions/CloudError'
      x-ms-examples:
        ServiceRunners_Delete:
          $ref: ./examples/ServiceRunners_Delete.json
      summary: Microsoft Azure Delete Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Devtestlab Labs Labname Servicerunners Name
definitions:
  Resource:
    description: An Azure resource.
    type: object
    properties:
      id:
        description: The identifier of the resource.
        type: string
        readOnly: true
      name:
        description: The name of the resource.
        type: string
        readOnly: true
      type:
        description: The type of the resource.
        type: string
        readOnly: true
      location:
        description: The location of the resource.
        type: string
      tags:
        description: The tags of the resource.
        type: object
        additionalProperties:
          type: string
    x-ms-azure-resource: true
  CloudError:
    description: Error from a REST request.
    type: object
    properties:
      error:
        $ref: '#/definitions/CloudErrorBody'
        description: The cloud error that occurred
    x-ms-external: true
  CloudErrorBody:
    description: Body of an error from a REST request.
    type: object
    properties:
      code:
        description: The error code.
        type: string
      message:
        description: The error message.
        type: string
      target:
        description: The error target.
        type: string
      details:
        description: Inner errors.
        type: array
        items:
          $ref: '#/definitions/CloudErrorBody'
    x-ms-external: true
  IdentityProperties:
    description: Properties of a managed identity
    type: object
    properties:
      type:
        description: Managed identity.
        enum:
        - None
        - SystemAssigned
        - UserAssigned
        - SystemAssigned,UserAssigned
        type: string
        x-ms-enum:
          name: ManagedIdentityType
          modelAsString: true
      principalId:
        description: The principal id of resource identity.
        type: string
      tenantId:
        description: The tenant identifier of resource.
        type: string
      clientSecretUrl:
        description: The client secret URL of the identity.
        type: string
  ServiceRunner:
    description: A container for a managed identity to execute DevTest lab services.
    type: object
    allOf:
    - $ref: '#/definitions/Resource'
    properties:
      identity:
        $ref: '#/definitions/IdentityProperties'
        description: The identity of the resource.
parameters:
  resourceGroupName:
    name: resourceGroupName
    in: path
    description: The name of the resource group.
    required: true
    type: string
    x-ms-parameter-location: method
  subscriptionId:
    name: subscriptionId
    in: path
    description: The subscription ID.
    required: true
    type: string
  api-version:
    name: api-version
    in: query
    description: Client API version.
    required: true
    type: string
    default: '2018-09-15'
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
