swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector Hybrid Use Benefit Revisions API
schemes:
- https
tags:
- name: Hybrid Use Benefit Revisions
paths:
  /{scope}/providers/Microsoft.SoftwarePlan/hybridUseBenefits/{planId}/revisions:
    get:
      description: Gets the version history of a hybrid use benefit
      operationId: microsoftAzureHybridusebenefitrevisionList
      tags:
      - Hybrid Use Benefit Revisions
      x-ms-examples:
        HybridUseBenefitRevisionsResponse:
          $ref: ./examples/GetHybridUseBenefitRevisions.json
      x-ms-pageable:
        nextLinkName: nextLink
      parameters:
      - $ref: '#/parameters/ScopeParameter'
      - $ref: '#/parameters/PlanIdParameter'
      - $ref: '#/parameters/ApiVersionParameter'
      responses:
        '200':
          description: OK - returns an array of plans ordered by revision
          schema:
            $ref: '#/definitions/HybridUseBenefitListResult'
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: '#/definitions/Error'
      summary: Microsoft Azure Get Scope Providers Microsoft Softwareplan Hybridusebenefits Planid Revisions
definitions:
  ErrorCode:
    type: string
    description: Defined error codes to be returned to the client.
    enum:
    - InvalidRequestParameter
    - MissingRequestParameter
    x-ms-enum:
      name: ErrorCode
      modelAsString: true
  HybridUseBenefitModel:
    description: Response on GET of a hybrid use benefit
    required:
    - sku
    allOf:
    - $ref: ../../../../../common-types/resource-management/v1/types.json#/definitions/Resource
    properties:
      sku:
        description: Hybrid use benefit SKU
        $ref: '#/definitions/Sku'
      etag:
        type: integer
        format: int32
        description: Indicates the revision of the hybrid use benefit
        readOnly: true
      properties:
        description: Property bag for a hybrid use benefit response
        x-ms-client-flatten: true
        $ref: '#/definitions/HybridUseBenefitProperties'
  ProvisioningState:
    type: string
    description: Represent the current state of the Reservation.
    enum:
    - Succeeded
    - Cancelled
    - Failed
    x-ms-enum:
      name: ProvisioningState
      modelAsString: true
  Sku:
    type: object
    description: The SKU to be applied for this resource
    properties:
      name:
        type: string
        description: Name of the SKU to be applied
  Error:
    type: object
    description: Error object returned by the RP
    properties:
      code:
        description: Error code
        $ref: '#/definitions/ErrorCode'
      message:
        type: string
        description: A user readable error message. Localized based on x-ms-effective-locale header in the request
  HybridUseBenefitListResult:
    description: List of hybrid use benefits
    properties:
      value:
        description: List of hybrid use benefits
        type: array
        items:
          $ref: '#/definitions/HybridUseBenefitModel'
      nextLink:
        type: string
        description: Url to get the next page of items.
  HybridUseBenefitProperties:
    description: Hybrid use benefit properties
    properties:
      provisioningState:
        type: string
        description: Provisioning state
        $ref: '#/definitions/ProvisioningState'
        readOnly: true
      createdDate:
        type: string
        description: Created date
        format: date-time
        readOnly: true
      lastUpdatedDate:
        type: string
        description: Last updated date
        format: date-time
        readOnly: true
parameters:
  ApiVersionParameter:
    name: api-version
    in: query
    x-ms-parameter-location: client
    required: true
    description: The api-version to be used by the service
    type: string
  PlanIdParameter:
    name: planId
    in: path
    x-ms-parameter-location: method
    required: true
    type: string
    description: This is a unique identifier for a plan. Should be a guid.
  ScopeParameter:
    name: scope
    in: path
    x-ms-parameter-location: method
    required: true
    type: string
    description: The scope at which the operation is performed. This is limited to Microsoft.Compute/virtualMachines and Microsoft.Compute/hostGroups/hosts for now
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
