swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector ExpressRouteCircuitAuthorizations API
schemes:
- https
tags:
- name: ExpressRouteCircuitAuthorizations
paths:
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/expressRouteCircuits/{circuitName}/authorizations/{authorizationName}
  : delete:
      tags:
      - ExpressRouteCircuitAuthorizations
      operationId: microsoftAzureExpressroutecircuitauthorizationsDelete
      description: The delete authorization operation deletes the specified authorization from the specified ExpressRouteCircuit.
      parameters:
      - name: resourceGroupName
        in: path
        required: true
        type: string
        description: The name of the resource group.
      - name: circuitName
        in: path
        required: true
        type: string
        description: The name of the express route circuit.
      - name: authorizationName
        in: path
        required: true
        type: string
        description: The name of the authorization.
      - $ref: '#/parameters/ApiVersionParameter'
      - $ref: '#/parameters/SubscriptionIdParameter'
      responses:
        '200':
          description: ''
        '202':
          description: ''
        '204':
          description: ''
      x-ms-long-running-operation: true
      summary: Microsoft Azure Delete Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Network Expressroutecircuits Circuitname Authorizations Authorizationname
    get:
      tags:
      - ExpressRouteCircuitAuthorizations
      operationId: microsoftAzureExpressroutecircuitauthorizationsGet
      description: The GET authorization operation retrieves the specified authorization from the specified ExpressRouteCircuit.
      parameters:
      - name: resourceGroupName
        in: path
        required: true
        type: string
        description: The name of the resource group.
      - name: circuitName
        in: path
        required: true
        type: string
        description: The name of the express route circuit.
      - name: authorizationName
        in: path
        required: true
        type: string
        description: The name of the authorization.
      - $ref: '#/parameters/ApiVersionParameter'
      - $ref: '#/parameters/SubscriptionIdParameter'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/ExpressRouteCircuitAuthorization'
      summary: Microsoft Azure Get Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Network Expressroutecircuits Circuitname Authorizations Authorizationname
    put:
      tags:
      - ExpressRouteCircuitAuthorizations
      operationId: microsoftAzureExpressroutecircuitauthorizationsCreateorupdate
      description: The Put Authorization operation creates/updates an authorization in the specified ExpressRouteCircuits
      parameters:
      - name: resourceGroupName
        in: path
        required: true
        type: string
        description: The name of the resource group.
      - name: circuitName
        in: path
        required: true
        type: string
        description: The name of the express route circuit.
      - name: authorizationName
        in: path
        required: true
        type: string
        description: The name of the authorization.
      - name: authorizationParameters
        in: body
        required: true
        schema:
          $ref: '#/definitions/ExpressRouteCircuitAuthorization'
        description: Parameters supplied to the create/update ExpressRouteCircuitAuthorization operation
      - $ref: '#/parameters/ApiVersionParameter'
      - $ref: '#/parameters/SubscriptionIdParameter'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/ExpressRouteCircuitAuthorization'
        '201':
          description: ''
          schema:
            $ref: '#/definitions/ExpressRouteCircuitAuthorization'
      x-ms-long-running-operation: true
      summary: Microsoft Azure Put Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Network Expressroutecircuits Circuitname Authorizations Authorizationname
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/expressRouteCircuits/{circuitName}/authorizations
  : get:
      tags:
      - ExpressRouteCircuitAuthorizations
      operationId: microsoftAzureExpressroutecircuitauthorizationsList
      description: The List authorization operation retrieves all the authorizations in an ExpressRouteCircuit.
      parameters:
      - name: resourceGroupName
        in: path
        required: true
        type: string
        description: The name of the resource group.
      - name: circuitName
        in: path
        required: true
        type: string
        description: The name of the circuit.
      - $ref: '#/parameters/ApiVersionParameter'
      - $ref: '#/parameters/SubscriptionIdParameter'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/AuthorizationListResult'
      x-ms-pageable:
        nextLinkName: nextLink
      summary: Microsoft Azure Get Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Network Expressroutecircuits Circuitname Authorizations
definitions:
  AuthorizationListResult:
    properties:
      value:
        type: array
        items:
          $ref: '#/definitions/ExpressRouteCircuitAuthorization'
        description: Gets the authorizations in an ExpressRoute Circuit
      nextLink:
        type: string
        description: Gets the URL to get the next set of results.
    description: Response for ListAuthorizations Api service callRetrieves all authorizations that belongs to an ExpressRouteCircuit
  SubResource:
    properties:
      id:
        type: string
        description: Resource Id
    x-ms-azure-resource: true
  AuthorizationPropertiesFormat:
    properties:
      authorizationKey:
        type: string
        description: Gets or sets the authorization key
      authorizationUseStatus:
        type: string
        description: Gets or sets AuthorizationUseStatus
        enum:
        - Available
        - InUse
        x-ms-enum:
          name: AuthorizationUseStatus
          modelAsString: true
      provisioningState:
        type: string
        description: Gets or sets Provisioning state of the PublicIP resource Updating/Deleting/Failed
  ExpressRouteCircuitAuthorization:
    properties:
      properties:
        x-ms-client-flatten: true
        $ref: '#/definitions/AuthorizationPropertiesFormat'
      name:
        type: string
        description: Gets name of the resource that is unique within a resource group. This name can be used to access the resource
      etag:
        type: string
        description: A unique read-only string that changes whenever the resource is updated
    allOf:
    - $ref: '#/definitions/SubResource'
    description: Authorization in a ExpressRouteCircuit resource
parameters:
  ApiVersionParameter:
    name: api-version
    in: query
    required: true
    type: string
    description: Client Api Version.
  SubscriptionIdParameter:
    name: subscriptionId
    in: path
    required: true
    type: string
    description: Gets subscription credentials which uniquely identify Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
