swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector AzureLargeStorageInstances API
schemes:
- https
tags:
- name: AzureLargeStorageInstances
paths:
  /subscriptions/{subscriptionId}/providers/Microsoft.AzureLargeInstance/azureLargeStorageInstances:
    get:
      operationId: microsoftAzureAzurelargestorageinstanceListbysubscription
      tags:
      - AzureLargeStorageInstances
      description: Gets a list of AzureLargeStorageInstances in the specified subscription. The<br>operations returns various properties of each Azure LargeStorage instance.
      parameters:
      - $ref: ../../../../../common-types/resource-management/v5/types.json#/parameters/ApiVersionParameter
      - $ref: ../../../../../common-types/resource-management/v5/types.json#/parameters/SubscriptionIdParameter
      responses:
        '200':
          description: Azure operation completed successfully.
          schema:
            $ref: '#/definitions/AzureLargeStorageInstanceListResult'
        default:
          description: An unexpected error response.
          schema:
            $ref: ../../../../../common-types/resource-management/v5/types.json#/definitions/ErrorResponse
      x-ms-examples:
        AzureLargeStorageInstance_ListBySubscription:
          $ref: ./examples/AzureLargeStorageInstance_ListBySubscription.json
      x-ms-pageable:
        nextLinkName: nextLink
      summary: Get Subscriptions Subscriptionid Providers Microsoft Azurelargeinstance Azurelargestorageinstances
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.AzureLargeInstance/azureLargeStorageInstances
  : get:
      operationId: microsoftAzureAzurelargestorageinstanceListbyresourcegroup
      tags:
      - AzureLargeStorageInstances
      description: Gets a list of AzureLargeStorageInstances in the specified subscription and<br>resource group. The operations returns various properties of each Azure<br>LargeStorage instance.
      parameters:
      - $ref: ../../../../../common-types/resource-management/v5/types.json#/parameters/ApiVersionParameter
      - $ref: ../../../../../common-types/resource-management/v5/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../common-types/resource-management/v5/types.json#/parameters/ResourceGroupNameParameter
      responses:
        '200':
          description: Azure operation completed successfully.
          schema:
            $ref: '#/definitions/AzureLargeStorageInstanceListResult'
        default:
          description: An unexpected error response.
          schema:
            $ref: ../../../../../common-types/resource-management/v5/types.json#/definitions/ErrorResponse
      x-ms-examples:
        AzureLargeStorageInstance_ListByResourceGroup:
          $ref: ./examples/AzureLargeStorageInstance_ListByResourceGroup.json
      x-ms-pageable:
        nextLinkName: nextLink
      summary: Get Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Azurelargeinstance Azurelargestorageinstances
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.AzureLargeInstance/azureLargeStorageInstances/{azureLargeStorageInstanceName}
  : get:
      operationId: microsoftAzureAzurelargestorageinstanceGet
      tags:
      - AzureLargeStorageInstances
      description: Gets an Azure Large Storage instance for the specified subscription, resource<br>group, and instance name.
      parameters:
      - $ref: ../../../../../common-types/resource-management/v5/types.json#/parameters/ApiVersionParameter
      - $ref: ../../../../../common-types/resource-management/v5/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../common-types/resource-management/v5/types.json#/parameters/ResourceGroupNameParameter
      - name: azureLargeStorageInstanceName
        in: path
        description: Name of the AzureLargeStorageInstance.
        required: true
        type: string
        pattern: .*
      responses:
        '200':
          description: Azure operation completed successfully.
          schema:
            $ref: '#/definitions/AzureLargeStorageInstance'
        default:
          description: An unexpected error response.
          schema:
            $ref: ../../../../../common-types/resource-management/v5/types.json#/definitions/ErrorResponse
      x-ms-examples:
        AzureLargeStorageInstance_Get:
          $ref: ./examples/AzureLargeStorageInstance_Get.json
      summary: Get Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Azurelargeinstance Azurelargestorageinstances Azurelargestorageinstancename
    patch:
      operationId: microsoftAzureAzurelargestorageinstanceUpdate
      tags:
      - AzureLargeStorageInstances
      description: Patches the Tags field of a Azure Large Storage Instance for the specified<br>subscription, resource group, and instance name.
      parameters:
      - $ref: ../../../../../common-types/resource-management/v5/types.json#/parameters/ApiVersionParameter
      - $ref: ../../../../../common-types/resource-management/v5/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../common-types/resource-management/v5/types.json#/parameters/ResourceGroupNameParameter
      - name: azureLargeStorageInstanceName
        in: path
        description: Name of the AzureLargeStorageInstance.
        required: true
        type: string
        pattern: .*
      - name: tagsParameter
        in: body
        description: The resource properties to be updated.
        required: true
        schema:
          $ref: '#/definitions/AzureLargeStorageInstanceTagsUpdate'
        x-ms-client-name: properties
      responses:
        '200':
          description: Azure operation completed successfully.
          schema:
            $ref: '#/definitions/AzureLargeStorageInstance'
        default:
          description: An unexpected error response.
          schema:
            $ref: ../../../../../common-types/resource-management/v5/types.json#/definitions/ErrorResponse
      x-ms-examples:
        AzureLargeStorageInstance_Delete_Tag:
          $ref: ./examples/AzureLargeStorageInstance_PatchTags_Delete.json
        AzureLargeStorageInstance_Update_Tag:
          $ref: ./examples/AzureLargeStorageInstance_PatchTags.json
      summary: Patch Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Azurelargeinstance Azurelargestorageinstances Azurelargestorageinstancename
definitions:
  StorageProperties:
    type: object
    description: described the storage properties of the azure large storage instance
    properties:
      provisioningState:
        $ref: '#/definitions/ProvisioningState'
        description: State of provisioning of the AzureLargeStorageInstance
      offeringType:
        type: string
        description: the offering type for which the resource is getting provisioned
      storageType:
        type: string
        description: the storage protocol for which the resource is getting provisioned
      generation:
        type: string
        description: the kind of storage instance
      hardwareType:
        $ref: '#/definitions/AzureLargeInstanceHardwareTypeNamesEnum'
        description: the hardware type of the storage instance
      workloadType:
        type: string
        description: the workload for which the resource is getting provisioned
      storageBillingProperties:
        $ref: '#/definitions/StorageBillingProperties'
        description: the billing related information for the resource
  AzureLargeInstanceHardwareTypeNamesEnum:
    type: string
    description: Enum of the hardware options (vendor and/or their product name) for an Azure Large Instance
    enum:
    - Cisco_UCS
    - HPE
    - SDFLEX
    x-ms-enum:
      name: AzureLargeInstanceHardwareTypeNamesEnum
      modelAsString: true
      values:
      - name: Cisco_UCS
        value: Cisco_UCS
        description: Hardware type of UCS from vendor Cisco
      - name: HPE
        value: HPE
        description: Hardware type of HPE from vendor Hewlett Packard Enterprise
      - name: SDFLEX
        value: SDFLEX
        description: Hardware type of SDFLEX
  AzureLargeStorageInstanceListResult:
    type: object
    description: The response of a AzureLargeStorageInstance list operation.
    properties:
      value:
        type: array
        description: The AzureLargeStorageInstance items on this page
        items:
          $ref: '#/definitions/AzureLargeStorageInstance'
      nextLink:
        type: string
        format: uri
        description: The link to the next page of items
    required:
    - value
  ProvisioningState:
    type: string
    description: An enum of possible operation states for an AzureLargeStorageInstances
    enum:
    - Accepted
    - Creating
    - Updating
    - Failed
    - Succeeded
    - Deleting
    - Canceled
    - Migrating
    x-ms-enum:
      name: ProvisioningState
      modelAsString: true
      values:
      - name: Accepted
        value: Accepted
        description: Accepted means ARM resource has been accepted.
      - name: Creating
        value: Creating
        description: Creating means ARM resource is being created.
      - name: Updating
        value: Updating
        description: Updating means an existing ARM resource is being updated
      - name: Failed
        value: Failed
        description: Failed means resource is in failed state
      - name: Succeeded
        value: Succeeded
        description: Succeeded means resource creation succeeded during last create/update
      - name: Deleting
        value: Deleting
        description: Deleting means resource is in the process of being deleted
      - name: Canceled
        value: Canceled
        description: Cancelled means resource operation has been cancelled
      - name: Migrating
        value: Migrating
        description: Migrating means resource is being migrated from one subscription or resource group to another
    readOnly: true
  StorageBillingProperties:
    type: object
    description: Describes the billing related details of the AzureLargeStorageInstance.
    properties:
      billingMode:
        type: string
        description: the billing mode for the storage instance
      sku:
        type: string
        description: the SKU type that is provisioned
  AzureLargeStorageInstanceProperties:
    type: object
    description: Describes the properties of an AzureLargeStorageInstance.
    properties:
      azureLargeStorageInstanceUniqueIdentifier:
        type: string
        description: Specifies the AzureLargeStorageInstance unique ID.
      storageProperties:
        $ref: '#/definitions/StorageProperties'
        description: Specifies the storage properties for the AzureLargeStorage instance.
  AzureLargeStorageInstance:
    type: object
    description: 'AzureLargeStorageInstance info on Azure (ARM properties and

      AzureLargeStorageInstance properties)'
    properties:
      properties:
        $ref: '#/definitions/AzureLargeStorageInstanceProperties'
        description: The resource-specific properties for this resource.
        x-ms-client-flatten: true
        x-ms-mutability:
        - read
        - create
    allOf:
    - $ref: ../../../../../common-types/resource-management/v5/types.json#/definitions/TrackedResource
  AzureLargeStorageInstanceTagsUpdate:
    type: object
    description: The type used for updating tags in AzureLargeStorageInstance resources.
    properties:
      tags:
        type: object
        description: Resource tags.
        additionalProperties:
          type: string
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
