swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector HybridIdentityMetadata API
schemes:
- https
tags:
- name: HybridIdentityMetadata
paths:
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ConnectedVMwarevSphere/virtualMachines/{virtualMachineName}/hybridIdentityMetadata/{metadataName}
  : put:
      tags:
      - HybridIdentityMetadata
      operationId: microsoftAzureHybrididentitymetadataCreate
      description: Create Or Update HybridIdentityMetadata.
      summary: Microsoft Azure Implements Hybrididentitymetadata Put Method
      x-ms-examples:
        CreateHybridIdentityMetadata:
          $ref: ./examples/CreateHybridIdentityMetadata.json
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/subscriptionId'
      - $ref: '#/parameters/resourceGroupName'
      - in: path
        name: virtualMachineName
        required: true
        type: string
        description: Name of the vm.
      - in: path
        name: metadataName
        required: true
        type: string
        description: Name of the hybridIdentityMetadata.
      - $ref: '#/parameters/api-version'
      - in: body
        name: body
        description: Request payload.
        schema:
          $ref: '#/definitions/HybridIdentityMetadata'
      responses:
        '200':
          description: Arm resource update successful.
          schema:
            $ref: '#/definitions/HybridIdentityMetadata'
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: ../../../../../common-types/resource-management/v3/types.json#/definitions/ErrorResponse
    get:
      tags:
      - HybridIdentityMetadata
      operationId: microsoftAzureHybrididentitymetadataGet
      summary: Microsoft Azure Gets Hybrididentitymetadata
      description: Implements HybridIdentityMetadata GET method.
      x-ms-examples:
        GetHybridIdentityMetadata:
          $ref: ./examples/GetHybridIdentityMetadata.json
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/subscriptionId'
      - $ref: '#/parameters/resourceGroupName'
      - in: path
        name: virtualMachineName
        required: true
        type: string
        description: Name of the vm.
      - in: path
        name: metadataName
        required: true
        type: string
        description: Name of the HybridIdentityMetadata.
      - $ref: '#/parameters/api-version'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/HybridIdentityMetadata'
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: ../../../../../common-types/resource-management/v3/types.json#/definitions/ErrorResponse
    delete:
      tags:
      - HybridIdentityMetadata
      operationId: microsoftAzureHybrididentitymetadataDelete
      summary: Microsoft Azure Deletes An Hybrididentitymetadata
      description: Implements HybridIdentityMetadata DELETE method.
      x-ms-examples:
        DeleteHybridIdentityMetadata:
          $ref: ./examples/DeleteHybridIdentityMetadata.json
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/subscriptionId'
      - $ref: '#/parameters/resourceGroupName'
      - in: path
        name: virtualMachineName
        required: true
        type: string
        description: Name of the vm.
      - in: path
        name: metadataName
        required: true
        type: string
        description: Name of the HybridIdentityMetadata.
      - $ref: '#/parameters/api-version'
      responses:
        '200':
          description: Success
        '204':
          description: No Content
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: ../../../../../common-types/resource-management/v3/types.json#/definitions/ErrorResponse
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ConnectedVMwarevSphere/virtualMachines/{virtualMachineName}/hybridIdentityMetadata
  : get:
      tags:
      - HybridIdentityMetadata
      operationId: microsoftAzureHybrididentitymetadataList
      summary: Microsoft Azure Implements Get Hybrididentitymetadata In A Vm
      description: Returns the list of HybridIdentityMetadata of the given vm.
      x-ms-examples:
        HybridIdentityMetadataListByVm:
          $ref: ./examples/HybridIdentityMetadata_ListByVm.json
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/subscriptionId'
      - $ref: '#/parameters/resourceGroupName'
      - in: path
        name: virtualMachineName
        required: true
        type: string
        description: Name of the vm.
      - $ref: '#/parameters/api-version'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/HybridIdentityMetadataList'
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: ../../../../../common-types/resource-management/v3/types.json#/definitions/ErrorResponse
      x-ms-pageable:
        nextLinkName: nextLink
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ScVmm/virtualMachines/{virtualMachineName}/hybridIdentityMetadata/{metadataName}
  : put:
      tags:
      - HybridIdentityMetadata
      operationId: microsoftAzureHybrididentitymetadatasCreate
      description: Create Or Update HybridIdentityMetadata.
      summary: Microsoft Azure Implements Hybrididentitymetadata Put Method
      x-ms-examples:
        CreateHybridIdentityMetadata:
          $ref: ./examples/CreateHybridIdentityMetadata.json
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/SubscriptionIdParameter'
      - $ref: '#/parameters/ResourceGroupNameParameter'
      - in: path
        name: virtualMachineName
        required: true
        type: string
        description: Name of the vm.
      - in: path
        name: metadataName
        required: true
        type: string
        description: Name of the hybridIdentityMetadata.
      - $ref: '#/parameters/ApiVersionParameter'
      - in: body
        name: body
        description: Request payload.
        schema:
          $ref: '#/definitions/HybridIdentityMetadata_2'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/HybridIdentityMetadata_2'
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: '#/definitions/ErrorResponse'
    get:
      tags:
      - HybridIdentityMetadata
      operationId: microsoftAzureHybrididentitymetadatasGet
      summary: Microsoft Azure Gets Hybrididentitymetadata
      description: Implements HybridIdentityMetadata GET method.
      x-ms-examples:
        GetHybridIdentityMetadata:
          $ref: ./examples/GetHybridIdentityMetadata.json
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/SubscriptionIdParameter'
      - $ref: '#/parameters/ResourceGroupNameParameter'
      - in: path
        name: virtualMachineName
        required: true
        type: string
        description: Name of the vm.
      - in: path
        name: metadataName
        required: true
        type: string
        description: Name of the HybridIdentityMetadata.
      - $ref: '#/parameters/ApiVersionParameter'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/HybridIdentityMetadata_2'
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: '#/definitions/ErrorResponse'
    delete:
      tags:
      - HybridIdentityMetadata
      operationId: microsoftAzureHybrididentitymetadatasDelete
      summary: Microsoft Azure Deletes An Hybrididentitymetadata
      description: Implements HybridIdentityMetadata DELETE method.
      x-ms-examples:
        DeleteHybridIdentityMetadata:
          $ref: ./examples/DeleteHybridIdentityMetadata.json
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/SubscriptionIdParameter'
      - $ref: '#/parameters/ResourceGroupNameParameter'
      - in: path
        name: virtualMachineName
        required: true
        type: string
        description: Name of the vm.
      - in: path
        name: metadataName
        required: true
        type: string
        description: Name of the HybridIdentityMetadata.
      - $ref: '#/parameters/ApiVersionParameter'
      responses:
        '200':
          description: Success
        '204':
          description: No Content
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: '#/definitions/ErrorResponse'
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ScVmm/virtualMachines/{virtualMachineName}/hybridIdentityMetadata
  : get:
      tags:
      - HybridIdentityMetadata
      operationId: microsoftAzureHybrididentitymetadatasListbyvm
      summary: Microsoft Azure Implements Get Hybrididentitymetadata In A Vm
      description: Returns the list of HybridIdentityMetadata of the given vm.
      x-ms-examples:
        HybridIdentityMetadataListByVm:
          $ref: ./examples/HybridIdentityMetadata_ListByVm.json
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/SubscriptionIdParameter'
      - $ref: '#/parameters/ResourceGroupNameParameter'
      - in: path
        name: virtualMachineName
        required: true
        type: string
        description: Name of the vm.
      - $ref: '#/parameters/ApiVersionParameter'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/HybridIdentityMetadataList'
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: '#/definitions/ErrorResponse'
      x-ms-pageable:
        nextLinkName: nextLink
definitions:
  ErrorDefinition:
    description: Error definition.
    type: object
    properties:
      code:
        description: Service specific error code which serves as the substatus for the HTTP error code.
        type: string
        readOnly: true
      message:
        description: Description of the error.
        type: string
        readOnly: true
      details:
        description: Internal error details.
        type: array
        items:
          $ref: '#/definitions/ErrorDefinition'
        x-ms-identifiers: []
        readOnly: true
  ErrorResponse:
    description: Error response.
    type: object
    properties:
      error:
        $ref: '#/definitions/ErrorDefinition'
        description: The error details.
  ResourceProvisioningState:
    type: string
    description: The current deployment state of resource.
    enum:
    - Succeeded
    - Failed
    - Canceled
    - Provisioning
    - Updating
    - Deleting
    - Accepted
    - Created
    x-ms-enum:
      name: ProvisioningState
      modelAsString: true
  HybridIdentityMetadata:
    description: Defines the HybridIdentityMetadata.
    required:
    - properties
    type: object
    allOf:
    - $ref: ../../../../../common-types/resource-management/v5/types.json#/definitions/ProxyResource
      description: The resource model definition for an Azure Resource Manager proxy resource. It will have everything other than required location and tags.
    properties:
      properties:
        x-ms-client-flatten: true
        description: Resource properties.
        $ref: '#/definitions/HybridIdentityMetadataProperties'
    x-ms-azure-resource: true
  Identity:
    type: object
    required:
    - type
    properties:
      principalId:
        readOnly: true
        type: string
        description: The principal id of managed service identity.
      tenantId:
        readOnly: true
        type: string
        description: The tenant of managed service identity.
      type:
        type: string
        description: The type of managed service identity.
        enum:
        - None
        - SystemAssigned
        x-ms-enum:
          name: IdentityType
          modelAsString: true
    description: Managed service identity.
  HybridIdentityMetadataList:
    description: List of HybridIdentityMetadata.
    type: object
    properties:
      nextLink:
        description: Url to follow for getting next page of HybridIdentityMetadata.
        type: string
      value:
        description: Array of HybridIdentityMetadata
        type: array
        items:
          $ref: '#/definitions/HybridIdentityMetadata'
    required:
    - value
  HybridIdentityMetadata_2:
    description: Defines the HybridIdentityMetadata.
    required:
    - properties
    type: object
    allOf:
    - $ref: ../../../../../common-types/resource-management/v3/types.json#/definitions/ProxyResource
      description: The resource model definition for an Azure Resource Manager proxy resource. It will have everything other than required location and tags.
    properties:
      properties:
        x-ms-client-flatten: true
        description: Resource properties.
        $ref: '#/definitions/HybridIdentityMetadataProperties_2'
    x-ms-azure-resource: true
  HybridIdentityMetadataProperties_2:
    description: Defines the resource properties.
    type: object
    properties:
      resourceUid:
        description: Gets or sets the Vm Id.
        type: string
      publicKey:
        description: Gets or sets the Public Key.
        type: string
      identity:
        $ref: '#/definitions/Identity'
        description: The identity of the resource.
        readOnly: true
      provisioningState:
        description: Gets or sets the provisioning state.
        type: string
        readOnly: true
  HybridIdentityMetadataProperties:
    description: Describes the properties of Hybrid Identity Metadata for a Virtual Machine.
    type: object
    properties:
      vmId:
        description: Gets or sets the Vm Id.
        type: string
      publicKey:
        description: Gets or sets the Public Key.
        type: string
      identity:
        $ref: '#/definitions/Identity'
        description: The identity of the resource.
        readOnly: true
      provisioningState:
        $ref: '#/definitions/ResourceProvisioningState'
        description: Gets the provisioning state.
        readOnly: true
parameters:
  ApiVersionParameter:
    name: api-version
    in: query
    required: true
    type: string
    description: The API version to be used with the HTTP request (e.g. YYYY-MM-DD).
  resourceGroupName:
    in: path
    name: resourceGroupName
    description: The Resource Group Name.
    required: true
    type: string
    x-ms-parameter-location: method
  subscriptionId:
    in: path
    name: subscriptionId
    description: The Subscription ID.
    required: true
    type: string
  SubscriptionIdParameter:
    name: subscriptionId
    in: path
    required: true
    type: string
    description: The Azure subscription ID. This is a GUID-formatted string (e.g. 00000000-0000-0000-0000-000000000000).
  api-version:
    in: query
    name: api-version
    description: Client Api Version.
    required: true
    type: string
  ResourceGroupNameParameter:
    name: resourceGroupName
    in: path
    required: true
    type: string
    description: The name of the resource group.
    x-ms-parameter-location: method
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
