swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector Benefits Operations API
schemes:
- https
tags:
- name: Benefits Operations
paths:
  /providers/Microsoft.BillingBenefits/operations:
    get:
      summary: Microsoft Azure Get Operations
      description: List all the operations.
      operationId: microsoftAzureOperationsList
      x-ms-examples:
        OperationsGet:
          $ref: ./examples/OperationsGet.json
      x-ms-pageable:
        nextLinkName: nextLink
      parameters:
      - $ref: '#/parameters/ApiVersionParameter'
      tags:
      - Benefits Operations
      responses:
        '200':
          description: List all the operations.
          schema:
            $ref: ../../../../../common-types/resource-management/v3/types.json#/definitions/OperationListResult
        default:
          description: Error response describing why the operation failed
          schema:
            $ref: ../../../../../common-types/resource-management/v3/types.json#/definitions/ErrorResponse
parameters:
  ApiVersionParameter:
    name: api-version
    in: query
    x-ms-parameter-location: client
    required: true
    description: The api-version to be used by the service
    type: string
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
