swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector FleetMembers API
schemes:
- https
tags:
- name: FleetMembers
paths:
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ContainerService/fleets/{fleetName}/members/{fleetMemberName}
  : put:
      tags:
      - FleetMembers
      operationId: microsoftAzureFleetmembersCreateorupdate
      summary: Microsoft Azure Creates Or Updates A Fleet Member
      description: A member contains a reference to an existing Kubernetes cluster. Creating a member makes the referenced cluster join the Fleet.
      parameters:
      - $ref: ../../../../../../common-types/resource-management/v3/types.json#/parameters/ApiVersionParameter
      - $ref: ../../../../../../common-types/resource-management/v3/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../../common-types/resource-management/v3/types.json#/parameters/ResourceGroupNameParameter
      - $ref: '#/parameters/FleetNameParameter'
      - $ref: '#/parameters/FleetMemberNameParameter'
      - $ref: '#/parameters/IfMatchHeader'
      - $ref: '#/parameters/IfNoneMatchHeader'
      - name: parameters
        in: body
        required: true
        schema:
          $ref: '#/definitions/FleetMember'
        description: The Fleet member to create or update.
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/FleetMember'
        '201':
          description: Created
          schema:
            $ref: '#/definitions/FleetMember'
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: ../../../../../../common-types/resource-management/v3/types.json#/definitions/ErrorResponse
      x-ms-long-running-operation: true
      x-ms-examples:
        Create a fleet member resource. Joins an existing cluster to the fleet:
          $ref: ./examples/FleetMembers_Create.json
    get:
      tags:
      - FleetMembers
      operationId: microsoftAzureFleetmembersGet
      summary: Microsoft Azure Gets A Fleet Member
      parameters:
      - $ref: ../../../../../../common-types/resource-management/v3/types.json#/parameters/ApiVersionParameter
      - $ref: ../../../../../../common-types/resource-management/v3/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../../common-types/resource-management/v3/types.json#/parameters/ResourceGroupNameParameter
      - $ref: '#/parameters/FleetNameParameter'
      - $ref: '#/parameters/FleetMemberNameParameter'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/FleetMember'
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: ../../../../../../common-types/resource-management/v3/types.json#/definitions/ErrorResponse
      x-ms-examples:
        Gets a fleet member resource.:
          $ref: ./examples/FleetMembers_Get.json
      description: Needs a more full description created.
    delete:
      tags:
      - FleetMembers
      operationId: microsoftAzureFleetmembersDelete
      summary: Microsoft Azure Deletes A Fleet Member
      description: Deleting a Fleet member results in the member cluster leaving fleet. The Member azure resource is deleted upon success. The underlying cluster is not deleted.
      parameters:
      - $ref: ../../../../../../common-types/resource-management/v3/types.json#/parameters/ApiVersionParameter
      - $ref: ../../../../../../common-types/resource-management/v3/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../../common-types/resource-management/v3/types.json#/parameters/ResourceGroupNameParameter
      - $ref: '#/parameters/FleetNameParameter'
      - $ref: '#/parameters/FleetMemberNameParameter'
      - $ref: '#/parameters/IfMatchHeader'
      responses:
        '200':
          description: OK
        '202':
          description: Accepted
        '204':
          description: NoContent
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: ../../../../../../common-types/resource-management/v3/types.json#/definitions/ErrorResponse
      x-ms-long-running-operation: true
      x-ms-long-running-operation-options:
        final-state-via: location
      x-ms-examples:
        Deletes a fleet member resource.:
          $ref: ./examples/FleetMembers_Delete.json
    patch:
      operationId: microsoftAzureFleetmembersUpdate
      tags:
      - FleetMembers
      description: Update a FleetMember
      parameters:
      - $ref: ../../../../../../common-types/resource-management/v3/types.json#/parameters/ApiVersionParameter
      - $ref: ../../../../../../common-types/resource-management/v3/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../../common-types/resource-management/v3/types.json#/parameters/ResourceGroupNameParameter
      - name: If-Match
        in: header
        description: The request should only proceed if an entity matches this string.
        required: false
        type: string
        x-ms-client-name: ifMatch
      - name: fleetName
        in: path
        description: The name of the Fleet resource.
        required: true
        type: string
        minLength: 1
        maxLength: 63
        pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$
      - name: fleetMemberName
        in: path
        description: The name of the Fleet member resource.
        required: true
        type: string
        minLength: 1
        maxLength: 50
        pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$
      - name: properties
        in: body
        description: The resource properties to be updated.
        required: true
        schema:
          $ref: '#/definitions/FleetMemberUpdate'
      responses:
        '200':
          description: Azure operation completed successfully.
          schema:
            $ref: '#/definitions/FleetMember_2'
        '202':
          description: Resource update request accepted.
          headers:
            Location:
              type: string
              description: The Location header contains the URL where the status of the long running operation can be checked.
            Retry-After:
              type: integer
              format: int32
              description: The Retry-After header can indicate how long the client should wait before polling the operation status.
        default:
          description: An unexpected error response.
          schema:
            $ref: ../../../../../../common-types/resource-management/v3/types.json#/definitions/ErrorResponse
      x-ms-examples:
        Updates a FleetMember resource synchronously.:
          $ref: ./examples/FleetMembers_Update.json
      x-ms-long-running-operation-options:
        final-state-via: original-uri
      x-ms-long-running-operation: true
      summary: Microsoft Azure Patch Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Containerservice Fleets Fleetname Members Fleetmembername
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ContainerService/fleets/{fleetName}/members
  : get:
      tags:
      - FleetMembers
      operationId: microsoftAzureFleetmembersListbyfleet
      summary: Microsoft Azure Lists The Members Of A Fleet
      parameters:
      - $ref: ../../../../../../common-types/resource-management/v3/types.json#/parameters/ApiVersionParameter
      - $ref: ../../../../../../common-types/resource-management/v3/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../../common-types/resource-management/v3/types.json#/parameters/ResourceGroupNameParameter
      - $ref: '#/parameters/FleetNameParameter'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/FleetMembersListResult'
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: ../../../../../../common-types/resource-management/v3/types.json#/definitions/ErrorResponse
      x-ms-pageable:
        nextLinkName: nextLink
      x-ms-examples:
        Lists the members of a fleet.:
          $ref: ./examples/FleetMembers_List.json
      description: Needs a more full description created.
definitions:
  FleetMemberProperties_2:
    type: object
    description: A member of the Fleet. It contains a reference to an existing Kubernetes cluster on Azure.
    properties:
      clusterResourceId:
        $ref: '#/definitions/ClusterResourceId'
        description: 'The ARM resource id of the cluster that joins the Fleet. Must be a valid Azure resource id. e.g.: ''/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ContainerService/managedClusters/{clusterName}''.'
        x-ms-mutability:
        - read
        - create
      group:
        type: string
        description: The group this member belongs to for multi-cluster update management.
        minLength: 1
        maxLength: 50
        pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$
      provisioningState:
        $ref: '#/definitions/FleetMemberProvisioningState'
        description: The status of the last operation.
        readOnly: true
    required:
    - clusterResourceId
  FleetMemberProvisioningState:
    type: string
    description: The provisioning state of the last accepted operation.
    enum:
    - Succeeded
    - Failed
    - Canceled
    - Joining
    - Leaving
    - Updating
    x-ms-enum:
      name: FleetMemberProvisioningState
      modelAsString: true
      values:
      - name: Succeeded
        value: Succeeded
        description: Resource has been created.
      - name: Failed
        value: Failed
        description: Resource creation failed.
      - name: Canceled
        value: Canceled
        description: Resource creation was canceled.
      - name: Joining
        value: Joining
        description: The provisioning state of a member joining a fleet.
      - name: Leaving
        value: Leaving
        description: The provisioning state of a member leaving a fleet.
      - name: Updating
        value: Updating
        description: The provisioning state of a member being updated.
    readOnly: true
  FleetMembersListResult:
    type: object
    properties:
      value:
        type: array
        items:
          $ref: '#/definitions/FleetMember'
        description: The list of members in a given Fleet.
      nextLink:
        readOnly: true
        type: string
        description: The URL to get the next page of Fleet members.
    description: The response from the List FleetMembers operation.
  FleetMember_2:
    type: object
    description: A member of the Fleet. It contains a reference to an existing Kubernetes cluster on Azure.
    properties:
      properties:
        $ref: '#/definitions/FleetMemberProperties_2'
        description: The resource-specific properties for this resource.
        x-ms-client-flatten: true
        x-ms-mutability:
        - read
        - create
      eTag:
        type: string
        description: If eTag is provided in the response body, it may also be provided as a header per the normal etag convention.  Entity tags are used for comparing two or more entities from the same requested resource. HTTP/1.1 uses entity tags in the etag (section 14.19), If-Match (section 14.24), If-None-Match (section 14.26), and If-Range (section 14.27) header fields.
        readOnly: true
    allOf:
    - $ref: ../../../../../../common-types/resource-management/v3/types.json#/definitions/ProxyResource
  FleetMember:
    type: object
    description: A member of the Fleet. It contains a reference to an existing Kubernetes cluster on Azure.
    properties:
      properties:
        description: Properties of a Fleet member.
        $ref: '#/definitions/FleetMemberProperties'
        x-ms-client-flatten: true
    allOf:
    - $ref: ../../../../../../common-types/resource-management/v3/types.json#/definitions/AzureEntityResource
  FleetMemberProperties:
    description: Properties of a Fleet member.
    type: object
    properties:
      clusterResourceId:
        type: string
        x-ms-mutability:
        - read
        - create
        description: 'The ARM resource id of the cluster that joins the Fleet. Must be a valid Azure resource id. e.g.: ''/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ContainerService/managedClusters/{clusterName}''.'
      provisioningState:
        readOnly: true
        type: string
        x-ms-enum:
          name: FleetMemberProvisioningState
          modelAsString: true
        enum:
        - Succeeded
        - Failed
        - Canceled
        - Joining
        - Leaving
        - Updating
        description: The provisioning state of the last accepted operation.
  ClusterResourceId:
    type: string
    format: arm-id
    description: A type definition that refers the id to an Azure Resource Manager resource.
    x-ms-arm-id-details:
      allowedResources:
      - type: Microsoft.ContainerService/managedClusters
  FleetMemberUpdate:
    type: object
    description: The type used for update operations of the FleetMember.
    properties:
      properties:
        $ref: '#/definitions/FleetMemberUpdateProperties'
        x-ms-client-flatten: true
  FleetMemberUpdateProperties:
    type: object
    description: The updatable properties of the FleetMember.
    properties:
      group:
        type: string
        description: The group this member belongs to for multi-cluster update management.
        minLength: 1
        maxLength: 50
        pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$
parameters:
  FleetNameParameter:
    name: fleetName
    in: path
    required: true
    type: string
    minLength: 1
    maxLength: 63
    pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$
    description: The name of the Fleet resource.
    x-ms-parameter-location: method
  IfMatchHeader:
    name: If-Match
    in: header
    required: false
    type: string
    x-ms-client-name: IfMatch
    x-ms-parameter-location: method
    description: Omit this value to always overwrite the current resource. Specify the last-seen ETag value to prevent accidentally overwriting concurrent changes.
  FleetMemberNameParameter:
    name: fleetMemberName
    in: path
    required: true
    type: string
    minLength: 1
    maxLength: 50
    pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$
    description: The name of the Fleet member resource.
    x-ms-parameter-location: method
  IfNoneMatchHeader:
    name: If-None-Match
    in: header
    required: false
    type: string
    x-ms-client-name: IfNoneMatch
    x-ms-parameter-location: method
    description: Set to '*' to allow a new resource to be created and prevent updating an existing resource. Other values will result in a 412 Pre-condition Failed response.
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
