openapi: 3.2.0
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector Data Set Mapping API
tags:
- name: DataSetMapping
paths:
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DataShare/accounts/{accountName}/shareSubscriptions/{shareSubscriptionName}/dataSetMappings/{dataSetMappingName}
  : get:
      tags:
      - DataSetMapping
      summary: Microsoft Azure Get Datasetmapping In A Sharesubscription
      description: Get a DataSetMapping in a shareSubscription
      operationId: microsoftAzureDatasetmappingsGet
      parameters:
      - $ref: '#/components/parameters/subscriptionId'
      - $ref: '#/components/parameters/resourceGroupName'
      - $ref: '#/components/parameters/accountName'
      - name: shareSubscriptionName
        in: path
        description: The name of the shareSubscription.
        required: true
        schema:
          type: string
      - name: dataSetMappingName
        in: path
        description: The name of the dataSetMapping.
        required: true
        schema:
          type: string
      - $ref: '#/components/parameters/api-version'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataSetMapping'
        default:
          description: An error response received from the Microsoft.DataShare resource provider.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataShareError'
      x-ms-examples:
        DataSetMappings_Get:
          $ref: ./examples/DataSetMappings_Get.json
    put:
      tags:
      - DataSetMapping
      summary: "Microsoft Azure Maps A Source Data Set In The Source Share To A Sink Data Set In The Share Subscription \nenables Copying The Data Set From Source To Destination"
      description: 'Create a DataSetMapping '
      operationId: microsoftAzureDatasetmappingsCreate
      parameters:
      - $ref: '#/components/parameters/subscriptionId'
      - $ref: '#/components/parameters/resourceGroupName'
      - $ref: '#/components/parameters/accountName'
      - name: shareSubscriptionName
        in: path
        description: The name of the share subscription which will hold the data set sink.
        required: true
        schema:
          type: string
      - name: dataSetMappingName
        in: path
        description: The name of the data set mapping to be created.
        required: true
        schema:
          type: string
      - $ref: '#/components/parameters/api-version'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataSetMapping'
        '201':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataSetMapping'
        default:
          description: An error response received from the Microsoft.DataShare resource provider.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataShareError'
      x-ms-examples:
        DataSetMappings_Create:
          $ref: ./examples/DataSetMappings_Create.json
        DataSetMappings_SqlDW_Create:
          $ref: ./examples/DataSetMappings_SqlDW_Create.json
        DataSetMappings_SqlDB_Create:
          $ref: ./examples/DataSetMappings_SqlDB_Create.json
        DataSetMappings_SqlDWDataSetToAdlsGen2File_Create:
          $ref: ./examples/DataSetMappings_SqlDWDataSetToAdlsGen2File_Create.json
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DataSetMapping'
        description: Destination data set configuration details.
        required: true
    delete:
      tags:
      - DataSetMapping
      summary: Microsoft Azure Delete Datasetmapping In A Sharesubscription
      description: Delete a DataSetMapping in a shareSubscription
      operationId: microsoftAzureDatasetmappingsDelete
      parameters:
      - $ref: '#/components/parameters/subscriptionId'
      - $ref: '#/components/parameters/resourceGroupName'
      - $ref: '#/components/parameters/accountName'
      - name: shareSubscriptionName
        in: path
        description: The name of the shareSubscription.
        required: true
        schema:
          type: string
      - name: dataSetMappingName
        in: path
        description: The name of the dataSetMapping.
        required: true
        schema:
          type: string
      - $ref: '#/components/parameters/api-version'
      responses:
        '200':
          description: Success
        '204':
          description: Success
        default:
          description: An error response received from the Microsoft.DataShare resource provider.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataShareError'
      x-ms-examples:
        DataSetMappings_Delete:
          $ref: ./examples/DataSetMappings_Delete.json
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DataShare/accounts/{accountName}/shareSubscriptions/{shareSubscriptionName}/dataSetMappings
  : get:
      tags:
      - DataSetMapping
      summary: Microsoft Azure List Datasetmappings In A Share Subscription
      description: List DataSetMappings in a share subscription
      operationId: microsoftAzureDatasetmappingsListbysharesubscription
      parameters:
      - $ref: '#/components/parameters/subscriptionId'
      - $ref: '#/components/parameters/resourceGroupName'
      - $ref: '#/components/parameters/accountName'
      - name: shareSubscriptionName
        in: path
        description: The name of the share subscription.
        required: true
        schema:
          type: string
      - $ref: '#/components/parameters/api-version'
      - name: $skipToken
        in: query
        description: Continuation token
        required: false
        schema:
          type: string
      - name: $filter
        in: query
        description: Filters the results using OData syntax.
        required: false
        schema:
          type: string
      - name: $orderby
        in: query
        description: Sorts the results using OData syntax.
        required: false
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataSetMappingList'
        default:
          description: An error response received from the Microsoft.DataShare resource provider.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataShareError'
      x-ms-pageable:
        nextLinkName: nextLink
      x-ms-examples:
        DataSetMappings_ListByShareSubscription:
          $ref: ./examples/DataSetMappings_ListByShareSubscription.json
components:
  parameters:
    accountName:
      name: accountName
      in: path
      description: The name of the share account.
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
    api-version:
      name: api-version
      in: query
      description: The api version to use.
      required: true
      schema:
        type: string
    subscriptionId:
      name: subscriptionId
      in: path
      description: The subscription identifier
      required: true
      schema:
        type: string
    resourceGroupName:
      name: resourceGroupName
      in: path
      description: The resource group name.
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
  schemas:
    DataShareErrorInfo:
      description: The data share error body model.
      required:
      - code
      - message
      type: object
      properties:
        code:
          description: Code of the error
          type: string
        details:
          description: Nested details of the error model
          uniqueItems: false
          type: array
          items:
            $ref: '#/components/schemas/DataShareErrorInfo'
        message:
          description: Message of the error
          type: string
        target:
          description: Target of the error
          type: string
    DataSetMappingList:
      description: List response for get DataSetMappings
      required:
      - value
      type: object
      properties:
        nextLink:
          description: The Url of next result page.
          type: string
        value:
          description: Collection of items of type DataTransferObjects.
          uniqueItems: false
          type: array
          items:
            $ref: '#/components/schemas/DataSetMapping'
    DataShareError:
      description: The data share error model.
      required:
      - error
      type: object
      properties:
        error:
          $ref: '#/components/schemas/DataShareErrorInfo'
          description: The data share error body
    ProxyDto:
      description: Base data transfer object implementation for proxy resources.
      type: object
      properties:
        id:
          description: The resource id of the azure resource
          type: string
          readOnly: true
        name:
          description: Name of the azure resource
          type: string
          readOnly: true
        type:
          description: Type of the azure resource
          type: string
          readOnly: true
      x-ms-azure-resource: true
    DataSetMapping:
      description: A data set mapping data transfer object.
      required:
      - kind
      type: object
      allOf:
      - $ref: '#/components/schemas/ProxyDto'
      properties:
        kind:
          description: Kind of data set mapping.
          enum:
          - Blob
          - Container
          - BlobFolder
          - AdlsGen2FileSystem
          - AdlsGen2Folder
          - AdlsGen2File
          - KustoCluster
          - KustoDatabase
          - SqlDBTable
          - SqlDWTable
          type: string
          x-ms-enum:
            name: dataSetMappingKind
            modelAsString: true
      discriminator:
        propertyName: kind
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/components/parameters/Endpoint'
