swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector Backup Policy API
schemes:
- https
tags:
- name: Backup Policy
paths:
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.NetApp/netAppAccounts/{accountName}/backupPolicies
  : get:
      tags:
      - Backup Policy
      summary: Microsoft Azure List Backup Policies
      description: List backup policies for Netapp Account
      operationId: microsoftAzureBackuppoliciesList
      parameters:
      - $ref: ../../../../../common-types/resource-management/v5/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../common-types/resource-management/v5/types.json#/parameters/ResourceGroupNameParameter
      - $ref: '#/parameters/AccountName'
      - $ref: ../../../../../common-types/resource-management/v5/types.json#/parameters/ApiVersionParameter
      x-ms-pageable:
        nextLinkName: null
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/backupPoliciesList'
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: ../../../../../common-types/resource-management/v5/types.json#/definitions/ErrorResponse
      x-ms-examples:
        Backups_List:
          $ref: examples/BackupPolicies_List.json
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.NetApp/netAppAccounts/{accountName}/backupPolicies/{backupPolicyName}
  : get:
      tags:
      - Backup Policy
      summary: Microsoft Azure Get A Backup Policy
      description: Get a particular backup Policy
      operationId: microsoftAzureBackuppoliciesGet
      parameters:
      - $ref: ../../../../../common-types/resource-management/v5/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../common-types/resource-management/v5/types.json#/parameters/ResourceGroupNameParameter
      - $ref: '#/parameters/AccountName'
      - $ref: '#/parameters/BackupPolicyName'
      - $ref: ../../../../../common-types/resource-management/v5/types.json#/parameters/ApiVersionParameter
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/backupPolicy'
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: ../../../../../common-types/resource-management/v5/types.json#/definitions/ErrorResponse
      x-ms-examples:
        Backups_Get:
          $ref: examples/BackupPolicies_Get.json
    put:
      tags:
      - Backup Policy
      summary: Microsoft Azure Create A Backup Policy
      description: Create a backup policy for Netapp Account
      operationId: microsoftAzureBackuppoliciesCreate
      parameters:
      - $ref: ../../../../../common-types/resource-management/v5/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../common-types/resource-management/v5/types.json#/parameters/ResourceGroupNameParameter
      - $ref: '#/parameters/AccountName'
      - $ref: '#/parameters/BackupPolicyName'
      - $ref: ../../../../../common-types/resource-management/v5/types.json#/parameters/ApiVersionParameter
      - name: body
        description: Backup policy object supplied in the body of the operation.
        in: body
        required: true
        schema:
          $ref: '#/definitions/backupPolicy'
      responses:
        '200':
          description: Backup Policy created
          schema:
            $ref: '#/definitions/backupPolicy'
        '201':
          description: Backup created
          schema:
            $ref: '#/definitions/backupPolicy'
        '202':
          description: Accepted -- Create request accepted; operation will complete asynchronously
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: ../../../../../common-types/resource-management/v5/types.json#/definitions/ErrorResponse
      x-ms-long-running-operation: true
      x-ms-long-running-operation-options:
        final-state-via: azure-async-operation
      x-ms-examples:
        BackupPolicies_Create:
          $ref: examples/BackupPolicies_Create.json
    patch:
      tags:
      - Backup Policy
      summary: Microsoft Azure Patch A Backup Policy
      description: Patch a backup policy for Netapp Account
      operationId: microsoftAzureBackuppoliciesUpdate
      parameters:
      - $ref: ../../../../../common-types/resource-management/v5/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../common-types/resource-management/v5/types.json#/parameters/ResourceGroupNameParameter
      - $ref: '#/parameters/AccountName'
      - $ref: '#/parameters/BackupPolicyName'
      - $ref: ../../../../../common-types/resource-management/v5/types.json#/parameters/ApiVersionParameter
      - name: body
        description: Backup policy object supplied in the body of the operation.
        in: body
        required: true
        schema:
          $ref: '#/definitions/backupPolicyPatch'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/backupPolicy'
        '202':
          description: Accepted -- Create or update request accepted; operation will complete asynchronously
          schema:
            $ref: '#/definitions/backupPolicy'
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: ../../../../../common-types/resource-management/v5/types.json#/definitions/ErrorResponse
      x-ms-long-running-operation: true
      x-ms-long-running-operation-options:
        final-state-via: azure-async-operation
      x-ms-examples:
        BackupPolicies_Update:
          $ref: examples/BackupPolicies_Update.json
    delete:
      tags:
      - Backup Policy
      summary: Microsoft Azure Delete A Backup Policy
      description: Delete backup policy
      operationId: microsoftAzureBackuppoliciesDelete
      parameters:
      - $ref: ../../../../../common-types/resource-management/v5/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../common-types/resource-management/v5/types.json#/parameters/ResourceGroupNameParameter
      - $ref: '#/parameters/AccountName'
      - $ref: '#/parameters/BackupPolicyName'
      - $ref: ../../../../../common-types/resource-management/v5/types.json#/parameters/ApiVersionParameter
      responses:
        '200':
          description: OK
        '202':
          description: Accepted -- Create or update request accepted; operation will complete asynchronously
        '204':
          description: NoContent -- Resource does not exist.
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: ../../../../../common-types/resource-management/v5/types.json#/definitions/ErrorResponse
      x-ms-long-running-operation: true
      x-ms-long-running-operation-options:
        final-state-via: location
      x-ms-examples:
        Backups_Delete:
          $ref: examples/BackupPolicies_Delete.json
definitions:
  volumeBackups:
    description: Volume details using the backup policy
    type: object
    readOnly: true
    properties:
      volumeName:
        type: string
        description: Volume name
      backupsCount:
        type: integer
        description: Total count of backups for volume
        format: int32
      policyEnabled:
        type: boolean
        description: Policy enabled
  backupPoliciesList:
    description: List of Backup Policies
    type: object
    properties:
      value:
        description: A list of backup policies
        type: array
        items:
          $ref: '#/definitions/backupPolicy'
  resourceTags:
    type: object
    additionalProperties:
      type: string
    description: Tags are a list of key-value pairs that describe the resource
  backupPolicyProperties:
    description: Backup policy properties
    type: object
    properties:
      backupPolicyId:
        type: string
        readOnly: true
        description: Backup Policy Resource ID
      provisioningState:
        type: string
        readOnly: true
        description: Azure lifecycle management
      dailyBackupsToKeep:
        type: integer
        description: Daily backups count to keep
        format: int32
      weeklyBackupsToKeep:
        type: integer
        description: Weekly backups count to keep
        format: int32
      monthlyBackupsToKeep:
        type: integer
        description: Monthly backups count to keep
        format: int32
      volumesAssigned:
        type: integer
        readOnly: true
        description: Volumes using current backup policy
        format: int32
      enabled:
        type: boolean
        description: The property to decide policy is enabled or not
      volumeBackups:
        description: A list of volumes assigned to this policy
        readOnly: true
        type: array
        items:
          $ref: '#/definitions/volumeBackups'
        x-ms-identifiers:
        - volumeName
  backupPolicyPatch:
    description: Backup policy Details for create and update
    type: object
    x-ms-azure-resource: true
    properties:
      location:
        type: string
        description: Resource location
        x-ms-mutability:
        - read
        - create
      id:
        type: string
        readOnly: true
        description: Resource Id
      name:
        type: string
        readOnly: true
        description: Resource name
      type:
        type: string
        readOnly: true
        description: Resource type
      tags:
        description: Resource tags
        $ref: '#/definitions/resourceTags'
      properties:
        description: Backup policy Properties
        $ref: '#/definitions/backupPolicyProperties'
        x-ms-client-flatten: true
  backupPolicy:
    description: Backup policy information
    type: object
    required:
    - location
    - properties
    allOf:
    - $ref: ../../../../../common-types/resource-management/v5/types.json#/definitions/TrackedResource
    properties:
      etag:
        readOnly: true
        type: string
        description: A unique read-only string that changes whenever the resource is updated.
      properties:
        description: Backup policy Properties
        $ref: '#/definitions/backupPolicyProperties'
        x-ms-client-flatten: true
parameters:
  AccountName:
    name: accountName
    type: string
    pattern: ^[a-zA-Z0-9][a-zA-Z0-9\-_]{0,127}$
    in: path
    required: true
    description: The name of the NetApp account
    x-ms-parameter-location: method
  BackupPolicyName:
    name: backupPolicyName
    in: path
    required: true
    type: string
    description: Backup policy Name which uniquely identify backup policy.
    x-ms-parameter-location: method
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
