swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector ContactAssignment API
schemes:
- https
tags:
- name: ContactAssignment
paths:
  /contactAssignments/{contactAssignmentId}:
    get:
      tags:
      - ContactAssignment
      description: Get a contactAssignment
      operationId: microsoftAzureContactassignmentsGetcontactassignment
      produces:
      - application/json
      parameters:
      - in: path
        name: contactAssignmentId
        required: true
        type: string
      - $ref: '#/parameters/api-version'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/ContactAssignment'
        default:
          description: An error response received from the provider.
          schema:
            $ref: '#/definitions/ErrorResponseModel'
      x-ms-examples:
        ContactAssignments_GetContactAssignment:
          $ref: ./examples/ContactAssignments_GetContactAssignment.json
      summary: Microsoft Azure Get Contactassignments Contactassignmentid
    put:
      tags:
      - ContactAssignment
      description: Creates or updates a contactAssignment entity.
      operationId: microsoftAzureContactassignmentsCreateorupdatecontactassignment
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: path
        name: contactAssignmentId
        required: true
        type: string
      - $ref: '#/parameters/api-version'
      - in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/ContactAssignment'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/ContactAssignment'
        default:
          description: An error response received from the provider.
          schema:
            $ref: '#/definitions/ErrorResponseModel'
      x-ms-examples:
        ContactAssignments_CreateOrUpdateContactAssignment:
          $ref: ./examples/ContactAssignments_CreateOrUpdateContactAssignment.json
      summary: Microsoft Azure Put Contactassignments Contactassignmentid
    delete:
      tags:
      - ContactAssignment
      description: Deletes a ContactAssignment entity.
      operationId: microsoftAzureContactassignmentsDeletecontactassignment
      produces:
      - application/json
      parameters:
      - in: path
        name: contactAssignmentId
        required: true
        type: string
      - $ref: '#/parameters/api-version'
      responses:
        '204':
          description: No Content
        default:
          description: An error response received from the provider.
          schema:
            $ref: '#/definitions/ErrorResponseModel'
      x-ms-examples:
        ContactAssignments_DeleteContactAssignment:
          $ref: ./examples/ContactAssignments_DeleteContactAssignment.json
      summary: Microsoft Azure Delete Contactassignments Contactassignmentid
  /contactAssignments:
    get:
      tags:
      - ContactAssignment
      description: List the contactAssignments in the account.
      operationId: microsoftAzureContactassignmentsListcontactassignments
      produces:
      - application/json
      parameters:
      - in: query
        name: scope
        type: string
      - in: query
        name: contactGroupDefinition
        type: string
      - in: query
        name: referenceType
        type: string
        enum:
        - Unknown
        - CollectionReference
        - ContactGroupDefinitionReference
        - DatasourceReference
        - ScanReference
        - AdaptiveScopeReference
        x-ms-enum:
          name: EntityReferenceType
          modelAsString: true
      - $ref: '#/parameters/api-version'
      - in: query
        name: $skipToken
        type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/ContactAssignmentList'
        default:
          description: An error response received from the provider.
          schema:
            $ref: '#/definitions/ErrorResponseModel'
      x-ms-pageable:
        nextLinkName: nextLink
      x-ms-examples:
        ContactAssignments_ListContactAssignments:
          $ref: ./examples/ContactAssignments_ListContactAssignments.json
      summary: Microsoft Azure Get Contactassignments
  /getScopedContactGroupNames:
    get:
      tags:
      - ContactAssignment
      description: Gets the distinct list of contact group names for the provided scope.
      operationId: microsoftAzureContactassignmentsListscopedcontactgroupnames
      produces:
      - application/json
      parameters:
      - in: query
        name: scope
        type: string
      - in: query
        name: referenceType
        type: string
        enum:
        - Unknown
        - CollectionReference
        - ContactGroupDefinitionReference
        - DatasourceReference
        - ScanReference
        - AdaptiveScopeReference
        x-ms-enum:
          name: EntityReferenceType
          modelAsString: true
      - $ref: '#/parameters/api-version'
      - in: query
        name: $skipToken
        type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/ContactGroupNameList'
        default:
          description: An error response received from the provider.
          schema:
            $ref: '#/definitions/ErrorResponseModel'
      x-ms-pageable:
        nextLinkName: nextLink
      x-ms-examples:
        ContactAssignments_ListScopedContactGroupNames:
          $ref: ./examples/ContactAssignments_ListScopedContactGroupNames.json
      summary: Microsoft Azure Get Getscopedcontactgroupnames
definitions:
  EntityReference:
    description: Entity reference type.
    type: object
    properties:
      referenceName:
        description: Gets or sets the reference name.
        type: string
      type:
        description: Gets or sets the reference type property.
        enum:
        - Unknown
        - CollectionReference
        - ContactGroupDefinitionReference
        - DatasourceReference
        - ScanReference
        - AdaptiveScopeReference
        type: string
        x-ms-enum:
          name: EntityReferenceType
          modelAsString: true
  ErrorResponseModel:
    description: Default error response model
    type: object
    properties:
      error:
        $ref: '#/definitions/ErrorModel'
  ErrorModel:
    description: Default error model
    type: object
    properties:
      code:
        description: Gets or sets the code.
        type: string
        readOnly: true
      details:
        description: Gets or sets the details.
        type: array
        items:
          $ref: '#/definitions/ErrorModel'
        readOnly: true
      message:
        description: Gets or sets the messages.
        type: string
        readOnly: true
      target:
        description: Gets or sets the target.
        type: string
        readOnly: true
  ContactAssignmentList:
    description: Paged list of contactAssignment.
    required:
    - value
    type: object
    properties:
      count:
        format: int64
        description: Total item count.
        type: integer
      nextLink:
        description: The Url of next result page.
        type: string
      value:
        description: Collection of items of type results.
        type: array
        items:
          $ref: '#/definitions/ContactAssignment'
  ContactAssignment:
    description: ContactAssignment resource.
    type: object
    properties:
      assignmentId:
        format: uuid
        description: Gets or sets the id of the assignment.
        type: string
      contactGroup:
        $ref: '#/definitions/EntityReference'
      principalId:
        description: Gets or sets the principal Id.
        type: string
      scope:
        $ref: '#/definitions/EntityReference'
      systemData:
        $ref: '#/definitions/SystemData'
  ContactGroupNameList:
    description: Paged list of contact group names.
    required:
    - value
    type: object
    properties:
      count:
        format: int64
        description: Total item count.
        type: integer
      nextLink:
        description: The Url of next result page.
        type: string
      value:
        description: Collection of items of type results.
        type: array
        items:
          type: string
  SystemData:
    description: Metadata pertaining to creation and last modification of the resource.
    type: object
    properties:
      createdAt:
        format: date-time
        description: The timestamp of resource creation (UTC).
        type: string
        readOnly: true
      createdBy:
        description: The identity that created the resource.
        type: string
        readOnly: true
      createdByType:
        description: The type of identity that created the resource.
        enum:
        - User
        - Application
        - ManagedIdentity
        - Key
        type: string
        readOnly: true
        x-ms-enum:
          name: IdentityType
          modelAsString: true
      lastModifiedAt:
        format: date-time
        description: The timestamp of the last modification the resource (UTC).
        type: string
        readOnly: true
      lastModifiedBy:
        description: The identity that last modified the resource.
        type: string
        readOnly: true
      lastModifiedByType:
        description: The type of identity that last modified the resource.
        enum:
        - User
        - Application
        - ManagedIdentity
        - Key
        type: string
        readOnly: true
        x-ms-enum:
          name: IdentityType
          modelAsString: true
parameters:
  api-version:
    in: query
    name: api-version
    description: The api version to use.
    required: true
    type: string
    x-ms-client-name: ApiVersion
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
