swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector Routes API
schemes:
- https
tags:
- name: Routes
paths:
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/routeTables/{routeTableName}/routes/{routeName}
  : delete:
      tags:
      - Routes
      operationId: microsoftAzureRoutesDelete
      description: The delete route operation deletes the specified route from a route table.
      parameters:
      - name: resourceGroupName
        in: path
        required: true
        type: string
        description: The name of the resource group.
      - name: routeTableName
        in: path
        required: true
        type: string
        description: The name of the route table.
      - name: routeName
        in: path
        required: true
        type: string
        description: The name of the route.
      - $ref: '#/parameters/ApiVersionParameter'
      - $ref: '#/parameters/SubscriptionIdParameter'
      responses:
        '200':
          description: ''
        '202':
          description: ''
        '204':
          description: ''
      x-ms-long-running-operation: true
      summary: Microsoft Azure Delete Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Network Routetables Routetablename Routes Routename
    get:
      tags:
      - Routes
      operationId: microsoftAzureRoutesGet
      description: The Get route operation retrieves information about the specified route from the route table.
      parameters:
      - name: resourceGroupName
        in: path
        required: true
        type: string
        description: The name of the resource group.
      - name: routeTableName
        in: path
        required: true
        type: string
        description: The name of the route table.
      - name: routeName
        in: path
        required: true
        type: string
        description: The name of the route.
      - $ref: '#/parameters/ApiVersionParameter'
      - $ref: '#/parameters/SubscriptionIdParameter'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Route'
      summary: Microsoft Azure Get Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Network Routetables Routetablename Routes Routename
    put:
      tags:
      - Routes
      operationId: microsoftAzureRoutesCreateorupdate
      description: The Put route operation creates/updates a route in the specified route table
      parameters:
      - name: resourceGroupName
        in: path
        required: true
        type: string
        description: The name of the resource group.
      - name: routeTableName
        in: path
        required: true
        type: string
        description: The name of the route table.
      - name: routeName
        in: path
        required: true
        type: string
        description: The name of the route.
      - name: routeParameters
        in: body
        required: true
        schema:
          $ref: '#/definitions/Route'
        description: Parameters supplied to the create/update route operation
      - $ref: '#/parameters/ApiVersionParameter'
      - $ref: '#/parameters/SubscriptionIdParameter'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Route'
        '201':
          description: ''
          schema:
            $ref: '#/definitions/Route'
      x-ms-long-running-operation: true
      summary: Microsoft Azure Put Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Network Routetables Routetablename Routes Routename
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/routeTables/{routeTableName}/routes
  : get:
      tags:
      - Routes
      operationId: microsoftAzureRoutesList
      description: The List network security rule operation retrieves all the routes in a route table.
      parameters:
      - name: resourceGroupName
        in: path
        required: true
        type: string
        description: The name of the resource group.
      - name: routeTableName
        in: path
        required: true
        type: string
        description: The name of the route table.
      - $ref: '#/parameters/ApiVersionParameter'
      - $ref: '#/parameters/SubscriptionIdParameter'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/RouteListResult'
      x-ms-pageable:
        nextLinkName: nextLink
      summary: Microsoft Azure Get Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Network Routetables Routetablename Routes
definitions:
  RouteListResult:
    properties:
      value:
        type: array
        items:
          $ref: '#/definitions/Route'
        description: Gets List of Routes in a resource group
      nextLink:
        type: string
        description: Gets the URL to get the next set of results.
    description: Response for ListRoute Api service call
  SubResource:
    properties:
      id:
        type: string
        description: Resource Id
    x-ms-azure-resource: true
  Route:
    properties:
      properties:
        x-ms-client-flatten: true
        $ref: '#/definitions/RoutePropertiesFormat'
      name:
        type: string
        description: Gets name of the resource that is unique within a resource group. This name can be used to access the resource
      etag:
        type: string
        description: A unique read-only string that changes whenever the resource is updated
    allOf:
    - $ref: '#/definitions/SubResource'
    description: Route resource
  RoutePropertiesFormat:
    properties:
      addressPrefix:
        type: string
        description: Gets or sets the destination CIDR to which the route applies.
      nextHopType:
        type: string
        description: Gets or sets the type of Azure hop the packet should be sent to.
        enum:
        - VirtualNetworkGateway
        - VnetLocal
        - Internet
        - VirtualAppliance
        - None
        x-ms-enum:
          name: RouteNextHopType
          modelAsString: true
      nextHopIpAddress:
        type: string
        description: Gets or sets the IP address packets should be forwarded to. Next hop values are only allowed in routes where the next hop type is VirtualAppliance.
      provisioningState:
        type: string
        description: Gets or sets Provisioning state of the resource Updating/Deleting/Failed
    required:
    - nextHopType
    description: Route resource
parameters:
  ApiVersionParameter:
    name: api-version
    in: query
    required: true
    type: string
    description: Client Api Version.
  SubscriptionIdParameter:
    name: subscriptionId
    in: path
    required: true
    type: string
    description: Gets subscription credentials which uniquely identify Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
