swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector Quotas API
schemes:
- https
tags:
- name: Quotas
paths:
  /subscriptions/{subscriptionId}/providers/Microsoft.AzurePlaywrightService/locations/{location}/quotas:
    get:
      operationId: microsoftAzureQuotasListbysubscription
      tags:
      - Quotas
      description: List quotas for a given subscription Id.
      parameters:
      - $ref: ../../../../../common-types/resource-management/v5/types.json#/parameters/ApiVersionParameter
      - $ref: ../../../../../common-types/resource-management/v5/types.json#/parameters/SubscriptionIdParameter
      - name: location
        in: path
        description: The location of quota in ARM Normalized format like eastus, southeastasia etc.
        required: true
        type: string
      responses:
        '200':
          description: Azure operation completed successfully.
          schema:
            $ref: '#/definitions/QuotaListResult'
        default:
          description: An unexpected error response.
          schema:
            $ref: ../../../../../common-types/resource-management/v5/types.json#/definitions/ErrorResponse
      x-ms-examples:
        Quotas_ListBySubscription:
          $ref: ./examples/Quotas_ListBySubscription.json
      x-ms-pageable:
        nextLinkName: nextLink
      summary: Get Subscriptions Subscriptionid Providers Microsoft Azureplaywrightservice Locations Location Quotas
  /subscriptions/{subscriptionId}/providers/Microsoft.AzurePlaywrightService/locations/{location}/quotas/{quotaName}:
    get:
      operationId: microsoftAzureQuotasGet
      tags:
      - Quotas
      description: Get subscription quota by name.
      parameters:
      - $ref: ../../../../../common-types/resource-management/v5/types.json#/parameters/ApiVersionParameter
      - $ref: ../../../../../common-types/resource-management/v5/types.json#/parameters/SubscriptionIdParameter
      - name: location
        in: path
        description: The location of quota in ARM Normalized format like eastus, southeastasia etc.
        required: true
        type: string
      - name: quotaName
        in: path
        description: The quota name.
        required: true
        type: string
        enum:
        - ScalableExecution
        x-ms-enum:
          name: QuotaNames
          modelAsString: true
          values:
          - name: ScalableExecution
            value: ScalableExecution
            description: The quota details for scalable execution feature. When enabled, Playwright client workers can connect to cloud-hosted browsers. This can increase the number of parallel workers for a test run, significantly minimizing test completion durations.
      responses:
        '200':
          description: Azure operation completed successfully.
          schema:
            $ref: '#/definitions/Quota'
        default:
          description: An unexpected error response.
          schema:
            $ref: ../../../../../common-types/resource-management/v5/types.json#/definitions/ErrorResponse
      x-ms-examples:
        Quotas_Get:
          $ref: ./examples/Quotas_Get.json
      summary: Get Subscriptions Subscriptionid Providers Microsoft Azureplaywrightservice Locations Location Quotas Quotaname
definitions:
  QuotaListResult:
    type: object
    description: The response of a Quota list operation.
    properties:
      value:
        type: array
        description: The Quota items on this page
        items:
          $ref: '#/definitions/Quota'
      nextLink:
        type: string
        format: uri
        description: The link to the next page of items
    required:
    - value
  Quota:
    type: object
    description: A subscription quota resource.
    properties:
      properties:
        $ref: '#/definitions/QuotaProperties'
        description: The resource-specific properties for this resource.
        x-ms-client-flatten: true
        x-ms-mutability:
        - read
        - create
    allOf:
    - $ref: ../../../../../common-types/resource-management/v5/types.json#/definitions/ProxyResource
  FreeTrialState:
    type: string
    description: The free-trial state.
    enum:
    - Active
    - Expired
    - NotEligible
    - NotRegistered
    x-ms-enum:
      name: FreeTrialState
      modelAsString: true
      values:
      - name: Active
        value: Active
        description: The free-trial is Active.
      - name: Expired
        value: Expired
        description: The free-trial is Expired.
      - name: NotEligible
        value: NotEligible
        description: The free-trial is Not Eligible.
      - name: NotRegistered
        value: NotRegistered
        description: The free-trial is Not Registered.
  ProvisioningState:
    type: string
    description: The status of the current operation.
    enum:
    - Succeeded
    - Failed
    - Canceled
    - Creating
    - Deleting
    - Accepted
    x-ms-enum:
      name: ProvisioningState
      modelAsString: true
      values:
      - name: Succeeded
        value: Succeeded
        description: Resource has been created.
      - name: Failed
        value: Failed
        description: Resource creation failed.
      - name: Canceled
        value: Canceled
        description: Resource creation was canceled.
      - name: Creating
        value: Creating
        description: Creation in progress..
      - name: Deleting
        value: Deleting
        description: Deletion in progress..
      - name: Accepted
        value: Accepted
        description: Change accepted for processing..
  FreeTrialProperties:
    type: object
    description: The subscription quota resource free-trial properties.
    properties:
      accountId:
        type: string
        description: The Playwright service account id.
        readOnly: true
      state:
        $ref: '#/definitions/FreeTrialState'
        description: The free-trial state.
        readOnly: true
    required:
    - accountId
    - state
  QuotaProperties:
    type: object
    description: The subscription quota resource properties.
    properties:
      freeTrial:
        $ref: '#/definitions/FreeTrialProperties'
        description: The subscription quota resource free-trial properties.
      provisioningState:
        $ref: '#/definitions/ProvisioningState'
        description: The status of the last operation.
        readOnly: true
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
