openapi: 3.2.0
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector Exposure Control API
tags:
- name: ExposureControl
paths:
  /features:
    post:
      tags:
      - ExposureControl
      description: Gets details from a list of features.
      operationId: microsoftAzureExposurecontrolGetfeatures
      parameters:
      - $ref: '#/components/parameters/api-version'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchFeatureStatus'
        default:
          description: An error response received from the provider.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseModel'
      x-ms-examples:
        ExposureControl_GetFeatures:
          $ref: ./examples/ExposureControl_GetFeatures.json
      summary: Microsoft Azure Post Features
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BatchFeatureRequest'
        required: true
components:
  schemas:
    BatchFeatureStatus:
      description: List of features with enabled status
      type: object
      properties:
        features:
          description: Features with enabled status
          type: object
          additionalProperties:
            type: boolean
          readOnly: true
    ErrorModel:
      description: Default error model
      type: object
      properties:
        code:
          description: Gets or sets the code.
          type: string
          readOnly: true
        details:
          description: Gets or sets the details.
          type: array
          items:
            $ref: '#/components/schemas/ErrorModel'
          readOnly: true
        message:
          description: Gets or sets the messages.
          type: string
          readOnly: true
        target:
          description: Gets or sets the target.
          type: string
          readOnly: true
    ErrorResponseModel:
      description: Default error response model
      type: object
      properties:
        error:
          $ref: '#/components/schemas/ErrorModel'
    BatchFeatureRequest:
      description: Feature request model
      type: object
      properties:
        features:
          description: Set of features
          uniqueItems: true
          type: array
          items:
            type: string
  parameters:
    api-version:
      in: query
      name: api-version
      description: The api version to use.
      required: true
      x-ms-client-name: ApiVersion
      schema:
        type: string
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/components/parameters/Endpoint'
