swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector Test Base Customer Event API
schemes:
- https
tags:
- name: Test Base Customer Event
paths:
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.TestBase/testBaseAccounts/{testBaseAccountName}/customerEvents/{customerEventName}
  : put:
      tags:
      - Test Base Customer Event
      operationId: microsoftAzureCustomereventsCreate
      description: Create or replace a Test Base Customer Event.
      x-ms-long-running-operation: true
      x-ms-long-running-operation-options:
        final-state-via: azure-async-operation
      parameters:
      - name: parameters
        in: body
        required: true
        schema:
          $ref: '#/definitions/CustomerEventResource'
        description: Parameters supplied to create a Test Base CustomerEvent.
      - $ref: '#/parameters/SubscriptionIdParameter'
      - $ref: '#/parameters/ResourceGroupParameter'
      - $ref: '#/parameters/TestBaseAccountNameParameter'
      - $ref: '#/parameters/CustomerEventNameParameter'
      - $ref: '#/parameters/ApiVersionParameter'
      responses:
        '200':
          description: The Test Base Customer Event was successfully created or updated.
          schema:
            $ref: '#/definitions/CustomerEventResource'
        '201':
          description: The Test Base Customer Event 'create' or 'update' operation was successfully enqueued. Check provisioningState to see detailed status.
          headers:
            Azure-AsyncOperation:
              description: URL to query for status of the operation.
              type: string
          schema:
            $ref: '#/definitions/CustomerEventResource'
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: '#/definitions/ErrorResponse'
      x-ms-examples:
        CustomerEventCreate:
          $ref: ./examples/CustomerEventCreate.json
      summary: Microsoft Azure Put Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Testbase Testbaseaccounts Testbaseaccountname Customerevents Customereventname
    delete:
      tags:
      - Test Base Customer Event
      operationId: microsoftAzureCustomereventsDelete
      description: Deletes a Test Base Customer Event.
      x-ms-long-running-operation: true
      x-ms-long-running-operation-options:
        final-state-via: azure-async-operation
      parameters:
      - $ref: '#/parameters/SubscriptionIdParameter'
      - $ref: '#/parameters/ResourceGroupParameter'
      - $ref: '#/parameters/TestBaseAccountNameParameter'
      - $ref: '#/parameters/CustomerEventNameParameter'
      - $ref: '#/parameters/ApiVersionParameter'
      responses:
        '200':
          description: The Test Base Customer Event 'delete' operation was completed successfully.
        '202':
          description: The Test Base Customer Event 'delete' operation was successfully enqueued. Follow the Location header to poll for final outcome.
          headers:
            Azure-AsyncOperation:
              description: URL to query for status of the operation.
              type: string
            Location:
              description: URL to query for status of the operation.
              type: string
        '204':
          description: The Test Base Customer Event 'delete' operation was completed successfully.
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: '#/definitions/ErrorResponse'
      x-ms-examples:
        CustomerEventDelete:
          $ref: ./examples/CustomerEventDelete.json
      summary: Microsoft Azure Delete Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Testbase Testbaseaccounts Testbaseaccountname Customerevents Customereventname
    get:
      tags:
      - Test Base Customer Event
      operationId: microsoftAzureCustomereventsGet
      description: Gets a Test Base CustomerEvent.
      parameters:
      - $ref: '#/parameters/SubscriptionIdParameter'
      - $ref: '#/parameters/ResourceGroupParameter'
      - $ref: '#/parameters/TestBaseAccountNameParameter'
      - $ref: '#/parameters/CustomerEventNameParameter'
      - $ref: '#/parameters/ApiVersionParameter'
      responses:
        '200':
          description: The Test Base Customer Event was successfully found.
          schema:
            $ref: '#/definitions/CustomerEventResource'
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: '#/definitions/ErrorResponse'
      x-ms-examples:
        CustomerEventGet:
          $ref: ./examples/CustomerEventGet.json
      summary: Microsoft Azure Get Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Testbase Testbaseaccounts Testbaseaccountname Customerevents Customereventname
definitions:
  ErrorDefinition:
    description: Error definition.
    properties:
      code:
        description: The error code.
        type: string
        readOnly: true
      message:
        description: The error message.
        type: string
        readOnly: true
      target:
        type: string
        description: The target of the particular error.
        readOnly: true
      details:
        description: The error details.
        type: array
        items:
          $ref: '#/definitions/ErrorDefinition'
        readOnly: true
  ErrorResponse:
    description: The error response send when an operation fails.
    properties:
      error:
        $ref: '#/definitions/ErrorDefinition'
        description: The error details.
  UserObjectReceiverValue:
    description: The user object receiver value.
    properties:
      userObjectIds:
        type: array
        items:
          type: string
        description: user object ids.
  ProxyResource:
    description: The resource model definition for an ARM proxy resource. It will have everything other than required location and tags
    allOf:
    - $ref: '#/definitions/Resource'
  Resource:
    description: The Resource definition.
    properties:
      id:
        readOnly: true
        type: string
        description: Resource ID.
      name:
        readOnly: true
        type: string
        description: Resource name.
      type:
        readOnly: true
        type: string
        description: Resource type.
    x-ms-azure-resource: true
  SubscriptionReceiverValue:
    description: The subscription role receiver value.
    properties:
      subscriptionId:
        type: string
        description: The subscription id of the notification receiver.
      subscriptionName:
        type: string
        description: The subscription name of the notification receiver.
      role:
        type: string
        description: The role of the notification receiver.
  CustomerEventProperties:
    description: A notification events subscribed to be received by customer.
    properties:
      eventName:
        type: string
        description: The name of the event subscribed to.
      receivers:
        type: array
        items:
          $ref: '#/definitions/NotificationEventReceiver'
        description: The notification event receivers.
    required:
    - eventName
    - receivers
  NotificationEventReceiver:
    description: A notification event receivers.
    properties:
      receiverType:
        type: string
        description: The type of the notification event receiver.
      receiverValue:
        description: The notification event receiver value.
        $ref: '#/definitions/NotificationReceiverValue'
  SystemData:
    description: Metadata pertaining to creation and last modification of the resource.
    type: object
    readOnly: true
    properties:
      createdBy:
        type: string
        description: The identity that created the resource.
      createdByType:
        type: string
        description: The type of identity that created the resource.
        enum:
        - User
        - Application
        - ManagedIdentity
        - Key
        x-ms-enum:
          name: createdByType
          modelAsString: true
      createdAt:
        type: string
        format: date-time
        description: The timestamp of resource creation (UTC).
      lastModifiedBy:
        type: string
        description: The identity that last modified the resource.
      lastModifiedByType:
        type: string
        description: The type of identity that last modified the resource.
        enum:
        - User
        - Application
        - ManagedIdentity
        - Key
        x-ms-enum:
          name: createdByType
          modelAsString: true
      lastModifiedAt:
        type: string
        format: date-time
        description: The type of identity that last modified the resource.
  CustomerEventResource:
    description: The Customer Notification Event resource.
    properties:
      systemData:
        description: The system metadata relating to this resource
        $ref: '#/definitions/SystemData'
      properties:
        $ref: '#/definitions/CustomerEventProperties'
        x-ms-client-flatten: true
        description: Customer Notification Event properties.
    allOf:
    - $ref: '#/definitions/ProxyResource'
  NotificationReceiverValue:
    description: A notification event receiver value.
    properties:
      userObjectReceiverValue:
        description: The user object receiver value.
        $ref: '#/definitions/UserObjectReceiverValue'
      subscriptionReceiverValue:
        description: The user object receiver value.
        $ref: '#/definitions/SubscriptionReceiverValue'
      distributionGroupListReceiverValue:
        description: The user object receiver value.
        $ref: '#/definitions/DistributionGroupListReceiverValue'
  DistributionGroupListReceiverValue:
    description: The user object receiver value.
    properties:
      distributionGroups:
        type: array
        items:
          type: string
        description: The list of distribution groups.
parameters:
  ApiVersionParameter:
    name: api-version
    in: query
    required: true
    type: string
    description: The API version to be used with the HTTP request.
  CustomerEventNameParameter:
    name: customerEventName
    in: path
    required: true
    type: string
    x-ms-parameter-location: method
    description: The resource name of the Test Base Customer event.
  ResourceGroupParameter:
    name: resourceGroupName
    in: path
    required: true
    type: string
    x-ms-parameter-location: method
    description: The name of the resource group that contains the resource.
  SubscriptionIdParameter:
    name: subscriptionId
    in: path
    required: true
    type: string
    description: The Azure subscription ID. This is a GUID-formatted string.
  TestBaseAccountNameParameter:
    name: testBaseAccountName
    in: path
    required: true
    type: string
    x-ms-parameter-location: method
    description: The resource name of the Test Base Account.
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
