swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector GlobalReachConnections API
schemes:
- https
tags:
- name: GlobalReachConnections
  description: ''
paths:
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.AVS/privateClouds/{privateCloudName}/globalReachConnections
  : get:
      operationId: microsoftAzureGlobalreachconnectionsList
      x-ms-pageable:
        nextLinkName: nextLink
      tags:
      - GlobalReachConnections
      summary: Microsoft Azure List Global Reach Connections In A Private Cloud
      parameters:
      - $ref: ../../../../../common-types/resource-management/v1/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../common-types/resource-management/v1/types.json#/parameters/ResourceGroupNameParameter
      - $ref: '#/parameters/privateCloudName'
      - $ref: ../../../../../common-types/resource-management/v1/types.json#/parameters/ApiVersionParameter
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/GlobalReachConnectionList'
        default:
          description: Error response describing why the operation failed
          schema:
            $ref: '#/definitions/CloudError'
      x-ms-examples:
        GlobalReachConnections_List:
          $ref: ./examples/GlobalReachConnections_List.json
      description: Needs a more full description created.
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.AVS/privateClouds/{privateCloudName}/globalReachConnections/{globalReachConnectionName}
  : get:
      operationId: microsoftAzureGlobalreachconnectionsGet
      tags:
      - GlobalReachConnections
      summary: Microsoft Azure Get A Global Reach Connection By Name In A Private Cloud
      parameters:
      - $ref: ../../../../../common-types/resource-management/v1/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../common-types/resource-management/v1/types.json#/parameters/ResourceGroupNameParameter
      - $ref: '#/parameters/privateCloudName'
      - $ref: '#/parameters/globalReachConnectionName'
      - $ref: ../../../../../common-types/resource-management/v1/types.json#/parameters/ApiVersionParameter
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/GlobalReachConnection'
        default:
          description: Error response describing why the operation failed
          schema:
            $ref: '#/definitions/CloudError'
      x-ms-examples:
        GlobalReachConnections_Get:
          $ref: ./examples/GlobalReachConnections_Get.json
      description: Needs a more full description created.
    put:
      operationId: microsoftAzureGlobalreachconnectionsCreateorupdate
      x-ms-long-running-operation: true
      tags:
      - GlobalReachConnections
      summary: Microsoft Azure Create Or Update A Global Reach Connection In A Private Cloud
      parameters:
      - $ref: ../../../../../common-types/resource-management/v1/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../common-types/resource-management/v1/types.json#/parameters/ResourceGroupNameParameter
      - name: privateCloudName
        in: path
        required: true
        type: string
        description: The name of the private cloud.
      - $ref: '#/parameters/globalReachConnectionName'
      - name: globalReachConnection
        description: A global reach connection in the private cloud
        in: body
        required: true
        schema:
          $ref: '#/definitions/GlobalReachConnection'
      - $ref: ../../../../../common-types/resource-management/v1/types.json#/parameters/ApiVersionParameter
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/GlobalReachConnection'
        '201':
          description: accepted operation
          schema:
            $ref: '#/definitions/GlobalReachConnection'
        default:
          description: Error response describing why the operation failed
          schema:
            $ref: '#/definitions/CloudError'
      x-ms-examples:
        GlobalReachConnections_CreateOrUpdate:
          $ref: ./examples/GlobalReachConnections_CreateOrUpdate.json
      description: Needs a more full description created.
    delete:
      operationId: microsoftAzureGlobalreachconnectionsDelete
      x-ms-long-running-operation: true
      tags:
      - GlobalReachConnections
      summary: Microsoft Azure Delete A Global Reach Connection In A Private Cloud
      parameters:
      - $ref: ../../../../../common-types/resource-management/v1/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../common-types/resource-management/v1/types.json#/parameters/ResourceGroupNameParameter
      - $ref: '#/parameters/privateCloudName'
      - $ref: '#/parameters/globalReachConnectionName'
      - $ref: ../../../../../common-types/resource-management/v1/types.json#/parameters/ApiVersionParameter
      responses:
        '200':
          description: OK. The delete has succeeded
        '202':
          description: Accepted. The delete will complete asynchronously
        '204':
          description: No Content. No global reach connection to delete
        default:
          description: Error response describing why the operation failed
          schema:
            $ref: '#/definitions/CloudError'
      x-ms-examples:
        GlobalReachConnections_Delete:
          $ref: ./examples/GlobalReachConnections_Delete.json
      description: Needs a more full description created.
definitions:
  GlobalReachConnectionProperties:
    description: The properties of a global reach connection
    properties:
      provisioningState:
        description: The state of the  ExpressRoute Circuit Authorization provisioning
        type: string
        readOnly: true
        enum:
        - Succeeded
        - Failed
        - Updating
        x-ms-enum:
          name: GlobalReachConnectionProvisioningState
          modelAsString: true
      addressPrefix:
        description: The network used for global reach carved out from the original network block provided for the private cloud
        type: string
        readOnly: true
      authorizationKey:
        description: Authorization key from the peer express route used for the global reach connection
        type: string
      circuitConnectionStatus:
        description: The connection status of the global reach connection
        type: string
        readOnly: true
        enum:
        - Connected
        - Connecting
        - Disconnected
        x-ms-enum:
          name: GlobalReachConnectionStatus
          modelAsString: true
      peerExpressRouteCircuit:
        type: string
        description: Identifier of the ExpressRoute Circuit to peer with in the global reach connection
  Resource:
    description: The core properties of ARM resources
    properties:
      id:
        description: Resource ID.
        readOnly: true
        type: string
      name:
        description: Resource name.
        readOnly: true
        type: string
      type:
        description: Resource type.
        readOnly: true
        type: string
    x-ms-azure-resource: true
  CloudError:
    x-ms-external: true
    properties:
      error:
        description: An error returned by the API
        $ref: ../../../../../common-types/resource-management/v1/types.json#/definitions/ErrorResponse
    description: API error response
  GlobalReachConnection:
    description: A global reach connection resource
    allOf:
    - $ref: '#/definitions/Resource'
    properties:
      properties:
        description: The properties of a global reach connection resource
        $ref: '#/definitions/GlobalReachConnectionProperties'
        x-ms-client-flatten: true
  GlobalReachConnectionList:
    description: A paged list of global reach connections
    properties:
      value:
        description: The items on a page
        type: array
        readOnly: true
        items:
          $ref: '#/definitions/GlobalReachConnection'
      nextLink:
        description: URL to get the next page if any
        type: string
        readOnly: true
parameters:
  privateCloudName:
    name: privateCloudName
    in: path
    required: true
    type: string
    description: Name of the private cloud
    x-ms-parameter-location: method
  globalReachConnectionName:
    name: globalReachConnectionName
    in: path
    required: true
    type: string
    description: Name of the global reach connection in the private cloud
    x-ms-parameter-location: method
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
