swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector AzureBareMetal API
schemes:
- https
tags:
- name: AzureBareMetal
paths:
  /providers/Microsoft.BareMetalInfrastructure/operations:
    get:
      tags:
      - AzureBareMetal
      operationId: microsoftAzureOperationsList
      x-ms-examples:
        List all management operations supported by the AzureBareMetal RP:
          $ref: ./examples/AzureBareMetalOperations_List.json
      description: Gets a list of AzureBareMetal management operations.
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - $ref: ../../../../../common-types/resource-management/v1/types.json#/parameters/ApiVersionParameter
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/OperationList'
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: '#/definitions/ErrorResponse'
      x-ms-pageable:
        nextLinkName: null
      summary: Microsoft Azure Get Providers Microsoft Baremetalinfrastructure Operations
definitions:
  ErrorDefinition:
    description: Error definition.
    properties:
      code:
        description: Service specific error code which serves as the substatus for the HTTP error code.
        type: string
        readOnly: true
      message:
        description: Description of the error.
        type: string
        readOnly: true
      details:
        description: Internal error details.
        type: array
        items:
          $ref: '#/definitions/ErrorDefinition'
        x-ms-identifiers: []
        readOnly: true
  ErrorResponse:
    description: Error response.
    properties:
      error:
        $ref: '#/definitions/ErrorDefinition'
        description: The error details.
  Operation:
    type: object
    properties:
      name:
        readOnly: true
        type: string
        description: The name of the operation being performed on this particular object. This name should match the action name that appears in RBAC / the event service.
      display:
        $ref: '#/definitions/Display'
        description: Displayed AzureBareMetal operation information
      isDataAction:
        readOnly: true
        description: indicates whether an operation is a data action or not.
        type: boolean
    description: AzureBareMetal operation information
  OperationList:
    type: object
    properties:
      value:
        type: array
        items:
          $ref: '#/definitions/Operation'
        x-ms-identifiers:
        - name
        description: List of AzureBareMetal operations
    description: List of AzureBareMetal operations
  Display:
    type: object
    properties:
      provider:
        readOnly: true
        type: string
        description: The localized friendly form of the resource provider name. This form is also expected to include the publisher/company responsible. Use Title Casing. Begin with "Microsoft" for 1st party services.
      resource:
        readOnly: true
        type: string
        description: The localized friendly form of the resource type related to this action/operation. This form should match the public documentation for the resource provider. Use Title Casing. For examples, refer to the “name” section.
      operation:
        readOnly: true
        type: string
        description: The localized friendly name for the operation as shown to the user. This name should be concise (to fit in drop downs), but clear (self-documenting). Use Title Casing and include the entity/resource to which it applies.
      description:
        readOnly: true
        type: string
        description: The localized friendly description for the operation as shown to the user. This description should be thorough, yet concise. It will be used in tool-tips and detailed views.
      origin:
        readOnly: true
        type: string
        description: The intended executor of the operation; governs the display of the operation in the RBAC UX and the audit logs UX. Default value is 'user,system'
    description: Detailed BareMetal operation information
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
