openapi: 3.2.0
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector Solution Inference API
tags:
- name: SolutionInference
paths:
  /solutions/{solutionId}:cancel:
    post:
      tags:
      - SolutionInference
      description: Cancels a job for given solution id.
      operationId: microsoftAzureSolutioninferenceCancel
      parameters:
      - in: path
        name: solutionId
        description: Id of solution for which job is to be cancelled.
        required: true
        schema:
          type: string
          pattern: ^[a-zA-Z]{3,50}[.][a-zA-Z]{3,100}$
      - in: query
        name: api-version
        description: The requested API version
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                additionalProperties: {}
        default:
          description: Error
          headers:
            x-ms-error-code:
              x-ms-client-name: ErrorCode
              schema:
                type: string
          x-ms-error-response: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      x-ms-examples:
        SolutionInference_Cancel:
          $ref: ./examples/SolutionInference_Cancel.json
      summary: Microsoft Azure Post Solutions Solutionid:cancel
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SolutionInference'
        description: solutionInferenceRequest containing input needed for job request processing.
        required: true
  /solutions/{solutionId}:create:
    post:
      tags:
      - SolutionInference
      description: Creates a job trigger for a solution.
      operationId: microsoftAzureSolutioninferenceCreateorupdate
      parameters:
      - in: path
        name: solutionId
        description: Id of the solution resource.
        required: true
        schema:
          type: string
          pattern: ^[a-zA-Z]{3,50}[.][a-zA-Z]{3,100}$
      - in: query
        name: api-version
        description: The requested API version
        required: true
        schema:
          type: string
      responses:
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                type: object
                additionalProperties: {}
        default:
          description: Error
          headers:
            x-ms-error-code:
              x-ms-client-name: ErrorCode
              schema:
                type: string
          x-ms-error-response: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      x-ms-long-running-operation: true
      x-ms-long-running-operation-options:
        final-state-via: location
      x-ms-examples:
        SolutionInference_CreateOrUpdate:
          $ref: ./examples/SolutionInference_CreateOrUpdate.json
      summary: Microsoft Azure Post Solutions Solutionid:create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SolutionInference'
        description: solutionInferenceRequest containing input needed for job request processing.
        required: true
  /solutions/{solutionId}:fetch:
    post:
      tags:
      - SolutionInference
      description: Fetches details of triggered job for a solution.
      operationId: microsoftAzureSolutioninferenceFetch
      parameters:
      - in: path
        name: solutionId
        description: Id of the solution.
        required: true
        schema:
          type: string
          pattern: ^[a-zA-Z]{3,50}[.][a-zA-Z]{3,100}$
      - in: query
        name: api-version
        description: The requested API version
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                additionalProperties: {}
        default:
          description: Error
          headers:
            x-ms-error-code:
              x-ms-client-name: ErrorCode
              schema:
                type: string
          x-ms-error-response: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      x-ms-examples:
        SolutionInference_Fetch:
          $ref: ./examples/SolutionInference_Fetch.json
      summary: Microsoft Azure Post Solutions Solutionid:fetch
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SolutionInference'
        description: solutionInferenceRequest containing input needed for job request processing.
        required: true
components:
  schemas:
    ErrorResponse:
      description: An error response from the Azure AgPlatform service. See https://github.com/Microsoft/api-guidelines/blob/vNext/Guidelines.md#7102-error-condition-responses for ErrorResponse reference document.
      type: object
      properties:
        error:
          $ref: '#/components/schemas/Error'
        traceId:
          description: Unique trace Id.
          type: string
    InnerError:
      description: Inner error containing list of errors.See https://github.com/Microsoft/api-guidelines/blob/vNext/Guidelines.md#innererror--object for InnerError reference document.
      type: object
      properties:
        code:
          description: Specific error code than was provided by the containing error.
          type: string
        innererror:
          $ref: '#/components/schemas/InnerError'
    SolutionInference:
      description: SolutionInference request model.
      required:
      - requestPath
      type: object
      properties:
        requestPath:
          description: 'RequestPath containing the api-version, query parameters and path route to be called for partner request.

            Expected format is "/{api-version}/{resourceExposedByPartner}/{customerDefinedJobId}?query1=value1".

            Not following this format may result into validation errors.'
          minLength: 1
          type: string
        partnerRequestBody:
          description: Api input parameters required by partner to trigger/cancel job request.
          type: object
          additionalProperties: {}
    Error:
      description: An error from the Azure AgPlatform service.
      required:
      - code
      - message
      type: object
      properties:
        code:
          description: Server-defined set of error codes.
          minLength: 1
          type: string
        message:
          description: Human-readable representation of the error.
          minLength: 1
          type: string
        target:
          description: Target of the error.
          type: string
        details:
          description: Array of details about specific errors that led to this reported error.
          type: array
          items:
            $ref: '#/components/schemas/Error'
        innererror:
          $ref: '#/components/schemas/InnerError'
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/components/parameters/Endpoint'
