swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector Domain API
schemes:
- https
tags:
- name: Domain
paths:
  /domains/{domainName}:
    get:
      tags:
      - Domain
      description: Get a domain
      operationId: microsoftAzureDomainsGetdomain
      produces:
      - application/json
      parameters:
      - in: path
        name: domainName
        required: true
        type: string
      - $ref: '#/parameters/api-version'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Domain'
        default:
          description: An error response received from the provider.
          schema:
            $ref: '#/definitions/ErrorResponseModel'
      x-ms-examples:
        Domains_GetDomain:
          $ref: ./examples/Domains_GetDomain.json
      summary: Microsoft Azure Get Domains Domainname
  /domains:
    get:
      tags:
      - Domain
      description: List the domains in the account.
      operationId: microsoftAzureDomainsListdomains
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/api-version'
      - in: query
        name: $skipToken
        type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/DomainList'
        default:
          description: An error response received from the provider.
          schema:
            $ref: '#/definitions/ErrorResponseModel'
      x-ms-pageable:
        nextLinkName: nextLink
      x-ms-examples:
        Domains_ListDomains:
          $ref: ./examples/Domains_ListDomains.json
      summary: Microsoft Azure Get Domains
  /{tenantID}/domains:
    get:
      tags:
      - Domain
      operationId: microsoftAzureDomainsList
      description: Gets a list of domains for the current tenant.
      parameters:
      - name: $filter
        in: query
        required: false
        type: string
        description: The filter to apply to the operation.
      - $ref: '#/parameters/ApiVersionParameter'
      - $ref: '#/parameters/tenantIDInPath'
      responses:
        '200':
          description: OK. The operation was successful.
          schema:
            $ref: '#/definitions/DomainListResult'
      x-ms-pageable:
        nextLinkName: null
      x-ms-odata: '#/definitions/User'
      summary: Microsoft Azure Get Tenantid Domains
  /{tenantID}/domains/{domainName}:
    get:
      tags:
      - Domain
      operationId: microsoftAzureDomainsGet
      description: Gets a specific domain in the current tenant.
      parameters:
      - name: domainName
        in: path
        required: true
        type: string
        description: name of the domain.
      - $ref: '#/parameters/ApiVersionParameter'
      - $ref: '#/parameters/tenantIDInPath'
      responses:
        '200':
          description: OK. The operation was successful.
          schema:
            $ref: '#/definitions/Domain_2'
      summary: Microsoft Azure Get Tenantid Domains Domainname
definitions:
  UserAssignedIdentity:
    description: Uses client ID and Principal ID
    type: object
    properties:
      clientId:
        description: Gets or Sets Client ID
        type: string
        readOnly: true
      principalId:
        description: Gets or Sets Principal ID
        type: string
        readOnly: true
  Identity:
    description: The Managed Identity of the resource
    type: object
    properties:
      principalId:
        description: Service principal object Id
        type: string
        readOnly: true
      tenantId:
        description: Tenant Id
        type: string
        readOnly: true
      type:
        description: Identity Type
        enum:
        - None
        - SystemAssigned
        - UserAssigned
        type: string
        x-ms-enum:
          name: ManagedIdentityType
          modelAsString: true
      userAssignedIdentities:
        description: User Assigned Identities
        type: object
        additionalProperties:
          $ref: '#/definitions/UserAssignedIdentity'
  ErrorResponseModel:
    description: Default error response model
    type: object
    properties:
      error:
        $ref: '#/definitions/ErrorModel'
  ErrorModel:
    description: Default error model
    type: object
    properties:
      code:
        description: Gets or sets the code.
        type: string
        readOnly: true
      details:
        description: Gets or sets the details.
        type: array
        items:
          $ref: '#/definitions/ErrorModel'
        readOnly: true
      message:
        description: Gets or sets the messages.
        type: string
        readOnly: true
      target:
        description: Gets or sets the target.
        type: string
        readOnly: true
  DomainMergeInfo:
    description: The public Domain Merge Info model.
    type: object
    properties:
      accountLocation:
        description: The account location of the source account in the merge operation.
        type: string
        readOnly: true
      accountName:
        description: The account name of the source account in the merge operation.
        type: string
        readOnly: true
      accountResourceGroupName:
        description: The resource group name of the source account in the merge operation.
        type: string
        readOnly: true
      accountSubscriptionId:
        description: The subscription id of the source account in the merge operation.
        type: string
        readOnly: true
      mergeStatus:
        description: The status of the merge operation.
        enum:
        - Succeeded
        - Failed
        - InProgress
        type: string
        readOnly: true
        x-ms-enum:
          name: MergeStatus
          modelAsString: true
  DomainListResult:
    type: object
    properties:
      value:
        type: array
        items:
          $ref: '#/definitions/Domain_2'
        description: the list of domains.
    description: Server response for Get tenant domains API call.
  Domain_2:
    type: object
    properties:
      authenticationType:
        type: string
        description: the type of the authentication into the domain.
        readOnly: true
      isDefault:
        type: boolean
        description: if this is the default domain in the tenant.
        readOnly: true
      isVerified:
        type: boolean
        description: if this domain's ownership is verified.
        readOnly: true
      name:
        type: string
        description: the domain name.
    required:
    - name
    additionalProperties:
      type: object
    description: Active Directory Domain information.
  Domain:
    description: Domain resource.
    type: object
    properties:
      containerType:
        description: Gets the container type.
        enum:
        - Domain
        - Collection
        type: string
        x-ms-enum:
          name: ContainerType
          modelAsString: true
      description:
        description: Gets or sets the description.
        type: string
      environment:
        description: Gets the environment of the domain.
        enum:
        - Prod
        - Test
        type: string
        x-ms-enum:
          name: DomainEnvironment
          modelAsString: true
      friendlyName:
        description: Gets or sets the friendly name of the domain.
        type: string
      identity:
        $ref: '#/definitions/Identity'
        readOnly: true
      mergeInfo:
        $ref: '#/definitions/DomainMergeInfo'
        readOnly: true
      name:
        description: Gets the name.
        type: string
        readOnly: true
      provisioningState:
        description: Gets the state of the provisioning.
        enum:
        - Unknown
        - Creating
        - Moving
        - Deleting
        - Failed
        - Succeeded
        type: string
        readOnly: true
        x-ms-enum:
          name: DomainProvisioningState
          modelAsString: true
      systemData:
        $ref: '#/definitions/SystemData'
  SystemData:
    description: Metadata pertaining to creation and last modification of the resource.
    type: object
    properties:
      createdAt:
        format: date-time
        description: The timestamp of resource creation (UTC).
        type: string
        readOnly: true
      createdBy:
        description: The identity that created the resource.
        type: string
        readOnly: true
      createdByType:
        description: The type of identity that created the resource.
        enum:
        - User
        - Application
        - ManagedIdentity
        - Key
        type: string
        readOnly: true
        x-ms-enum:
          name: IdentityType
          modelAsString: true
      lastModifiedAt:
        format: date-time
        description: The timestamp of the last modification the resource (UTC).
        type: string
        readOnly: true
      lastModifiedBy:
        description: The identity that last modified the resource.
        type: string
        readOnly: true
      lastModifiedByType:
        description: The type of identity that last modified the resource.
        enum:
        - User
        - Application
        - ManagedIdentity
        - Key
        type: string
        readOnly: true
        x-ms-enum:
          name: IdentityType
          modelAsString: true
  DomainList:
    description: Paged list of domains.
    required:
    - value
    type: object
    properties:
      count:
        format: int64
        description: Total item count.
        type: integer
      nextLink:
        description: The Url of next result page.
        type: string
      value:
        description: Collection of items of type results.
        type: array
        items:
          $ref: '#/definitions/Domain'
parameters:
  ApiVersionParameter:
    name: api-version
    in: query
    required: true
    type: string
    description: Client API version.
  tenantIDInPath:
    name: tenantID
    in: path
    required: true
    type: string
    description: The tenant ID.
    x-ms-parameter-location: client
  api-version:
    in: query
    name: api-version
    description: The api version to use.
    required: true
    type: string
    x-ms-client-name: ApiVersion
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
