swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector NginxCertificate API
schemes:
- https
tags:
- name: NginxCertificate
paths:
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Nginx.NginxPlus/nginxDeployments/{deploymentName}/certificates/{certificateName}
  : get:
      tags:
      - NginxCertificate
      summary: Microsoft Azure Get A Certificate Of Given Nginx Deployment
      operationId: microsoftAzureCertificatesGet
      produces:
      - application/json
      parameters:
      - $ref: ../../../../../common-types/resource-management/v1/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../common-types/resource-management/v1/types.json#/parameters/ResourceGroupNameParameter
      - $ref: '#/parameters/DeploymentNameParameter'
      - in: path
        name: certificateName
        description: The name of certificate
        required: true
        type: string
      - $ref: ../../../../../common-types/resource-management/v1/types.json#/parameters/ApiVersionParameter
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/NginxCertificate'
        default:
          description: Default error response.
          schema:
            $ref: '#/definitions/ResourceProviderDefaultErrorResponse'
      x-ms-examples:
        Certificates_Get:
          $ref: ./examples/Certificates_Get.json
      description: Needs a more full description created.
    put:
      tags:
      - NginxCertificate
      summary: Microsoft Azure Create Or Update The Nginx Certificates For Given Nginx Deployment
      operationId: microsoftAzureCertificatesCreate
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - $ref: ../../../../../common-types/resource-management/v1/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../common-types/resource-management/v1/types.json#/parameters/ResourceGroupNameParameter
      - $ref: '#/parameters/DeploymentNameParameter'
      - in: path
        name: certificateName
        description: The name of certificate
        required: true
        type: string
      - $ref: ../../../../../common-types/resource-management/v1/types.json#/parameters/ApiVersionParameter
      - in: body
        name: body
        description: The certificate
        schema:
          $ref: '#/definitions/NginxCertificate'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/NginxCertificate'
        '201':
          description: Success
          schema:
            $ref: '#/definitions/NginxCertificate'
        default:
          description: Default error response.
          schema:
            $ref: '#/definitions/ResourceProviderDefaultErrorResponse'
      x-ms-long-running-operation: true
      x-ms-long-running-operation-options:
        final-state-via: azure-async-operation
      x-ms-examples:
        Certificates_CreateOrUpdate:
          $ref: ./examples/Certificates_CreateOrUpdate.json
      description: Needs a more full description created.
    delete:
      tags:
      - NginxCertificate
      summary: Microsoft Azure Deletes A Certificate From The Nginx Deployment
      operationId: microsoftAzureCertificatesDelete
      produces:
      - application/json
      parameters:
      - $ref: ../../../../../common-types/resource-management/v1/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../common-types/resource-management/v1/types.json#/parameters/ResourceGroupNameParameter
      - $ref: '#/parameters/DeploymentNameParameter'
      - in: path
        name: certificateName
        description: The name of certificate
        required: true
        type: string
      - $ref: ../../../../../common-types/resource-management/v1/types.json#/parameters/ApiVersionParameter
      responses:
        '200':
          description: Success
        '202':
          description: Success
        '204':
          description: Success
        default:
          description: Default error response.
          schema:
            $ref: '#/definitions/ResourceProviderDefaultErrorResponse'
      x-ms-long-running-operation: true
      x-ms-examples:
        Certificates_Delete:
          $ref: ./examples/Certificates_Delete.json
      description: Needs a more full description created.
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Nginx.NginxPlus/nginxDeployments/{deploymentName}/certificates
  : get:
      tags:
      - NginxCertificate
      summary: Microsoft Azure List All Certificates Of Given Nginx Deployment
      operationId: microsoftAzureCertificatesList
      produces:
      - application/json
      parameters:
      - $ref: ../../../../../common-types/resource-management/v1/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../common-types/resource-management/v1/types.json#/parameters/ResourceGroupNameParameter
      - $ref: '#/parameters/DeploymentNameParameter'
      - $ref: ../../../../../common-types/resource-management/v1/types.json#/parameters/ApiVersionParameter
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/NginxCertificateListResponse'
        default:
          description: Default error response.
          schema:
            $ref: '#/definitions/ResourceProviderDefaultErrorResponse'
      x-ms-pageable:
        nextLinkName: nextLink
      x-ms-examples:
        Certificates_List:
          $ref: ./examples/Certificates_List.json
      description: Needs a more full description created.
definitions:
  NginxCertificate:
    type: object
    x-ms-azure-resource: true
    properties:
      id:
        type: string
        readOnly: true
      name:
        type: string
        readOnly: true
      type:
        type: string
        readOnly: true
      properties:
        $ref: '#/definitions/NginxCertificateProperties'
      tags:
        type: object
        additionalProperties:
          type: string
      location:
        type: string
      systemData:
        $ref: ../../../../../common-types/resource-management/v2/types.json#/definitions/systemData
        readOnly: true
  NginxCertificateProperties:
    type: object
    properties:
      provisioningState:
        $ref: '#/definitions/ProvisioningState'
      keyVirtualPath:
        type: string
      certificateVirtualPath:
        type: string
      keyVaultSecretId:
        type: string
  ProvisioningState:
    enum:
    - Accepted
    - Creating
    - Updating
    - Deleting
    - Succeeded
    - Failed
    - Canceled
    - Deleted
    - NotSpecified
    type: string
    readOnly: true
    x-ms-enum:
      modelAsString: true
      name: ProvisioningState
  ResourceProviderDefaultErrorResponse:
    type: object
    properties:
      error:
        $ref: '#/definitions/ErrorResponseBody'
  NginxCertificateListResponse:
    type: object
    properties:
      value:
        type: array
        items:
          $ref: '#/definitions/NginxCertificate'
      nextLink:
        type: string
  ErrorResponseBody:
    type: object
    properties:
      code:
        type: string
      message:
        type: string
      target:
        type: string
      details:
        type: array
        items:
          $ref: '#/definitions/ErrorResponseBody'
        x-ms-identifiers: []
parameters:
  DeploymentNameParameter:
    in: path
    name: deploymentName
    description: The name of targeted Nginx deployment
    required: true
    type: string
    x-ms-parameter-location: method
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
