openapi: 3.2.0
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector Service Principals By App ID API
tags:
- name: ServicePrincipalsByAppId
paths:
  /{tenantID}/servicePrincipalsByAppId/{applicationID}/objectId:
    get:
      tags:
      - ServicePrincipalsByAppId
      operationId: microsoftAzureApplicationsGetserviceprincipalsidbyappid
      description: Gets an object id for a given application id from the current tenant.
      parameters:
      - $ref: '#/components/parameters/ApiVersionParameter'
      - $ref: '#/components/parameters/tenantIDInPath'
      - name: applicationID
        in: path
        required: true
        description: The application ID.
        schema:
          type: string
      responses:
        '200':
          description: OK. The operation was successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServicePrincipalObjectResult'
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GraphError'
      summary: Microsoft Azure Get Tenantid Serviceprincipalsbyappid Applicationid Objectid
components:
  schemas:
    OdataError:
      type: object
      properties:
        code:
          type: string
          description: Error code.
        message:
          type: object
          x-ms-client-flatten: true
          $ref: '#/components/schemas/ErrorMessage'
          description: Error Message.
      description: Active Directory OData error information.
    ErrorMessage:
      type: object
      properties:
        value:
          type: string
          x-ms-client-name: message
          description: Error message value.
      description: Active Directory error message.
    ServicePrincipalObjectResult:
      type: object
      properties:
        value:
          type: string
          description: The Object ID of the service principal with the specified application ID.
        odata.metadata:
          type: string
          description: The URL representing edm equivalent.
      description: Service Principal Object Result.
    GraphError:
      type: object
      properties:
        odata.error:
          type: object
          x-ms-client-flatten: true
          $ref: '#/components/schemas/OdataError'
          description: A Graph API error.
      description: Active Directory error information.
  parameters:
    tenantIDInPath:
      name: tenantID
      in: path
      required: true
      description: The tenant ID.
      x-ms-parameter-location: client
      schema:
        type: string
    ApiVersionParameter:
      name: api-version
      in: query
      required: true
      description: Client API version.
      schema:
        type: string
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/components/parameters/Endpoint'
