openapi: 3.2.0
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector Entries API
tags:
- name: Entries
paths:
  /entries:
    post:
      operationId: microsoftAzureCreateentry
      description: Post an entry to be registered on the CodeTransparency instance.
      parameters:
      - $ref: '#/components/parameters/Azure.Core.Foundations.ApiVersionParameter'
      - $ref: '#/components/parameters/CoseEntry.body'
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateEntryResult'
        default:
          description: An unexpected error response.
          headers:
            x-ms-error-code:
              description: String error code indicating what went wrong.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Azure.Core.Foundations.ErrorResponse'
      x-ms-examples:
        CreateEntry:
          $ref: ./examples/CreateEntry.json
      summary: Microsoft Azure Post Entries
      tags:
      - Entries
  /entries/{entryId}:
    get:
      operationId: microsoftAzureGetentry
      description: Get Entry with or without receipt embedded in its unprotected header
      parameters:
      - $ref: '#/components/parameters/Azure.Core.Foundations.ApiVersionParameter'
      - $ref: '#/components/parameters/EmbedReceiptParameter.embedReceipt'
      - $ref: '#/components/parameters/EntryIdParameter'
      responses:
        '200':
          description: An Entry in Cose format
          content:
            application/cose:
              schema:
                type: string
                format: binary
            application/json:
              schema:
                type: string
                format: binary
        default:
          description: An unexpected error response.
          headers:
            x-ms-error-code:
              description: String error code indicating what went wrong.
              schema:
                type: string
          content:
            application/cose:
              schema:
                $ref: '#/components/schemas/Azure.Core.Foundations.ErrorResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/Azure.Core.Foundations.ErrorResponse'
      x-ms-examples:
        GetEntry:
          $ref: ./examples/GetEntry.json
      summary: Microsoft Azure Get Entries Entryid
      tags:
      - Entries
  /entries/{entryId}/receipt:
    get:
      operationId: microsoftAzureGetentryreceipt
      description: Get the receipt of an entry given a specific entry id.
      parameters:
      - $ref: '#/components/parameters/Azure.Core.Foundations.ApiVersionParameter'
      - $ref: '#/components/parameters/EntryIdParameter'
      responses:
        '200':
          description: A Raw Entry in cbor format
          content:
            application/cbor:
              schema:
                type: string
                format: binary
            application/json:
              schema:
                type: string
                format: binary
        default:
          description: An unexpected error response.
          headers:
            x-ms-error-code:
              description: String error code indicating what went wrong.
              schema:
                type: string
          content:
            application/cbor:
              schema:
                $ref: '#/components/schemas/Azure.Core.Foundations.ErrorResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/Azure.Core.Foundations.ErrorResponse'
      x-ms-examples:
        GetEntryReceipt:
          $ref: ./examples/GetEntryReceipt.json
      summary: Microsoft Azure Get Entries Entryid Receipt
      tags:
      - Entries
  /entries/txIds:
    get:
      operationId: microsoftAzureListentryids
      description: Historical query to get a list of entries of a given range
      parameters:
      - $ref: '#/components/parameters/Azure.Core.Foundations.ApiVersionParameter'
      - $ref: '#/components/parameters/TransactionsRange.from'
      - $ref: '#/components/parameters/TransactionsRange.to'
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntryIds'
        '503':
          description: Service unavailable.
          headers:
            Retry-After:
              description: Retry the same request after a suggested number of seconds
              schema:
                type: string
            x-ms-error-code:
              description: String error code indicating what went wrong.
              schema:
                type: string
          x-ms-error-response: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceUnavailableError'
        default:
          description: An unexpected error response.
          headers:
            x-ms-error-code:
              description: String error code indicating what went wrong.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Azure.Core.Foundations.ErrorResponse'
      x-ms-examples:
        ListEntryIds:
          $ref: ./examples/ListEntryIds.json
      x-ms-pageable:
        nextLinkName: nextLink
      summary: Microsoft Azure Get Entries Txids
      tags:
      - Entries
components:
  parameters:
    CoseEntry.body:
      name: body
      in: body
      description: A raw CoseSign1 signature
      required: true
      schema:
        type: string
        format: binary
      x-ms-parameter-location: method
    EntryIdParameter:
      name: entryId
      in: path
      description: ID of the entry to retrieve.
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
        pattern: ^[0-9]+\.[0-9]+$
    EmbedReceiptParameter.embedReceipt:
      name: embedReceipt
      in: query
      description: Embed a receipt as part of the response
      required: false
      x-ms-parameter-location: method
      schema:
        type: boolean
        default: false
    TransactionsRange.to:
      name: to
      in: query
      description: Ending Transaction Id
      required: false
      x-ms-parameter-location: method
      schema:
        type: integer
        format: int64
        minimum: 0
    Azure.Core.Foundations.ApiVersionParameter:
      name: api-version
      in: query
      description: The API version to use for this operation.
      required: true
      x-ms-parameter-location: method
      x-ms-client-name: apiVersion
      schema:
        type: string
        minLength: 1
    TransactionsRange.from:
      name: from
      in: query
      description: Starting Transaction Id
      required: false
      x-ms-parameter-location: method
      schema:
        type: integer
        format: int64
        minimum: 0
  schemas:
    CreateEntryResult:
      type: object
      description: Response of entry submission containing the operationId.
      properties:
        operationId:
          type: string
          description: String representing the operation id submitted
          pattern: ^[0-9]+\.[0-9]+$
      required:
      - operationId
    Azure.Core.Foundations.Error:
      type: object
      description: The error object.
      properties:
        code:
          type: string
          description: One of a server-defined set of error codes.
        message:
          type: string
          description: A human-readable representation of the error.
        target:
          type: string
          description: The target of the error.
        details:
          type: array
          description: An array of details about specific errors that led to this reported error.
          items:
            $ref: '#/components/schemas/Azure.Core.Foundations.Error'
          x-ms-identifiers: []
        innererror:
          $ref: '#/components/schemas/Azure.Core.Foundations.InnerError'
          description: An object containing more specific information than the current object about the error.
      required:
      - code
      - message
    Azure.Core.Foundations.InnerError:
      type: object
      description: An object containing more specific information about the error. As per Microsoft One API guidelines - https://github.com/Microsoft/api-guidelines/blob/vNext/Guidelines.md#7102-error-condition-responses.
      properties:
        code:
          type: string
          description: One of a server-defined set of error codes.
        innererror:
          $ref: '#/components/schemas/Azure.Core.Foundations.InnerError'
          description: Inner error.
    ServiceUnavailableError:
      type: object
      description: Service temporarily unavailable
      properties:
        error:
          $ref: '#/components/schemas/Azure.Core.Foundations.Error'
          description: The error object.
      required:
      - error
    Azure.Core.Foundations.ErrorResponse:
      type: object
      description: A response containing error details.
      properties:
        error:
          $ref: '#/components/schemas/Azure.Core.Foundations.Error'
          description: The error object.
      required:
      - error
    EntryIds:
      type: object
      description: A List of Entry IDs
      properties:
        transactionIds:
          type: array
          description: List of entry ids
          items:
            type: string
        nextLink:
          type: string
          description: Path to the next page of results
      required:
      - transactionIds
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/components/parameters/Endpoint'
