openapi: 3.2.0
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector Suggest Tags And Regions API
tags:
- name: SuggestTagsAndRegionsApi
paths:
  /projects/{projectId}/tagsandregions/suggestions:
    post:
      tags:
      - SuggestTagsAndRegionsApi
      summary: Microsoft Azure Suggest Tags And Regions For An Array Batch Of Untagged Images Returns Empty Array If No Tags Are Found
      description: This API will get suggested tags and regions for an array/batch of untagged images along with confidences for the tags. It returns an empty array if no tags are found.<br>There is a limit of 64 images in the batch.
      operationId: microsoftAzureSuggesttagsandregions
      parameters:
      - name: projectId
        in: path
        description: The project id.
        required: true
        schema:
          type: string
          format: uuid
      - name: iterationId
        in: query
        description: IterationId to use for tag and region suggestion.
        required: true
        schema:
          type: string
          format: uuid
      - name: imageIds
        in: query
        description: Array of image ids tag suggestion are needed for. Use GetUntaggedImages API to get imageIds.
        required: true
        style: form
        explode: false
        schema:
          type: array
          items:
            type: string
            format: uuid
          maxItems: 64
          minItems: 0
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SuggestedTagAndRegion'
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SuggestedTagAndRegion'
            text/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SuggestedTagAndRegion'
        default:
          description: Error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomVisionError'
            application/xml:
              schema:
                $ref: '#/components/schemas/CustomVisionError'
            text/xml:
              schema:
                $ref: '#/components/schemas/CustomVisionError'
      x-ms-examples:
        Successful SuggestTagsAndRegions request:
          $ref: ./examples/SuggestTagsAndRegions.json
components:
  schemas:
    BoundingBox:
      description: Bounding box that defines a region of an image.
      required:
      - left
      - top
      - width
      - height
      type: object
      properties:
        left:
          format: float
          description: Coordinate of the left boundary.
          type: number
          readOnly: false
        top:
          format: float
          description: Coordinate of the top boundary.
          type: number
          readOnly: false
        width:
          format: float
          description: Width.
          type: number
          readOnly: false
        height:
          format: float
          description: Height.
          type: number
          readOnly: false
    CustomVisionError:
      required:
      - code
      - message
      type: object
      properties:
        code:
          description: The error code.
          enum:
          - NoError
          - BadRequest
          - BadRequestExceededBatchSize
          - BadRequestNotSupported
          - BadRequestInvalidIds
          - BadRequestProjectName
          - BadRequestProjectNameNotUnique
          - BadRequestProjectDescription
          - BadRequestProjectUnknownDomain
          - BadRequestProjectUnknownClassification
          - BadRequestProjectUnsupportedDomainTypeChange
          - BadRequestProjectUnsupportedExportPlatform
          - BadRequestProjectImagePreprocessingSettings
          - BadRequestProjectDuplicated
          - BadRequestIterationName
          - BadRequestIterationNameNotUnique
          - BadRequestIterationDescription
          - BadRequestIterationIsNotTrained
          - BadRequestIterationValidationFailed
          - BadRequestWorkspaceCannotBeModified
          - BadRequestWorkspaceNotDeletable
          - BadRequestTagName
          - BadRequestTagNameNotUnique
          - BadRequestTagDescription
          - BadRequestTagType
          - BadRequestMultipleNegativeTag
          - BadRequestMultipleGeneralProductTag
          - BadRequestImageTags
          - BadRequestImageRegions
          - BadRequestNegativeAndRegularTagOnSameImage
          - BadRequestUnsupportedDomain
          - BadRequestRequiredParamIsNull
          - BadRequestIterationIsPublished
          - BadRequestInvalidPublishName
          - BadRequestInvalidPublishTarget
          - BadRequestUnpublishFailed
          - BadRequestIterationNotPublished
          - BadRequestSubscriptionApi
          - BadRequestExceedProjectLimit
          - BadRequestExceedIterationPerProjectLimit
          - BadRequestExceedTagPerProjectLimit
          - BadRequestExceedTagPerImageLimit
          - BadRequestExceededQuota
          - BadRequestCannotMigrateProjectWithName
          - BadRequestNotLimitedTrial
          - BadRequestImageBatch
          - BadRequestImageStream
          - BadRequestImageUrl
          - BadRequestImageFormat
          - BadRequestImageSizeBytes
          - BadRequestImageDimensions
          - BadRequestImageExceededCount
          - BadRequestTrainingNotNeeded
          - BadRequestTrainingNotNeededButTrainingPipelineUpdated
          - BadRequestTrainingValidationFailed
          - BadRequestClassificationTrainingValidationFailed
          - BadRequestMultiClassClassificationTrainingValidationFailed
          - BadRequestMultiLabelClassificationTrainingValidationFailed
          - BadRequestDetectionTrainingValidationFailed
          - BadRequestTrainingAlreadyInProgress
          - BadRequestDetectionTrainingNotAllowNegativeTag
          - BadRequestInvalidEmailAddress
          - BadRequestDomainNotSupportedForAdvancedTraining
          - BadRequestExportPlatformNotSupportedForAdvancedTraining
          - BadRequestReservedBudgetInHoursNotEnoughForAdvancedTraining
          - BadRequestExportValidationFailed
          - BadRequestExportAlreadyInProgress
          - BadRequestPredictionIdsMissing
          - BadRequestPredictionIdsExceededCount
          - BadRequestPredictionTagsExceededCount
          - BadRequestPredictionResultsExceededCount
          - BadRequestPredictionInvalidApplicationName
          - BadRequestPredictionInvalidQueryParameters
          - BadRequestInvalidImportToken
          - BadRequestExportWhileTraining
          - BadRequestImageMetadataKey
          - BadRequestImageMetadataValue
          - BadRequestOperationNotSupported
          - BadRequestInvalidArtifactUri
          - BadRequestCustomerManagedKeyRevoked
          - BadRequestInvalid
          - UnsupportedMediaType
          - Forbidden
          - ForbiddenUser
          - ForbiddenUserResource
          - ForbiddenUserSignupDisabled
          - ForbiddenUserSignupAllowanceExceeded
          - ForbiddenUserDoesNotExist
          - ForbiddenUserDisabled
          - ForbiddenUserInsufficientCapability
          - ForbiddenDRModeEnabled
          - ForbiddenInvalid
          - NotFound
          - NotFoundProject
          - NotFoundProjectDefaultIteration
          - NotFoundIteration
          - NotFoundIterationPerformance
          - NotFoundTag
          - NotFoundImage
          - NotFoundDomain
          - NotFoundApimSubscription
          - NotFoundInvalid
          - Conflict
          - ConflictInvalid
          - ErrorUnknown
          - ErrorIterationCopyFailed
          - ErrorPreparePerformanceMigrationFailed
          - ErrorProjectInvalidWorkspace
          - ErrorProjectInvalidPipelineConfiguration
          - ErrorProjectInvalidDomain
          - ErrorProjectTrainingRequestFailed
          - ErrorProjectImportRequestFailed
          - ErrorProjectExportRequestFailed
          - ErrorFeaturizationServiceUnavailable
          - ErrorFeaturizationQueueTimeout
          - ErrorFeaturizationInvalidFeaturizer
          - ErrorFeaturizationAugmentationUnavailable
          - ErrorFeaturizationUnrecognizedJob
          - ErrorFeaturizationAugmentationError
          - ErrorExporterInvalidPlatform
          - ErrorExporterInvalidFeaturizer
          - ErrorExporterInvalidClassifier
          - ErrorPredictionServiceUnavailable
          - ErrorPredictionModelNotFound
          - ErrorPredictionModelNotCached
          - ErrorPrediction
          - ErrorPredictionStorage
          - ErrorRegionProposal
          - ErrorUnknownBaseModel
          - ErrorInvalid
          type: string
          x-ms-enum:
            name: CustomVisionErrorCodes
            modelAsString: true
        message:
          description: A message explaining the error reported by the service.
          type: string
    Prediction:
      description: Prediction result.
      type: object
      properties:
        probability:
          format: float
          description: Probability of the tag.
          type: number
          readOnly: true
        tagId:
          format: uuid
          description: Id of the predicted tag.
          type: string
          readOnly: true
        tagName:
          description: Name of the predicted tag.
          type:
          - string
          - 'null'
          readOnly: true
        boundingBox:
          $ref: '#/components/schemas/BoundingBox'
          description: Bounding box of the prediction.
          readOnly: true
        tagType:
          description: Type of the predicted tag.
          enum:
          - Regular
          - Negative
          - GeneralProduct
          type:
          - string
          - 'null'
          readOnly: true
          x-ms-enum:
            name: TagType
            modelAsString: true
    SuggestedTagAndRegion:
      description: Result of a suggested tags and regions request.
      type: object
      properties:
        id:
          format: uuid
          description: Prediction Id.
          type: string
          readOnly: true
        project:
          format: uuid
          description: Project Id.
          type: string
          readOnly: true
        iteration:
          format: uuid
          description: Iteration Id.
          type: string
          readOnly: true
        created:
          format: date-time
          description: Date this prediction was created.
          type: string
          readOnly: true
        predictions:
          description: List of predictions.
          type: array
          items:
            $ref: '#/components/schemas/Prediction'
          readOnly: true
        predictionUncertainty:
          format: double
          description: Uncertainty (entropy) of suggested tags or regions per image.
          type: number
          readOnly: true
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/components/parameters/Endpoint'
