swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector ServerGroupOperations API
schemes:
- https
tags:
- name: ServerGroupOperations
paths:
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DBForPostgreSql/serverGroupsv2/{serverGroupName}/restart
  : post:
      description: Restarts the server group.
      tags:
      - ServerGroupOperations
      operationId: microsoftAzureServergroupsRestart
      x-ms-long-running-operation: true
      x-ms-examples:
        Restart all servers in the server group:
          $ref: ./examples/ServerGroupRestart.json
      parameters:
      - $ref: ../../../../../common-types/resource-management/v1/types.json#/parameters/ApiVersionParameter
      - $ref: ../../../../../common-types/resource-management/v1/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../common-types/resource-management/v1/types.json#/parameters/ResourceGroupNameParameter
      - $ref: '#/parameters/ServerGroupNameParameter'
      responses:
        '200':
          description: OK
        '202':
          description: Accepted
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: '#/definitions/CloudError'
      summary: Microsoft Azure Post Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Dbforpostgresql Servergroupsv2 Servergroupname Restart
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DBForPostgreSql/serverGroupsv2/{serverGroupName}/start
  : post:
      description: Starts the server group.
      tags:
      - ServerGroupOperations
      operationId: microsoftAzureServergroupsStart
      x-ms-long-running-operation: true
      x-ms-examples:
        Start all servers in the server group:
          $ref: ./examples/ServerGroupStart.json
      parameters:
      - $ref: ../../../../../common-types/resource-management/v1/types.json#/parameters/ApiVersionParameter
      - $ref: ../../../../../common-types/resource-management/v1/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../common-types/resource-management/v1/types.json#/parameters/ResourceGroupNameParameter
      - $ref: '#/parameters/ServerGroupNameParameter'
      responses:
        '200':
          description: OK
        '202':
          description: Accepted
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: '#/definitions/CloudError'
      summary: Microsoft Azure Post Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Dbforpostgresql Servergroupsv2 Servergroupname Start
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DBForPostgreSql/serverGroupsv2/{serverGroupName}/stop
  : post:
      description: Stops the server group.
      tags:
      - ServerGroupOperations
      operationId: microsoftAzureServergroupsStop
      x-ms-long-running-operation: true
      x-ms-examples:
        Stop all servers in the server group:
          $ref: ./examples/ServerGroupStop.json
      parameters:
      - $ref: ../../../../../common-types/resource-management/v1/types.json#/parameters/ApiVersionParameter
      - $ref: ../../../../../common-types/resource-management/v1/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../common-types/resource-management/v1/types.json#/parameters/ResourceGroupNameParameter
      - $ref: '#/parameters/ServerGroupNameParameter'
      responses:
        '200':
          description: OK
        '202':
          description: Accepted
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: '#/definitions/CloudError'
      summary: Microsoft Azure Post Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Dbforpostgresql Servergroupsv2 Servergroupname Stop
definitions:
  CloudErrorBody:
    x-ms-external: true
    description: An error response from the Batch service.
    properties:
      code:
        type: string
        description: An identifier for the error. Codes are invariant and are intended to be consumed programmatically.
      message:
        type: string
        description: A message describing the error, intended to be suitable for display in a user interface.
      target:
        type: string
        description: The target of the particular error. For example, the name of the property in error.
      details:
        type: array
        description: A list of additional details about the error.
        items:
          $ref: '#/definitions/CloudErrorBody'
        x-ms-identifiers:
        - code
  CloudError:
    x-ms-external: true
    description: An error response from the Batch service.
    properties:
      error:
        $ref: '#/definitions/CloudErrorBody'
        description: The error.
parameters:
  ServerGroupNameParameter:
    name: serverGroupName
    in: path
    required: true
    type: string
    description: The name of the server group.
    minLength: 1
    maxLength: 90
    x-ms-parameter-location: method
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
