swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector Asset API
schemes:
- https
tags:
- name: Asset
paths:
  ? /modelmanagement/v1.0/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.MachineLearningServices/workspaces/{workspace}/assets
  : get:
      tags:
      - Asset
      summary: Microsoft Azure Query The List Of Assets In A Workspace
      description: If no filter is passed, the query lists all the Assets in the given workspace. The returned list is paginated and the count of items in each page is an optional parameter.
      operationId: microsoftAzureAssetsListquery
      consumes: []
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/subscriptionIdParameter'
      - $ref: '#/parameters/resourceGroupParameter'
      - $ref: '#/parameters/workspaceParameter'
      - name: runId
        in: query
        description: The run Id associated with the Assets.
        required: false
        type: string
      - name: name
        in: query
        description: The object name.
        required: false
        type: string
      - name: count
        in: query
        description: The number of items to retrieve in a page.
        required: false
        type: integer
        format: int32
      - name: $skipToken
        in: query
        description: The continuation token to retrieve the next page.
        required: false
        type: string
      - name: tags
        in: query
        description: "A set of tags with which to filter the returned models.\r\n            It is a comma separated string of tags key or tags key=value\r\n            Example: tagKey1,tagKey2,tagKey3=value3"
        required: false
        type: string
      - name: properties
        in: query
        description: "A set of properties with which to filter the returned models.\r\n            It is a comma separated string of properties key and/or properties key=value\r\n            Example: propKey1,propKey2,propKey3=value3"
        required: false
        type: string
      - name: orderby
        in: query
        description: An option for specifying how to order the list.
        required: false
        type: string
        default: CreatedAtDesc
        enum:
        - CreatedAtDesc
        - CreatedAtAsc
        - UpdatedAtDesc
        - UpdatedAtAsc
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/PaginatedAssetList'
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: '#/definitions/ModelErrorResponse'
      x-ms-pageable:
        nextLinkName: nextLink
    post:
      tags:
      - Asset
      summary: Microsoft Azure Create An Asset
      description: Create an Asset from the provided payload.
      operationId: microsoftAzureAssetsCreate
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/subscriptionIdParameter'
      - $ref: '#/parameters/resourceGroupParameter'
      - $ref: '#/parameters/workspaceParameter'
      - name: asset
        in: body
        description: The Asset to be created.
        required: false
        schema:
          $ref: '#/definitions/Asset'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Asset'
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: '#/definitions/ModelErrorResponse'
  ? /modelmanagement/v1.0/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.MachineLearningServices/workspaces/{workspace}/assets/{id}
  : get:
      tags:
      - Asset
      summary: Microsoft Azure Get An Asset
      description: Get an Asset by Id.
      operationId: microsoftAzureAssetsQuerybyid
      consumes: []
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/subscriptionIdParameter'
      - $ref: '#/parameters/resourceGroupParameter'
      - $ref: '#/parameters/workspaceParameter'
      - name: id
        in: path
        description: The Asset Id.
        required: true
        type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Asset'
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: '#/definitions/ModelErrorResponse'
    delete:
      tags:
      - Asset
      summary: Microsoft Azure Delete An Asset
      description: Delete the specified Asset.
      operationId: microsoftAzureAssetsDelete
      consumes: []
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/subscriptionIdParameter'
      - $ref: '#/parameters/resourceGroupParameter'
      - $ref: '#/parameters/workspaceParameter'
      - name: id
        in: path
        description: The Id of the Asset to delete.
        required: true
        type: string
      responses:
        '200':
          description: The resource exists and was deleted successfully.
        '204':
          description: The resource does not exist and the request was well formed.
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: '#/definitions/ModelErrorResponse'
    patch:
      tags:
      - Asset
      summary: Microsoft Azure Update An Asset
      description: Patch a specific Asset.
      operationId: microsoftAzureAssetsPatch
      consumes:
      - application/json-patch+json
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/subscriptionIdParameter'
      - $ref: '#/parameters/resourceGroupParameter'
      - $ref: '#/parameters/workspaceParameter'
      - name: id
        in: path
        description: The Id of the Asset to patch.
        required: true
        type: string
      - name: patch
        in: body
        description: The payload that is used to patch an Asset.
        required: true
        schema:
          uniqueItems: false
          type: array
          items:
            $ref: '#/definitions/JsonPatchOperation'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Asset'
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: '#/definitions/ModelErrorResponse'
definitions:
  ModelErrorResponse:
    description: The Model Management Service Error object.
    type: object
    properties:
      code:
        description: The error code.
        type: string
      statusCode:
        format: int32
        description: The HTTP status code.
        type: integer
      message:
        description: The error message.
        type: string
      details:
        description: An array of error detail objects.
        uniqueItems: false
        type: array
        items:
          $ref: '#/definitions/ErrorDetails'
  Asset:
    description: The Asset definition.
    required:
    - name
    type: object
    properties:
      id:
        description: The Asset Id.
        type: string
      name:
        description: The name of the Asset.
        type: string
      description:
        description: The Asset description.
        type: string
      artifacts:
        description: A list of child artifacts.
        uniqueItems: false
        type: array
        items:
          $ref: '#/definitions/ArtifactDetails'
      kvTags:
        description: The Asset tag dictionary. Tags are mutable.
        type: object
        additionalProperties:
          type: string
      properties:
        description: The Asset property dictionary. Properties are immutable.
        type: object
        additionalProperties:
          type: string
      runid:
        description: The RunId associated with this Asset.
        type: string
      meta:
        description: A dictionary containing metadata about the Asset.
        type: object
        additionalProperties:
          type: string
      createdTime:
        format: date-time
        description: The time the Asset was created in UTC.
        type: string
        readOnly: true
  PaginatedAssetList:
    description: A paginated list of Assets.
    type: object
    properties:
      value:
        description: An array of objects of type Asset.
        uniqueItems: false
        type: array
        items:
          $ref: '#/definitions/Asset'
      nextLink:
        description: A continuation link (absolute URI) to the next page of results in the list.
        type: string
  ArtifactDetails:
    type: object
    properties:
      id:
        type: string
      prefix:
        type: string
  ErrorDetails:
    description: The error details.
    type: object
    properties:
      code:
        description: The error code.
        type: string
      message:
        description: The error message.
        type: string
      target:
        description: The target of the error (e.g., the name of the property in error).
        type: string
  JsonPatchOperation:
    description: The Json Patch definition.
    type: object
    properties:
      value:
        description: The value.
        type: object
      path:
        description: The target location.
        type: string
      op:
        description: The operation.
        type: string
      from:
        description: The source location.
        type: string
parameters:
  workspaceParameter:
    name: workspace
    in: path
    description: The name of the workspace.
    required: true
    type: string
    x-ms-parameter-location: method
  subscriptionIdParameter:
    name: subscriptionId
    in: path
    description: The Azure Subscription ID.
    required: true
    type: string
    format: uuid
    x-ms-parameter-location: method
  resourceGroupParameter:
    name: resourceGroup
    in: path
    description: The Name of the resource group in which the workspace is located.
    required: true
    type: string
    x-ms-parameter-location: method
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
