swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector CloudServiceRoles API
schemes:
- https
tags:
- name: CloudServiceRoles
paths:
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/cloudServices/{cloudServiceName}/roles/{roleName}
  : get:
      tags:
      - CloudServiceRoles
      description: Gets a role from a cloud service.
      operationId: microsoftAzureCloudservicerolesGet
      parameters:
      - in: path
        name: roleName
        description: Name of the role.
        required: true
        type: string
      - in: path
        name: resourceGroupName
        description: Name of the resource group.
        required: true
        type: string
      - in: path
        name: cloudServiceName
        description: Name of the cloud service.
        required: true
        type: string
      - $ref: ./common.json#/parameters/SubscriptionIdParameter
      - $ref: ./common.json#/parameters/ApiVersionParameter
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/CloudServiceRole'
        default:
          description: Error
          schema:
            $ref: ./common.json#/definitions/CloudError
      x-ms-examples:
        Get Cloud Service Role:
          $ref: ./examples/CloudServiceRole_Get.json
      summary: Microsoft Azure Get Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Compute Cloudservices Cloudservicename Roles Rolename
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/cloudServices/{cloudServiceName}/roles
  : get:
      tags:
      - CloudServiceRoles
      description: Gets a list of all roles in a cloud service. Use nextLink property in the response to get the next page of roles. Do this till nextLink is null to fetch all the roles.
      operationId: microsoftAzureCloudservicerolesList
      parameters:
      - in: path
        name: resourceGroupName
        description: Name of the resource group.
        required: true
        type: string
      - in: path
        name: cloudServiceName
        description: Name of the cloud service.
        required: true
        type: string
      - $ref: ./common.json#/parameters/SubscriptionIdParameter
      - $ref: ./common.json#/parameters/ApiVersionParameter
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/CloudServiceRoleListResult'
        default:
          description: Error
          schema:
            $ref: ./common.json#/definitions/CloudError
      x-ms-examples:
        List Roles in a Cloud Service:
          $ref: ./examples/CloudServiceRole_List.json
      x-ms-pageable:
        nextLinkName: nextLink
      summary: Microsoft Azure Get Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Compute Cloudservices Cloudservicename Roles
definitions:
  CloudServiceRoleListResult:
    description: The list operation result.
    type: object
    properties:
      value:
        description: The list of resources.
        type: array
        items:
          $ref: '#/definitions/CloudServiceRole'
      nextLink:
        description: The URI to fetch the next page of resources. Use this to get the next page of resources. Do this till nextLink is null to fetch all the resources.
        type: string
    required:
    - value
  CloudServiceRoleSku:
    description: Describes the cloud service role sku.
    type: object
    properties:
      name:
        description: 'The sku name. NOTE: If the new SKU is not supported on the hardware the cloud service is currently on, you need to delete and recreate the cloud service or move back to the old sku.'
        type: string
      tier:
        description: Specifies the tier of the cloud service. Possible Values are <br /><br /> **Standard** <br /><br /> **Basic**
        type: string
      capacity:
        format: int64
        description: Specifies the number of role instances in the cloud service.
        type: integer
  CloudServiceRole:
    description: Describes a role of the cloud service.
    type: object
    properties:
      id:
        description: Resource id
        type: string
        readOnly: true
      name:
        description: Resource name
        type: string
        readOnly: true
      type:
        description: Resource type
        type: string
        readOnly: true
      location:
        description: Resource location
        type: string
        readOnly: true
      sku:
        $ref: '#/definitions/CloudServiceRoleSku'
      properties:
        $ref: '#/definitions/CloudServiceRoleProperties'
  CloudServiceRoleProperties:
    description: The cloud service role properties.
    type: object
    properties:
      uniqueId:
        description: Specifies the ID which uniquely identifies a cloud service role.
        type: string
        readOnly: true
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
