swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector ReplicationvCenters API
schemes:
- https
tags:
- name: ReplicationvCenters
paths:
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.RecoveryServices/vaults/{resourceName}/replicationFabrics/{fabricName}/replicationvCenters
  : get:
      tags:
      - ReplicationvCenters
      summary: Microsoft Azure Gets The List Of Vcenter Registered Under A Fabric
      description: Lists the vCenter servers registered in a fabric.
      operationId: microsoftAzureReplicationvcentersListbyreplicationfabrics
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/ApiVersion'
      - $ref: '#/parameters/ResourceName'
      - $ref: '#/parameters/ResourceGroupName'
      - $ref: '#/parameters/SubscriptionId'
      - name: fabricName
        in: path
        description: Fabric name.
        required: true
        type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/VCenterCollection'
      x-ms-pageable:
        nextLinkName: nextLink
      x-ms-examples:
        Gets the list of vCenter registered under a fabric.:
          $ref: ./examples/ReplicationvCenters_ListByReplicationFabrics.json
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.RecoveryServices/vaults/{resourceName}/replicationFabrics/{fabricName}/replicationvCenters/{vcenterName}
  : get:
      tags:
      - ReplicationvCenters
      summary: Microsoft Azure Gets The Details Of A Vcenter
      description: Gets the details of a registered vCenter server(Add vCenter server).
      operationId: microsoftAzureReplicationvcentersGet
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/ApiVersion'
      - $ref: '#/parameters/ResourceName'
      - $ref: '#/parameters/ResourceGroupName'
      - $ref: '#/parameters/SubscriptionId'
      - name: fabricName
        in: path
        description: Fabric name.
        required: true
        type: string
      - name: vcenterName
        in: path
        description: vcenter name.
        required: true
        type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/VCenter'
      x-ms-examples:
        Gets the details of a vCenter.:
          $ref: ./examples/ReplicationvCenters_Get.json
    put:
      tags:
      - ReplicationvCenters
      summary: Microsoft Azure Add Vcenter
      description: The operation to create a vCenter object..
      operationId: microsoftAzureReplicationvcentersCreate
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/ApiVersion'
      - $ref: '#/parameters/ResourceName'
      - $ref: '#/parameters/ResourceGroupName'
      - $ref: '#/parameters/SubscriptionId'
      - name: fabricName
        in: path
        description: Fabric name.
        required: true
        type: string
      - name: vcenterName
        in: path
        description: vcenter name.
        required: true
        type: string
      - name: addVCenterRequest
        in: body
        description: The input to the add vCenter operation.
        required: true
        schema:
          $ref: '#/definitions/AddVCenterRequest'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/VCenter'
        '202':
          description: Accepted
      x-ms-long-running-operation: true
      x-ms-examples:
        Add vCenter.:
          $ref: ./examples/ReplicationvCenters_Create.json
    delete:
      tags:
      - ReplicationvCenters
      summary: Microsoft Azure Remove Vcenter Operation
      description: The operation to remove(unregister) a registered vCenter server from the vault.
      operationId: microsoftAzureReplicationvcentersDelete
      parameters:
      - $ref: '#/parameters/ApiVersion'
      - $ref: '#/parameters/ResourceName'
      - $ref: '#/parameters/ResourceGroupName'
      - $ref: '#/parameters/SubscriptionId'
      - name: fabricName
        in: path
        description: Fabric name.
        required: true
        type: string
      - name: vcenterName
        in: path
        description: vcenter name.
        required: true
        type: string
      responses:
        '202':
          description: Accepted
        '204':
          description: NoContent
      x-ms-long-running-operation: true
      x-ms-examples:
        Remove vCenter operation.:
          $ref: ./examples/ReplicationvCenters_Delete.json
    patch:
      tags:
      - ReplicationvCenters
      summary: Microsoft Azure Update Vcenter Operation
      description: The operation to update a registered vCenter.
      operationId: microsoftAzureReplicationvcentersUpdate
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/ApiVersion'
      - $ref: '#/parameters/ResourceName'
      - $ref: '#/parameters/ResourceGroupName'
      - $ref: '#/parameters/SubscriptionId'
      - name: fabricName
        in: path
        description: Fabric name.
        required: true
        type: string
      - name: vcenterName
        in: path
        description: vcenter name.
        required: true
        type: string
      - name: updateVCenterRequest
        in: body
        description: The input to the update vCenter operation.
        required: true
        schema:
          $ref: '#/definitions/UpdateVCenterRequest'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/VCenter'
        '202':
          description: Accepted
      x-ms-long-running-operation: true
      x-ms-examples:
        Update vCenter operation.:
          $ref: ./examples/ReplicationvCenters_Update.json
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.RecoveryServices/vaults/{resourceName}/replicationvCenters
  : get:
      tags:
      - ReplicationvCenters
      summary: Microsoft Azure Gets The List Of Vcenter Registered Under The Vault
      description: Lists the vCenter servers registered in the vault.
      operationId: microsoftAzureReplicationvcentersList
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/ApiVersion'
      - $ref: '#/parameters/ResourceName'
      - $ref: '#/parameters/ResourceGroupName'
      - $ref: '#/parameters/SubscriptionId'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/VCenterCollection'
      x-ms-pageable:
        nextLinkName: nextLink
      x-ms-examples:
        Gets the list of vCenter registered under the vault.:
          $ref: ./examples/ReplicationvCenters_List.json
definitions:
  VCenterCollection:
    description: Collection of vCenter details.
    type: object
    properties:
      value:
        description: The vCenter details.
        type: array
        items:
          $ref: '#/definitions/VCenter'
      nextLink:
        description: The value of next link.
        type: string
  InnerHealthError:
    description: Implements InnerHealthError class. HealthError object has a list of InnerHealthErrors as child errors. InnerHealthError is used because this will prevent an infinite loop of structures when Hydra tries to auto-generate the contract. We are exposing the related health errors as inner health errors and all API consumers can utilize this in the same fashion as Exception -&gt; InnerException.
    type: object
    properties:
      errorSource:
        description: Source of error.
        type: string
      errorType:
        description: Type of error.
        type: string
      errorLevel:
        description: Level of error.
        type: string
      errorCategory:
        description: Category of error.
        type: string
      errorCode:
        description: Error code.
        type: string
      summaryMessage:
        description: Summary message of the entity.
        type: string
      errorMessage:
        description: Error message.
        type: string
      possibleCauses:
        description: Possible causes of error.
        type: string
      recommendedAction:
        description: Recommended action to resolve error.
        type: string
      creationTimeUtc:
        format: date-time
        description: Error creation time (UTC).
        type: string
      recoveryProviderErrorMessage:
        description: DRA error message.
        type: string
      entityId:
        description: ID of the entity.
        type: string
      errorId:
        description: The health error unique id.
        type: string
      customerResolvability:
        description: Value indicating whether the health error is customer resolvable.
        enum:
        - Allowed
        - NotAllowed
        type: string
        x-ms-enum:
          name: HealthErrorCustomerResolvability
          modelAsString: true
  AddVCenterRequest:
    description: Input required to add vCenter.
    type: object
    properties:
      properties:
        $ref: '#/definitions/AddVCenterRequestProperties'
        description: The properties of an add vCenter request.
  Resource:
    description: Azure resource.
    type: object
    properties:
      id:
        description: Resource Id
        type: string
        readOnly: true
      name:
        description: Resource Name
        type: string
        readOnly: true
      type:
        description: Resource Type
        type: string
        readOnly: true
      location:
        description: Resource Location
        type: string
    x-ms-azure-resource: true
  UpdateVCenterRequest:
    description: Input required to update vCenter.
    type: object
    properties:
      properties:
        $ref: '#/definitions/UpdateVCenterRequestProperties'
        description: The update VCenter Request Properties.
  AddVCenterRequestProperties:
    description: The properties of an add vCenter request.
    type: object
    properties:
      friendlyName:
        description: The friendly name of the vCenter.
        type: string
      ipAddress:
        description: The IP address of the vCenter to be discovered.
        type: string
      processServerId:
        description: The process server Id from where the discovery is orchestrated.
        type: string
      port:
        description: The port number for discovery.
        type: string
      runAsAccountId:
        description: The account Id which has privileges to discover the vCenter.
        type: string
  HealthError:
    description: Health Error.
    type: object
    properties:
      innerHealthErrors:
        description: The inner health errors. HealthError having a list of HealthError as child errors is problematic. InnerHealthError is used because this will prevent an infinite loop of structures when Hydra tries to auto-generate the contract. We are exposing the related health errors as inner health errors and all API consumers can utilize this in the same fashion as Exception -&gt; InnerException.
        type: array
        items:
          $ref: '#/definitions/InnerHealthError'
      errorSource:
        description: Source of error.
        type: string
      errorType:
        description: Type of error.
        type: string
      errorLevel:
        description: Level of error.
        type: string
      errorCategory:
        description: Category of error.
        type: string
      errorCode:
        description: Error code.
        type: string
      summaryMessage:
        description: Summary message of the entity.
        type: string
      errorMessage:
        description: Error message.
        type: string
      possibleCauses:
        description: Possible causes of error.
        type: string
      recommendedAction:
        description: Recommended action to resolve error.
        type: string
      creationTimeUtc:
        format: date-time
        description: Error creation time (UTC).
        type: string
      recoveryProviderErrorMessage:
        description: DRA error message.
        type: string
      entityId:
        description: ID of the entity.
        type: string
      errorId:
        description: The health error unique id.
        type: string
      customerResolvability:
        description: Value indicating whether the health error is customer resolvable.
        enum:
        - Allowed
        - NotAllowed
        type: string
        x-ms-enum:
          name: HealthErrorCustomerResolvability
          modelAsString: true
  UpdateVCenterRequestProperties:
    description: The properties of an update vCenter request.
    type: object
    properties:
      friendlyName:
        description: The friendly name of the vCenter.
        type: string
      ipAddress:
        description: The IP address of the vCenter to be discovered.
        type: string
      processServerId:
        description: The process server Id from where the update can be orchestrated.
        type: string
      port:
        description: The port number for discovery.
        type: string
      runAsAccountId:
        description: The CS account Id which has privileges to update the vCenter.
        type: string
  VCenter:
    description: vCenter definition.
    type: object
    allOf:
    - $ref: '#/definitions/Resource'
    properties:
      properties:
        $ref: '#/definitions/VCenterProperties'
        description: VCenter related data.
  VCenterProperties:
    description: vCenter properties.
    type: object
    properties:
      friendlyName:
        description: Friendly name of the vCenter.
        type: string
      internalId:
        description: VCenter internal ID.
        type: string
      lastHeartbeat:
        format: date-time
        description: The time when the last heartbeat was received by vCenter.
        type: string
      discoveryStatus:
        description: The VCenter discovery status.
        type: string
      processServerId:
        description: The process server Id.
        type: string
      ipAddress:
        description: The IP address of the vCenter.
        type: string
      infrastructureId:
        description: The infrastructure Id of vCenter.
        type: string
      port:
        description: The port number for discovery.
        type: string
      runAsAccountId:
        description: The account Id which has privileges to discover the vCenter.
        type: string
      fabricArmResourceName:
        description: The ARM resource name of the fabric containing this VCenter.
        type: string
      healthErrors:
        description: The health errors for this VCenter.
        type: array
        items:
          $ref: '#/definitions/HealthError'
parameters:
  ResourceGroupName:
    name: resourceGroupName
    in: path
    description: The name of the resource group where the recovery services vault is present.
    required: true
    type: string
    x-ms-parameter-location: client
  ResourceName:
    name: resourceName
    in: path
    description: The name of the recovery services vault.
    required: true
    type: string
    x-ms-parameter-location: client
  ApiVersion:
    name: api-version
    in: query
    description: Client Api Version.
    required: true
    type: string
  SubscriptionId:
    name: subscriptionId
    in: path
    description: The subscription Id.
    required: true
    type: string
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
