swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector WorkflowVersions API
schemes:
- https
tags:
- name: WorkflowVersions
paths:
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Logic/workflows/{workflowName}/versions
  : get:
      tags:
      - WorkflowVersions
      operationId: microsoftAzureWorkflowversionsList
      description: Gets a list of workflow versions.
      x-ms-examples:
        List a workflows versions:
          $ref: ./examples/WorkflowVersions_List.json
      parameters:
      - $ref: '#/parameters/subscriptionId'
      - name: resourceGroupName
        description: The resource group name.
        in: path
        required: true
        type: string
      - name: workflowName
        description: The workflow name.
        in: path
        required: true
        type: string
      - $ref: '#/parameters/api-version'
      - name: $top
        description: The number of items to be included in the result.
        in: query
        required: false
        type: integer
        format: int32
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/WorkflowVersionListResult'
      x-ms-pageable:
        nextLinkName: nextLink
      summary: Microsoft Azure Get Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Logic Workflows Workflowname Versions
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Logic/workflows/{workflowName}/versions/{versionId}
  : get:
      tags:
      - WorkflowVersions
      operationId: microsoftAzureWorkflowversionsGet
      description: Gets a workflow version.
      x-ms-examples:
        Get a workflow version:
          $ref: ./examples/WorkflowVersions_Get.json
      parameters:
      - $ref: '#/parameters/subscriptionId'
      - name: resourceGroupName
        description: The resource group name.
        in: path
        required: true
        type: string
      - name: workflowName
        description: The workflow name.
        in: path
        required: true
        type: string
      - name: versionId
        description: The workflow versionId.
        in: path
        required: true
        type: string
      - $ref: '#/parameters/api-version'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/WorkflowVersion'
      summary: Microsoft Azure Get Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Logic Workflows Workflowname Versions Versionid
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Web/sites/{name}/hostruntime/runtime/webhooks/workflow/api/management/workflows/{workflowName}/versions
  : get:
      tags:
      - WorkflowVersions
      operationId: microsoftAzureWorkflowversionsList
      description: Gets a list of workflow versions.
      x-ms-examples:
        List a workflows versions:
          $ref: ./examples/WorkflowVersions_List.json
      parameters:
      - $ref: '#/parameters/subscriptionIdParameter'
      - $ref: '#/parameters/resourceGroupNameParameter'
      - $ref: '#/parameters/siteNameParameter'
      - name: workflowName
        description: The workflow name.
        in: path
        required: true
        type: string
      - $ref: '#/parameters/apiVersionParameter'
      - name: $top
        description: The number of items to be included in the result.
        in: query
        required: false
        type: integer
        format: int32
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/WorkflowVersionListResult_2'
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: '#/definitions/ErrorResponse'
      x-ms-pageable:
        nextLinkName: nextLink
      summary: Microsoft Azure Get Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Web Sites Name Hostruntime Runtime Webhooks Workflow Api Management Workflows Workflowname Versions
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Web/sites/{name}/hostruntime/runtime/webhooks/workflow/api/management/workflows/{workflowName}/versions/{versionId}
  : get:
      tags:
      - WorkflowVersions
      operationId: microsoftAzureWorkflowversionsGet
      description: Gets a workflow version.
      x-ms-examples:
        Get a workflow version:
          $ref: ./examples/WorkflowVersions_Get.json
      parameters:
      - $ref: '#/parameters/subscriptionIdParameter'
      - $ref: '#/parameters/resourceGroupNameParameter'
      - $ref: '#/parameters/siteNameParameter'
      - name: workflowName
        description: The workflow name.
        in: path
        required: true
        type: string
      - name: versionId
        description: The workflow versionId.
        in: path
        required: true
        type: string
      - $ref: '#/parameters/apiVersionParameter'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/WorkflowVersion_2'
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: '#/definitions/ErrorResponse'
      summary: Microsoft Azure Get Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Web Sites Name Hostruntime Runtime Webhooks Workflow Api Management Workflows Workflowname Versions Versionid
definitions:
  FlowAccessControlConfiguration:
    type: object
    description: The access control configuration.
    properties:
      triggers:
        $ref: '#/definitions/FlowAccessControlConfigurationPolicy'
        description: The access control configuration for invoking workflow triggers.
      contents:
        $ref: '#/definitions/FlowAccessControlConfigurationPolicy'
        description: The access control configuration for accessing workflow run contents.
      actions:
        $ref: '#/definitions/FlowAccessControlConfigurationPolicy'
        description: The access control configuration for workflow actions.
      workflowManagement:
        $ref: '#/definitions/FlowAccessControlConfigurationPolicy'
        description: The access control configuration for workflow management.
  Sku:
    type: object
    required:
    - name
    properties:
      name:
        $ref: '#/definitions/SkuName'
        description: The name.
      plan:
        $ref: '#/definitions/ResourceReference'
        description: The reference to plan.
    description: The sku type.
  WorkflowSku:
    type: object
    description: The sku type.
    required:
    - name
    properties:
      name:
        $ref: '#/definitions/WorkflowSkuName'
        description: The name.
      plan:
        $ref: '#/definitions/ResourceReference'
        description: The reference to plan.
  SkuName:
    type: string
    enum:
    - NotSpecified
    - Free
    - Shared
    - Basic
    - Standard
    - Premium
    x-ms-enum:
      name: SkuName
      modelAsString: true
    description: The sku name.
  WorkflowVersionListResult:
    type: object
    properties:
      value:
        type: array
        items:
          $ref: '#/definitions/WorkflowVersion'
        description: A list of workflow versions.
      nextLink:
        type: string
        description: The URL to get the next set of results.
    description: The list of workflow versions.
  WorkflowParameter:
    type: object
    properties:
      type:
        $ref: '#/definitions/ParameterType'
        description: The type.
      value:
        $ref: '#/definitions/Object'
        description: The value.
      metadata:
        $ref: '#/definitions/Object'
        description: The metadata.
      description:
        type: string
        description: The description.
    description: The workflow parameters.
  WorkflowSkuName:
    type: string
    enum:
    - NotSpecified
    - Free
    - Shared
    - Basic
    - Standard
    - Premium
    x-ms-enum:
      name: WorkflowSkuName
      modelAsString: true
    description: The sku name.
  Resource:
    properties:
      id:
        type: string
        readOnly: true
        description: The resource id.
      name:
        type: string
        readOnly: true
        description: Gets the resource name.
      type:
        type: string
        readOnly: true
        description: Gets the resource type.
      location:
        type: string
        description: The resource location.
      tags:
        type: object
        additionalProperties:
          type: string
        description: The resource tags.
    x-ms-azure-resource: true
    description: The base resource type.
  WorkflowVersionListResult_2:
    type: object
    properties:
      value:
        type: array
        items:
          $ref: '#/definitions/WorkflowVersion_2'
          description: The workflow version.
        description: A list of workflow versions.
      nextLink:
        type: string
        description: The URL to get the next set of results.
    description: The list of workflow versions.
  WorkflowProvisioningState:
    type: string
    description: The workflow provisioning state.
    enum:
    - NotSpecified
    - Accepted
    - Running
    - Ready
    - Creating
    - Created
    - Deleting
    - Deleted
    - Canceled
    - Failed
    - Succeeded
    - Moving
    - Updating
    - Registering
    - Registered
    - Unregistering
    - Unregistered
    - Completed
    - Renewing
    - Pending
    - Waiting
    - InProgress
    x-ms-enum:
      name: WorkflowProvisioningState
      modelAsString: true
  IpAddress:
    type: object
    description: The ip address.
    properties:
      address:
        type: string
        description: The address.
  WorkflowState_2:
    type: string
    description: The workflow state.
    enum:
    - NotSpecified
    - Completed
    - Enabled
    - Disabled
    - Deleted
    - Suspended
    x-ms-enum:
      name: WorkflowState
      modelAsString: true
  ParameterType:
    type: string
    enum:
    - NotSpecified
    - String
    - SecureString
    - Int
    - Float
    - Bool
    - Array
    - Object
    - SecureObject
    x-ms-enum:
      name: ParameterType
      modelAsString: true
  WorkflowVersion:
    type: object
    properties:
      properties:
        x-ms-client-flatten: true
        $ref: '#/definitions/WorkflowVersionProperties'
        description: The workflow version properties.
    description: The workflow version.
    allOf:
    - $ref: '#/definitions/Resource'
  FlowEndpoints:
    type: object
    description: The flow endpoints configuration.
    properties:
      outgoingIpAddresses:
        type: array
        description: The outgoing ip address.
        items:
          $ref: '#/definitions/IpAddress'
          description: The ip address.
        x-ms-identifiers:
        - address
      accessEndpointIpAddresses:
        type: array
        description: The access endpoint ip address.
        items:
          $ref: '#/definitions/IpAddress'
          description: The ip address.
        x-ms-identifiers:
        - address
  WorkflowVersion_2:
    type: object
    properties:
      properties:
        x-ms-client-flatten: true
        $ref: '#/definitions/WorkflowVersionProperties_2'
        description: The workflow version properties.
    description: The workflow version.
    allOf:
    - $ref: '#/definitions/WorkflowResource'
  FlowEndpointsConfiguration:
    type: object
    description: The endpoints configuration.
    properties:
      workflow:
        $ref: '#/definitions/FlowEndpoints'
        description: The workflow endpoints.
      connector:
        $ref: '#/definitions/FlowEndpoints'
        description: The connector endpoints.
  WorkflowVersionProperties:
    type: object
    properties:
      createdTime:
        type: string
        format: date-time
        readOnly: true
        description: Gets the created time.
      changedTime:
        type: string
        format: date-time
        readOnly: true
        description: Gets the changed time.
      state:
        $ref: '#/definitions/WorkflowState'
        description: The state.
      version:
        type: string
        readOnly: true
        description: Gets the version.
      accessEndpoint:
        type: string
        readOnly: true
        description: Gets the access endpoint.
      sku:
        $ref: '#/definitions/Sku'
        description: The sku.
      integrationAccount:
        $ref: '#/definitions/ResourceReference'
        description: The integration account.
      definition:
        $ref: '#/definitions/Object'
        description: The definition.
      parameters:
        type: object
        additionalProperties:
          $ref: '#/definitions/WorkflowParameter'
        description: The parameters.
    description: The workflow version properties.
  OpenAuthenticationPolicyClaim:
    type: object
    description: Open authentication policy claim.
    properties:
      name:
        type: string
        description: The name of the claim.
      value:
        type: string
        description: The value of the claim.
  OpenAuthenticationProviderType:
    type: string
    description: Open authentication policy provider type.
    enum:
    - AAD
    x-ms-enum:
      name: OpenAuthenticationProviderType
      modelAsString: true
  IpAddressRange:
    type: object
    description: The ip address range.
    properties:
      addressRange:
        type: string
        description: The IP address range.
  WorkflowState:
    type: string
    enum:
    - NotSpecified
    - Completed
    - Enabled
    - Disabled
    - Deleted
    - Suspended
    x-ms-enum:
      name: WorkflowState
      modelAsString: true
  ErrorProperties:
    description: Error properties indicate why the Logic service was not able to process the incoming request. The reason is provided in the error message.
    type: object
    properties:
      code:
        description: Error code.
        type: string
      message:
        description: Error message indicating why the operation failed.
        type: string
  WorkflowResource:
    type: object
    properties:
      id:
        type: string
        readOnly: true
        description: The resource id.
      name:
        type: string
        readOnly: true
        description: Gets the resource name.
      type:
        type: string
        readOnly: true
        description: Gets the resource type.
      location:
        type: string
        description: The resource location.
      tags:
        type: object
        additionalProperties:
          type: string
        description: The resource tags.
    x-ms-azure-resource: true
    description: The base resource type.
  ResourceReference:
    type: object
    properties:
      id:
        type: string
        description: The resource id.
      name:
        type: string
        readOnly: true
        description: Gets the resource name.
      type:
        type: string
        readOnly: true
        description: Gets the resource type.
    description: The resource reference.
  OpenAuthenticationAccessPolicy:
    type: object
    description: Open authentication access policy defined by user.
    properties:
      type:
        $ref: '#/definitions/OpenAuthenticationProviderType'
        description: Type of provider for OAuth.
      claims:
        type: array
        description: The access policy claims.
        items:
          $ref: '#/definitions/OpenAuthenticationPolicyClaim'
          description: The access policy claim.
        x-ms-identifiers:
        - name
  ErrorResponse:
    description: Error response indicates Logic service is not able to process the incoming request. The error property contains the error details.
    type: object
    properties:
      error:
        $ref: '#/definitions/ErrorProperties'
        description: The error properties.
  OpenAuthenticationAccessPolicies:
    type: object
    description: AuthenticationPolicy of type Open.
    properties:
      policies:
        type: object
        additionalProperties:
          $ref: '#/definitions/OpenAuthenticationAccessPolicy'
        description: Open authentication policies.
  Object:
    type: object
    properties: {}
  WorkflowVersionProperties_2:
    type: object
    properties:
      provisioningState:
        $ref: '#/definitions/WorkflowProvisioningState'
        readOnly: true
        description: The provisioning state.
      createdTime:
        type: string
        format: date-time
        readOnly: true
        description: Gets the created time.
      changedTime:
        type: string
        format: date-time
        readOnly: true
        description: Gets the changed time.
      state:
        $ref: '#/definitions/WorkflowState_2'
        description: The state.
      version:
        type: string
        readOnly: true
        description: Gets the version.
      accessEndpoint:
        type: string
        readOnly: true
        description: Gets the access endpoint.
      endpointsConfiguration:
        $ref: '#/definitions/FlowEndpointsConfiguration'
        description: The endpoints configuration.
      accessControl:
        $ref: '#/definitions/FlowAccessControlConfiguration'
        description: The access control configuration.
      sku:
        $ref: '#/definitions/WorkflowSku'
        readOnly: true
        description: The sku.
      integrationAccount:
        $ref: '#/definitions/ResourceReference'
        description: The integration account.
      definition:
        $ref: '#/definitions/Object'
        description: The definition.
      parameters:
        type: object
        additionalProperties:
          $ref: '#/definitions/WorkflowParameter'
        description: The parameters.
    description: The workflow version properties.
  FlowAccessControlConfigurationPolicy:
    type: object
    description: The access control configuration policy.
    properties:
      allowedCallerIpAddresses:
        type: array
        description: The allowed caller IP address ranges.
        items:
          $ref: '#/definitions/IpAddressRange'
          description: The ip address range.
        x-ms-identifiers: []
      openAuthenticationPolicies:
        $ref: '#/definitions/OpenAuthenticationAccessPolicies'
        description: The authentication policies for workflow.
parameters:
  resourceGroupNameParameter:
    name: resourceGroupName
    in: path
    description: Name of the resource group to which the resource belongs.
    required: true
    type: string
    maxLength: 90
    minLength: 1
    pattern: ^[-\w\._\(\)]+[^\.]$
    x-ms-parameter-location: method
  api-version:
    name: api-version
    description: The API version.
    in: query
    required: true
    type: string
  subscriptionId:
    name: subscriptionId
    description: The subscription id.
    in: path
    required: true
    type: string
  apiVersionParameter:
    name: api-version
    in: query
    description: API Version
    required: true
    type: string
    x-ms-parameter-location: client
  subscriptionIdParameter:
    name: subscriptionId
    in: path
    description: Your Azure subscription ID. This is a GUID-formatted string (e.g. 00000000-0000-0000-0000-000000000000).
    required: true
    type: string
    x-ms-parameter-location: client
  siteNameParameter:
    name: name
    in: path
    description: Site name.
    required: true
    type: string
    x-ms-parameter-location: method
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
