swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector DataSet API
schemes:
- https
tags:
- name: DataSet
paths:
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DataShare/accounts/{accountName}/shares/{shareName}/dataSets/{dataSetName}
  : get:
      tags:
      - DataSet
      summary: Microsoft Azure Get Dataset In A Share
      description: Get a DataSet in a share
      operationId: microsoftAzureDatasetsGet
      parameters:
      - $ref: '#/parameters/subscriptionId'
      - $ref: '#/parameters/resourceGroupName'
      - $ref: '#/parameters/accountName'
      - name: shareName
        in: path
        description: The name of the share.
        required: true
        type: string
      - name: dataSetName
        in: path
        description: The name of the dataSet.
        required: true
        type: string
      - $ref: '#/parameters/api-version'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/DataSet'
        default:
          description: An error response received from the Microsoft.DataShare resource provider.
          schema:
            $ref: '#/definitions/DataShareError'
      x-ms-examples:
        DataSets_Get:
          $ref: ./examples/DataSets_Get.json
    put:
      tags:
      - DataSet
      summary: Microsoft Azure Adds A New Data Set To An Existing Share
      description: 'Create a DataSet '
      operationId: microsoftAzureDatasetsCreate
      parameters:
      - $ref: '#/parameters/subscriptionId'
      - $ref: '#/parameters/resourceGroupName'
      - $ref: '#/parameters/accountName'
      - name: shareName
        in: path
        description: The name of the share to add the data set to.
        required: true
        type: string
      - name: dataSetName
        in: path
        description: The name of the dataSet.
        required: true
        type: string
      - name: dataSet
        in: body
        description: The new data set information.
        required: true
        schema:
          $ref: '#/definitions/DataSet'
      - $ref: '#/parameters/api-version'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/DataSet'
        '201':
          description: Success
          schema:
            $ref: '#/definitions/DataSet'
        default:
          description: An error response received from the Microsoft.DataShare resource provider.
          schema:
            $ref: '#/definitions/DataShareError'
      x-ms-examples:
        DataSets_Create:
          $ref: ./examples/DataSets_Create.json
        DataSets_KustoCluster_Create:
          $ref: ./examples/DataSets_KustoCluster_Create.json
        DataSets_KustoDatabase_Create:
          $ref: ./examples/DataSets_KustoDatabase_Create.json
        DataSets_SqlDWTable_Create:
          $ref: ./examples/DataSets_SqlDWTable_Create.json
        DataSets_SqlDBTable_Create:
          $ref: ./examples/DataSets_SqlDBTable_Create.json
    delete:
      tags:
      - DataSet
      summary: Microsoft Azure Delete Dataset In A Share
      description: Delete a DataSet in a share
      operationId: microsoftAzureDatasetsDelete
      parameters:
      - $ref: '#/parameters/subscriptionId'
      - $ref: '#/parameters/resourceGroupName'
      - $ref: '#/parameters/accountName'
      - name: shareName
        in: path
        description: The name of the share.
        required: true
        type: string
      - name: dataSetName
        in: path
        description: The name of the dataSet.
        required: true
        type: string
      - $ref: '#/parameters/api-version'
      responses:
        '200':
          description: Success
        '202':
          description: Accepted
        '204':
          description: Success
        default:
          description: An error response received from the Microsoft.DataShare resource provider.
          schema:
            $ref: '#/definitions/DataShareError'
      x-ms-long-running-operation: true
      x-ms-examples:
        DataSets_Delete:
          $ref: ./examples/DataSets_Delete.json
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DataShare/accounts/{accountName}/shares/{shareName}/dataSets
  : get:
      tags:
      - DataSet
      summary: Microsoft Azure List Datasets In A Share
      description: List DataSets in a share
      operationId: microsoftAzureDatasetsListbyshare
      parameters:
      - $ref: '#/parameters/subscriptionId'
      - $ref: '#/parameters/resourceGroupName'
      - $ref: '#/parameters/accountName'
      - name: shareName
        in: path
        description: The name of the share.
        required: true
        type: string
      - $ref: '#/parameters/api-version'
      - name: $skipToken
        in: query
        description: continuation token
        required: false
        type: string
      - name: $filter
        in: query
        description: Filters the results using OData syntax.
        required: false
        type: string
      - name: $orderby
        in: query
        description: Sorts the results using OData syntax.
        required: false
        type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/DataSetList'
        default:
          description: An error response received from the Microsoft.DataShare resource provider.
          schema:
            $ref: '#/definitions/DataShareError'
      x-ms-pageable:
        nextLinkName: nextLink
      x-ms-examples:
        DataSets_ListByShare:
          $ref: ./examples/DataSets_ListByShare.json
definitions:
  ProxyDto:
    description: Base data transfer object implementation for proxy resources.
    type: object
    properties:
      id:
        description: The resource id of the azure resource
        type: string
        readOnly: true
      name:
        description: Name of the azure resource
        type: string
        readOnly: true
      type:
        description: Type of the azure resource
        type: string
        readOnly: true
    x-ms-azure-resource: true
  DataSet:
    description: A DataSet data transfer object.
    required:
    - kind
    type: object
    allOf:
    - $ref: '#/definitions/ProxyDto'
    properties:
      kind:
        description: Kind of data set.
        enum:
        - Blob
        - Container
        - BlobFolder
        - AdlsGen2FileSystem
        - AdlsGen2Folder
        - AdlsGen2File
        - AdlsGen1Folder
        - AdlsGen1File
        - KustoCluster
        - KustoDatabase
        - SqlDBTable
        - SqlDWTable
        type: string
        x-ms-enum:
          name: dataSetKind
          modelAsString: true
    discriminator: kind
  DataShareErrorInfo:
    description: The data share error body model.
    required:
    - code
    - message
    type: object
    properties:
      code:
        description: Code of the error
        type: string
      details:
        description: Nested details of the error model
        uniqueItems: false
        type: array
        items:
          $ref: '#/definitions/DataShareErrorInfo'
      message:
        description: Message of the error
        type: string
      target:
        description: Target of the error
        type: string
  DataSetList:
    description: List response for get DataSets
    required:
    - value
    type: object
    properties:
      nextLink:
        description: The Url of next result page.
        type: string
      value:
        description: Collection of items of type DataTransferObjects.
        uniqueItems: false
        type: array
        items:
          $ref: '#/definitions/DataSet'
  DataShareError:
    description: The data share error model.
    required:
    - error
    type: object
    properties:
      error:
        $ref: '#/definitions/DataShareErrorInfo'
        description: The data share error body
parameters:
  resourceGroupName:
    name: resourceGroupName
    in: path
    description: The resource group name.
    required: true
    type: string
    x-ms-parameter-location: method
  accountName:
    name: accountName
    in: path
    description: The name of the share account.
    required: true
    type: string
    x-ms-parameter-location: method
  subscriptionId:
    name: subscriptionId
    in: path
    description: The subscription identifier
    required: true
    type: string
  api-version:
    name: api-version
    in: query
    description: The api version to use.
    required: true
    type: string
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
