swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector Prediction API
schemes:
- https
tags:
- name: Prediction
paths:
  /subscriptions/{subscriptionId}/providers/Microsoft.Advisor/predict:
    post:
      tags:
      - Prediction
      summary: Microsoft Azure Predicts A Recommendation
      operationId: microsoftAzurePredict
      parameters:
      - $ref: '#/parameters/subscriptionIdParameter'
      - name: predictionRequest
        in: body
        description: Parameters for predict recommendation.
        required: true
        schema:
          $ref: '#/definitions/PredictionRequest'
      - $ref: '#/parameters/apiVersionParameter'
      responses:
        '200':
          description: OK. Successfully obtained prediction.
          schema:
            $ref: '#/definitions/PredictionResponse'
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: '#/definitions/ArmErrorResponse'
      deprecated: false
      x-ms-examples:
        Predict:
          $ref: ./examples/Predict.json
      description: Needs a more full description created.
definitions:
  PredictionResponseProperties:
    description: Properties of the prediction
    type: object
    properties:
      extendedProperties:
        description: Extended properties
        type: object
      predictionType:
        description: Type of the prediction.
        enum:
        - PredictiveRightsizing
        type: string
        x-ms-enum:
          name: predictionType
          modelAsString: true
      category:
        description: The category of the recommendation.
        enum:
        - HighAvailability
        - Security
        - Performance
        - Cost
        - OperationalExcellence
        type: string
        x-ms-enum:
          name: category
          modelAsString: true
      impact:
        description: The business impact of the recommendation.
        enum:
        - High
        - Medium
        - Low
        type: string
        x-ms-enum:
          name: impact
          modelAsString: true
      impactedField:
        description: The resource type identified by Advisor.
        type: string
      lastUpdated:
        format: date-time
        description: The most recent time that Advisor checked the validity of the recommendation.
        type: string
      shortDescription:
        $ref: '#/definitions/ShortDescription'
        description: A summary of the recommendation.
  ArmErrorResponse:
    type: object
    properties:
      error:
        $ref: '#/definitions/ARMErrorResponseBody'
  ARMErrorResponseBody:
    description: ARM error response body.
    type: object
    properties:
      message:
        description: Gets or sets the string that describes the error in detail and provides debugging information.
        type: string
      code:
        description: Gets or sets the string that can be used to programmatically identify the error.
        type: string
  ShortDescription:
    description: A summary of the recommendation.
    type: object
    properties:
      solution:
        description: The remediation action suggested by the recommendation.
        type: string
  PredictionRequestProperties:
    description: Properties given for the predictor.
    type: object
    properties:
      predictionType:
        description: Type of the prediction.
        enum:
        - PredictiveRightsizing
        type: string
        x-ms-enum:
          name: predictionType
          modelAsString: true
      extendedProperties:
        description: Extended properties are arguments specific for each prediction type.
        type: object
  PredictionRequest:
    description: Parameters for predict recommendation.
    type: object
    properties:
      properties:
        $ref: '#/definitions/PredictionRequestProperties'
        description: Request properties for prediction recommendation.
        x-ms-client-flatten: true
  PredictionResponse:
    description: Response used by predictions.
    type: object
    properties:
      properties:
        $ref: '#/definitions/PredictionResponseProperties'
        description: The properties of the prediction.
        x-ms-client-flatten: true
    x-ms-azure-resource: true
parameters:
  subscriptionIdParameter:
    name: subscriptionId
    in: path
    description: The Azure subscription ID.
    required: true
    type: string
  apiVersionParameter:
    name: api-version
    in: query
    description: The version of the API to be used with the client request.
    required: true
    type: string
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
