swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector Agreements API
schemes:
- https
tags:
- name: Agreements
paths:
  /subscriptions/{subscriptionId}/providers/Microsoft.Confluent/agreements:
    get:
      tags:
      - Agreements
      summary: Microsoft Azure List Confluent Marketplace Agreements In The Subscription
      operationId: microsoftAzureMarketplaceagreementsList
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/ApiVersionParameter'
      - $ref: '#/parameters/SubscriptionIdParameter'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/ConfluentAgreementResourceListResponse'
        default:
          description: Default error response.
          schema:
            $ref: '#/definitions/ResourceProviderDefaultErrorResponse'
      x-ms-pageable:
        nextLinkName: nextLink
      x-ms-examples:
        MarketplaceAgreements_List:
          $ref: ./examples/MarketplaceAgreements_List.json
      description: Needs a more full description created.
  /subscriptions/{subscriptionId}/providers/Microsoft.Confluent/agreements/default:
    put:
      tags:
      - Agreements
      summary: Microsoft Azure Create Confluent Marketplace Agreement In The Subscription
      operationId: microsoftAzureMarketplaceagreementsCreate
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/ApiVersionParameter'
      - $ref: '#/parameters/SubscriptionIdParameter'
      - in: body
        name: body
        description: Confluent Marketplace Agreement resource
        schema:
          $ref: '#/definitions/ConfluentAgreementResource'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/ConfluentAgreementResource'
        default:
          description: Default error response.
          schema:
            $ref: '#/definitions/ResourceProviderDefaultErrorResponse'
      x-ms-examples:
        MarketplaceAgreements_Create:
          $ref: ./examples/MarketplaceAgreements_Create.json
      description: Needs a more full description created.
  /subscriptions/{subscriptionId}/providers/Microsoft.Datadog/agreements:
    get:
      tags:
      - Agreements
      summary: Microsoft Azure List Datadog Marketplace Agreements In The Subscription
      operationId: microsoftAzureMarketplaceagreementsList
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/SubscriptionIdParameter_2'
      - $ref: ../../../../../common-types/resource-management/v1/types.json#/parameters/ApiVersionParameter
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/DatadogAgreementResourceListResponse'
        default:
          description: Default error response.
          schema:
            $ref: '#/definitions/ResourceProviderDefaultErrorResponse_2'
      x-ms-pageable:
        nextLinkName: nextLink
      x-ms-examples:
        MarketplaceAgreements_List:
          $ref: ./examples/MarketplaceAgreements_List.json
      description: Needs a more full description created.
  /subscriptions/{subscriptionId}/providers/Microsoft.Datadog/agreements/default:
    put:
      tags:
      - Agreements
      summary: Microsoft Azure Create Datadog Marketplace Agreement In The Subscription
      operationId: microsoftAzureMarketplaceagreementsCreateorupdate
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/SubscriptionIdParameter_2'
      - $ref: ../../../../../common-types/resource-management/v1/types.json#/parameters/ApiVersionParameter
      - in: body
        name: body
        schema:
          $ref: '#/definitions/DatadogAgreementResource'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/DatadogAgreementResource'
        default:
          description: Default error response.
          schema:
            $ref: '#/definitions/ResourceProviderDefaultErrorResponse_2'
      x-ms-examples:
        MarketplaceAgreements_CreateOrUpdate:
          $ref: ./examples/MarketplaceAgreements_Create.json
      description: Needs a more full description created.
definitions:
  DatadogAgreementProperties:
    description: Terms properties.
    type: object
    properties:
      publisher:
        description: Publisher identifier string.
        type: string
      product:
        description: Product identifier string.
        type: string
      plan:
        description: Plan identifier string.
        type: string
      licenseTextLink:
        description: Link to HTML with Microsoft and Publisher terms.
        type: string
      privacyPolicyLink:
        description: Link to the privacy policy of the publisher.
        type: string
      retrieveDatetime:
        format: date-time
        description: Date and time in UTC of when the terms were accepted. This is empty if Accepted is false.
        type: string
      signature:
        description: Terms signature.
        type: string
      accepted:
        description: If any version of the terms have been accepted, otherwise false.
        type: boolean
  DatadogAgreementResource:
    type: object
    x-ms-azure-resource: true
    properties:
      id:
        description: ARM id of the resource.
        type: string
        readOnly: true
      name:
        description: Name of the agreement.
        type: string
        readOnly: true
      type:
        description: The type of the resource.
        type: string
        readOnly: true
      properties:
        $ref: '#/definitions/DatadogAgreementProperties'
        description: Represents the properties of the resource.
  ConfluentAgreementResource:
    description: Agreement Terms definition
    type: object
    x-ms-azure-resource: true
    properties:
      id:
        description: The ARM id of the resource.
        type: string
        readOnly: true
      name:
        description: The name of the agreement.
        type: string
        readOnly: true
      type:
        description: The type of the agreement.
        type: string
        readOnly: true
      systemData:
        description: Metadata pertaining to creation and last modification of the resource
        $ref: ../../../../../common-types/resource-management/v2/types.json#/definitions/systemData
        readOnly: true
      properties:
        x-ms-client-flatten: true
        $ref: '#/definitions/ConfluentAgreementProperties'
        description: Represents the properties of the resource.
  ConfluentAgreementResourceListResponse:
    description: Response of a list operation.
    type: object
    properties:
      value:
        description: Results of a list operation.
        type: array
        items:
          $ref: '#/definitions/ConfluentAgreementResource'
      nextLink:
        description: Link to the next set of results, if any.
        type: string
  ErrorResponseBody_2:
    type: object
    properties:
      code:
        type: string
      message:
        type: string
      target:
        type: string
      details:
        type: array
        items:
          $ref: '#/definitions/ErrorResponseBody_2'
  DatadogAgreementResourceListResponse:
    description: Response of a list operation.
    type: object
    properties:
      value:
        description: Results of a list operation.
        type: array
        items:
          $ref: '#/definitions/DatadogAgreementResource'
      nextLink:
        description: Link to the next set of results, if any.
        type: string
  ResourceProviderDefaultErrorResponse:
    type: object
    description: Default error response for resource provider
    title: ResourceProviderDefaultErrorResponse
    properties:
      error:
        description: Response body of Error
        readOnly: true
        $ref: '#/definitions/ErrorResponseBody'
  ResourceProviderDefaultErrorResponse_2:
    type: object
    properties:
      error:
        $ref: '#/definitions/ErrorResponseBody_2'
  ConfluentAgreementProperties:
    description: Terms properties for Marketplace and Confluent.
    type: object
    properties:
      publisher:
        description: Publisher identifier string.
        type: string
      product:
        description: Product identifier string.
        type: string
      plan:
        description: Plan identifier string.
        type: string
      licenseTextLink:
        description: Link to HTML with Microsoft and Publisher terms.
        type: string
      privacyPolicyLink:
        description: Link to the privacy policy of the publisher.
        type: string
      retrieveDatetime:
        format: date-time
        description: Date and time in UTC of when the terms were accepted. This is empty if Accepted is false.
        type: string
      signature:
        description: Terms signature.
        type: string
      accepted:
        description: If any version of the terms have been accepted, otherwise false.
        type: boolean
  ErrorResponseBody:
    description: Response body of Error
    title: ErrorResponseBody
    type: object
    properties:
      code:
        description: Error code
        type: string
        readOnly: true
      message:
        description: Error message
        type: string
        readOnly: true
      target:
        description: Error target
        type: string
        readOnly: true
      details:
        description: Error detail
        type: array
        readOnly: true
        items:
          $ref: '#/definitions/ErrorResponseBody'
        x-ms-identifiers:
        - message
        - target
parameters:
  SubscriptionIdParameter_2:
    name: subscriptionId
    in: path
    description: The Microsoft Azure subscription ID.
    required: true
    type: string
  ApiVersionParameter:
    name: api-version
    in: query
    description: Client Api Version.
    required: true
    type: string
    enum:
    - 2021-09-01-preview
  SubscriptionIdParameter:
    in: path
    name: subscriptionId
    description: Microsoft Azure subscription id
    required: true
    type: string
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
