swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector MaintenanceConfigurations API
schemes:
- https
tags:
- name: MaintenanceConfigurations
paths:
  ? /subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/Microsoft.Maintenance/maintenanceConfigurations/{resourceName}
  : get:
      tags:
      - MaintenanceConfigurations
      summary: Microsoft Azure Get Configuration Record
      operationId: microsoftAzureMaintenanceconfigurationsGet
      consumes: []
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/SubscriptionIdParameter'
      - name: resourceGroupName
        in: path
        description: Resource Group Name
        required: true
        type: string
      - name: resourceName
        in: path
        description: Maintenance Configuration Name
        required: true
        type: string
      - $ref: '#/parameters/ApiVersionParameter'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/MaintenanceConfiguration'
        default:
          description: BadRequest
          schema:
            $ref: '#/definitions/MaintenanceError'
      x-ms-examples:
        MaintenanceConfigurations_GetForResource:
          $ref: ./examples/MaintenanceConfigurations_GetForResource.json
        MaintenanceConfigurations_GetForResource_GuestOSPatchWindows:
          $ref: ./examples/MaintenanceConfigurations_GetForResource_GuestOSPatchWindows.json
        MaintenanceConfigurations_GetForResource_GuestOSPatchLinux:
          $ref: ./examples/MaintenanceConfigurations_GetForResource_GuestOSPatchLinux.json
      description: Needs a more full description created.
    put:
      tags:
      - MaintenanceConfigurations
      summary: Microsoft Azure Create Or Update Configuration Record
      operationId: microsoftAzureMaintenanceconfigurationsCreateorupdate
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/SubscriptionIdParameter'
      - name: resourceGroupName
        in: path
        description: Resource Group Name
        required: true
        type: string
      - name: resourceName
        in: path
        description: Maintenance Configuration Name
        required: true
        type: string
      - name: configuration
        in: body
        description: The configuration
        required: true
        schema:
          $ref: '#/definitions/MaintenanceConfiguration'
      - $ref: '#/parameters/ApiVersionParameter'
      responses:
        '200':
          description: Maintenance configuration update request accepted
          schema:
            $ref: '#/definitions/MaintenanceConfiguration'
        '201':
          description: Maintenance configuration create request accepted
          schema:
            $ref: '#/definitions/MaintenanceConfiguration'
        default:
          description: BadRequest
          schema:
            $ref: '#/definitions/MaintenanceError'
      x-ms-examples:
        MaintenanceConfigurations_CreateOrUpdateForResource:
          $ref: ./examples/MaintenanceConfigurations_CreateOrUpdateForResource.json
      description: Needs a more full description created.
    delete:
      tags:
      - MaintenanceConfigurations
      summary: Microsoft Azure Delete Configuration Record
      operationId: microsoftAzureMaintenanceconfigurationsDelete
      consumes: []
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/SubscriptionIdParameter'
      - name: resourceGroupName
        in: path
        description: Resource Group Name
        required: true
        type: string
      - name: resourceName
        in: path
        description: Maintenance Configuration Name
        required: true
        type: string
      - $ref: '#/parameters/ApiVersionParameter'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/MaintenanceConfiguration'
        '204':
          description: No Content
        default:
          description: BadRequest
          schema:
            $ref: '#/definitions/MaintenanceError'
      x-ms-examples:
        MaintenanceConfigurations_DeleteForResource:
          $ref: ./examples/MaintenanceConfigurations_DeleteForResource.json
      description: Needs a more full description created.
    patch:
      tags:
      - MaintenanceConfigurations
      summary: Microsoft Azure Patch Configuration Record
      operationId: microsoftAzureMaintenanceconfigurationsUpdate
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/SubscriptionIdParameter'
      - name: resourceGroupName
        in: path
        description: Resource Group Name
        required: true
        type: string
      - name: resourceName
        in: path
        description: Maintenance Configuration Name
        required: true
        type: string
      - name: configuration
        in: body
        description: The configuration
        required: true
        schema:
          $ref: '#/definitions/MaintenanceConfiguration'
      - $ref: '#/parameters/ApiVersionParameter'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/MaintenanceConfiguration'
        default:
          description: BadRequest
          schema:
            $ref: '#/definitions/MaintenanceError'
      x-ms-examples:
        MaintenanceConfigurations_UpdateForResource:
          $ref: ./examples/MaintenanceConfigurations_UpdateForResource.json
      description: Needs a more full description created.
  /subscriptions/{subscriptionId}/providers/Microsoft.Maintenance/maintenanceConfigurations:
    get:
      tags:
      - MaintenanceConfigurations
      summary: Microsoft Azure Get Configuration Records Within A Subscription
      operationId: microsoftAzureMaintenanceconfigurationsList
      consumes: []
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/SubscriptionIdParameter'
      - $ref: '#/parameters/ApiVersionParameter'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ListMaintenanceConfigurationsResult'
        default:
          description: BadRequest
          schema:
            $ref: '#/definitions/MaintenanceError'
      x-ms-pageable:
        nextLinkName: null
      x-ms-examples:
        MaintenanceConfigurations_List:
          $ref: ./examples/MaintenanceConfigurations_List.json
      description: Needs a more full description created.
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Maintenance/maintenanceConfigurations
  : get:
      tags:
      - MaintenanceConfigurations
      summary: Microsoft Azure Get Configuration Records Within A Subscription And Resource Group
      operationId: microsoftAzureMaintenanceconfigurationsforresourcegroupList
      consumes: []
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/SubscriptionIdParameter'
      - name: resourceGroupName
        in: path
        description: Resource Group Name
        required: true
        type: string
      - $ref: '#/parameters/ApiVersionParameter'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ListMaintenanceConfigurationsResult'
        default:
          description: BadRequest
          schema:
            $ref: '#/definitions/MaintenanceError'
      x-ms-pageable:
        nextLinkName: null
      x-ms-examples:
        MaintenanceConfigurationsResourceGroup_List:
          $ref: ./examples/MaintenanceConfigurationsResourceGroup_List.json
      description: Needs a more full description created.
definitions:
  Resource:
    description: Definition of a Resource
    type: object
    properties:
      id:
        description: Fully qualified identifier of the resource
        type: string
        readOnly: true
      name:
        description: Name of the resource
        type: string
        readOnly: true
      type:
        description: Type of the resource
        type: string
        readOnly: true
      systemData:
        readOnly: true
        type: object
        description: Azure Resource Manager metadata containing createdBy and modifiedBy information.
        $ref: ../../../../../common-types/resource-management/v2/types.json#/definitions/systemData
    x-ms-azure-resource: true
  MaintenanceConfiguration:
    description: Maintenance configuration record type
    type: object
    allOf:
    - $ref: '#/definitions/Resource'
    properties:
      location:
        description: Gets or sets location of the resource
        type: string
      tags:
        description: Gets or sets tags of the resource
        type: object
        additionalProperties:
          type: string
      properties:
        $ref: '#/definitions/MaintenanceConfigurationProperties'
        description: Gets or sets properties of the resource
        x-ms-client-flatten: true
  ErrorDetails:
    description: An error response details received from the Azure Maintenance service.
    type: object
    properties:
      code:
        description: Service-defined error code. This code serves as a sub-status for the HTTP error code specified in the response.
        type: string
      message:
        description: Human-readable representation of the error.
        type: string
  InputPatchConfiguration:
    type: object
    properties:
      rebootSetting:
        type: string
        enum:
        - IfRequired
        - Never
        - Always
        x-ms-enum:
          name: RebootOptions
          modelAsString: true
        default: IfRequired
        description: Possible reboot preference as defined by the user based on which it would be decided to reboot the machine or not after the patch operation is completed.
      windowsParameters:
        $ref: '#/definitions/InputWindowsParameters'
        description: Input parameters specific to patching a Windows machine. For Linux machines, do not pass this property.
      linuxParameters:
        $ref: '#/definitions/InputLinuxParameters'
        description: Input parameters specific to patching Linux machine. For Windows machines, do not pass this property.
    description: Input configuration for a patch run
  MaintenanceWindow:
    description: Definition of a MaintenanceWindow
    type: object
    properties:
      startDateTime:
        description: Effective start date of the maintenance window in YYYY-MM-DD hh:mm format. The start date can be set to either the current date or future date. The window will be created in the time zone provided and adjusted to daylight savings according to that time zone.
        type: string
      expirationDateTime:
        description: Effective expiration date of the maintenance window in YYYY-MM-DD hh:mm format. The window will be created in the time zone provided and adjusted to daylight savings according to that time zone. Expiration date must be set to a future date. If not provided, it will be set to the maximum datetime 9999-12-31 23:59:59.
        type: string
      duration:
        description: 'Duration of the maintenance window in HH:mm format. If not provided, default value will be used based on maintenance scope provided. Example: 05:00.'
        type: string
      timeZone:
        description: 'Name of the timezone. List of timezones can be obtained by executing [System.TimeZoneInfo]::GetSystemTimeZones() in PowerShell. Example: Pacific Standard Time, UTC, W. Europe Standard Time, Korea Standard Time, Cen. Australia Standard Time.'
        type: string
      recurEvery:
        description: 'Rate at which a Maintenance window is expected to recur. The rate can be expressed as daily, weekly, or monthly schedules. Daily schedule are formatted as recurEvery: [Frequency as integer][''Day(s)'']. If no frequency is provided, the default frequency is 1. Daily schedule examples are recurEvery: Day, recurEvery: 3Days.  Weekly schedule are formatted as recurEvery: [Frequency as integer][''Week(s)''] [Optional comma separated list of weekdays Monday-Sunday]. Weekly schedule examples are recurEvery: 3Weeks, recurEvery: Week Saturday,Sunday. Monthly schedules are formatted as [Frequency as integer][''Month(s)''] [Comma separated list of month days] or [Frequency as integer][''Month(s)''] [Week of Month (First, Second, Third, Fourth, Last)] [Weekday Monday-Sunday] [Optional Offset(No. of days)]. Offset value must be between -6 to 6 inclusive. Monthly schedule examples are recurEvery: Month, recurEvery: 2Months, recurEvery: Month day23,day24, recurEvery: Month Last Sunday, recurEvery: Month Fourth Monday, recurEvery: Month Last Sunday Offset-3, recurEvery: Month Third Sunday Offset6.'
        type: string
  MaintenanceError:
    description: An error response received from the Azure Maintenance service.
    type: object
    properties:
      error:
        $ref: '#/definitions/ErrorDetails'
        description: Details of the error
  MaintenanceConfigurationProperties:
    description: Properties for maintenance configuration
    type: object
    properties:
      namespace:
        description: Gets or sets namespace of the resource
        type: string
      extensionProperties:
        description: Gets or sets extensionProperties of the maintenanceConfiguration
        type: object
        additionalProperties:
          type: string
      maintenanceScope:
        description: Gets or sets maintenanceScope of the configuration
        enum:
        - Host
        - Resource
        - OSImage
        - Extension
        - InGuestPatch
        - SQLDB
        - SQLManagedInstance
        type: string
        x-ms-enum:
          name: MaintenanceScope
          modelAsString: true
          values:
          - value: Host
            description: This maintenance scope controls installation of azure platform updates i.e. services on physical nodes hosting customer VMs.
          - value: Resource
            description: This maintenance scope controls the default update maintenance of the Azure Resource
          - value: OSImage
            description: This maintenance scope controls os image installation on VM/VMSS
          - value: Extension
            description: This maintenance scope controls extension installation on VM/VMSS
          - value: InGuestPatch
            description: This maintenance scope controls installation of windows and linux packages on VM/VMSS
          - value: SQLDB
            description: This maintenance scope controls installation of SQL server platform updates.
          - value: SQLManagedInstance
            description: This maintenance scope controls installation of SQL managed instance platform update.
      maintenanceWindow:
        $ref: '#/definitions/MaintenanceWindow'
        description: Definition of a MaintenanceWindow
        x-ms-client-flatten: true
      visibility:
        description: Gets or sets the visibility of the configuration. The default value is 'Custom'
        enum:
        - Custom
        - Public
        type: string
        x-ms-enum:
          name: Visibility
          modelAsString: true
          values:
          - value: Custom
            description: Only visible to users with permissions.
          - value: Public
            description: Visible to all users.
      installPatches:
        $ref: '#/definitions/InputPatchConfiguration'
        description: The input parameters to be passed to the patch run operation.
  InputLinuxParameters:
    type: object
    properties:
      packageNameMasksToExclude:
        type: array
        items:
          type: string
        description: Package names to be excluded for patching.
      packageNameMasksToInclude:
        type: array
        items:
          type: string
        description: Package names to be included for patching.
      classificationsToInclude:
        type: array
        items:
          type: string
        description: Classification category of patches to be patched
    description: Input properties for patching a Linux machine.
  InputWindowsParameters:
    type: object
    properties:
      kbNumbersToExclude:
        type: array
        items:
          type: string
        description: Windows KBID to be excluded for patching.
      kbNumbersToInclude:
        type: array
        items:
          type: string
        description: Windows KBID to be included for patching.
      classificationsToInclude:
        type: array
        items:
          type: string
        description: Classification category of patches to be patched
      excludeKbsRequiringReboot:
        type: boolean
        description: Exclude patches which need reboot
    description: Input properties for patching a Windows machine.
  ListMaintenanceConfigurationsResult:
    description: Response for MaintenanceConfigurations list
    type: object
    properties:
      value:
        description: The list of maintenance Configurations
        type: array
        items:
          $ref: '#/definitions/MaintenanceConfiguration'
parameters:
  ApiVersionParameter:
    name: api-version
    in: query
    description: Version of the API to be used with the client request.
    required: true
    type: string
    x-ms-parameter-location: client
  SubscriptionIdParameter:
    name: subscriptionId
    in: path
    description: Subscription credentials that uniquely identify a Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.
    required: true
    type: string
    x-ms-parameter-location: client
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
