swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector BandwidthSettings API
schemes:
- https
tags:
- name: BandwidthSettings
paths:
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.StorSimple/managers/{managerName}/bandwidthSettings
  : get:
      tags:
      - BandwidthSettings
      description: Retrieves all the bandwidth setting in a manager.
      operationId: microsoftAzureBandwidthsettingsListbymanager
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/subscriptionIdParameter'
      - $ref: '#/parameters/resourceGroupNameParameter'
      - $ref: '#/parameters/managerNameParameter'
      - $ref: '#/parameters/apiVersionParameter'
      responses:
        '200':
          description: The collection of bandwidth settings.
          schema:
            $ref: '#/definitions/BandwidthSettingList'
      deprecated: false
      x-ms-pageable:
        nextLinkName: null
      x-ms-examples:
        BandwidthSettingsListByManager:
          $ref: ./examples/BandwidthSettingsListByManager.json
      summary: Microsoft Azure Get Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Storsimple Managers Managername Bandwidthsettings
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.StorSimple/managers/{managerName}/bandwidthSettings/{bandwidthSettingName}
  : get:
      tags:
      - BandwidthSettings
      description: Returns the properties of the specified bandwidth setting name.
      operationId: microsoftAzureBandwidthsettingsGet
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: bandwidthSettingName
        in: path
        description: The name of bandwidth setting to be fetched.
        required: true
        type: string
        x-ms-skip-url-encoding: true
      - $ref: '#/parameters/subscriptionIdParameter'
      - $ref: '#/parameters/resourceGroupNameParameter'
      - $ref: '#/parameters/managerNameParameter'
      - $ref: '#/parameters/apiVersionParameter'
      responses:
        '200':
          description: The bandwidth setting.
          schema:
            $ref: '#/definitions/BandwidthSetting'
      deprecated: false
      x-ms-examples:
        BandwidthSettingsGet:
          $ref: ./examples/BandwidthSettingsGet.json
      summary: Microsoft Azure Get Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Storsimple Managers Managername Bandwidthsettings Bandwidthsettingname
    put:
      tags:
      - BandwidthSettings
      description: Creates or updates the bandwidth setting
      operationId: microsoftAzureBandwidthsettingsCreateorupdate
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: bandwidthSettingName
        in: path
        description: The bandwidth setting name.
        required: true
        type: string
        x-ms-skip-url-encoding: true
      - name: parameters
        in: body
        description: The bandwidth setting to be added or updated.
        required: true
        schema:
          $ref: '#/definitions/BandwidthSetting'
      - $ref: '#/parameters/subscriptionIdParameter'
      - $ref: '#/parameters/resourceGroupNameParameter'
      - $ref: '#/parameters/managerNameParameter'
      - $ref: '#/parameters/apiVersionParameter'
      responses:
        '200':
          description: Successfully created or updated the bandwidth setting.
          schema:
            $ref: '#/definitions/BandwidthSetting'
        '202':
          description: Accepted the request to create or update the bandwidth setting.
      deprecated: false
      x-ms-long-running-operation: true
      x-ms-examples:
        BandwidthSettingsCreateOrUpdate:
          $ref: ./examples/BandwidthSettingsCreateOrUpdate.json
      summary: Microsoft Azure Put Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Storsimple Managers Managername Bandwidthsettings Bandwidthsettingname
    delete:
      tags:
      - BandwidthSettings
      description: Deletes the bandwidth setting
      operationId: microsoftAzureBandwidthsettingsDelete
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: bandwidthSettingName
        in: path
        description: The name of the bandwidth setting.
        required: true
        type: string
        x-ms-skip-url-encoding: true
      - $ref: '#/parameters/subscriptionIdParameter'
      - $ref: '#/parameters/resourceGroupNameParameter'
      - $ref: '#/parameters/managerNameParameter'
      - $ref: '#/parameters/apiVersionParameter'
      responses:
        '202':
          description: Accepted the request to delete the bandwidth setting.
        '204':
          description: Successfully deleted the bandwidth setting.
      deprecated: false
      x-ms-long-running-operation: true
      x-ms-examples:
        BandwidthSettingsDelete:
          $ref: ./examples/BandwidthSettingsDelete.json
      summary: Microsoft Azure Delete Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Storsimple Managers Managername Bandwidthsettings Bandwidthsettingname
definitions:
  BandwidthSchedule:
    description: The schedule for bandwidth setting.
    required:
    - start
    - stop
    - rateInMbps
    - days
    type: object
    properties:
      start:
        $ref: '#/definitions/Time'
        description: The start time of the schedule.
      stop:
        $ref: '#/definitions/Time'
        description: The stop time of the schedule.
      rateInMbps:
        format: int32
        description: The rate in Mbps.
        type: integer
      days:
        description: The days of the week when this schedule is applicable.
        type: array
        items:
          enum:
          - Sunday
          - Monday
          - Tuesday
          - Wednesday
          - Thursday
          - Friday
          - Saturday
          type: string
          x-ms-enum:
            name: DayOfWeek
            modelAsString: false
  Time:
    description: The time.
    required:
    - hours
    - minutes
    - seconds
    type: object
    properties:
      hours:
        format: int32
        description: The hour.
        maximum: 23
        minimum: 0
        type: integer
      minutes:
        format: int32
        description: The minute.
        maximum: 59
        minimum: 0
        type: integer
      seconds:
        format: int32
        description: The second.
        maximum: 59
        minimum: 0
        type: integer
  BandwidthRateSettingProperties:
    description: The properties of the bandwidth setting.
    required:
    - schedules
    type: object
    properties:
      schedules:
        description: The schedules.
        type: array
        items:
          $ref: '#/definitions/BandwidthSchedule'
        x-ms-identifiers: []
      volumeCount:
        format: int32
        description: The number of volumes that uses the bandwidth setting.
        type: integer
        readOnly: true
  BandwidthSetting:
    description: The bandwidth setting.
    required:
    - properties
    type: object
    allOf:
    - $ref: '#/definitions/BaseModel'
    properties:
      properties:
        $ref: '#/definitions/BandwidthRateSettingProperties'
        description: The properties of the bandwidth setting.
        x-ms-client-flatten: true
  BaseModel:
    description: Represents the base class for all other ARM object models
    type: object
    properties:
      id:
        description: The path ID that uniquely identifies the object.
        type: string
        readOnly: true
      name:
        description: The name of the object.
        type: string
        readOnly: true
      type:
        description: The hierarchical type of the object.
        type: string
        readOnly: true
      kind:
        description: The Kind of the object. Currently only Series8000 is supported
        enum:
        - Series8000
        type: string
        x-ms-enum:
          name: Kind
          modelAsString: false
  BandwidthSettingList:
    description: The collection of bandwidth setting entities.
    required:
    - value
    type: object
    properties:
      value:
        description: The value.
        type: array
        items:
          $ref: '#/definitions/BandwidthSetting'
parameters:
  managerNameParameter:
    name: managerName
    in: path
    description: The manager name
    required: true
    type: string
    maxLength: 50
    minLength: 2
    x-ms-parameter-location: method
    x-ms-skip-url-encoding: true
  subscriptionIdParameter:
    name: subscriptionId
    in: path
    description: The subscription id
    required: true
    type: string
    x-ms-skip-url-encoding: true
  apiVersionParameter:
    name: api-version
    in: query
    description: The api version
    required: true
    type: string
    x-ms-skip-url-encoding: true
  resourceGroupNameParameter:
    name: resourceGroupName
    in: path
    description: The resource group name
    required: true
    type: string
    x-ms-parameter-location: method
    x-ms-skip-url-encoding: true
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
