swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector Kpi API
schemes:
- https
tags:
- name: Kpi
paths:
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.CustomerInsights/hubs/{hubName}/kpi/{kpiName}
  : put:
      tags:
      - Kpi
      operationId: microsoftAzureKpiCreateorupdate
      x-ms-examples:
        Kpi_CreateOrUpdate:
          $ref: ./examples/KpiCreateOrUpdate.json
      description: Creates a KPI or updates an existing KPI in the hub.
      parameters:
      - name: resourceGroupName
        in: path
        required: true
        type: string
        description: The name of the resource group.
      - name: hubName
        in: path
        required: true
        type: string
        description: The name of the hub.
      - name: kpiName
        in: path
        required: true
        type: string
        description: The name of the KPI.
        pattern: ^[a-zA-Z][a-zA-Z0-9_]+$
        minLength: 1
        maxLength: 512
      - name: parameters
        in: body
        required: true
        schema:
          $ref: '#/definitions/KpiResourceFormat'
        description: Parameters supplied to the create/update KPI operation.
      - $ref: '#/parameters/ApiVersionParameter'
      - $ref: '#/parameters/SubscriptionIdParameter'
      responses:
        '200':
          description: OK. Successfully created the KPI.
          schema:
            $ref: '#/definitions/KpiResourceFormat'
        '202':
          description: Accepted. The create KPI operation is accepted.
      x-ms-long-running-operation: true
      summary: Microsoft Azure Put Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Customerinsights Hubs Hubname Kpi Kpiname
    get:
      tags:
      - Kpi
      operationId: microsoftAzureKpiGet
      x-ms-examples:
        Kpi_Get:
          $ref: ./examples/KpiGet.json
      description: Gets a KPI in the hub.
      parameters:
      - name: resourceGroupName
        in: path
        required: true
        type: string
        description: The name of the resource group.
      - name: hubName
        in: path
        required: true
        type: string
        description: The name of the hub.
      - name: kpiName
        in: path
        required: true
        type: string
        description: The name of the KPI.
      - $ref: '#/parameters/ApiVersionParameter'
      - $ref: '#/parameters/SubscriptionIdParameter'
      responses:
        '200':
          description: OK. Successfully get the KPI.
          schema:
            $ref: '#/definitions/KpiResourceFormat'
      summary: Microsoft Azure Get Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Customerinsights Hubs Hubname Kpi Kpiname
    delete:
      tags:
      - Kpi
      operationId: microsoftAzureKpiDelete
      x-ms-examples:
        Kpi_Delete:
          $ref: ./examples/KpiDelete.json
      description: Deletes a KPI in the hub.
      parameters:
      - name: resourceGroupName
        in: path
        required: true
        type: string
        description: The name of the resource group.
      - name: hubName
        in: path
        required: true
        type: string
        description: The name of the hub.
      - name: kpiName
        in: path
        required: true
        type: string
        description: The name of the KPI.
      - $ref: '#/parameters/ApiVersionParameter'
      - $ref: '#/parameters/SubscriptionIdParameter'
      responses:
        '200':
          description: OK. The KPI is deleted.
        '202':
          description: Accepted. The delete operation is accepted.
      x-ms-long-running-operation: true
      summary: Microsoft Azure Delete Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Customerinsights Hubs Hubname Kpi Kpiname
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.CustomerInsights/hubs/{hubName}/kpi/{kpiName}/reprocess
  : post:
      tags:
      - Kpi
      operationId: microsoftAzureKpiReprocess
      x-ms-examples:
        Kpi_Reprocess:
          $ref: ./examples/KpiReprocess.json
      description: Reprocesses the Kpi values of the specified KPI.
      parameters:
      - name: resourceGroupName
        in: path
        required: true
        type: string
        description: The name of the resource group.
      - name: hubName
        in: path
        required: true
        type: string
        description: The name of the hub.
      - name: kpiName
        in: path
        required: true
        type: string
        description: The name of the KPI.
      - $ref: '#/parameters/ApiVersionParameter'
      - $ref: '#/parameters/SubscriptionIdParameter'
      responses:
        '202':
          description: Accepted. Reprocessing Kpi Values operation is accepted.
      summary: Microsoft Azure Post Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Customerinsights Hubs Hubname Kpi Kpiname Reprocess
  /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.CustomerInsights/hubs/{hubName}/kpi:
    get:
      tags:
      - Kpi
      operationId: microsoftAzureKpiListbyhub
      x-ms-examples:
        Kpi_ListByHub:
          $ref: ./examples/KpiListByHub.json
      description: Gets all the KPIs in the specified hub.
      parameters:
      - name: resourceGroupName
        in: path
        required: true
        type: string
        description: The name of the resource group.
      - name: hubName
        in: path
        required: true
        type: string
        description: The name of the hub.
      - $ref: '#/parameters/ApiVersionParameter'
      - $ref: '#/parameters/SubscriptionIdParameter'
      responses:
        '200':
          description: OK. Successfully get all the KPIs in the hub.
          schema:
            $ref: '#/definitions/KpiListResult'
      x-ms-pageable:
        nextLinkName: nextLink
      summary: Microsoft Azure Get Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Customerinsights Hubs Hubname Kpi
definitions:
  KpiDefinition:
    required:
    - entityType
    - entityTypeName
    - calculationWindow
    - function
    - expression
    properties:
      entityType:
        type: string
        enum:
        - None
        - Profile
        - Interaction
        - Relationship
        x-ms-enum:
          name: EntityTypes
          modelAsString: false
        description: The mapping entity type.
      entityTypeName:
        type: string
        description: The mapping entity name.
      tenantId:
        type: string
        readOnly: true
        description: The hub name.
      kpiName:
        type: string
        readOnly: true
        description: The KPI name.
      displayName:
        type: object
        additionalProperties:
          type: string
        description: Localized display name for the KPI.
      description:
        type: object
        additionalProperties:
          type: string
        description: Localized description for the KPI.
      calculationWindow:
        type: string
        enum:
        - Lifetime
        - Hour
        - Day
        - Week
        - Month
        x-ms-enum:
          name: CalculationWindowTypes
          modelAsString: false
        description: The calculation window.
      calculationWindowFieldName:
        type: string
        description: Name of calculation window field.
      function:
        type: string
        enum:
        - Sum
        - Avg
        - Min
        - Max
        - Last
        - Count
        - None
        - CountDistinct
        x-ms-enum:
          name: KpiFunctions
          modelAsString: false
        description: The computation function for the KPI.
      expression:
        type: string
        description: The computation expression for the KPI.
      unit:
        type: string
        description: The unit of measurement for the KPI.
      filter:
        type: string
        description: The filter expression for the KPI.
      groupBy:
        type: array
        items:
          type: string
        description: the group by properties for the KPI.
      groupByMetadata:
        type: array
        readOnly: true
        items:
          $ref: '#/definitions/KpiGroupByMetadata'
        description: The KPI GroupByMetadata.
      participantProfilesMetadata:
        type: array
        readOnly: true
        items:
          $ref: '#/definitions/KpiParticipantProfilesMetadata'
        description: The participant profiles.
      provisioningState:
        $ref: '#/definitions/ProvisioningState'
        readOnly: true
        description: Provisioning state.
      thresHolds:
        $ref: '#/definitions/KpiThresholds'
        description: The KPI thresholds.
      aliases:
        type: array
        items:
          $ref: '#/definitions/KpiAlias'
        description: The aliases.
      extracts:
        type: array
        items:
          $ref: '#/definitions/KpiExtract'
        description: The KPI extracts.
    description: Defines the KPI Threshold limits.
  ProxyResource:
    properties:
      id:
        readOnly: true
        type: string
        description: Resource ID.
      name:
        readOnly: true
        type: string
        description: Resource name.
      type:
        readOnly: true
        type: string
        description: Resource type.
    x-ms-azure-resource: true
    description: Common properties of proxy resource.
  KpiResourceFormat:
    description: The KPI resource format.
    properties:
      properties:
        x-ms-client-flatten: true
        $ref: '#/definitions/KpiDefinition'
    allOf:
    - $ref: '#/definitions/ProxyResource'
  KpiExtract:
    required:
    - extractName
    - expression
    properties:
      extractName:
        type: string
        description: KPI extract name.
      expression:
        type: string
        description: The expression.
    description: The KPI extract.
  ProvisioningState:
    type: string
    enum:
    - Provisioning
    - Succeeded
    - Expiring
    - Deleting
    - HumanIntervention
    - Failed
    x-ms-enum:
      name: ProvisioningStates
      modelAsString: true
    description: Provisioning state.
  KpiParticipantProfilesMetadata:
    required:
    - typeName
    properties:
      typeName:
        type: string
        description: Name of the type.
    description: The KPI participant profile metadata.
  KpiGroupByMetadata:
    properties:
      displayName:
        type: object
        additionalProperties:
          type: string
        description: The display name.
      fieldName:
        type: string
        description: The name of the field.
      fieldType:
        type: string
        description: The type of the field.
    description: The KPI GroupBy field metadata.
  KpiAlias:
    required:
    - aliasName
    - expression
    properties:
      aliasName:
        type: string
        description: KPI alias name.
      expression:
        type: string
        description: The expression.
    description: The KPI alias.
  KpiListResult:
    properties:
      value:
        type: array
        items:
          $ref: '#/definitions/KpiResourceFormat'
        description: Results of the list operation.
      nextLink:
        type: string
        description: Link to the next set of results.
    description: The response of list KPI operation.
  KpiThresholds:
    properties:
      lowerLimit:
        type: number
        format: decimal
        description: The lower threshold limit.
      upperLimit:
        type: number
        format: decimal
        description: The upper threshold limit.
      increasingKpi:
        type: boolean
        description: Whether or not the KPI is an increasing KPI.
    required:
    - lowerLimit
    - upperLimit
    - increasingKpi
    description: Defines the KPI Threshold limits.
parameters:
  ApiVersionParameter:
    name: api-version
    in: query
    required: true
    type: string
    description: Client Api Version.
  SubscriptionIdParameter:
    name: subscriptionId
    in: path
    required: true
    type: string
    description: Gets subscription credentials which uniquely identify Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
