swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector FluidRelayOperations API
schemes:
- https
tags:
- name: FluidRelayOperations
paths:
  /providers/Microsoft.FluidRelay/operations:
    get:
      tags:
      - FluidRelayOperations
      summary: Microsoft Azure List All Operations Provided By Microsoft Fluidrelay
      operationId: microsoftAzureFluidrelayoperationsList
      x-ms-examples:
        List Fluid Relay server operations:
          $ref: ./examples/FluidRelayServerOperations.json
      parameters:
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/ApiVersionParameter
      responses:
        '200':
          description: Operation completed synchronously.
          schema:
            $ref: '#/definitions/OperationListResult'
        default:
          schema:
            $ref: ../../../../../common-types/resource-management/v2/types.json#/definitions/ErrorResponse
          description: Error in operation.
      x-ms-pageable:
        nextLinkName: nextLink
      description: Needs a more full description created.
definitions:
  OperationResult:
    description: A FluidRelay REST API operation.
    type: object
    properties:
      name:
        description: 'Operation name: {provider}/{resource}/{operation}'
        type: string
      display:
        description: The object that represents the operation.
        $ref: '#/definitions/OperationDisplay'
      isDataAction:
        description: Indicates whether the operation is a data action
        type: boolean
  OperationDisplay:
    description: The object that represents the operation.
    type: object
    properties:
      provider:
        description: 'Service provider: Microsoft.FluidRelay'
        type: string
      resource:
        description: Type on which the operation is performed, e.g., 'servers'.
        type: string
      operation:
        description: Operation type, e.g., read, write, delete, etc.
        type: string
      description:
        description: Description of the operation, e.g., 'Write confluent'.
        type: string
  OperationListResult:
    description: Result of GET request to list FluidRelay operations.
    type: object
    properties:
      value:
        description: List of FluidRelay operations supported by the Microsoft.FluidRelay provider.
        type: array
        items:
          $ref: '#/definitions/OperationResult'
      nextLink:
        description: URL to get the next set of operation list results if there are any.
        type: string
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
