swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector EmailGetSendResult API
schemes:
- https
tags:
- name: EmailGetSendResult
paths:
  /emails/operations/{operationId}:
    get:
      tags:
      - EmailGetSendResult
      summary: Microsoft Azure Gets The Status Of The Email Send Operation
      operationId: microsoftAzureEmailGetsendresult
      produces:
      - application/json
      parameters:
      - in: path
        name: operationId
        description: ID of the long running operation (GUID) returned from a previous call to send email
        required: true
        type: string
      - $ref: '#/parameters/ApiVersionParameter'
      responses:
        '200':
          description: Message status was successfully retrieved.
          headers:
            retry-after:
              description: This header will only be present when the status is a non-terminal status. It indicates the minimum amount of time in seconds to wait before polling for operation status again.
              type: integer
              format: int32
          schema:
            $ref: '#/definitions/EmailSendResult'
        default:
          description: Error
          headers:
            x-ms-error-code:
              description: Error code - this will be the same as the code in the error property in the response body.
              type: string
          schema:
            $ref: ../../../../../common-types/data-plane/v1/types.json#/definitions/ErrorResponse
      x-ms-examples:
        Get Message Status FailedTerminalStatus:
          $ref: ./examples/GetOperationStatusReturnsFailedTerminalStatus.json
        Get Message Status NonTerminalStatus:
          $ref: ./examples/GetOperationStatusReturnsNonTerminalStatus.json
        Get Message Status SuccessTerminalStatus:
          $ref: ./examples/GetOperationStatusReturnsSuccessTerminalStatus.json
      description: Needs a more full description created.
definitions:
  EmailSendResult:
    description: Status of the long running operation
    required:
    - id
    - status
    type: object
    properties:
      id:
        description: The unique id of the operation. Use a UUID.
        type: string
        example: 8540c0de-899f-5cce-acb5-3ec493af3800
      status:
        description: Status of operation.
        enum:
        - NotStarted
        - Running
        - Succeeded
        - Failed
        - Canceled
        type: string
        x-ms-enum:
          name: EmailSendStatus
          modelAsString: true
      error:
        description: Error details when status is a non-success terminal state.
        $ref: ../../../../../common-types/data-plane/v1/types.json#/definitions/ErrorDetail
parameters:
  ApiVersionParameter:
    in: query
    name: api-version
    description: Version of API to invoke.
    required: true
    type: string
    x-ms-parameter-location: client
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
