swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector VirtualMachineScaleSetVMs API
schemes:
- https
tags:
- name: VirtualMachineScaleSetVMs
paths:
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/virtualMachineScaleSets/{vmScaleSetName}/virtualmachines/{instanceId}/runCommand
  : post:
      tags:
      - VirtualMachineScaleSetVMs
      operationId: microsoftAzureVirtualmachinescalesetvmsRuncommand
      x-ms-examples:
        VirtualMachineScaleSetVMs_RunCommand:
          $ref: ./examples/runCommandExamples/VirtualMachineScaleSetVMRunCommand.json
      description: Run command on a virtual machine in a VM scale set.
      parameters:
      - name: resourceGroupName
        in: path
        required: true
        type: string
        description: The name of the resource group.
      - name: vmScaleSetName
        in: path
        required: true
        type: string
        description: The name of the VM scale set.
      - name: instanceId
        in: path
        required: true
        type: string
        description: The instance ID of the virtual machine.
      - name: parameters
        in: body
        required: true
        schema:
          $ref: '#/definitions/RunCommandInput'
        description: Parameters supplied to the Run command operation.
      - $ref: ../../../common-types/v1/common.json#/parameters/ApiVersionParameter
      - $ref: ../../../common-types/v1/common.json#/parameters/SubscriptionIdParameter
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/RunCommandResult'
        '202':
          description: Accepted
      x-ms-long-running-operation: true
      x-ms-long-running-operation-options:
        final-state-via: location
      summary: Microsoft Azure Post Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Compute Virtualmachinescalesets Vmscalesetname Virtualmachines Instanceid Runcommand
definitions:
  RunCommandInput:
    properties:
      commandId:
        type: string
        description: The run command id.
      script:
        type: array
        items:
          type: string
        description: Optional. The script to be executed.  When this value is given, the given script will override the default script of the command.
      parameters:
        type: array
        items:
          $ref: '#/definitions/RunCommandInputParameter'
        x-ms-identifiers:
        - name
        description: The run command parameters.
    required:
    - commandId
    type: object
    description: Capture Virtual Machine parameters.
  RunCommandResult:
    properties:
      value:
        type: array
        items:
          $ref: ./computeRPCommon.json#/definitions/InstanceViewStatus
        x-ms-identifiers: []
        description: Run command operation response.
    type: object
  RunCommandInputParameter:
    properties:
      name:
        type: string
        description: The run command parameter name.
      value:
        type: string
        description: The run command parameter value.
    required:
    - name
    - value
    type: object
    description: Describes the properties of a run command parameter.
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
