swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector CertificateRegistrationProvider API
schemes:
- https
tags:
- name: CertificateRegistrationProvider
paths:
  /providers/Microsoft.CertificateRegistration/operations:
    get:
      tags:
      - CertificateRegistrationProvider
      summary: Microsoft Azure Implements Csm Operations Api To Exposes The List Of Available Csm Apis Under The Resource Provider
      description: Description for Implements Csm operations Api to exposes the list of available Csm Apis under the resource provider
      operationId: microsoftAzureCertificateregistrationproviderListoperations
      parameters:
      - $ref: '#/parameters/apiVersionParameter'
      responses:
        '200':
          description: OK
          schema:
            $ref: ../../../Microsoft.Web/stable/2023-01-01/CommonDefinitions.json#/definitions/CsmOperationCollection
        default:
          description: App Service error response.
          schema:
            $ref: ../../../Microsoft.Web/stable/2023-01-01/CommonDefinitions.json#/definitions/DefaultErrorResponse
      x-ms-examples:
        List operations:
          $ref: ./examples/ListOperations.json
      x-ms-pageable:
        nextLinkName: nextLink
parameters:
  apiVersionParameter:
    name: api-version
    in: query
    description: API Version
    required: true
    type: string
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
