swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector deploymentManifests API
schemes:
- https
tags:
- name: deploymentManifests
paths:
  /deploymentManifests:
    get:
      operationId: microsoftAzureDeploymentmanifestsList
      summary: Microsoft Azure Get The List Of Deployment Manifests
      description: Get the list of deployment manifests.
      x-ms-examples:
        List deployment manifests:
          $ref: ./examples/deploymentManifest_list.json
      parameters:
      - $ref: '#/parameters/Version'
      - $ref: '#/parameters/MaxPageSize'
      - $ref: '#/parameters/Filter'
      x-ms-pageable:
        nextLinkName: nextLink
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/DeploymentManifestCollection'
        default:
          description: An error response received from the IoT Central Service.
          headers:
            x-ms-error-code:
              type: string
              description: Error code for specific error that occurred.
          schema:
            $ref: '#/definitions/Error'
      tags:
      - deploymentManifests
  /deploymentManifests/{deploymentManifestId}:
    get:
      operationId: microsoftAzureDeploymentmanifestsGet
      summary: Microsoft Azure Get A Deployment Manifest By Id
      description: Get a deployment manifest by ID.
      x-ms-examples:
        Get deployment manifest by ID:
          $ref: ./examples/deploymentManifest_get.json
      parameters:
      - $ref: '#/parameters/Version'
      - $ref: '#/parameters/DeploymentManifestId'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/DeploymentManifest'
        default:
          description: An error response received from the IoT Central Service.
          headers:
            x-ms-error-code:
              type: string
              description: Error code for specific error that occurred.
          schema:
            $ref: '#/definitions/Error'
      tags:
      - deploymentManifests
    put:
      operationId: microsoftAzureDeploymentmanifestsCreate
      summary: Microsoft Azure Create A New Deployment Manifest
      description: Create a new deployment manifest.
      x-ms-examples:
        Create deployment manifest:
          $ref: ./examples/deploymentManifest_create.json
      parameters:
      - $ref: '#/parameters/Version'
      - $ref: '#/parameters/DeploymentManifestId'
      - in: body
        name: body
        description: deployment manifest body.
        schema:
          $ref: '#/definitions/DeploymentManifest'
        required: true
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/DeploymentManifest'
        default:
          description: An error response received from the IoT Central Service.
          headers:
            x-ms-error-code:
              type: string
              description: Error code for specific error that occurred.
          schema:
            $ref: '#/definitions/Error'
      tags:
      - deploymentManifests
    patch:
      operationId: microsoftAzureDeploymentmanifestsUpdate
      summary: Microsoft Azure Update An Existing Deployment Manifest
      description: Update an existing deployment manifest.
      x-ms-examples:
        Update deployment manifest:
          $ref: ./examples/deploymentManifest_update.json
      consumes:
      - application/merge-patch+json
      parameters:
      - $ref: '#/parameters/Version'
      - $ref: '#/parameters/DeploymentManifestId'
      - in: body
        name: body
        description: Deployment manifest patch body.
        schema:
          type: object
        required: true
      - $ref: '#/parameters/IfMatch'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/DeploymentManifest'
        default:
          description: An error response received from the IoT Central Service.
          headers:
            x-ms-error-code:
              type: string
              description: Error code for specific error that occurred.
          schema:
            $ref: '#/definitions/Error'
      tags:
      - deploymentManifests
    delete:
      operationId: microsoftAzureDeploymentmanifestsRemove
      summary: Microsoft Azure Delete A Deployment Manifest
      description: Delete a deployment manifest.
      x-ms-examples:
        Delete deployment manifest:
          $ref: ./examples/deploymentManifest_delete.json
      parameters:
      - $ref: '#/parameters/Version'
      - $ref: '#/parameters/DeploymentManifestId'
      responses:
        '204':
          description: Success
        default:
          description: An error response received from the IoT Central Service.
          headers:
            x-ms-error-code:
              type: string
              description: Error code for specific error that occurred.
          schema:
            $ref: '#/definitions/Error'
      tags:
      - deploymentManifests
definitions:
  ErrorDetails:
    description: The detail information of the error.
    type: object
    properties:
      code:
        type: string
        description: Error code.
      message:
        type: string
        description: Error message details.
      requestId:
        type: string
        description: Correlation Id for current request.
      time:
        type: string
        format: date-time-rfc1123
        description: The time that error request failed.
    required:
    - code
    - message
  DeploymentManifestCollection:
    description: The paged results of deployment manifests.
    type: object
    properties:
      value:
        description: The collection of deployment manifests.
        type: array
        items:
          $ref: '#/definitions/DeploymentManifest'
      nextLink:
        description: URL to get the next page of deployment manifests.
        type: string
    required:
    - value
  DeploymentManifest:
    description: The deployment manifest used for edge devices.
    type: object
    properties:
      id:
        description: Unique ID of the deployment manifest.
        type: string
        readOnly: true
      displayName:
        description: Display name of the deployment manifest.
        type: string
        minLength: 1
      data:
        description: Content of the the deployment manifest.
        type: object
      etag:
        description: Etag to prevent conflict when updating the deployment manifest.
        type: string
      organizations:
        description: The organization that deployment manifest belongs to. If not present, the deployment manifest is root-level or personal. Only one organization is supported today, multiple organizations will be supported soon.
        type: array
        items:
          type: string
        maxItems: 1
        minItems: 1
    required:
    - data
  Error:
    description: The response error definition.
    type: object
    properties:
      error:
        description: Error details for current request.
        $ref: '#/definitions/ErrorDetails'
    required:
    - error
parameters:
  DeploymentManifestId:
    in: path
    name: deploymentManifestId
    description: Unique ID for the deployment manifest.
    x-ms-parameter-location: method
    type: string
    maxLength: 255
    pattern: ^[a-zA-Z0-9:;]*$
    required: true
  Filter:
    in: query
    name: filter
    description: An expression on the resource type that selects the resources to be returned.
    x-ms-parameter-location: method
    type: string
    required: false
  MaxPageSize:
    in: query
    name: maxpagesize
    description: The maximum number of resources to return from one response.
    x-ms-parameter-location: method
    type: integer
    format: int32
    minimum: 1
    maximum: 100
    required: false
  Version:
    in: query
    name: api-version
    description: The version of the API being called.
    x-ms-parameter-location: client
    type: string
    required: true
  IfMatch:
    in: header
    name: If-Match
    description: Only perform the operation if the entity's etag matches one of the etags provided or * is provided.
    x-ms-parameter-location: method
    type: string
    required: false
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
