swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector Predictions API
schemes:
- https
tags:
- name: Predictions
paths:
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.CustomerInsights/hubs/{hubName}/predictions/{predictionName}
  : put:
      tags:
      - Predictions
      operationId: microsoftAzurePredictionsCreateorupdate
      x-ms-examples:
        Predictions_CreateOrUpdate:
          $ref: ./examples/PredictionsCreateOrUpdate.json
      description: Creates a Prediction or updates an existing Prediction in the hub.
      parameters:
      - name: resourceGroupName
        in: path
        required: true
        type: string
        description: The name of the resource group.
      - name: hubName
        in: path
        required: true
        type: string
        description: The name of the hub.
      - name: predictionName
        in: path
        required: true
        type: string
        description: The name of the Prediction.
        minLength: 1
        maxLength: 512
      - name: parameters
        in: body
        required: true
        schema:
          $ref: '#/definitions/PredictionResourceFormat'
        description: Parameters supplied to the create/update Prediction operation.
      - $ref: '#/parameters/ApiVersionParameter'
      - $ref: '#/parameters/SubscriptionIdParameter'
      responses:
        '200':
          description: OK. Successfully created the Prediction.
          schema:
            $ref: '#/definitions/PredictionResourceFormat'
        '202':
          description: Accepted. The create Prediction operation is accepted.
      x-ms-long-running-operation: true
      summary: Microsoft Azure Put Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Customerinsights Hubs Hubname Predictions Predictionname
    get:
      tags:
      - Predictions
      operationId: microsoftAzurePredictionsGet
      x-ms-examples:
        Predictions_Get:
          $ref: ./examples/PredictionsGet.json
      description: Gets a Prediction in the hub.
      parameters:
      - name: resourceGroupName
        in: path
        required: true
        type: string
        description: The name of the resource group.
      - name: hubName
        in: path
        required: true
        type: string
        description: The name of the hub.
      - name: predictionName
        in: path
        required: true
        type: string
        description: The name of the Prediction.
      - $ref: '#/parameters/ApiVersionParameter'
      - $ref: '#/parameters/SubscriptionIdParameter'
      responses:
        '200':
          description: OK. Successfully get the Prediction.
          schema:
            $ref: '#/definitions/PredictionResourceFormat'
      summary: Microsoft Azure Get Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Customerinsights Hubs Hubname Predictions Predictionname
    delete:
      tags:
      - Predictions
      operationId: microsoftAzurePredictionsDelete
      x-ms-examples:
        Predictions_Delete:
          $ref: ./examples/PredictionsDelete.json
      description: Deletes a Prediction in the hub.
      parameters:
      - name: resourceGroupName
        in: path
        required: true
        type: string
        description: The name of the resource group.
      - name: hubName
        in: path
        required: true
        type: string
        description: The name of the hub.
      - name: predictionName
        in: path
        required: true
        type: string
        description: The name of the Prediction.
      - $ref: '#/parameters/ApiVersionParameter'
      - $ref: '#/parameters/SubscriptionIdParameter'
      responses:
        '200':
          description: OK. The Prediction is deleted.
        '202':
          description: Accepted. The delete operation is accepted.
      x-ms-long-running-operation: true
      summary: Microsoft Azure Delete Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Customerinsights Hubs Hubname Predictions Predictionname
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.CustomerInsights/hubs/{hubName}/predictions/{predictionName}/getTrainingResults
  : post:
      tags:
      - Predictions
      operationId: microsoftAzurePredictionsGettrainingresults
      x-ms-examples:
        Predictions_GetTrainingResults:
          $ref: ./examples/PredictionsGetTrainingResults.json
      description: Gets training results.
      parameters:
      - name: resourceGroupName
        in: path
        required: true
        type: string
        description: The name of the resource group.
      - name: hubName
        in: path
        required: true
        type: string
        description: The name of the hub.
      - name: predictionName
        in: path
        required: true
        type: string
        description: The name of the Prediction.
      - $ref: '#/parameters/ApiVersionParameter'
      - $ref: '#/parameters/SubscriptionIdParameter'
      responses:
        '200':
          description: OK. Successfully get the training results.
          schema:
            $ref: '#/definitions/PredictionTrainingResults'
      summary: Microsoft Azure Post Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Customerinsights Hubs Hubname Predictions Predictionname Gettrainingresults
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.CustomerInsights/hubs/{hubName}/predictions/{predictionName}/getModelStatus
  : post:
      tags:
      - Predictions
      operationId: microsoftAzurePredictionsGetmodelstatus
      x-ms-examples:
        Predictions_GetModelStatus:
          $ref: ./examples/PredictionsGetModelStatus.json
      description: Gets model status of the prediction.
      parameters:
      - name: resourceGroupName
        in: path
        required: true
        type: string
        description: The name of the resource group.
      - name: hubName
        in: path
        required: true
        type: string
        description: The name of the hub.
      - name: predictionName
        in: path
        required: true
        type: string
        description: The name of the Prediction.
      - $ref: '#/parameters/ApiVersionParameter'
      - $ref: '#/parameters/SubscriptionIdParameter'
      responses:
        '200':
          description: OK. Successfully get the model status.
          schema:
            $ref: '#/definitions/PredictionModelStatus'
      summary: Microsoft Azure Post Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Customerinsights Hubs Hubname Predictions Predictionname Getmodelstatus
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.CustomerInsights/hubs/{hubName}/predictions/{predictionName}/modelStatus
  : post:
      tags:
      - Predictions
      operationId: microsoftAzurePredictionsModelstatus
      x-ms-examples:
        Predictions_ModelStatus:
          $ref: ./examples/PredictionsModelStatus.json
      description: Creates or updates the model status of prediction.
      parameters:
      - name: resourceGroupName
        in: path
        required: true
        type: string
        description: The name of the resource group.
      - name: hubName
        in: path
        required: true
        type: string
        description: The name of the hub.
      - name: predictionName
        in: path
        required: true
        type: string
        description: The name of the Prediction.
      - name: parameters
        in: body
        required: true
        schema:
          $ref: '#/definitions/PredictionModelStatus'
        description: Parameters supplied to the create/update prediction model status operation.
      - $ref: '#/parameters/ApiVersionParameter'
      - $ref: '#/parameters/SubscriptionIdParameter'
      responses:
        '200':
          description: OK. Successfully created or updated the prediction model status.
      summary: Microsoft Azure Post Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Customerinsights Hubs Hubname Predictions Predictionname Modelstatus
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.CustomerInsights/hubs/{hubName}/predictions
  : get:
      tags:
      - Predictions
      operationId: microsoftAzurePredictionsListbyhub
      x-ms-examples:
        Predictions_ListByHub:
          $ref: ./examples/PredictionsListByHub.json
      description: Gets all the predictions in the specified hub.
      parameters:
      - name: resourceGroupName
        in: path
        required: true
        type: string
        description: The name of the resource group.
      - name: hubName
        in: path
        required: true
        type: string
        description: The name of the hub.
      - $ref: '#/parameters/ApiVersionParameter'
      - $ref: '#/parameters/SubscriptionIdParameter'
      responses:
        '200':
          description: OK. Successfully get all the predictions in the hub.
          schema:
            $ref: '#/definitions/PredictionListResult'
      x-ms-pageable:
        nextLinkName: nextLink
      summary: Microsoft Azure Get Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Customerinsights Hubs Hubname Predictions
definitions:
  PredictionModelStatus:
    required:
    - status
    description: The prediction model status.
    properties:
      tenantId:
        type: string
        readOnly: true
        description: The hub name.
      predictionName:
        type: string
        readOnly: true
        description: The prediction name.
      predictionGuidId:
        type: string
        readOnly: true
        description: The prediction GUID ID.
      status:
        type: string
        enum:
        - New
        - Provisioning
        - ProvisioningFailed
        - PendingDiscovering
        - Discovering
        - PendingFeaturing
        - Featuring
        - FeaturingFailed
        - PendingTraining
        - Training
        - TrainingFailed
        - Evaluating
        - EvaluatingFailed
        - PendingModelConfirmation
        - Active
        - Deleted
        - HumanIntervention
        - Failed
        x-ms-enum:
          name: PredictionModelLifeCycle
          modelAsString: true
        description: Prediction model life cycle.  When prediction is in PendingModelConfirmation status, it is allowed to update the status to PendingFeaturing or Active through API.
      message:
        type: string
        readOnly: true
        description: The model status message.
      trainingSetCount:
        type: integer
        readOnly: true
        description: Count of the training set.
      testSetCount:
        type: integer
        readOnly: true
        description: Count of the test set.
      validationSetCount:
        type: integer
        readOnly: true
        description: Count of the validation set.
      trainingAccuracy:
        type: integer
        format: decimal
        readOnly: true
        description: The training accuracy.
      signalsUsed:
        type: integer
        readOnly: true
        description: The signals used.
      modelVersion:
        type: string
        readOnly: true
        description: Version of the model.
  Prediction:
    required:
    - negativeOutcomeExpression
    - positiveOutcomeExpression
    - primaryProfileType
    - scopeExpression
    - autoAnalyze
    - mappings
    - scoreLabel
    description: The prediction definition.
    properties:
      description:
        type: object
        additionalProperties:
          type: string
        description: Description of the prediction.
      displayName:
        type: object
        additionalProperties:
          type: string
        description: Display name of the prediction.
      involvedInteractionTypes:
        type: array
        items:
          type: string
        description: Interaction types involved in the prediction.
      involvedKpiTypes:
        type: array
        items:
          type: string
        description: KPI types involved in the prediction.
      involvedRelationships:
        type: array
        items:
          type: string
        description: Relationships involved in the prediction.
      negativeOutcomeExpression:
        type: string
        description: Negative outcome expression.
      positiveOutcomeExpression:
        type: string
        description: Positive outcome expression.
      primaryProfileType:
        type: string
        description: Primary profile type.
      provisioningState:
        $ref: '#/definitions/ProvisioningState'
        readOnly: true
        description: Provisioning state.
      predictionName:
        type: string
        description: Name of the prediction.
      scopeExpression:
        type: string
        description: Scope expression.
      tenantId:
        type: string
        readOnly: true
        description: The hub name.
      autoAnalyze:
        type: boolean
        description: Whether do auto analyze.
      mappings:
        required:
        - score
        - grade
        - reason
        type: object
        properties:
          score:
            type: string
            description: The score of the link mapping.
          grade:
            type: string
            description: The grade of the link mapping.
          reason:
            type: string
            description: The reason of the link mapping.
        description: Definition of the link mapping of prediction.
      scoreLabel:
        type: string
        description: Score label.
      grades:
        type: array
        items:
          type: object
          properties:
            gradeName:
              type: string
              description: Name of the grade.
            minScoreThreshold:
              type: integer
              description: Minimum score threshold.
            maxScoreThreshold:
              type: integer
              description: Maximum score threshold.
          description: The definition of a prediction grade.
        description: The prediction grades.
      systemGeneratedEntities:
        readOnly: true
        properties:
          generatedInteractionTypes:
            type: array
            items:
              type: string
            description: Generated interaction types.
          generatedLinks:
            type: array
            items:
              type: string
            description: Generated links.
          generatedKpis:
            type: object
            additionalProperties:
              type: string
            description: Generated KPIs.
        description: System generated entities.
  ProxyResource:
    properties:
      id:
        readOnly: true
        type: string
        description: Resource ID.
      name:
        readOnly: true
        type: string
        description: Resource name.
      type:
        readOnly: true
        type: string
        description: Resource type.
    x-ms-azure-resource: true
    description: Common properties of proxy resource.
  PredictionResourceFormat:
    description: The prediction resource format.
    properties:
      properties:
        x-ms-client-flatten: true
        $ref: '#/definitions/Prediction'
    allOf:
    - $ref: '#/definitions/ProxyResource'
  CanonicalProfileDefinition:
    properties:
      canonicalProfileId:
        type: integer
        description: Canonical profile ID.
      properties:
        type: array
        items:
          type: object
          properties:
            profileName:
              type: string
              description: Profile name.
            profilePropertyName:
              type: string
              description: Property name of profile.
            rank:
              type: integer
              description: The rank.
            type:
              type: string
              enum:
              - Numeric
              - Categorical
              - DerivedCategorical
              - DerivedNumeric
              x-ms-enum:
                name: CanonicalPropertyValueType
                modelAsString: true
              description: Type of canonical property value.
            value:
              type: string
              description: Value of the canonical property.
          description: The definition of a canonical profile property.
        description: Properties of the canonical profile.
    description: Definition of canonical profile.
  PredictionListResult:
    properties:
      value:
        type: array
        items:
          $ref: '#/definitions/PredictionResourceFormat'
        description: Results of the list operation.
      nextLink:
        type: string
        description: Link to the next set of results.
    description: The response of list predictions operation.
  PredictionTrainingResults:
    properties:
      tenantId:
        type: string
        readOnly: true
        description: The hub name.
      scoreName:
        type: string
        readOnly: true
        description: Score name.
      predictionDistribution:
        readOnly: true
        $ref: '#/definitions/PredictionDistributionDefinition'
        description: Prediction distribution.
      canonicalProfiles:
        readOnly: true
        type: array
        items:
          $ref: '#/definitions/CanonicalProfileDefinition'
        description: Canonical profiles.
      primaryProfileInstanceCount:
        readOnly: true
        type: integer
        format: int64
        description: Instance count of the primary profile.
    description: The training results of the prediction.
  ProvisioningState:
    type: string
    enum:
    - Provisioning
    - Succeeded
    - Expiring
    - Deleting
    - HumanIntervention
    - Failed
    x-ms-enum:
      name: ProvisioningStates
      modelAsString: true
    description: Provisioning state.
  PredictionDistributionDefinition:
    properties:
      totalPositives:
        type: integer
        format: int64
        description: Total positive in the distribution.
      totalNegatives:
        type: integer
        format: int64
        description: Total negatives in the distribution.
      distributions:
        type: array
        items:
          type: object
          properties:
            scoreThreshold:
              type: integer
              description: Score threshold.
            positives:
              type: integer
              format: int64
              description: Number of positives.
            negatives:
              type: integer
              format: int64
              description: Number of negatives.
            positivesAboveThreshold:
              type: integer
              format: int64
              description: Number of positives above threshold.
            negativesAboveThreshold:
              type: integer
              format: int64
              description: Number of negatives above threshold.
          description: The definition of a prediction distribution.
        description: Distributions of the prediction.
    description: The definition of the prediction distribution.
parameters:
  ApiVersionParameter:
    name: api-version
    in: query
    required: true
    type: string
    description: Client Api Version.
  SubscriptionIdParameter:
    name: subscriptionId
    in: path
    required: true
    type: string
    description: Gets subscription credentials which uniquely identify Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
