swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector Blueprint API
schemes:
- https
tags:
- name: Blueprint
paths:
  /{resourceScope}/providers/Microsoft.Blueprint/blueprints/{blueprintName}:
    put:
      tags:
      - Blueprint
      operationId: microsoftAzureBlueprintsCreateorupdate
      description: Create or update a blueprint definition.
      x-ms-examples:
        SubscriptionBlueprint:
          $ref: ./examples/subscriptionBPDef/Blueprint_Create.json
        ManagementGroupBlueprint:
          $ref: ./examples/managementGroupBPDef/Blueprint_Create.json
        ResourceGroupWithTags:
          $ref: ./examples/ResourceGroupWithTags.json
      parameters:
      - $ref: '#/parameters/ApiVersionParameter'
      - $ref: '#/parameters/ScopeParameter'
      - $ref: '#/parameters/BlueprintNameParameter'
      - name: blueprint
        in: body
        required: true
        schema:
          $ref: '#/definitions/Blueprint'
        description: Blueprint definition.
      responses:
        '201':
          description: Created -- blueprint definition saved.
          schema:
            $ref: '#/definitions/Blueprint'
        default:
          description: Blueprints error response.
          schema:
            $ref: '#/definitions/CloudError'
      summary: Microsoft Azure Put Resourcescope Providers Microsoft Blueprint Blueprints Blueprintname
    get:
      tags:
      - Blueprint
      operationId: microsoftAzureBlueprintsGet
      description: Get a blueprint definition.
      x-ms-examples:
        SubscriptionBlueprint:
          $ref: ./examples/subscriptionBPDef/Blueprint_Get.json
        ManagementGroupBlueprint:
          $ref: ./examples/managementGroupBPDef/Blueprint_Get.json
      parameters:
      - $ref: '#/parameters/ApiVersionParameter'
      - $ref: '#/parameters/ScopeParameter'
      - $ref: '#/parameters/BlueprintNameParameter'
      responses:
        '200':
          description: OK -- blueprint definition retrieved.
          schema:
            $ref: '#/definitions/Blueprint'
        default:
          description: Blueprints error response.
          schema:
            $ref: '#/definitions/CloudError'
      summary: Microsoft Azure Get Resourcescope Providers Microsoft Blueprint Blueprints Blueprintname
    delete:
      tags:
      - Blueprint
      operationId: microsoftAzureBlueprintsDelete
      description: Delete a blueprint definition.
      x-ms-examples:
        SubscriptionBlueprint:
          $ref: ./examples/subscriptionBPDef/Blueprint_Delete.json
        ManagementGroupBlueprint:
          $ref: ./examples/managementGroupBPDef/Blueprint_Delete.json
      parameters:
      - $ref: '#/parameters/ApiVersionParameter'
      - $ref: '#/parameters/ScopeParameter'
      - $ref: '#/parameters/BlueprintNameParameter'
      responses:
        '200':
          description: OK -- blueprint definition deleted.
          schema:
            $ref: '#/definitions/Blueprint'
        '204':
          description: No Content
        default:
          description: Blueprints error response.
          schema:
            $ref: '#/definitions/CloudError'
      summary: Microsoft Azure Delete Resourcescope Providers Microsoft Blueprint Blueprints Blueprintname
  /{resourceScope}/providers/Microsoft.Blueprint/blueprints:
    get:
      tags:
      - Blueprint
      operationId: microsoftAzureBlueprintsList
      description: List blueprint definitions.
      x-ms-examples:
        SubscriptionBlueprint:
          $ref: ./examples/subscriptionBPDef/Blueprint_List.json
        ManagementGroupBlueprint:
          $ref: ./examples/managementGroupBPDef/Blueprint_List.json
      parameters:
      - $ref: '#/parameters/ApiVersionParameter'
      - $ref: '#/parameters/ScopeParameter'
      responses:
        '200':
          description: OK -- retrieved list of blueprint definitions.
          schema:
            $ref: '#/definitions/BlueprintList'
        default:
          description: Blueprints error response.
          schema:
            $ref: '#/definitions/CloudError'
      x-ms-pageable:
        nextLinkName: nextLink
      summary: Microsoft Azure Get Resourcescope Providers Microsoft Blueprint Blueprints
definitions:
  ParameterDefinition:
    description: Represent a parameter with constrains and metadata.
    type: object
    properties:
      type:
        type: string
        description: Allowed data types for Resource Manager template parameters.
        enum:
        - string
        - array
        - bool
        - int
        - object
        - secureObject
        - secureString
        x-ms-enum:
          name: TemplateParameterType
          modelAsString: true
      metadata:
        description: User-friendly properties for this parameter.
        x-ms-client-flatten: true
        $ref: '#/definitions/ParameterDefinitionMetadata'
      defaultValue:
        description: Default Value for this parameter.
      allowedValues:
        type: array
        description: Array of allowed values for this parameter.
        items:
          description: Allowed value.
    required:
    - type
  ResourceGroupDefinition:
    description: Represents an Azure resource group in a blueprint definition.
    type: object
    properties:
      name:
        type: string
        description: Name of this resourceGroup. Leave empty if the resource group name will be specified during the blueprint assignment.
      location:
        type: string
        description: Location of this resourceGroup. Leave empty if the resource group location will be specified during the blueprint assignment.
      metadata:
        description: User-friendly properties for this resource group.
        x-ms-client-flatten: true
        $ref: '#/definitions/ParameterDefinitionMetadata'
      dependsOn:
        type: array
        description: Artifacts which need to be deployed before this resource group.
        items:
          type: string
          description: Name of peer artifact.
      tags:
        description: Tags to be assigned to this resource group.
        type: object
        additionalProperties:
          type: string
  CloudError:
    x-ms-external: true
    properties:
      error:
        $ref: ../../../../../common-types/resource-management/v1/types.json#/definitions/ErrorResponse
  Blueprint:
    type: object
    description: Represents a Blueprint definition.
    allOf:
    - $ref: '#/definitions/AzureResourceBase'
    properties:
      properties:
        description: Detailed properties for blueprint definition.
        x-ms-client-flatten: true
        $ref: '#/definitions/BlueprintProperties'
    required:
    - properties
  SharedBlueprintProperties:
    description: Shared Schema for both blueprintProperties and publishedBlueprintProperties.
    type: object
    x-ms-external: true
    properties:
      status:
        description: Status of the blueprint. This field is readonly.
        readOnly: true
        $ref: '#/definitions/BlueprintStatus'
      targetScope:
        type: string
        description: The scope where this blueprint definition can be assigned.
        enum:
        - subscription
        - managementGroup
        x-ms-enum:
          name: BlueprintTargetScope
          modelAsString: true
          values:
          - value: subscription
            description: The blueprint targets a subscription during blueprint assignment.
          - value: managementGroup
            description: The blueprint targets a management group during blueprint assignment. This is reserved for future use.
      parameters:
        description: Parameters required by this blueprint definition.
        type: object
        additionalProperties:
          description: Named collection of parameter metadata.
          $ref: '#/definitions/ParameterDefinition'
      resourceGroups:
        description: Resource group placeholders defined by this blueprint definition.
        type: object
        additionalProperties:
          description: Named collection for resourceGroupDefinition.
          $ref: '#/definitions/ResourceGroupDefinition'
    allOf:
    - $ref: '#/definitions/BlueprintResourcePropertiesBase'
  BlueprintResourcePropertiesBase:
    description: Shared properties between all blueprint resources.
    type: object
    x-ms-external: true
    properties:
      displayName:
        type: string
        description: One-liner string explain this resource.
        maxLength: 256
      description:
        type: string
        description: Multi-line explain this resource.
        maxLength: 500
  BlueprintList:
    type: object
    title: BlueprintList
    description: List of blueprint definitions.
    properties:
      value:
        type: array
        description: List of blueprint definitions.
        items:
          $ref: '#/definitions/Blueprint'
      nextLink:
        type: string
        readOnly: true
        description: Link to the next page of results.
  BlueprintStatus:
    description: The status of the blueprint. This field is readonly.
    type: object
    properties: {}
    allOf:
    - $ref: '#/definitions/BlueprintResourceStatusBase'
  BlueprintProperties:
    description: Schema for blueprint definition properties.
    type: object
    x-ms-external: true
    allOf:
    - $ref: '#/definitions/SharedBlueprintProperties'
    properties:
      versions:
        type: object
        description: Published versions of this blueprint definition.
      layout:
        type: object
        readOnly: true
        description: Layout view of the blueprint definition for UI reference.
    required:
    - targetScope
  AzureResourceBase:
    description: Common properties for all Azure resources.
    type: object
    x-ms-azure-resource: true
    properties:
      id:
        readOnly: true
        type: string
        description: String Id used to locate any resource on Azure.
      type:
        readOnly: true
        type: string
        description: Type of this resource.
      name:
        readOnly: true
        type: string
        description: Name of this resource.
  ParameterDefinitionMetadata:
    type: object
    description: User-friendly properties for this parameter.
    properties:
      displayName:
        type: string
        description: DisplayName of this parameter/resourceGroup.
        maxLength: 256
      description:
        type: string
        description: Description of this parameter/resourceGroup.
        maxLength: 500
      strongType:
        type: string
        description: StrongType for UI to render rich experience during blueprint assignment. Supported strong types are resourceType, principalId and location.
        maxLength: 64
  BlueprintResourceStatusBase:
    description: Shared status properties between all blueprint resources.
    type: object
    properties:
      timeCreated:
        type: string
        format: date-time
        readOnly: true
        description: Creation time of this blueprint definition.
      lastModified:
        type: string
        format: date-time
        readOnly: true
        description: Last modified time of this blueprint definition.
parameters:
  ApiVersionParameter:
    name: api-version
    in: query
    required: true
    type: string
    x-ms-parameter-location: client
    description: Client API Version.
  ScopeParameter:
    name: resourceScope
    in: path
    required: true
    type: string
    description: 'The scope of the resource. Valid scopes are: management group (format: ''/providers/Microsoft.Management/managementGroups/{managementGroup}''), subscription (format: ''/subscriptions/{subscriptionId}'').'
    x-ms-parameter-location: method
    x-ms-skip-url-encoding: true
  BlueprintNameParameter:
    name: blueprintName
    in: path
    required: true
    type: string
    x-ms-parameter-location: method
    description: Name of the blueprint definition.
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
