swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector DefaultAccount API
schemes:
- https
tags:
- name: DefaultAccount
paths:
  /providers/Microsoft.Purview/getDefaultAccount:
    get:
      tags:
      - DefaultAccount
      summary: Microsoft Azure Gets The Default Account Information Set For The Scope
      description: Get the default account for the scope.
      operationId: microsoftAzureDefaultaccountsGet
      parameters:
      - name: scopeTenantId
        in: query
        description: The tenant ID.
        required: true
        type: string
        format: uuid
      - name: scopeType
        in: query
        description: The scope for the default account.
        required: true
        type: string
        enum:
        - Tenant
        - Subscription
        x-ms-enum:
          name: ScopeType
          modelAsString: true
      - name: scope
        in: query
        description: The Id of the scope object, for example if the scope is "Subscription" then it is the ID of that subscription.
        required: false
        type: string
      - $ref: '#/parameters/api-version'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/DefaultAccountPayload'
        default:
          description: An error response received from the provider.
          schema:
            $ref: '#/definitions/ErrorResponseModel'
      x-ms-examples:
        DefaultAccounts_Get:
          $ref: ./examples/DefaultAccounts_Get.json
  /providers/Microsoft.Purview/setDefaultAccount:
    post:
      tags:
      - DefaultAccount
      summary: Microsoft Azure Sets The Default Account For The Scope
      description: Sets the default account for the scope.
      operationId: microsoftAzureDefaultaccountsSet
      parameters:
      - name: defaultAccountPayload
        in: body
        description: The payload containing the default account information and the scope.
        required: true
        schema:
          $ref: '#/definitions/DefaultAccountPayload'
      - $ref: '#/parameters/api-version'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/DefaultAccountPayload'
        default:
          description: An error response received from the provider.
          schema:
            $ref: '#/definitions/ErrorResponseModel'
      x-ms-examples:
        DefaultAccounts_Set:
          $ref: ./examples/DefaultAccounts_Set.json
  /providers/Microsoft.Purview/removeDefaultAccount:
    post:
      tags:
      - DefaultAccount
      summary: Microsoft Azure Removes The Default Account From The Scope
      description: Removes the default account from the scope.
      operationId: microsoftAzureDefaultaccountsRemove
      parameters:
      - name: scopeTenantId
        in: query
        description: The tenant ID.
        required: true
        type: string
        format: uuid
      - name: scopeType
        in: query
        description: The scope for the default account.
        required: true
        type: string
        enum:
        - Tenant
        - Subscription
        x-ms-enum:
          name: ScopeType
          modelAsString: true
      - name: scope
        in: query
        description: The Id of the scope object, for example if the scope is "Subscription" then it is the ID of that subscription.
        required: false
        type: string
      - $ref: '#/parameters/api-version'
      responses:
        '200':
          description: Success
        '204':
          description: Success
        default:
          description: An error response received from the provider.
          schema:
            $ref: '#/definitions/ErrorResponseModel'
      x-ms-examples:
        DefaultAccounts_Remove:
          $ref: ./examples/DefaultAccounts_Remove.json
definitions:
  ErrorResponseModel:
    description: Default error response model
    type: object
    properties:
      error:
        description: Gets or sets the error.
        allOf:
        - $ref: '#/definitions/ErrorModel'
        readOnly: true
  ErrorModel:
    description: Default error model
    type: object
    properties:
      code:
        description: Gets or sets the code.
        type: string
        readOnly: true
      details:
        description: Gets or sets the details.
        uniqueItems: false
        type: array
        items:
          $ref: '#/definitions/ErrorModel'
        readOnly: true
      message:
        description: Gets or sets the messages.
        type: string
        readOnly: true
      target:
        description: Gets or sets the target.
        type: string
        readOnly: true
  DefaultAccountPayload:
    description: Payload to get and set the default account in the given scope
    type: object
    properties:
      accountName:
        description: The name of the account that is set as the default.
        type: string
      resourceGroupName:
        description: The resource group name of the account that is set as the default.
        type: string
      scope:
        description: The scope object ID. For example, sub ID or tenant ID.
        type: string
      scopeTenantId:
        description: The scope tenant in which the default account is set.
        type: string
      scopeType:
        description: The scope where the default account is set.
        enum:
        - Tenant
        - Subscription
        type: string
        x-ms-enum:
          name: scopeType
          modelAsString: true
      subscriptionId:
        description: The subscription ID of the account that is set as the default.
        type: string
parameters:
  api-version:
    name: api-version
    in: query
    description: The api version to use.
    required: true
    type: string
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
