swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector Addresses API
schemes:
- https
tags:
- name: Addresses
paths:
  /subscriptions/{subscriptionId}/providers/Microsoft.EdgeOrder/addresses:
    get:
      tags:
      - Addresses
      description: List all the addresses available under the subscription.
      operationId: microsoftAzureAddressesListbysubscription
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/ApiVersionParameter
      - name: $filter
        in: query
        description: $filter is supported to filter based on shipping address properties. Filter supports only equals operation.
        required: false
        type: string
      - name: $skipToken
        in: query
        description: $skipToken is supported on Get list of addresses, which provides the next page in the list of addresses.
        required: false
        type: string
      - name: $top
        in: query
        description: $top is supported on fetching list of resources. $top=10 means that the first 10 items in the list will be returned to the API caller.
        required: false
        type: integer
        format: int32
      responses:
        '200':
          description: List of addresses available under the subscription.
          schema:
            $ref: '#/definitions/AddressResourceList'
        default:
          description: Error response describing reason for operation failure.
          schema:
            $ref: ../../../../../common-types/resource-management/v2/types.json#/definitions/ErrorResponse
      x-ms-pageable:
        nextLinkName: nextLink
      x-ms-examples:
        ListAddressesAtSubscriptionLevel:
          $ref: ./examples/ListAddressesAtSubscriptionLevel.json
      summary: Microsoft Azure Get Subscriptions Subscriptionid Providers Microsoft Edgeorder Addresses
  /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.EdgeOrder/addresses:
    get:
      tags:
      - Addresses
      description: List all the addresses available under the given resource group.
      operationId: microsoftAzureAddressesListbyresourcegroup
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/ResourceGroupNameParameter
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/ApiVersionParameter
      - name: $filter
        in: query
        description: $filter is supported to filter based on shipping address properties. Filter supports only equals operation.
        required: false
        type: string
      - name: $skipToken
        in: query
        description: $skipToken is supported on Get list of addresses, which provides the next page in the list of addresses.
        required: false
        type: string
      - name: $top
        in: query
        description: $top is supported on fetching list of resources. $top=10 means that the first 10 items in the list will be returned to the API caller.
        required: false
        type: integer
        format: int32
      responses:
        '200':
          description: List of addresses available under the resource group.
          schema:
            $ref: '#/definitions/AddressResourceList'
        default:
          description: Error response describing reason for operation failure.
          schema:
            $ref: ../../../../../common-types/resource-management/v2/types.json#/definitions/ErrorResponse
      x-ms-pageable:
        nextLinkName: nextLink
      x-ms-examples:
        ListAddressesAtResourceGroupLevel:
          $ref: ./examples/ListAddressesAtResourceGroupLevel.json
      summary: Microsoft Azure Get Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Edgeorder Addresses
  /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.EdgeOrder/addresses/{addressName}:
    get:
      tags:
      - Addresses
      description: Get information about the specified address.
      operationId: microsoftAzureAddressesGet
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/ResourceGroupNameParameter
      - $ref: '#/parameters/addressNameParameter'
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/ApiVersionParameter
      responses:
        '200':
          description: Address object.
          schema:
            $ref: '#/definitions/AddressResource'
        default:
          description: Error response describing reason for operation failure.
          schema:
            $ref: ../../../../../common-types/resource-management/v2/types.json#/definitions/ErrorResponse
      x-ms-examples:
        GetAddressByName:
          $ref: ./examples/GetAddressByName.json
      summary: Microsoft Azure Get Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Edgeorder Addresses Addressname
    put:
      tags:
      - Addresses
      description: Create a new address with the specified parameters. Existing address cannot be updated with this API and should<br>instead be updated with the Update address API.
      operationId: microsoftAzureAddressesCreate
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/ResourceGroupNameParameter
      - $ref: '#/parameters/addressNameParameter'
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/ApiVersionParameter
      - name: addressResource
        in: body
        description: Address details from request body.
        required: true
        schema:
          $ref: '#/definitions/AddressResource'
      responses:
        '200':
          description: Address resource object.
          schema:
            $ref: '#/definitions/AddressResource'
        '202':
          description: Accepted request for create Address.
        default:
          description: Error response describing reason for operation failure.
          schema:
            $ref: ../../../../../common-types/resource-management/v2/types.json#/definitions/ErrorResponse
      x-ms-long-running-operation: true
      x-ms-examples:
        CreateAddress:
          $ref: ./examples/CreateAddress.json
      summary: Microsoft Azure Put Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Edgeorder Addresses Addressname
    delete:
      tags:
      - Addresses
      description: Delete an address.
      operationId: microsoftAzureAddressesDelete
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/ResourceGroupNameParameter
      - $ref: '#/parameters/addressNameParameter'
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/ApiVersionParameter
      responses:
        '200':
          description: Address deleted.
        '202':
          description: Accepted request for delete address.
          headers:
            Location:
              description: The URL to track the status of the long running operation.
              type: string
        '204':
          description: No content. Address deleted.
        default:
          description: Error response describing reason for operation failure.
          schema:
            $ref: ../../../../../common-types/resource-management/v2/types.json#/definitions/ErrorResponse
      x-ms-long-running-operation: true
      x-ms-examples:
        DeleteAddressByName:
          $ref: ./examples/DeleteAddressByName.json
      summary: Microsoft Azure Delete Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Edgeorder Addresses Addressname
    patch:
      tags:
      - Addresses
      description: Update the properties of an existing address.
      operationId: microsoftAzureAddressesUpdate
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/ResourceGroupNameParameter
      - $ref: '#/parameters/addressNameParameter'
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/ApiVersionParameter
      - name: If-Match
        in: header
        description: Defines the If-Match condition. The patch will be performed only if the ETag of the job on the server matches this value.
        required: false
        type: string
      - name: addressUpdateParameter
        in: body
        description: Address update parameters from request body.
        required: true
        schema:
          $ref: '#/definitions/AddressUpdateParameter'
      responses:
        '200':
          description: Address resource object.
          schema:
            $ref: '#/definitions/AddressResource'
        '202':
          description: Accepted request for address update.
          headers:
            Location:
              description: The URL to track the status of the long running operation.
              type: string
        default:
          description: Error response describing reason for operation failure.
          schema:
            $ref: ../../../../../common-types/resource-management/v2/types.json#/definitions/ErrorResponse
      x-ms-long-running-operation: true
      x-ms-examples:
        UpdateAddress:
          $ref: ./examples/UpdateAddress.json
      summary: Microsoft Azure Patch Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Edgeorder Addresses Addressname
definitions:
  AddressProperties:
    description: Address Properties.
    required:
    - contactDetails
    type: object
    properties:
      shippingAddress:
        $ref: '#/definitions/ShippingAddress'
        description: Shipping details for the address.
      contactDetails:
        $ref: '#/definitions/ContactDetails'
        description: Contact details for the address.
      addressValidationStatus:
        description: Status of address validation.
        enum:
        - Valid
        - Invalid
        - Ambiguous
        type: string
        readOnly: true
        x-ms-enum:
          name: AddressValidationStatus
          modelAsString: true
          values:
          - value: Valid
            description: Address provided is valid.
          - value: Invalid
            description: Address provided is invalid or not supported.
          - value: Ambiguous
            description: Address provided is ambiguous, please choose one of the alternate addresses returned.
  AddressUpdateParameter:
    description: The Address update parameters.
    type: object
    properties:
      properties:
        $ref: '#/definitions/AddressUpdateProperties'
        description: Properties of an address to be updated.
        x-ms-client-flatten: true
      tags:
        description: The list of key value pairs that describe the resource. These tags can be used in viewing and grouping this resource (across resource groups).
        type: object
        additionalProperties:
          type: string
  AddressUpdateProperties:
    description: Address Update Properties.
    type: object
    properties:
      shippingAddress:
        $ref: '#/definitions/ShippingAddress'
        description: Shipping details for the address.
      contactDetails:
        $ref: '#/definitions/ContactDetails'
        description: Contact details for the address.
  AddressResourceList:
    description: Address Resource Collection.
    type: object
    properties:
      value:
        description: List of address resources.
        uniqueItems: false
        type: array
        items:
          $ref: '#/definitions/AddressResource'
        readOnly: true
      nextLink:
        description: Link for the next set of job resources.
        type: string
  ShippingAddress:
    description: Shipping address where customer wishes to receive the device.
    required:
    - streetAddress1
    - country
    type: object
    properties:
      streetAddress1:
        description: Street Address line 1.
        type: string
      streetAddress2:
        description: Street Address line 2.
        type: string
      streetAddress3:
        description: Street Address line 3.
        type: string
      city:
        description: Name of the City.
        type: string
      stateOrProvince:
        description: Name of the State or Province.
        type: string
      country:
        description: Name of the Country.
        type: string
      postalCode:
        description: Postal code.
        type: string
      zipExtendedCode:
        description: Extended Zip Code.
        type: string
      companyName:
        description: Name of the company.
        type: string
      addressType:
        description: Type of address.
        enum:
        - None
        - Residential
        - Commercial
        type: string
        x-ms-enum:
          name: AddressType
          modelAsString: true
          values:
          - value: None
            description: Address type not known.
          - value: Residential
            description: Residential Address.
          - value: Commercial
            description: Commercial Address.
  ContactDetails:
    description: Contact Details.
    required:
    - contactName
    - phone
    - emailList
    type: object
    properties:
      contactName:
        description: Contact name of the person.
        type: string
      phone:
        description: Phone number of the contact person.
        type: string
      phoneExtension:
        description: Phone extension number of the contact person.
        type: string
      mobile:
        description: Mobile number of the contact person.
        type: string
      emailList:
        description: List of Email-ids to be notified about job progress.
        uniqueItems: false
        type: array
        items:
          type: string
  AddressResource:
    description: Address Resource.
    required:
    - properties
    type: object
    allOf:
    - $ref: ../../../../../common-types/resource-management/v2/types.json#/definitions/TrackedResource
    properties:
      properties:
        $ref: '#/definitions/AddressProperties'
        description: Properties of an address.
        x-ms-client-flatten: true
      systemData:
        $ref: ../../../../../common-types/resource-management/v2/types.json#/definitions/systemData
        description: Represents resource creation and update time.
        readOnly: true
parameters:
  addressNameParameter:
    name: addressName
    in: path
    description: The name of the address Resource within the specified resource group. address names must be between 3 and 24 characters in length and use any alphanumeric and underscore only.
    required: true
    type: string
    maxLength: 24
    minLength: 3
    pattern: ^[-\w\.]+$
    x-ms-parameter-location: method
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
