swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector GetAccessReviewInstanceDecisions API
schemes:
- https
tags:
- name: GetAccessReviewInstanceDecisions
paths:
  ? /subscriptions/{subscriptionId}/providers/Microsoft.Authorization/accessReviewScheduleDefinitions/{scheduleDefinitionId}/instances/{id}/decisions
  : get:
      tags:
      - GetAccessReviewInstanceDecisions
      operationId: microsoftAzureAccessreviewinstancedecisionsList
      x-ms-examples:
        GetAccessReviewInstanceDecisions:
          $ref: ./examples/GetAccessReviewInstanceDecisions.json
      description: Get access review instance decisions
      parameters:
      - name: scheduleDefinitionId
        in: path
        required: true
        type: string
        description: The id of the access review schedule definition.
      - name: id
        in: path
        required: true
        type: string
        description: The id of the access review instance.
      - $ref: '#/parameters/ApiVersionParameter'
      - $ref: '#/parameters/SubscriptionIdParameter'
      - $ref: '#/parameters/AccessReviewsFilterParameter'
      responses:
        '200':
          description: Describe the result of a successful operation.
          schema:
            $ref: '#/definitions/AccessReviewDecisionListResult'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/ErrorDefinition'
      x-ms-pageable:
        nextLinkName: nextLink
      summary: Microsoft Azure Get Subscriptions Subscriptionid Providers Microsoft Authorization Accessreviewscheduledefinitions Scheduledefinitionid Instances Id Decisions
definitions:
  ErrorDefinition:
    type: object
    title: Error
    description: Error description and code explaining why an operation failed.
    properties:
      error:
        $ref: '#/definitions/ErrorDefinitionProperties'
        description: Error of the list gateway status.
  AccessReviewDecisionListResult:
    type: object
    properties:
      value:
        type: array
        items:
          $ref: '#/definitions/AccessReviewDecision'
        description: Access Review Decision list.
      nextLink:
        type: string
        description: The URL to use for getting the next set of results.
    description: List of access review decisions.
  AccessReviewDecisionResource:
    type: object
    discriminator: type
    required:
    - type
    properties:
      type:
        type: string
        description: 'The type of resource: azureRole'
        enum:
        - azureRole
        x-ms-enum:
          name: DecisionResourceType
          modelAsString: true
      id:
        type: string
        readOnly: true
        description: The id of resource associated with a decision record.
      displayName:
        type: string
        readOnly: true
        description: The display name of resource associated with a decision record.
    description: Target of the decision.
  AccessReviewDecision:
    type: object
    x-ms-azure-resource: true
    properties:
      id:
        type: string
        readOnly: true
        description: The access review decision id.
      name:
        type: string
        readOnly: true
        description: The access review decision name.
      type:
        type: string
        readOnly: true
        description: The resource type.
      properties:
        x-ms-client-flatten: true
        $ref: '#/definitions/AccessReviewDecisionProperties'
        description: Access Review Decision properties.
    description: Access Review.
  AccessReviewActorIdentity:
    type: object
    properties:
      principalId:
        type: string
        readOnly: true
        description: The identity id
      principalType:
        type: string
        readOnly: true
        description: 'The identity type : user/servicePrincipal'
        enum:
        - user
        - servicePrincipal
        x-ms-enum:
          name: AccessReviewActorIdentityType
          modelAsString: true
      principalName:
        type: string
        readOnly: true
        description: The identity display name
      userPrincipalName:
        type: string
        readOnly: true
        description: The user principal name(if valid)
    description: Details of the actor identity
  AccessReviewDecisionIdentity:
    type: object
    discriminator: type
    required:
    - type
    properties:
      type:
        type: string
        description: 'The type of decision target : User/ServicePrincipal'
        enum:
        - user
        - servicePrincipal
        x-ms-enum:
          name: DecisionTargetType
          modelAsString: true
      id:
        type: string
        readOnly: true
        description: The id of principal whose access was reviewed.
      displayName:
        type: string
        readOnly: true
        description: The display name of the user whose access was reviewed.
    description: Target of the decision.
  ErrorDefinitionProperties:
    type: object
    title: Error
    description: Error description and code explaining why an operation failed.
    properties:
      message:
        type: string
        readOnly: true
        description: Description of the error.
      code:
        type: string
        description: Error code of list gateway.
  AccessReviewDecisionProperties:
    type: object
    properties:
      principal:
        readOnly: true
        x-ms-client-flatten: true
        $ref: '#/definitions/AccessReviewDecisionIdentity'
        description: Principal associated with the decision record. Can be AccessReviewDecisionUserIdentity or AccessReviewDecisionServicePrincipalIdentity
        x-nullable: true
      resource:
        readOnly: true
        x-ms-client-flatten: true
        $ref: '#/definitions/AccessReviewDecisionResource'
        description: Resource associated with this decision record.
        x-nullable: true
      recommendation:
        type: string
        readOnly: true
        description: The feature- generated recommendation shown to the reviewer.
        enum:
        - Approve
        - Deny
        - NoInfoAvailable
        x-ms-enum:
          name: AccessRecommendationType
          modelAsString: true
      decision:
        type: string
        description: The decision on the approval step. This value is initially set to NotReviewed. Approvers can take action of Approve/Deny
        enum:
        - Approve
        - Deny
        - NotReviewed
        - DontKnow
        - NotNotified
        x-ms-enum:
          name: AccessReviewResult
          modelAsString: true
      justification:
        type: string
        description: Justification provided by approvers for their action
      reviewedDateTime:
        type: string
        readOnly: true
        format: date-time
        description: Date Time when a decision was taken.
        x-nullable: true
      reviewedBy:
        readOnly: true
        x-ms-client-flatten: true
        $ref: '#/definitions/AccessReviewActorIdentity'
        description: Details of the approver.
        x-nullable: true
      applyResult:
        type: string
        readOnly: true
        description: The outcome of applying the decision.
        enum:
        - New
        - Applying
        - AppliedSuccessfully
        - AppliedWithUnknownFailure
        - AppliedSuccessfullyButObjectNotFound
        - ApplyNotSupported
        x-ms-enum:
          name: AccessReviewApplyResult
          modelAsString: true
      appliedDateTime:
        type: string
        readOnly: true
        format: date-time
        description: The date and time when the review decision was applied.
        x-nullable: true
      appliedBy:
        readOnly: true
        x-ms-client-flatten: true
        $ref: '#/definitions/AccessReviewActorIdentity'
        description: Details of the approver.
        x-nullable: true
    description: Approval Step.
parameters:
  AccessReviewsFilterParameter:
    name: $filter
    in: query
    required: false
    type: string
    description: 'The filter to apply on the operation. Other than standard filters, one custom filter option is supported : ''assignedToMeToReview()''. When one specified $filter=assignedToMeToReview(), only items that are assigned to the calling user to review are returned'
    x-ms-skip-url-encoding: true
    x-ms-parameter-location: method
  ApiVersionParameter:
    name: api-version
    in: query
    required: true
    type: string
    description: The API version to be used with the HTTP request.
  SubscriptionIdParameter:
    name: subscriptionId
    in: path
    required: true
    type: string
    description: The ID of the target subscription.
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
