swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector LocalNetworkGateways API
schemes:
- https
tags:
- name: LocalNetworkGateways
paths:
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/localNetworkGateways/{localNetworkGatewayName}
  : put:
      tags:
      - LocalNetworkGateways
      operationId: microsoftAzureLocalnetworkgatewaysCreateorupdate
      description: The Put LocalNetworkGateway operation creates/updates a local network gateway in the specified resource group through Network resource provider.
      parameters:
      - name: resourceGroupName
        in: path
        required: true
        type: string
        description: The name of the resource group.
      - name: localNetworkGatewayName
        in: path
        required: true
        type: string
        description: The name of the local network gateway.
      - name: parameters
        in: body
        required: true
        schema:
          $ref: '#/definitions/LocalNetworkGateway'
        description: Parameters supplied to the Begin Create or update Local Network Gateway operation through Network resource provider.
      - $ref: '#/parameters/ApiVersionParameter'
      - $ref: '#/parameters/SubscriptionIdParameter'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/LocalNetworkGateway'
        '201':
          description: ''
          schema:
            $ref: '#/definitions/LocalNetworkGateway'
      x-ms-long-running-operation: true
      summary: Microsoft Azure Put Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Network Localnetworkgateways Localnetworkgatewayname
    get:
      tags:
      - LocalNetworkGateways
      operationId: microsoftAzureLocalnetworkgatewaysGet
      description: The Get LocalNetworkGateway operation retrieves information about the specified local network gateway through Network resource provider.
      parameters:
      - name: resourceGroupName
        in: path
        required: true
        type: string
        description: The name of the resource group.
      - name: localNetworkGatewayName
        in: path
        required: true
        type: string
        description: The name of the local network gateway.
      - $ref: '#/parameters/ApiVersionParameter'
      - $ref: '#/parameters/SubscriptionIdParameter'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/LocalNetworkGateway'
      summary: Microsoft Azure Get Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Network Localnetworkgateways Localnetworkgatewayname
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/localNetworkGateways/{localNetworkGatewayName}/
  : delete:
      tags:
      - LocalNetworkGateways
      operationId: microsoftAzureLocalnetworkgatewaysDelete
      description: The Delete LocalNetworkGateway operation deletes the specified local network Gateway through Network resource provider.
      parameters:
      - name: resourceGroupName
        in: path
        required: true
        type: string
        description: The name of the resource group.
      - name: localNetworkGatewayName
        in: path
        required: true
        type: string
        description: The name of the local network gateway.
      - $ref: '#/parameters/ApiVersionParameter'
      - $ref: '#/parameters/SubscriptionIdParameter'
      responses:
        '200':
          description: ''
        '202':
          description: ''
        '204':
          description: ''
      x-ms-long-running-operation: true
      summary: Microsoft Azure Delete Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Network Localnetworkgateways Localnetworkgatewayname
  /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/localNetworkGateways:
    get:
      tags:
      - LocalNetworkGateways
      operationId: microsoftAzureLocalnetworkgatewaysList
      description: The List LocalNetworkGateways operation retrieves all the local network gateways stored.
      parameters:
      - name: resourceGroupName
        in: path
        required: true
        type: string
        description: The name of the resource group.
      - $ref: '#/parameters/ApiVersionParameter'
      - $ref: '#/parameters/SubscriptionIdParameter'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/LocalNetworkGatewayListResult'
      x-ms-pageable:
        nextLinkName: nextLink
      summary: Microsoft Azure Get Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Network Localnetworkgateways
definitions:
  LocalNetworkGatewayPropertiesFormat:
    properties:
      localNetworkAddressSpace:
        $ref: '#/definitions/AddressSpace'
        description: Local network site Address space
      gatewayIpAddress:
        type: string
        description: IP address of local network gateway.
      resourceGuid:
        type: string
        description: Gets or sets resource guid property of the LocalNetworkGateway resource
      provisioningState:
        type: string
        description: Gets or sets Provisioning state of the LocalNetworkGateway resource Updating/Deleting/Failed
    description: LocalNetworkGateway properties
  Resource:
    properties:
      id:
        readOnly: true
        type: string
        description: Resource Id
      name:
        readOnly: true
        type: string
        description: Resource name
      type:
        readOnly: true
        type: string
        description: Resource type
      location:
        type: string
        description: Resource location
      tags:
        type: object
        additionalProperties:
          type: string
        description: Resource tags
    required:
    - location
    x-ms-azure-resource: true
  LocalNetworkGatewayListResult:
    properties:
      value:
        type: array
        items:
          $ref: '#/definitions/LocalNetworkGateway'
        description: Gets List of LocalNetworkGateways that exists in a resource group
      nextLink:
        type: string
        description: Gets the URL to get the next set of results.
    description: Response for ListLocalNetworkGateways Api service call
  LocalNetworkGateway:
    properties:
      properties:
        x-ms-client-flatten: true
        $ref: '#/definitions/LocalNetworkGatewayPropertiesFormat'
      etag:
        type: string
        description: Gets a unique read-only string that changes whenever the resource is updated
    allOf:
    - $ref: '#/definitions/Resource'
    description: A common class for general resource information
  AddressSpace:
    properties:
      addressPrefixes:
        type: array
        items:
          type: string
        description: Gets or sets List of address blocks reserved for this virtual network in CIDR notation
    description: AddressSpace contains an array of IP address ranges that can be used by subnets
parameters:
  ApiVersionParameter:
    name: api-version
    in: query
    required: true
    type: string
    description: Client Api Version.
  SubscriptionIdParameter:
    name: subscriptionId
    in: path
    required: true
    type: string
    description: Gets subscription credentials which uniquely identify Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
