swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector Disks API
schemes:
- https
tags:
- name: Disks
paths:
  /subscriptions/{subscriptionId}/providers/Microsoft.Compute.Admin/locations/{location}/disks:
    get:
      x-ms-examples:
        Returns a list of disks.:
          $ref: ./examples/Disks/List.json
      tags:
      - Disks
      operationId: microsoftAzureDisksList
      description: Returns a list of disks.
      parameters:
      - $ref: ../2015-12-01-preview/Compute.json#/parameters/SubscriptionIdParameter
      - $ref: ../2015-12-01-preview/Compute.json#/parameters/LocationParameter
      - $ref: Disks.json#/parameters/UserSubscriptionIdParameter
      - $ref: Disks.json#/parameters/DiskStateParameter
      - $ref: Disks.json#/parameters/SourceSharePathParameter
      - $ref: Disks.json#/parameters/SourceScaleUnitParameter
      - $ref: Disks.json#/parameters/SourceVolumeLabelParameter
      - $ref: Disks.json#/parameters/DiskCountParameter
      - $ref: Disks.json#/parameters/DiskStartParameter
      - $ref: ../../../../../../common-types/resource-management/v2/types.json#/parameters/ApiVersionParameter
      responses:
        '200':
          description: OK -- The list of disks has been returned.
          schema:
            $ref: Disks.json#/definitions/DiskList
        default:
          description: Common error response for all Azure Resource Manager APIs to return error details for failed operations. (This also follows the OData error response format.).
          schema:
            $ref: ../2015-12-01-preview/Compute.json#/definitions/CrpErrorResponse
      x-ms-pageable:
        nextLinkName: null
      summary: Microsoft Azure Get Subscriptions Subscriptionid Providers Microsoft Compute Admin Locations Location Disks
  /subscriptions/{subscriptionId}/providers/Microsoft.Compute.Admin/locations/{location}/disks/{DiskId}:
    get:
      x-ms-examples:
        Returns the requested disk.:
          $ref: ./examples/Disks/Get.json
      tags:
      - Disks
      operationId: microsoftAzureDisksGet
      description: Returns the disk.
      parameters:
      - $ref: ../2015-12-01-preview/Compute.json#/parameters/SubscriptionIdParameter
      - $ref: ../2015-12-01-preview/Compute.json#/parameters/LocationParameter
      - $ref: Disks.json#/parameters/DiskIdParameter
      - $ref: ../../../../../../common-types/resource-management/v2/types.json#/parameters/ApiVersionParameter
      responses:
        '200':
          description: OK -- The disk has been returned.
          schema:
            $ref: Disks.json#/definitions/Disk
        default:
          description: Common error response for all Azure Resource Manager APIs to return error details for failed operations. (This also follows the OData error response format.).
          schema:
            $ref: ../2015-12-01-preview/Compute.json#/definitions/CrpErrorResponse
      summary: Microsoft Azure Get Subscriptions Subscriptionid Providers Microsoft Compute Admin Locations Location Disks Diskid
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DevTestLab/labs/{labName}/users/{userName}/disks
  : get:
      tags:
      - Disks
      description: List disks in a given user profile.
      operationId: microsoftAzureDisksList
      parameters:
      - $ref: '#/parameters/subscriptionId'
      - $ref: '#/parameters/resourceGroupName'
      - name: labName
        in: path
        description: The name of the lab.
        required: true
        type: string
      - name: userName
        in: path
        description: The name of the user profile.
        required: true
        type: string
      - name: $expand
        in: query
        description: 'Specify the $expand query. Example: ''properties($select=diskType)'''
        type: string
      - name: $filter
        in: query
        description: 'The filter to apply to the operation. Example: ''$filter=contains(name,''myName'')'
        type: string
      - name: $top
        in: query
        description: 'The maximum number of resources to return from the operation. Example: ''$top=10'''
        type: integer
        format: int32
      - name: $orderby
        in: query
        description: 'The ordering expression for the results, using OData notation. Example: ''$orderby=name desc'''
        type: string
      - $ref: '#/parameters/api-version'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/DiskList'
        default:
          description: BadRequest
          schema:
            $ref: '#/definitions/CloudError'
      x-ms-pageable:
        nextLinkName: nextLink
      x-ms-odata: '#/definitions/Disk'
      x-ms-examples:
        Disks_List:
          $ref: ./examples/Disks_List.json
      summary: Microsoft Azure Get Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Devtestlab Labs Labname Users Username Disks
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DevTestLab/labs/{labName}/users/{userName}/disks/{name}
  : get:
      tags:
      - Disks
      description: Get disk.
      operationId: microsoftAzureDisksGet
      parameters:
      - $ref: '#/parameters/subscriptionId'
      - $ref: '#/parameters/resourceGroupName'
      - name: labName
        in: path
        description: The name of the lab.
        required: true
        type: string
      - name: userName
        in: path
        description: The name of the user profile.
        required: true
        type: string
      - name: name
        in: path
        description: The name of the disk.
        required: true
        type: string
      - name: $expand
        in: query
        description: 'Specify the $expand query. Example: ''properties($select=diskType)'''
        type: string
      - $ref: '#/parameters/api-version'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Disk'
        default:
          description: BadRequest
          schema:
            $ref: '#/definitions/CloudError'
      x-ms-examples:
        Disks_Get:
          $ref: ./examples/Disks_Get.json
      summary: Microsoft Azure Get Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Devtestlab Labs Labname Users Username Disks Name
    put:
      tags:
      - Disks
      description: Create or replace an existing disk. This operation can take a while to complete.
      operationId: microsoftAzureDisksCreateorupdate
      parameters:
      - $ref: '#/parameters/subscriptionId'
      - $ref: '#/parameters/resourceGroupName'
      - name: labName
        in: path
        description: The name of the lab.
        required: true
        type: string
      - name: userName
        in: path
        description: The name of the user profile.
        required: true
        type: string
      - name: name
        in: path
        description: The name of the disk.
        required: true
        type: string
      - name: disk
        in: body
        description: A Disk.
        required: true
        schema:
          $ref: '#/definitions/Disk'
      - $ref: '#/parameters/api-version'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Disk'
        '201':
          description: Created
          schema:
            $ref: '#/definitions/Disk'
        default:
          description: BadRequest
          schema:
            $ref: '#/definitions/CloudError'
      x-ms-examples:
        Disks_CreateOrUpdate:
          $ref: ./examples/Disks_CreateOrUpdate.json
      x-ms-long-running-operation: true
      summary: Microsoft Azure Put Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Devtestlab Labs Labname Users Username Disks Name
    delete:
      tags:
      - Disks
      description: Delete disk. This operation can take a while to complete.
      operationId: microsoftAzureDisksDelete
      parameters:
      - $ref: '#/parameters/subscriptionId'
      - $ref: '#/parameters/resourceGroupName'
      - name: labName
        in: path
        description: The name of the lab.
        required: true
        type: string
      - name: userName
        in: path
        description: The name of the user profile.
        required: true
        type: string
      - name: name
        in: path
        description: The name of the disk.
        required: true
        type: string
      - $ref: '#/parameters/api-version'
      responses:
        '200':
          description: OK
        '202':
          description: Accepted
        '204':
          description: No Content
        default:
          description: BadRequest
          schema:
            $ref: '#/definitions/CloudError'
      x-ms-examples:
        Disks_Delete:
          $ref: ./examples/Disks_Delete.json
      x-ms-long-running-operation: true
      summary: Microsoft Azure Delete Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Devtestlab Labs Labname Users Username Disks Name
    patch:
      tags:
      - Disks
      description: Allows modifying tags of disks. All other properties will be ignored.
      operationId: microsoftAzureDisksUpdate
      parameters:
      - $ref: '#/parameters/subscriptionId'
      - $ref: '#/parameters/resourceGroupName'
      - name: labName
        in: path
        description: The name of the lab.
        required: true
        type: string
      - name: userName
        in: path
        description: The name of the user profile.
        required: true
        type: string
      - name: name
        in: path
        description: The name of the disk.
        required: true
        type: string
      - name: disk
        in: body
        description: A Disk.
        required: true
        schema:
          $ref: '#/definitions/DiskFragment'
      - $ref: '#/parameters/api-version'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Disk'
        default:
          description: BadRequest
          schema:
            $ref: '#/definitions/CloudError'
      x-ms-examples:
        Disks_Update:
          $ref: ./examples/Disks_Update.json
      summary: Microsoft Azure Patch Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Devtestlab Labs Labname Users Username Disks Name
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DevTestLab/labs/{labName}/users/{userName}/disks/{name}/attach
  : post:
      tags:
      - Disks
      description: Attach and create the lease of the disk to the virtual machine. This operation can take a while to complete.
      operationId: microsoftAzureDisksAttach
      parameters:
      - $ref: '#/parameters/subscriptionId'
      - $ref: '#/parameters/resourceGroupName'
      - name: labName
        in: path
        description: The name of the lab.
        required: true
        type: string
      - name: userName
        in: path
        description: The name of the user profile.
        required: true
        type: string
      - name: name
        in: path
        description: The name of the disk.
        required: true
        type: string
      - name: attachDiskProperties
        in: body
        description: Properties of the disk to attach.
        required: true
        schema:
          $ref: '#/definitions/AttachDiskProperties'
      - $ref: '#/parameters/api-version'
      responses:
        '200':
          description: OK
        '202':
          description: Accepted
        default:
          description: BadRequest
          schema:
            $ref: '#/definitions/CloudError'
      x-ms-examples:
        Disks_Attach:
          $ref: ./examples/Disks_Attach.json
      x-ms-long-running-operation: true
      summary: Microsoft Azure Post Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Devtestlab Labs Labname Users Username Disks Name Attach
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DevTestLab/labs/{labName}/users/{userName}/disks/{name}/detach
  : post:
      tags:
      - Disks
      description: Detach and break the lease of the disk attached to the virtual machine. This operation can take a while to complete.
      operationId: microsoftAzureDisksDetach
      parameters:
      - $ref: '#/parameters/subscriptionId'
      - $ref: '#/parameters/resourceGroupName'
      - name: labName
        in: path
        description: The name of the lab.
        required: true
        type: string
      - name: userName
        in: path
        description: The name of the user profile.
        required: true
        type: string
      - name: name
        in: path
        description: The name of the disk.
        required: true
        type: string
      - name: detachDiskProperties
        in: body
        description: Properties of the disk to detach.
        required: true
        schema:
          $ref: '#/definitions/DetachDiskProperties'
      - $ref: '#/parameters/api-version'
      responses:
        '200':
          description: OK
        '202':
          description: Accepted
        default:
          description: BadRequest
          schema:
            $ref: '#/definitions/CloudError'
      x-ms-examples:
        Disks_Detach:
          $ref: ./examples/Disks_Detach.json
      x-ms-long-running-operation: true
      summary: Microsoft Azure Post Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Devtestlab Labs Labname Users Username Disks Name Detach
definitions:
  DetachDiskProperties:
    description: Properties of the disk to detach.
    type: object
    properties:
      leasedByLabVmId:
        description: The resource ID of the Lab VM to which the disk is attached.
        type: string
  Resource:
    description: An Azure resource.
    type: object
    properties:
      id:
        description: The identifier of the resource.
        type: string
        readOnly: true
      name:
        description: The name of the resource.
        type: string
        readOnly: true
      type:
        description: The type of the resource.
        type: string
        readOnly: true
      location:
        description: The location of the resource.
        type: string
      tags:
        description: The tags of the resource.
        type: object
        additionalProperties:
          type: string
    x-ms-azure-resource: true
  CloudError:
    description: Error from a REST request.
    type: object
    properties:
      error:
        $ref: '#/definitions/CloudErrorBody'
        description: The cloud error that occurred
    x-ms-external: true
  DiskList:
    description: The response of a list operation.
    type: object
    properties:
      value:
        description: Results of the list operation.
        type: array
        items:
          $ref: '#/definitions/Disk'
      nextLink:
        description: Link for next set of results.
        type: string
  DiskProperties:
    description: Properties of a disk.
    type: object
    properties:
      diskType:
        description: The storage type for the disk (i.e. Standard, Premium).
        enum:
        - Standard
        - Premium
        - StandardSSD
        type: string
        x-ms-enum:
          name: StorageType
          modelAsString: true
      diskSizeGiB:
        format: int32
        description: The size of the disk in Gibibytes.
        type: integer
      leasedByLabVmId:
        description: The resource ID of the VM to which this disk is leased.
        type: string
      diskBlobName:
        description: When backed by a blob, the name of the VHD blob without extension.
        type: string
      diskUri:
        description: When backed by a blob, the URI of underlying blob.
        type: string
      storageAccountId:
        description: When backed by a blob, the storage account where the blob is.
        type: string
      createdDate:
        format: date-time
        description: The creation date of the disk.
        type: string
        readOnly: true
      hostCaching:
        description: The host caching policy of the disk (i.e. None, ReadOnly, ReadWrite).
        type: string
      managedDiskId:
        description: When backed by managed disk, this is the ID of the compute disk resource.
        type: string
      provisioningState:
        description: The provisioning status of the resource.
        type: string
        readOnly: true
      uniqueIdentifier:
        description: The unique immutable identifier of a resource (Guid).
        type: string
        readOnly: true
  AttachDiskProperties:
    description: Properties of the disk to attach.
    type: object
    properties:
      leasedByLabVmId:
        description: The resource ID of the Lab virtual machine to which the disk is attached.
        type: string
  Disk:
    description: A Disk.
    required:
    - properties
    type: object
    allOf:
    - $ref: '#/definitions/Resource'
    properties:
      properties:
        $ref: '#/definitions/DiskProperties'
        description: The properties of the resource.
        x-ms-client-flatten: true
  UpdateResource:
    description: Represents an update resource
    type: object
    properties:
      tags:
        description: The tags of the resource.
        type: object
        additionalProperties:
          type: string
  CloudErrorBody:
    description: Body of an error from a REST request.
    type: object
    properties:
      code:
        description: The error code.
        type: string
      message:
        description: The error message.
        type: string
      target:
        description: The error target.
        type: string
      details:
        description: Inner errors.
        type: array
        items:
          $ref: '#/definitions/CloudErrorBody'
    x-ms-external: true
  DiskFragment:
    description: A Disk.
    type: object
    allOf:
    - $ref: '#/definitions/UpdateResource'
    properties: {}
parameters:
  resourceGroupName:
    name: resourceGroupName
    in: path
    description: The name of the resource group.
    required: true
    type: string
    x-ms-parameter-location: method
  subscriptionId:
    name: subscriptionId
    in: path
    description: The subscription ID.
    required: true
    type: string
  api-version:
    name: api-version
    in: query
    description: Client API version.
    required: true
    type: string
    default: '2018-09-15'
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
