swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector ContainerHostMappings API
schemes:
- https
tags:
- name: ContainerHostMappings
paths:
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DevSpaces/locations/{location}/checkContainerHostMapping
  : post:
      tags:
      - ContainerHostMappings
      summary: Microsoft Azure Returns Container Host Mapping Object For A Container Host Resource Id If An Associated Controller Exists
      operationId: microsoftAzureContainerhostmappingsGetcontainerhostmapping
      parameters:
      - $ref: '#/parameters/ApiVersionParameter'
      - name: containerHostMapping
        in: body
        required: true
        schema:
          $ref: '#/definitions/ContainerHostMapping'
      - $ref: '#/parameters/SubscriptionIdParameter'
      - $ref: '#/parameters/ResourceGroupParameter'
      - name: location
        in: path
        description: Location of the container host.
        required: true
        type: string
      responses:
        '200':
          description: The request was successful; response contains the container host mapping.
          schema:
            $ref: '#/definitions/ContainerHostMapping'
        '204':
          description: The request was successful; container host mapping does not exist.
        default:
          description: Error response describing the reason for operation failure. 400 - BadRequest(Invalid container host resource ID.)
          schema:
            $ref: '#/definitions/DevSpacesErrorResponse'
      x-ms-examples:
        ContainerHostMappingsGetContainerHostMapping:
          $ref: ./examples/ContainerHostMappingsGetContainerHostMapping_example.json
      description: Needs a more full description created.
definitions:
  ContainerHostMapping:
    description: Container host mapping object specifying the Container host resource ID and its associated Controller resource.
    properties:
      containerHostResourceId:
        description: ARM ID of the Container Host resource
        type: string
      mappedControllerResourceId:
        description: ARM ID of the mapped Controller resource
        type: string
        readOnly: true
  ErrorDetails:
    properties:
      code:
        description: Status code for the error.
        type: string
        readOnly: true
      message:
        description: Error message describing the error in detail.
        type: string
        readOnly: true
      target:
        description: The target of the particular error.
        type: string
        readOnly: true
  DevSpacesErrorResponse:
    description: Error response indicates that the service is not able to process the incoming request. The reason is provided in the error message.
    properties:
      error:
        $ref: '#/definitions/ErrorDetails'
        description: The details of the error.
parameters:
  ApiVersionParameter:
    name: api-version
    in: query
    description: Client API version.
    required: true
    type: string
  ResourceGroupParameter:
    name: resourceGroupName
    in: path
    description: Resource group to which the resource belongs.
    required: true
    type: string
    maxLength: 90
    minLength: 1
    x-ms-parameter-location: method
  SubscriptionIdParameter:
    name: subscriptionId
    in: path
    description: Azure subscription ID.
    required: true
    type: string
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
