swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector Pipeline API
schemes:
- https
tags:
- name: Pipeline
paths:
  /pipelines:
    get:
      tags:
      - Pipeline
      operationId: microsoftAzurePipelineList
      description: Lists all pipelines.
      parameters:
      - name: startDateTime
        in: query
        required: false
        type: string
        format: date-time
        description: The start date for when to get the list of pipelines. The startDateTime and endDateTime can be no more than 30 days apart.
      - name: endDateTime
        in: query
        required: false
        type: string
        format: date-time
        description: The end date for when to get the list of pipelines. The startDateTime and endDateTime can be no more than 30 days apart.
      - $ref: '#/parameters/ApiVersionParameter'
      responses:
        '200':
          description: Successfully retrieved the list of pipelines.
          schema:
            $ref: '#/definitions/JobPipelineInformationListResult'
      x-ms-examples:
        Lists all pipelines:
          $ref: ./examples/Pipeline_List.json
      x-ms-pageable:
        nextLinkName: nextLink
      summary: Microsoft Azure Get Pipelines
  /pipelines/{pipelineIdentity}:
    get:
      tags:
      - Pipeline
      operationId: microsoftAzurePipelineGet
      description: Gets the Pipeline information for the specified pipeline ID.
      parameters:
      - name: pipelineIdentity
        in: path
        required: true
        type: string
        format: uuid
        description: Pipeline ID.
      - name: startDateTime
        in: query
        required: false
        type: string
        format: date-time
        description: The start date for when to get the pipeline and aggregate its data. The startDateTime and endDateTime can be no more than 30 days apart.
      - name: endDateTime
        in: query
        required: false
        type: string
        format: date-time
        description: The end date for when to get the pipeline and aggregate its data. The startDateTime and endDateTime can be no more than 30 days apart.
      - $ref: '#/parameters/ApiVersionParameter'
      responses:
        '200':
          description: Successfully retrieved details of the specified pipeline.
          schema:
            $ref: '#/definitions/JobPipelineInformation'
      x-ms-examples:
        Gets the Pipeline information for the specified pipeline ID:
          $ref: ./examples/Pipeline_Get.json
      summary: Microsoft Azure Get Pipelines Pipelineidentity
definitions:
  JobPipelineRunInformation:
    properties:
      runId:
        readOnly: true
        type: string
        format: uuid
        description: The run identifier of an instance of pipeline executions (a GUID).
      lastSubmitTime:
        readOnly: true
        type: string
        format: date-time
        description: The time this instance was last submitted.
    description: Run info for a specific job pipeline.
  JobPipelineInformationListResult:
    properties:
      value:
        readOnly: true
        type: array
        items:
          $ref: '#/definitions/JobPipelineInformation'
        description: The list of job pipeline information items.
      nextLink:
        readOnly: true
        type: string
        description: The link (url) to the next page of results.
    description: List of job pipeline information items.
  JobPipelineInformation:
    properties:
      pipelineId:
        readOnly: true
        type: string
        format: uuid
        description: The job relationship pipeline identifier (a GUID).
      pipelineName:
        readOnly: true
        type: string
        maxLength: 260
        description: The friendly name of the job relationship pipeline, which does not need to be unique.
      pipelineUri:
        readOnly: true
        type: string
        description: The pipeline uri, unique, links to the originating service for this pipeline.
      numJobsFailed:
        readOnly: true
        type: integer
        format: int32
        description: The number of jobs in this pipeline that have failed.
      numJobsCanceled:
        readOnly: true
        type: integer
        format: int32
        description: The number of jobs in this pipeline that have been canceled.
      numJobsSucceeded:
        readOnly: true
        type: integer
        format: int32
        description: The number of jobs in this pipeline that have succeeded.
      auHoursFailed:
        readOnly: true
        type: number
        format: double
        description: The number of job execution hours that resulted in failed jobs.
      auHoursCanceled:
        readOnly: true
        type: number
        format: double
        description: The number of job execution hours that resulted in canceled jobs.
      auHoursSucceeded:
        readOnly: true
        type: number
        format: double
        description: The number of job execution hours that resulted in successful jobs.
      lastSubmitTime:
        readOnly: true
        type: string
        format: date-time
        description: The last time a job in this pipeline was submitted.
      runs:
        readOnly: true
        type: array
        items:
          $ref: '#/definitions/JobPipelineRunInformation'
        description: The list of recurrence identifiers representing each run of this pipeline.
      recurrences:
        readOnly: true
        type: array
        items:
          type: string
          format: uuid
        description: The list of recurrence identifiers representing each run of this pipeline.
    description: Job Pipeline Information, showing the relationship of jobs and recurrences of those jobs in a pipeline.
parameters:
  ApiVersionParameter:
    name: api-version
    in: query
    required: true
    type: string
    description: Client Api Version.
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
