openapi: 3.2.0
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector Synapse Rbac Scopes API
tags:
- name: SynapseRbacScopes
paths:
  /rbacScopes:
    get:
      tags:
      - SynapseRbacScopes
      operationId: microsoftAzureRoledefinitionsListscopes
      description: List rbac scopes.
      x-ms-examples:
        List rbac scopes:
          $ref: ./examples/RoleDefinitions_ListScopes.json
      parameters:
      - $ref: '#/components/parameters/ApiVersionParameter'
      responses:
        '200':
          description: Success response.
          content:
            application/json:
              schema:
                description: A list of Synapse rbac scopes available.
                type: array
                items:
                  description: Synapse rbac scope.
                  type: string
            text/json:
              schema:
                description: A list of Synapse rbac scopes available.
                type: array
                items:
                  description: Synapse rbac scope.
                  type: string
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                $ref: ./roleAssignments.json#/definitions/ErrorContract
            text/json:
              schema:
                $ref: ./roleAssignments.json#/definitions/ErrorContract
      summary: Microsoft Azure Get Rbacscopes
components:
  parameters:
    ApiVersionParameter:
      name: api-version
      in: query
      required: true
      description: The Synapse client API Version.
      schema:
        type: string
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/components/parameters/Endpoint'
