swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector ListManagementTermLists API
schemes:
- https
tags:
- name: ListManagementTermLists
paths:
  /contentmoderator/lists/v1.0/termlists/{listId}:
    get:
      tags:
      - ListManagementTermLists
      operationId: microsoftAzureListmanagementtermlistsGetdetails
      description: Returns list ID details of the term list with listId equal to the passed list ID.
      parameters:
      - $ref: '#/parameters/listId'
      responses:
        '200':
          description: OK.
          schema:
            $ref: '#/definitions/TermList'
        default:
          description: Error response.
          schema:
            $ref: '#/definitions/APIError'
      x-ms-examples:
        Get Term ListId Details request:
          $ref: ../v1.0/examples/GetTermListIdDetailsResource.JSON
      produces:
      - application/json
      summary: Microsoft Azure Get Contentmoderator Lists 0 Termlists Listid
    delete:
      tags:
      - ListManagementTermLists
      operationId: microsoftAzureListmanagementtermlistsDelete
      description: Deletes the term list with listId equal to the passed list ID.
      parameters:
      - $ref: '#/parameters/listId'
      responses:
        '200':
          description: OK.
          schema:
            type: string
        default:
          description: Error response.
          schema:
            $ref: '#/definitions/APIError'
      x-ms-examples:
        Delete Termlist request:
          $ref: ../v1.0/examples/DeleteTermListResource.JSON
      produces:
      - application/json
      summary: Microsoft Azure Delete Contentmoderator Lists 0 Termlists Listid
    put:
      tags:
      - ListManagementTermLists
      operationId: microsoftAzureListmanagementtermlistsUpdate
      description: Updates a term list.
      parameters:
      - $ref: '#/parameters/listId'
      - name: Content-Type
        description: Content type.
        required: true
        type: string
        in: header
      - $ref: '#/parameters/body'
      consumes:
      - application/json
      responses:
        '200':
          description: OK.
          schema:
            $ref: '#/definitions/TermList'
        default:
          description: Error response.
          schema:
            $ref: '#/definitions/APIError'
      x-ms-examples:
        Update Termlist request:
          $ref: ../v1.0/examples/UpdateTermListResource.JSON
      produces:
      - application/json
      summary: Microsoft Azure Put Contentmoderator Lists 0 Termlists Listid
  /contentmoderator/lists/v1.0/termlists:
    post:
      tags:
      - ListManagementTermLists
      operationId: microsoftAzureListmanagementtermlistsCreate
      description: Creates a term list.
      parameters:
      - name: Content-Type
        description: Content type.
        required: true
        type: string
        in: header
      - $ref: '#/parameters/body'
      consumes:
      - application/json
      responses:
        '200':
          description: OK.
          schema:
            $ref: '#/definitions/TermList'
        default:
          description: Error response.
          schema:
            $ref: '#/definitions/APIError'
      x-ms-examples:
        Create Termlist request:
          $ref: ../v1.0/examples/CreateTermListResource.JSON
      produces:
      - application/json
      summary: Microsoft Azure Post Contentmoderator Lists 0 Termlists
    get:
      tags:
      - ListManagementTermLists
      operationId: microsoftAzureListmanagementtermlistsGetalltermlists
      description: Gets all the term lists.
      parameters: []
      responses:
        '200':
          description: OK.
          schema:
            $ref: '#/definitions/TermLists'
        default:
          description: Error response.
          schema:
            $ref: '#/definitions/APIError'
      x-ms-examples:
        Get All Termlists request:
          $ref: ../v1.0/examples/GetTermListsResource.JSON
      produces:
      - application/json
      summary: Microsoft Azure Get Contentmoderator Lists 0 Termlists
  /contentmoderator/lists/v1.0/termlists/{listId}/RefreshIndex:
    post:
      tags:
      - ListManagementTermLists
      operationId: microsoftAzureListmanagementtermlistsRefreshindex
      description: Refreshes the index of the list with listId equal to the passed list ID.
      parameters:
      - $ref: '#/parameters/listId'
      - $ref: '#/parameters/language'
      consumes:
      - application/json
      responses:
        '200':
          description: OK.
          schema:
            $ref: '#/definitions/RefreshIndex'
        default:
          description: Error response.
          schema:
            $ref: '#/definitions/APIError'
      x-ms-examples:
        Refresh Term Index request:
          $ref: ../v1.0/examples/RefreshTermIndexResource.JSON
      produces:
      - application/json
      summary: Microsoft Azure Post Contentmoderator Lists 0 Termlists Listid Refreshindex
definitions:
  APIError:
    type: object
    description: Error information that the API returns.
    properties:
      Error:
        $ref: '#/definitions/Error'
  TermLists:
    type: array
    items:
      $ref: '#/definitions/TermList'
  TermList:
    description: Term list properties.
    properties:
      Id:
        description: Term list ID.
        type: integer
      Name:
        description: Term list name.
        type: string
      Description:
        description: Description for the term list.
        type: string
      Metadata:
        description: Term list metadata.
        type: object
        additionalProperties:
          type: string
  Status:
    description: Status properties.
    properties:
      Code:
        description: Status code.
        type: integer
      Description:
        description: Status description.
        type: string
      Exception:
        description: Exception status.
        type: string
  RefreshIndex:
    description: Response after you refresh the index.
    properties:
      ContentSourceId:
        description: Content source ID.
        type: string
      IsUpdateSuccess:
        description: Update success status.
        type: boolean
      AdvancedInfo:
        description: Advanced info list.
        type: array
        items:
          type: object
          additionalProperties:
            type: string
      Status:
        description: Status of refreshing the index.
        $ref: '#/definitions/Status'
      TrackingId:
        description: Tracking ID.
        type: string
  Error:
    type: object
    description: Error body.
    properties:
      Code:
        type: string
      Message:
        type: string
parameters:
  listId:
    name: listId
    in: path
    description: List ID of the image list.
    required: true
    type: string
    x-ms-parameter-location: method
  language:
    name: language
    in: query
    description: Language of the terms.
    required: true
    type: string
    x-ms-parameter-location: method
  body:
    name: body
    in: body
    description: Schema of the body.
    required: true
    schema:
      type: object
      properties:
        Name:
          description: Name of the list.
          type: string
        Description:
          description: Description of the list.
          type: string
        Metadata:
          description: Metadata of the list.
          type: object
          additionalProperties:
            type: string
    x-ms-parameter-location: method
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
