openapi: 3.2.0
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector Disco Templates API
  description: Provides access to disco template resources.
tags:
- description: Provides access to disco template resources.
  name: Disco Templates
paths:
  /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/workspaces/{workspaceName}/discoTemplates:
    get:
      parameters:
      - $ref: '#/components/parameters/FilterParameter'
      - $ref: '#/components/parameters/SkipParameter'
      - $ref: '#/components/parameters/MaxPageSizeParameter'
      - $ref: ../../../../../common-types/resource-management/v3/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../common-types/resource-management/v3/types.json#/parameters/ResourceGroupNameParameter
      - $ref: '#/components/parameters/WorkspaceNameParameter'
      - $ref: ../../../../../common-types/resource-management/v3/types.json#/parameters/ApiVersionParameter
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DiscoTemplatePageResponse'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      tags:
      - Disco Templates
      operationId: microsoftAzureDiscotemplatesList
      summary: Microsoft Azure Retrieve A List Of Disco Templates For The Provided Search Parameters
      x-ms-examples:
        DiscoTemplates:
          $ref: ./examples/DiscoTemplates_List.json
      x-ms-pageable:
        itemName: content
        nextLinkName: nextLink
      description: Needs a more full description created.
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/workspaces/{workspaceName}/discoTemplates/{discoTemplateId}
  : get:
      parameters:
      - $ref: '#/components/parameters/DiscoTemplateIdParameter'
      - $ref: ../../../../../common-types/resource-management/v3/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../common-types/resource-management/v3/types.json#/parameters/ResourceGroupNameParameter
      - $ref: '#/components/parameters/WorkspaceNameParameter'
      - $ref: ../../../../../common-types/resource-management/v3/types.json#/parameters/ApiVersionParameter
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DiscoTemplateResponse'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      tags:
      - Disco Templates
      operationId: microsoftAzureDiscotemplatesGet
      summary: Microsoft Azure Retrieve A Disco Template With A Given Discotemplateid
      x-ms-examples:
        DiscoTemplates:
          $ref: ./examples/DiscoTemplates_Get.json
      description: Needs a more full description created.
components:
  schemas:
    ErrorResponse:
      properties:
        error:
          $ref: '#/components/schemas/ErrorDetail'
      required:
      - error
      type: object
    AssetId:
      description: The list of excludes used for the disco group runs, aka assets to exclude from the discovery algorithm.
      properties:
        displayName:
          type: string
        id:
          type: string
        kind:
          enum:
          - as
          - contact
          - domain
          - host
          - ipAddress
          - ipBlock
          - page
          - sslCert
          type: string
          x-ms-enum:
            modelAsString: true
            name: assetIdKind
        name:
          type: string
      type: object
    ErrorDetail:
      description: This is the top-level error object whose code matches the x-ms-error-code response header
      properties:
        code:
          description: This is one of a server-defined set of error codes.
          type: string
        details:
          description: This is an array of details about specific errors that led to this reported error.
          items:
            $ref: '#/components/schemas/ErrorDetail'
          type: array
        innererror:
          $ref: '#/components/schemas/InnerError'
        message:
          description: This is a human-readable representation of the error.
          type: string
        target:
          description: This is the error target.
          type: string
      required:
      - code
      - message
      type: object
    DiscoTemplatePageResponse:
      properties:
        content:
          items:
            $ref: '#/components/schemas/DiscoTemplateResponse'
          type: array
        first:
          type: boolean
        last:
          type: boolean
        nextLink:
          type: string
        number:
          format: int32
          type: integer
        numberOfElements:
          format: int32
          type: integer
        size:
          format: int32
          type: integer
        totalElements:
          format: int64
          type: integer
        totalPages:
          format: int32
          type: integer
      type: object
    DiscoTemplateResponse:
      properties:
        aliases:
          description: The list of disco template name aliases.
          items:
            description: The list of disco template name aliases.
            type: string
          type: array
        city:
          description: The name of the city.
          type: string
        countryCode:
          description: The country code.
          type: string
        displayName:
          type: string
        id:
          type: string
        industry:
          description: The name of the industry.
          type: string
        name:
          type: string
        region:
          description: The name of the region.
          type: string
        seeds:
          description: The list of disco template seeds.
          items:
            $ref: '#/components/schemas/AssetId'
          type: array
        stateCode:
          description: The state code.
          type: string
      type: object
    InnerError:
      description: This is an object containing more specific information than the current object about the error.
      properties:
        code:
          description: This is a more specific error code than was provided by the containing error..
          type: string
      type: object
  parameters:
    DiscoTemplateIdParameter:
      in: path
      name: discoTemplateId
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
    WorkspaceNameParameter:
      description: The name of the Workspace.
      in: path
      name: workspaceName
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
    SkipParameter:
      description: An offset into the collection of the first resource to be returned.
      in: query
      name: skip
      required: false
      x-ms-parameter-location: method
      schema:
        type: integer
        format: int32
        default: 0
    MaxPageSizeParameter:
      description: An offset into the collection of the first resource to be returned.
      in: query
      name: maxpagesize
      required: false
      x-ms-parameter-location: method
      schema:
        type: integer
        format: int32
        default: 20
    FilterParameter:
      description: An expression on the resource type that selects the resources to be returned.
      in: query
      name: filter
      required: false
      x-ms-parameter-location: method
      schema:
        type: string
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/components/parameters/Endpoint'
