swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector WebSitesController API
schemes:
- https
tags:
- name: WebSitesController
paths:
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Migrate/migrateProjects/{migrateProjectName}/webSites
  : get:
      tags:
      - WebSitesController
      summary: Microsoft Azure Gets A List Of Websites In The Migrate Project
      operationId: microsoftAzureWebsitescontrollerListwebsites
      parameters:
      - $ref: ../../../../../../common-types/resource-management/v3/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../../common-types/resource-management/v3/types.json#/parameters/ResourceGroupNameParameter
      - $ref: '#/parameters/migrateProjectName'
      - $ref: ../../../../../../common-types/resource-management/v3/types.json#/parameters/ApiVersionParameter
      - $ref: '#/parameters/continuationToken'
      - $ref: '#/parameters/pageSize'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/WebSiteCollection'
        default:
          description: An unexpected error response.
          schema:
            $ref: ../../../../../../common-types/resource-management/v3/types.json#/definitions/ErrorResponse
      deprecated: false
      x-ms-pageable:
        nextLinkName: nextLink
      x-ms-examples:
        WebSitesController_ListWebSites_MaximumSet_Gen:
          $ref: ./examples/WebSitesController_ListWebSites_MaximumSet_Gen.json
        WebSitesController_ListWebSites_MinimumSet_Gen:
          $ref: ./examples/WebSitesController_ListWebSites_MinimumSet_Gen.json
      description: Needs a more full description created.
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Migrate/migrateProjects/{migrateProjectName}/webSites/{webSiteName}
  : get:
      tags:
      - WebSitesController
      summary: Microsoft Azure Gets A Website In The Migrate Project
      operationId: microsoftAzureWebsitescontrollerGetwebsite
      parameters:
      - $ref: ../../../../../../common-types/resource-management/v3/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../../common-types/resource-management/v3/types.json#/parameters/ResourceGroupNameParameter
      - $ref: '#/parameters/migrateProjectName'
      - $ref: '#/parameters/webSiteName'
      - $ref: ../../../../../../common-types/resource-management/v3/types.json#/parameters/ApiVersionParameter
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/WebSite'
        default:
          description: An unexpected error response.
          schema:
            $ref: ../../../../../../common-types/resource-management/v3/types.json#/definitions/ErrorResponse
      deprecated: false
      x-ms-examples:
        WebSitesController_GetWebSite_MaximumSet_Gen:
          $ref: ./examples/WebSitesController_GetWebSite_MaximumSet_Gen.json
        WebSitesController_GetWebSite_MinimumSet_Gen:
          $ref: ./examples/WebSitesController_GetWebSite_MinimumSet_Gen.json
      description: Needs a more full description created.
definitions:
  WebSiteDiscoveryDetails:
    type: object
    description: Details of discovery data of web site.
    properties:
      lastUpdatedTime:
        format: date-time
        type: string
      id:
        description: Gets the relative URL to get to this WebSiteDiscoveryDetails resource.
        type: string
      webServerId:
        type: string
      webServerType:
        type: string
      webSiteName:
        type: string
      enqueueTime:
        type: string
      solutionName:
        type: string
      port:
        format: int32
        type: integer
      extendedInfo:
        type: object
        additionalProperties:
          type: string
  WebSiteCollection:
    type: object
    description: Collection of web sites.
    properties:
      value:
        type: array
        items:
          $ref: '#/definitions/WebSite'
      nextLink:
        type: string
  WebSiteAssessmentDetails:
    type: object
    description: Details of assessment data of web site.
    properties:
      assessmentId:
        type: string
      id:
        description: Gets the relative URL to get to this WebSiteAssessmentDetails resource.
        type: string
      isReadyForMigration:
        type: boolean
      assessmentTargetType:
        type: string
      migrationBlockersCount:
        format: int32
        type: integer
      successList:
        type: array
        items:
          type: string
      warningList:
        type: array
        items:
          type: string
      errorList:
        type: array
        items:
          type: string
      framework:
        type: string
      frameworkVersion:
        type: string
      lastUpdatedTime:
        format: date-time
        type: string
      webServerId:
        type: string
      webServerType:
        type: string
      webSiteName:
        type: string
      enqueueTime:
        type: string
      solutionName:
        type: string
      port:
        format: int32
        type: integer
      extendedInfo:
        type: object
        additionalProperties:
          type: string
  WebSite:
    type: object
    description: Class representing a web site.
    properties:
      id:
        type: string
      name:
        type: string
      type:
        type: string
        readOnly: true
      properties:
        $ref: '#/definitions/WebSiteProperties'
  WebSiteProperties:
    type: object
    description: Properties of class representing web site.
    properties:
      discoveryData:
        type: array
        items:
          $ref: '#/definitions/WebSiteDiscoveryDetails'
      assessmentData:
        type: array
        items:
          $ref: '#/definitions/WebSiteAssessmentDetails'
      migrationData:
        type: array
        items:
          $ref: '#/definitions/WebSiteMigrationDetails'
      lastUpdatedTime:
        format: date-time
        type: string
  WebSiteMigrationDetails:
    type: object
    description: Details of migration data of web site.
    properties:
      id:
        description: Gets the relative URL to get to this WebSiteMigrationDetails resource.
        type: string
      migrationPhase:
        type: string
      progressPercentage:
        format: int32
        type: integer
      targetAppServiceArmId:
        type: string
      lastUpdatedTime:
        format: date-time
        type: string
      webServerId:
        type: string
      webServerType:
        type: string
      webSiteName:
        type: string
      enqueueTime:
        type: string
      solutionName:
        type: string
      port:
        format: int32
        type: integer
      extendedInfo:
        type: object
        additionalProperties:
          type: string
parameters:
  migrateProjectName:
    name: migrateProjectName
    description: Name of the Azure Migrate project.
    type: string
    in: path
    x-ms-parameter-location: method
    required: true
    pattern: ^[a-zA-Z0-9-]{3,24}$
  webSiteName:
    name: webSiteName
    description: The ARM name of the website to be fetched.
    type: string
    in: path
    x-ms-parameter-location: method
    required: true
    pattern: ^[a-zA-Z0-9-]{3,24}$
  pageSize:
    name: pageSize
    description: The number of items to be returned in a single page. This value is honored only if it is less than the 100.
    type: integer
    format: int32
    in: query
    required: false
    x-ms-parameter-location: method
  continuationToken:
    name: continuationToken
    description: The continuation token.
    type: string
    in: query
    required: false
    x-ms-parameter-location: method
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
