swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector TestLines API
schemes:
- https
tags:
- name: TestLines
paths:
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.VoiceServices/communicationsGateways/{communicationsGatewayName}/testLines
  : get:
      tags:
      - TestLines
      operationId: microsoftAzureTestlinesListbycommunicationsgateway
      description: List TestLine resources by CommunicationsGateway
      parameters:
      - $ref: ../../../../../common-types/resource-management/v3/types.json#/parameters/ApiVersionParameter
      - $ref: ../../../../../common-types/resource-management/v3/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../common-types/resource-management/v3/types.json#/parameters/ResourceGroupNameParameter
      - $ref: '#/parameters/CommunicationsGateway.communicationsGatewayName'
      responses:
        '200':
          description: ARM operation completed successfully.
          schema:
            $ref: '#/definitions/TestLineListResult'
        default:
          description: An unexpected error response.
          schema:
            $ref: ../../../../../common-types/resource-management/v3/types.json#/definitions/ErrorResponse
      x-ms-pageable:
        nextLinkName: nextLink
      x-ms-examples:
        ListTestLineResource:
          $ref: ./examples/TestLines_ListByCommunicationsGateway.json
      summary: Microsoft Azure Get Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Voiceservices Communicationsgateways Communicationsgatewayname Testlines
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.VoiceServices/communicationsGateways/{communicationsGatewayName}/testLines/{testLineName}
  : get:
      tags:
      - TestLines
      operationId: microsoftAzureTestlinesGet
      description: Get a TestLine
      parameters:
      - $ref: ../../../../../common-types/resource-management/v3/types.json#/parameters/ApiVersionParameter
      - $ref: ../../../../../common-types/resource-management/v3/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../common-types/resource-management/v3/types.json#/parameters/ResourceGroupNameParameter
      - $ref: '#/parameters/CommunicationsGateway.communicationsGatewayName'
      - $ref: '#/parameters/TestLine.testLineName'
      responses:
        '200':
          description: ARM operation completed successfully.
          schema:
            $ref: '#/definitions/TestLine'
        default:
          description: An unexpected error response.
          schema:
            $ref: ../../../../../common-types/resource-management/v3/types.json#/definitions/ErrorResponse
      x-ms-examples:
        GetTestLineResource:
          $ref: ./examples/TestLines_Get.json
      summary: Microsoft Azure Get Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Voiceservices Communicationsgateways Communicationsgatewayname Testlines Testlinename
    put:
      tags:
      - TestLines
      operationId: microsoftAzureTestlinesCreateorupdate
      description: Create a TestLine
      parameters:
      - $ref: ../../../../../common-types/resource-management/v3/types.json#/parameters/ApiVersionParameter
      - $ref: ../../../../../common-types/resource-management/v3/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../common-types/resource-management/v3/types.json#/parameters/ResourceGroupNameParameter
      - $ref: '#/parameters/CommunicationsGateway.communicationsGatewayName'
      - $ref: '#/parameters/TestLine.testLineName'
      - name: resource
        in: body
        required: true
        description: Resource create parameters.
        schema:
          $ref: '#/definitions/TestLine'
      responses:
        '200':
          description: ARM operation completed successfully.
          schema:
            $ref: '#/definitions/TestLine'
        '201':
          description: ARM create operation completed successfully.
          headers:
            Retry-After:
              description: The Retry-After header can indicate how long the client should wait before polling the operation status.
              type: integer
              format: int32
          schema:
            $ref: '#/definitions/TestLine'
        default:
          description: An unexpected error response.
          schema:
            $ref: ../../../../../common-types/resource-management/v3/types.json#/definitions/ErrorResponse
      x-ms-examples:
        CreateTestLineResource:
          $ref: ./examples/TestLines_CreateOrUpdate.json
      x-ms-long-running-operation-options:
        final-state-via: azure-async-operation
      x-ms-long-running-operation: true
      summary: Microsoft Azure Put Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Voiceservices Communicationsgateways Communicationsgatewayname Testlines Testlinename
    delete:
      tags:
      - TestLines
      operationId: microsoftAzureTestlinesDelete
      description: Delete a TestLine
      parameters:
      - $ref: ../../../../../common-types/resource-management/v3/types.json#/parameters/ApiVersionParameter
      - $ref: ../../../../../common-types/resource-management/v3/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../common-types/resource-management/v3/types.json#/parameters/ResourceGroupNameParameter
      - $ref: '#/parameters/CommunicationsGateway.communicationsGatewayName'
      - $ref: '#/parameters/TestLine.testLineName'
      responses:
        '200':
          description: Resource deleted successfully.
        '202':
          description: Resource deletion accepted.
          headers:
            Retry-After:
              description: The Retry-After header can indicate how long the client should wait before polling the operation status.
              type: integer
              format: int32
        '204':
          description: Resource deleted successfully.
        default:
          description: An unexpected error response.
          schema:
            $ref: ../../../../../common-types/resource-management/v3/types.json#/definitions/ErrorResponse
      x-ms-examples:
        DeleteTestLineResource:
          $ref: ./examples/TestLines_Delete.json
      x-ms-long-running-operation-options:
        final-state-via: azure-async-operation
      x-ms-long-running-operation: true
      summary: Microsoft Azure Delete Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Voiceservices Communicationsgateways Communicationsgatewayname Testlines Testlinename
    patch:
      tags:
      - TestLines
      operationId: microsoftAzureTestlinesUpdate
      description: Update a TestLine
      parameters:
      - $ref: ../../../../../common-types/resource-management/v3/types.json#/parameters/ApiVersionParameter
      - $ref: ../../../../../common-types/resource-management/v3/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../common-types/resource-management/v3/types.json#/parameters/ResourceGroupNameParameter
      - $ref: '#/parameters/CommunicationsGateway.communicationsGatewayName'
      - $ref: '#/parameters/TestLine.testLineName'
      - name: properties
        in: body
        required: true
        description: The resource properties to be updated.
        schema:
          $ref: '#/definitions/TestLineUpdate'
      responses:
        '200':
          description: ARM operation completed successfully.
          schema:
            $ref: '#/definitions/TestLine'
        default:
          description: An unexpected error response.
          schema:
            $ref: ../../../../../common-types/resource-management/v3/types.json#/definitions/ErrorResponse
      x-ms-examples:
        UpdateTestLineResource:
          $ref: ./examples/TestLines_Update.json
      summary: Microsoft Azure Patch Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Voiceservices Communicationsgateways Communicationsgatewayname Testlines Testlinename
definitions:
  TestLine:
    type: object
    properties:
      properties:
        $ref: '#/definitions/TestLineProperties'
        description: The resource-specific properties for this resource.
        x-ms-mutability:
        - read
        - create
        x-ms-client-flatten: true
    description: A TestLine resource
    allOf:
    - $ref: ../../../../../common-types/resource-management/v3/types.json#/definitions/TrackedResource
  TestLinePurpose:
    type: string
    description: The purpose of the TestLine resource.
    enum:
    - Manual
    - Automated
    x-ms-enum:
      name: TestLinePurpose
      modelAsString: false
  ProvisioningState:
    type: string
    description: Provisioning state of the resource.
    enum:
    - Succeeded
    - Failed
    - Canceled
    x-ms-enum:
      name: ProvisioningState
      modelAsString: true
  TestLineListResult:
    type: object
    properties:
      value:
        type: array
        items:
          $ref: '#/definitions/TestLine'
        x-cadl-name: TestLine[]
        description: The TestLine items on this page
      nextLink:
        type: string
        description: The link to the next page of items
        x-cadl-name: Rest.ResourceLocation<TestLine>
    description: The response of a TestLine list operation.
    required:
    - value
  TestLineProperties:
    type: object
    properties:
      provisioningState:
        $ref: '#/definitions/ProvisioningState'
        description: Resource provisioning state.
        readOnly: true
      phoneNumber:
        type: string
        description: The phone number
        x-ms-mutability:
        - read
        - update
        - create
      purpose:
        $ref: '#/definitions/TestLinePurpose'
        description: Purpose of this test line, e.g. automated or manual testing
        x-ms-mutability:
        - read
        - update
        - create
    description: Details of the TestLine resource.
    required:
    - phoneNumber
    - purpose
  TestLineUpdate:
    type: object
    properties:
      tags:
        type: object
        additionalProperties:
          type: string
        x-cadl-name: Record<string>
        description: Resource tags.
    description: The type used for update operations of the TestLine.
parameters:
  TestLine.testLineName:
    name: testLineName
    in: path
    required: true
    description: Unique identifier for this test line
    pattern: ^[a-zA-Z0-9-]{3,24}$
    type: string
    x-ms-parameter-location: method
  CommunicationsGateway.communicationsGatewayName:
    name: communicationsGatewayName
    in: path
    required: true
    description: Unique identifier for this deployment
    pattern: ^[a-zA-Z0-9-]{3,24}$
    type: string
    x-ms-parameter-location: method
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
