swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector SolutionSelfHelp API
schemes:
- https
tags:
- name: SolutionSelfHelp
paths:
  /providers/Microsoft.Help/selfHelp/{solutionId}:
    get:
      tags:
      - SolutionSelfHelp
      description: Gets Self Help Solutions for a given solutionId. Self Help Solutions consist of rich instructional video tutorials, links and guides to public documentation related to a specific problem that enables users to troubleshoot Azure issues.
      operationId: microsoftAzureSolutionselfhelpGet
      parameters:
      - $ref: '#/parameters/solutionId'
      - $ref: '#/parameters/ApiVersionParameter'
      responses:
        '200':
          description: Successful fetched solution result.
          schema:
            $ref: '#/definitions/SolutionResourceSelfHelp'
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: ../../../../../common-types/resource-management/v5/types.json#/definitions/ErrorResponse
      x-ms-examples:
        Solution_Get:
          $ref: ./examples/SelfHelpSolution_Get.json
      summary: Microsoft Azure Get Providers Microsoft Help Selfhelp Solutionid
definitions:
  SectionSelfHelp:
    description: Part of the solution and are dividers in the solution rendering.
    type: object
    properties:
      title:
        description: Solution sections title.
        type: string
      content:
        description: Solution sections content.
        type: string
      replacementMaps:
        $ref: '#/definitions/ReplacementMapsSelfHelp'
  WebResult:
    description: AzureKB web result
    type: object
    properties:
      replacementKey:
        description: Place holder used in HTML Content replace control with the content
        type: string
      searchResults:
        description: AzureKB search results
        type: array
        items:
          $ref: '#/definitions/SearchResult'
        x-ms-identifiers:
        - solutionId
  Video:
    allOf:
    - $ref: '#/definitions/VideoGroupVideo'
    description: Video detail
    type: object
    properties:
      replacementKey:
        description: Place holder used in HTML Content replace control with the insight content
        type: string
  SolutionResourceSelfHelp:
    description: Self Help Solution response.
    type: object
    x-ms-azure-resource: true
    allOf:
    - $ref: ../../../../../common-types/resource-management/v5/types.json#/definitions/ProxyResource
    properties:
      properties:
        $ref: '#/definitions/SolutionsResourcePropertiesSelfHelp'
        x-ms-client-flatten: true
  SolutionsResourcePropertiesSelfHelp:
    description: Solution result
    type: object
    properties:
      solutionId:
        description: SolutionId is a unique id to identify a solution. You can retrieve the solution id using the Discovery api - https://learn.microsoft.com/en-us/rest/api/help/discovery-solution/list?view=rest-help-2023-09-01-preview&tabs=HTTP
        readOnly: true
        type: string
      title:
        description: The title.
        readOnly: true
        type: string
      content:
        description: The HTML content that needs to be rendered and shown to customer.
        readOnly: true
        type: string
      replacementMaps:
        $ref: '#/definitions/ReplacementMapsSelfHelp'
        readOnly: true
      sections:
        description: List of section object.
        type: array
        readOnly: true
        items:
          $ref: '#/definitions/SectionSelfHelp'
        x-ms-identifiers:
        - title
  SearchResult:
    description: Details of an AzureKB search result.
    type: object
    properties:
      solutionId:
        description: Unique id of the result.
        type: string
      content:
        description: Content of the search result.
        type: string
      title:
        description: Title of the search result.
        type: string
      confidence:
        description: Confidence of the search result.
        type: string
        enum:
        - Low
        - Medium
        - High
        x-ms-enum:
          name: confidence
          modelAsString: true
      source:
        description: Source of the search result.
        type: string
      resultType:
        description: Result type of the search result.
        type: string
        enum:
        - Community
        - Documentation
        x-ms-enum:
          name: resultType
          modelAsString: true
      rank:
        description: rank of the search result
        type: integer
        format: int32
      link:
        description: Link to the document.
        type: string
  ReplacementMapsSelfHelp:
    description: Solution replacement maps.
    type: object
    properties:
      webResults:
        description: Solution AzureKB results
        type: array
        items:
          $ref: '#/definitions/WebResult'
        x-ms-identifiers: []
      videos:
        description: Video solutions, which have the power to engage the customer by stimulating their senses
        type: array
        items:
          $ref: '#/definitions/Video'
        x-ms-identifiers: []
      videoGroups:
        description: Group of Videos
        type: array
        items:
          $ref: '#/definitions/VideoGroup'
        x-ms-identifiers: []
  VideoGroupVideo:
    description: VideoGroup video detail
    type: object
    properties:
      src:
        description: Link to the video
        type: string
      title:
        description: Title of the video
        type: string
  VideoGroup:
    description: Video group detail
    type: object
    properties:
      videos:
        description: List of videos will be shown to customers
        type: array
        items:
          $ref: '#/definitions/VideoGroupVideo'
        x-ms-identifiers: []
      replacementKey:
        description: Place holder used in HTML Content replace control with the insight content
        type: string
parameters:
  ApiVersionParameter:
    name: api-version
    in: query
    required: true
    type: string
    description: Client Api Version.
    x-ms-parameter-location: client
  solutionId:
    name: solutionId
    in: path
    required: true
    type: string
    description: SolutionId is a unique id to identify a solution. You can retrieve the solution id using the Discovery api - https://learn.microsoft.com/en-us/rest/api/help/discovery-solution/list?view=rest-help-2023-09-01-preview&tabs=HTTP
    x-ms-parameter-location: method
    minLength: 1
    maxLength: 100
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
