swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector AcrManifest API
  description: ACR APIs related to manifests
schemes:
- https
tags:
- name: AcrManifest
  description: ACR APIs related to manifests
paths:
  /acr/v1/{name}/_manifests:
    get:
      tags:
      - AcrManifest
      description: List manifests of a repository
      operationId: microsoftAzureGetacrmanifests
      x-ms-examples:
        Get details of repository:
          $ref: ./examples/GetAcrManifests.json
      parameters:
      - $ref: '#/parameters/ImageName'
      - $ref: '#/parameters/QueryLast'
      - $ref: '#/parameters/QueryNum'
      - $ref: '#/parameters/QueryOrderBy'
      responses:
        '200':
          description: Returns a list of manifests
          schema:
            $ref: '#/definitions/AcrManifests'
        default:
          description: ACR error response describing why the operation failed.
          schema:
            $ref: '#/definitions/AcrErrors'
      summary: Microsoft Azure Get Acr Name Manifests
  /acr/v1/{name}/_manifests/{reference}:
    get:
      tags:
      - AcrManifest
      description: Get manifest attributes
      operationId: microsoftAzureGetacrmanifestattributes
      x-ms-examples:
        Get manifest attributes:
          $ref: ./examples/GetAcrManifestAttributes.json
      parameters:
      - $ref: '#/parameters/ImageName'
      - $ref: '#/parameters/ImageReference'
      responses:
        '200':
          description: List of attributes
          schema:
            $ref: '#/definitions/AcrManifestAttributes'
        default:
          description: ACR error response describing why the operation failed.
          schema:
            $ref: '#/definitions/AcrErrors'
      summary: Microsoft Azure Get Acr Name Manifests Reference
    patch:
      tags:
      - AcrManifest
      description: Update attributes of a manifest
      operationId: microsoftAzureUpdateacrmanifestattributes
      consumes:
      - application/json
      x-ms-examples:
        Update attributes of a manifest:
          $ref: ./examples/UpdateAcrManifestAttributes.json
      parameters:
      - $ref: '#/parameters/ImageName'
      - $ref: '#/parameters/ImageReference'
      - $ref: '#/parameters/RepoValue'
      responses:
        '200':
          description: The attributes are updated
        default:
          description: ACR error response describing why the operation failed.
          schema:
            $ref: '#/definitions/AcrErrors'
      summary: Microsoft Azure Patch Acr Name Manifests Reference
definitions:
  ChangeableAttributes:
    properties:
      deleteEnabled:
        type: boolean
        description: Delete enabled
      writeEnabled:
        type: boolean
        description: Write enabled
      listEnabled:
        type: boolean
        description: List enabled
      readEnabled:
        type: boolean
        description: Read enabled
    example:
      readEnabled: true
      listEnabled: true
      deleteEnabled: true
      writeEnabled: true
  AcrManifestAttributesBase:
    type: object
    description: Manifest details
    properties:
      digest:
        type: string
        description: Manifest
      imageSize:
        type: integer
        description: Image size
      createdTime:
        type: string
        description: Created time
      lastUpdateTime:
        type: string
        description: Last update time
      architecture:
        type: string
        description: CPU architecture
      os:
        type: string
        description: Operating system
      mediaType:
        type: string
        description: Media type
      configMediaType:
        type: string
        description: Config blob media type
      tags:
        type: array
        description: List of tags
        items:
          type: string
          description: Tag name
      changeableAttributes:
        $ref: '#/definitions/ChangeableAttributes'
        description: Changeable attributes
    example:
      changeableAttributes:
        readEnabled: true
        listEnabled: true
        deleteEnabled: true
        writeEnabled: true
      os: os
      digest: digest
      imageSize: 2401606
      createdTime: createdTime
      mediaType: mediaType
      configMediaType: configMediaType
      lastUpdateTime: lastUpdateTime
      architecture: architecture
      tags:
      - tags
      - tags
  AcrErrors:
    description: Acr error response describing why the operation failed
    properties:
      errors:
        type: array
        description: Array of detailed error
        items:
          $ref: '#/definitions/AcrErrorInfo'
  AcrManifestAttributes:
    description: Manifest attributes details
    properties:
      registry:
        description: Registry name
        type: string
      imageName:
        description: Image name
        type: string
      manifest:
        x-ms-client-name: ManifestAttributes
        description: Manifest attributes
        $ref: '#/definitions/AcrManifestAttributesBase'
    example:
      registry: acrapi.azurecr-test.io
      imageName: nanoserver
      manifest:
        digest: sha256:110d2b6c84592561338aa040b1b14b7ab81c2f9edbd564c2285dd7d70d777086
        imageSize: 2401606
        createdTime: '2018-09-06T06:17:20.9983915Z'
        lastUpdateTime: '2018-09-06T06:17:20.9983915Z'
        architecture: amd64
        os: windows
        mediaType: application/vnd.docker.distribution.manifest.v2+json
        configMediaType: application/vnd.docker.container.image.v1+json
        tags:
        - 4.7.2-20180905-nanoserver-1803
        changeableAttributes:
          deleteEnabled: true
          writeEnabled: true
          readEnabled: true
          listEnabled: true
  AcrManifests:
    description: Manifest attributes
    properties:
      registry:
        type: string
        description: Registry name
      imageName:
        type: string
        description: Image name
      manifests:
        x-ms-client-name: ManifestsAttributes
        type: array
        description: List of manifests
        items:
          $ref: '#/definitions/AcrManifestAttributesBase'
          description: Manifest details
    example:
      registry: registry
      imageName: imageName
      manifests:
      - changeableAttributes:
          quarantineDetails: quarantineDetails
          readEnabled: true
          quarantineState: quarantineState
          listEnabled: true
          deleteEnabled: true
          writeEnabled: true
        os: os
        digest: digest
        imageSize: 2401606
        createdTime: createdTime
        mediaType: mediaType
        configMediaType: configMediaType
        lastUpdateTime: lastUpdateTime
        architecture: architecture
        tags:
        - tags
        - tags
      - changeableAttributes:
          quarantineDetails: quarantineDetails
          readEnabled: true
          quarantineState: quarantineState
          listEnabled: true
          deleteEnabled: true
          writeEnabled: true
        os: os
        digest: digest
        imageSize: 2401606
        createdTime: createdTime
        mediaType: mediaType
        configMediaType: configMediaType
        lastUpdateTime: lastUpdateTime
        architecture: architecture
        tags:
        - tags
        - tags
  AcrErrorInfo:
    description: Error information
    properties:
      code:
        description: Error code
        type: string
      message:
        type: string
        description: Error message
      detail:
        type: object
        description: Error details
parameters:
  RepoValue:
    name: value
    in: body
    description: Repository attribute value
    required: false
    schema:
      $ref: '#/definitions/ChangeableAttributes'
    x-ms-parameter-location: method
  ImageName:
    name: name
    in: path
    description: Name of the image (including the namespace)
    required: true
    type: string
    x-ms-parameter-location: method
  QueryLast:
    name: last
    in: query
    description: Query parameter for the last item in previous query. Result set will include values lexically after last.
    required: false
    type: string
    x-ms-parameter-location: method
  QueryNum:
    name: n
    in: query
    description: query parameter for max number of items
    required: false
    type: integer
    x-ms-parameter-location: method
  ImageReference:
    name: reference
    in: path
    description: A tag or a digest, pointing to a specific image
    required: true
    type: string
    x-ms-parameter-location: method
  QueryOrderBy:
    name: orderby
    in: query
    description: orderby query parameter
    required: false
    type: string
    x-ms-parameter-location: method
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
