swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector Content_Recording API
schemes:
- https
tags:
- name: Content_Recording
paths:
  /calling/recordings:
    post:
      tags:
      - Content_Recording
      summary: Microsoft Azure Start Recording The Call
      operationId: microsoftAzureContentRecording
      parameters:
      - name: startCallRecording
        in: body
        description: The request body of start call recording request.
        required: true
        schema:
          $ref: '#/definitions/StartCallRecordingRequest'
      - $ref: '#/parameters/ApiVersionParameter'
      - name: Repeatability-Request-ID
        in: header
        description: If specified, the client directs that the request is repeatable; that is, that the client can make the request multiple times with the same Repeatability-Request-Id and get back an appropriate response without the server executing the request multiple times. The value of the Repeatability-Request-Id is an opaque string representing a client-generated unique identifier for the request. It is a version 4 (random) UUID.
        type: string
        format: uuid
      - name: Repeatability-First-Sent
        in: header
        description: 'If Repeatability-Request-ID header is specified, then Repeatability-First-Sent header must also be specified. The value should be the date and time at which the request was first created, expressed using the IMF-fixdate form of HTTP-date. Example: Sun, 06 Nov 1994 08:49:37 GMT.'
        type: string
      responses:
        '200':
          description: Returns the start call recording response.
          schema:
            $ref: '#/definitions/RecordingStateResponse'
        default:
          description: Error
          schema:
            $ref: '#/definitions/CommunicationErrorResponse'
      x-ms-examples:
        Start recording the call.:
          $ref: ./examples/Content_Recording.json
      description: Needs a more full description created.
  /calling/recordings/{recordingId}:
    get:
      tags:
      - Content_Recording
      summary: Microsoft Azure Get Call Recording Properties
      operationId: microsoftAzureServercallsGetrecordingproperties
      parameters:
      - name: recordingId
        in: path
        description: The recording id.
        required: true
        type: string
      - $ref: '#/parameters/ApiVersionParameter'
      responses:
        '200':
          description: Returns the recording properties.
          schema:
            $ref: '#/definitions/RecordingStateResponse'
        default:
          description: Error
          schema:
            $ref: '#/definitions/CommunicationErrorResponse'
      x-ms-examples:
        Get call recording properties.:
          $ref: ./examples/ServerCalls_GetRecordingProperties.json
      description: Needs a more full description created.
    delete:
      tags:
      - Content_Recording
      summary: Microsoft Azure Stop Recording The Call
      operationId: microsoftAzureServercallsStoprecording
      parameters:
      - name: recordingId
        in: path
        description: The recording id.
        required: true
        type: string
      - $ref: '#/parameters/ApiVersionParameter'
      responses:
        '204':
          description: Returns the stop call recording response.
        default:
          description: Error
          schema:
            $ref: '#/definitions/CommunicationErrorResponse'
      x-ms-examples:
        Stop recording the call.:
          $ref: ./examples/ServerCalls_StopRecording.json
      description: Needs a more full description created.
  /calling/recordings/{recordingId}:pause:
    post:
      tags:
      - Content_Recording
      summary: Microsoft Azure Pause Recording The Call
      operationId: microsoftAzureServercallsPauserecording
      parameters:
      - name: recordingId
        in: path
        description: The recording id.
        required: true
        type: string
      - $ref: '#/parameters/ApiVersionParameter'
      responses:
        '202':
          description: Returns the pause call recording response.
        default:
          description: Error
          schema:
            $ref: '#/definitions/CommunicationErrorResponse'
      x-ms-examples:
        Pause recording the call.:
          $ref: ./examples/ServerCalls_PauseRecording.json
      description: Needs a more full description created.
  /calling/recordings/{recordingId}:resume:
    post:
      tags:
      - Content_Recording
      summary: Microsoft Azure Resume Recording The Call
      operationId: microsoftAzureServercallsResumerecording
      parameters:
      - name: recordingId
        in: path
        description: The recording id.
        required: true
        type: string
      - $ref: '#/parameters/ApiVersionParameter'
      responses:
        '202':
          description: Returns the resume call recording response.
        default:
          description: Error
          schema:
            $ref: '#/definitions/CommunicationErrorResponse'
      x-ms-examples:
        Resume recording the call.:
          $ref: ./examples/ServerCalls_ResumeRecording.json
      description: Needs a more full description created.
definitions:
  CommunicationUserIdentifierModel:
    required:
    - id
    type: object
    properties:
      id:
        type: string
  CommunicationError:
    type: object
    properties:
      code:
        type: string
      message:
        type: string
      target:
        type: string
      details:
        type: array
        items:
          $ref: '#/definitions/CommunicationError'
      innererror:
        $ref: '#/definitions/CommunicationError'
  MicrosoftTeamsUserIdentifierModel:
    required:
    - userId
    type: object
    properties:
      userId:
        type: string
      isAnonymous:
        type: boolean
      cloud:
        $ref: '#/definitions/CommunicationCloudEnvironmentModel'
  CommunicationErrorResponse:
    description: The Communication Services error response
    required:
    - error
    type: object
    properties:
      error:
        $ref: '#/definitions/CommunicationError'
  RecordingChannelType:
    description: The channel type of call recording.
    enum:
    - mixed
    - unmixed
    type: string
    x-ms-enum:
      name: RecordingChannelType
      modelAsString: true
  CallLocator:
    description: The locator used for joining or taking action on a call.
    type: object
    properties:
      groupCallId:
        description: The group call id
        type: string
      serverCallId:
        description: The server call id.
        type: string
      kind:
        $ref: '#/definitions/CallLocatorKind'
  PhoneNumberIdentifierModel:
    required:
    - value
    type: object
    properties:
      value:
        type: string
  CommunicationIdentifierModelKind:
    description: Type of CommunicationIdentifierModel.
    enum:
    - unknown
    - communicationUser
    - phoneNumber
    - microsoftTeamsUser
    type: string
    x-ms-enum:
      name: CommunicationIdentifierModelKind
      modelAsString: true
  RecordingContentType:
    description: The content type of call recording.
    enum:
    - audio
    - audioVideo
    type: string
    x-ms-enum:
      name: RecordingContentType
      modelAsString: true
  CallLocatorKind:
    description: The call locator kind.
    enum:
    - groupCallLocator
    - serverCallLocator
    type: string
    x-ms-enum:
      name: CallLocatorKind
      modelAsString: true
  RecordingFormatType:
    description: The format type of call recording.
    enum:
    - wav
    - mp3
    - mp4
    type: string
    x-ms-enum:
      name: RecordingFormatType
      modelAsString: true
  RecordingState:
    enum:
    - active
    - inactive
    type: string
    x-ms-enum:
      name: RecordingState
      modelAsString: true
  CommunicationIdentifierModel:
    type: object
    properties:
      rawId:
        description: Full ID of the identifier.
        type: string
      kind:
        $ref: '#/definitions/CommunicationIdentifierModelKind'
      communicationUser:
        $ref: '#/definitions/CommunicationUserIdentifierModel'
        description: The communication user.
      phoneNumber:
        $ref: '#/definitions/PhoneNumberIdentifierModel'
        description: The phone number.
      microsoftTeamsUser:
        $ref: '#/definitions/MicrosoftTeamsUserIdentifierModel'
        description: The Microsoft Teams user.
  StartCallRecordingRequest:
    description: The request payload start for call recording operation with call locator.
    required:
    - callLocator
    type: object
    properties:
      callLocator:
        $ref: '#/definitions/CallLocator'
        description: The call locator.
      recordingStateCallbackUri:
        description: The uri to send notifications to.
        type: string
      recordingContentType:
        $ref: '#/definitions/RecordingContentType'
      recordingChannelType:
        $ref: '#/definitions/RecordingChannelType'
      recordingFormatType:
        $ref: '#/definitions/RecordingFormatType'
      audioChannelParticipantOrdering:
        description: "The sequential order in which audio channels are assigned to participants in the unmixed recording.\r\nWhen 'recordingChannelType' is set to 'unmixed' and `audioChannelParticipantOrdering is not specified,\r\nthe audio channel to participant mapping will be automatically assigned based on the order in which participant\r\nfirst audio was detected.  Channel to participant mapping details can be found in the metadata of the recording."
        type: array
        items:
          $ref: '#/definitions/CommunicationIdentifierModel'
  RecordingStateResponse:
    type: object
    properties:
      recordingId:
        type: string
      recordingState:
        $ref: '#/definitions/RecordingState'
  CommunicationCloudEnvironmentModel:
    enum:
    - public
    - dod
    - gcch
    type: string
    x-ms-enum:
      name: CommunicationCloudEnvironmentModel
      modelAsString: true
parameters:
  ApiVersionParameter:
    name: api-version
    in: query
    description: Version of API to invoke.
    required: true
    type: string
    x-ms-parameter-location: method
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
