swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector OAuth2PermissionGrant_List API
schemes:
- https
tags:
- name: OAuth2PermissionGrant_List
paths:
  /{tenantID}/oauth2PermissionGrants:
    get:
      tags:
      - OAuth2PermissionGrant_List
      operationId: microsoftAzureOauth2permissiongrantList
      description: Queries OAuth2 permissions grants for the relevant SP ObjectId of an app.
      produces:
      - application/json
      parameters:
      - name: $filter
        in: query
        required: false
        type: string
        x-example: clientId+eq+'61ed44c3-5a1d-4639-a215-07f25129c6c3
        description: This is the Service Principal ObjectId associated with the app
      - $ref: '#/parameters/ApiVersionParameter'
      - $ref: '#/parameters/tenantIDInPath'
      responses:
        '200':
          description: OK. The operation was successful.
          schema:
            $ref: '#/definitions/OAuth2PermissionGrantListResult'
      x-ms-pageable:
        nextLinkName: odata.nextLink
        operationName: OAuth2PermissionGrant_ListNext
      summary: Microsoft Azure Get Tenantid Oauth2permissiongrants
definitions:
  OAuth2PermissionGrant:
    properties:
      odata.type:
        type: string
        description: Microsoft.DirectoryServices.OAuth2PermissionGrant
      clientId:
        type: string
        description: The id of the resource's service principal granted consent to impersonate the user when accessing the resource (represented by the resourceId property).
      objectId:
        type: string
        description: The id of the permission grant
      consentType:
        type: string
        description: Indicates if consent was provided by the administrator (on behalf of the organization) or by an individual.
        enum:
        - AllPrincipals
        - Principal
        x-ms-enum:
          name: ConsentType
          modelAsString: true
      principalId:
        type: string
        description: When consent type is Principal, this property specifies the id of the user that granted consent and applies only for that user.
      resourceId:
        type: string
        description: Object Id of the resource you want to grant
      scope:
        type: string
        description: Specifies the value of the scope claim that the resource application should expect in the OAuth 2.0 access token. For example, User.Read
      startTime:
        type: string
        description: Start time for TTL
      expiryTime:
        type: string
        description: Expiry time for TTL
    example:
      odata.type: odata.type
      resourceId: resourceId
      clientId: clientId
      scope: scope
      expiryTime: expiryTime
      consentType: consentType
      principalId: ''
      startTime: startTime
  OAuth2PermissionGrantListResult:
    type: object
    properties:
      value:
        type: array
        items:
          $ref: '#/definitions/OAuth2PermissionGrant'
        description: the list of oauth2 permissions grants
      odata.nextLink:
        type: string
        description: the URL to get the next set of results.
    description: Server response for get oauth2 permissions grants
parameters:
  ApiVersionParameter:
    name: api-version
    in: query
    required: true
    type: string
    description: Client API version.
  tenantIDInPath:
    name: tenantID
    in: path
    required: true
    type: string
    description: The tenant ID.
    x-ms-parameter-location: client
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
