swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector ApiKey API
schemes:
- https
tags:
- name: ApiKey
paths:
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Datadog/monitors/{monitorName}/listApiKeys
  : post:
      tags:
      - ApiKey
      summary: Microsoft Azure List The Api Keys For A Given Monitor Resource
      operationId: microsoftAzureMonitorsListapikeys
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/SubscriptionIdParameter'
      - $ref: '#/parameters/ResourceGroupNameParameter'
      - $ref: '#/parameters/MonitorNameParameter'
      - $ref: ../../../../../common-types/resource-management/v1/types.json#/parameters/ApiVersionParameter
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/DatadogApiKeyListResponse'
        default:
          description: Default error response.
          schema:
            $ref: '#/definitions/ResourceProviderDefaultErrorResponse'
      x-ms-pageable:
        nextLinkName: nextLink
      x-ms-examples:
        Monitors_ListApiKeys:
          $ref: ./examples/ApiKeys_List.json
      description: Needs a more full description created.
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Datadog/monitors/{monitorName}/getDefaultKey
  : post:
      tags:
      - ApiKey
      summary: Microsoft Azure Get The Default Api Key
      operationId: microsoftAzureMonitorsGetdefaultkey
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/SubscriptionIdParameter'
      - $ref: '#/parameters/ResourceGroupNameParameter'
      - $ref: '#/parameters/MonitorNameParameter'
      - $ref: ../../../../../common-types/resource-management/v1/types.json#/parameters/ApiVersionParameter
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/DatadogApiKey'
        default:
          description: Default error response.
          schema:
            $ref: '#/definitions/ResourceProviderDefaultErrorResponse'
      x-ms-examples:
        Monitors_GetDefaultKey:
          $ref: ./examples/ApiKeys_GetDefaultKey.json
      description: Needs a more full description created.
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Datadog/monitors/{monitorName}/setDefaultKey
  : post:
      tags:
      - ApiKey
      summary: Microsoft Azure Set The Default Api Key
      operationId: microsoftAzureMonitorsSetdefaultkey
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/SubscriptionIdParameter'
      - $ref: '#/parameters/ResourceGroupNameParameter'
      - $ref: '#/parameters/MonitorNameParameter'
      - $ref: ../../../../../common-types/resource-management/v1/types.json#/parameters/ApiVersionParameter
      - in: body
        name: body
        schema:
          $ref: '#/definitions/DatadogApiKey'
      responses:
        '200':
          description: Success
        default:
          description: Default error response.
          schema:
            $ref: '#/definitions/ResourceProviderDefaultErrorResponse'
      x-ms-examples:
        Monitors_SetDefaultKey:
          $ref: ./examples/ApiKeys_SetDefaultKey.json
      description: Needs a more full description created.
  /subscriptions/{subscriptionId}/providers/Microsoft.Elastic/getOrganizationApiKey:
    post:
      tags:
      - ApiKey
      summary: Microsoft Azure Fetch User Api Key From Internal Database, If It Was Generated And Stored While Creating The Elasticsearch Organization
      description: Fetch User API Key from internal database, if it was generated and stored while creating the Elasticsearch Organization.
      operationId: microsoftAzureOrganizationsGetapikey
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - $ref: ../../../../../common-types/resource-management/v5/types.json#/parameters/ApiVersionParameter
      - $ref: ../../../../../common-types/resource-management/v5/types.json#/parameters/SubscriptionIdParameter
      - in: body
        name: body
        description: Email Id parameter of the User Organization, of which the API Key must be returned
        schema:
          $ref: '#/definitions/UserEmailId'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/UserApiKeyResponse'
        default:
          description: Default error response.
          schema:
            $ref: '#/definitions/ResourceProviderDefaultErrorResponse_2'
      x-ms-examples:
        Organizations_GetApiKey:
          $ref: ./examples/Organizations_GetApiKey.json
definitions:
  DatadogApiKey:
    required:
    - key
    type: object
    properties:
      createdBy:
        description: The user that created the API key.
        type: string
      name:
        description: The name of the API key.
        type: string
      key:
        description: The value of the API key.
        type: string
      created:
        description: The time of creation of the API key.
        type: string
  UserApiKeyResponseProperties:
    type: object
    properties:
      apiKey:
        description: The User Api Key Generated based on GenerateApiKey flag. This is applicable for non-Portal clients only.
        type: string
        x-ms-secret: true
  ErrorResponseBody_2:
    description: Error response body.
    title: ErrorResponseBody
    type: object
    properties:
      code:
        description: Error code.
        type: string
      message:
        description: Error message.
        type: string
      target:
        description: Error target.
        type: string
      details:
        description: Error details.
        type: array
        x-ms-identifiers: []
        items:
          $ref: '#/definitions/ErrorResponseBody_2'
  ResourceProviderDefaultErrorResponse:
    type: object
    properties:
      error:
        $ref: '#/definitions/ErrorResponseBody'
  ResourceProviderDefaultErrorResponse_2:
    description: RP default error response.
    type: object
    properties:
      error:
        description: Response body of Error
        readOnly: true
        $ref: '#/definitions/ErrorResponseBody_2'
  UserApiKeyResponse:
    description: The User Api Key created for the Organization associated with the User Email Id that was passed in the request
    type: object
    properties:
      properties:
        $ref: '#/definitions/UserApiKeyResponseProperties'
  ErrorResponseBody:
    type: object
    properties:
      code:
        type: string
      message:
        type: string
      target:
        type: string
      details:
        type: array
        items:
          $ref: '#/definitions/ErrorResponseBody'
  DatadogApiKeyListResponse:
    description: Response of a list operation.
    type: object
    properties:
      value:
        description: Results of a list operation.
        type: array
        items:
          $ref: '#/definitions/DatadogApiKey'
      nextLink:
        description: Link to the next set of results, if any.
        type: string
  UserEmailId:
    description: Email Id of the User Organization, of which the API Key must be returned
    type: object
    properties:
      emailId:
        type: string
        description: The User email Id
parameters:
  MonitorNameParameter:
    in: path
    name: monitorName
    description: Monitor resource name
    required: true
    type: string
    x-ms-parameter-location: method
  SubscriptionIdParameter:
    name: subscriptionId
    in: path
    description: The Microsoft Azure subscription ID.
    required: true
    type: string
  ResourceGroupNameParameter:
    name: resourceGroupName
    in: path
    description: The name of the resource group to which the Datadog resource belongs.
    required: true
    type: string
    x-ms-parameter-location: method
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
