swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector Saved Filters API
  description: Provides access to saved filter resources.
schemes:
- https
tags:
- description: Provides access to saved filter resources.
  name: Saved Filters
paths:
  /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/workspaces/{workspaceName}/savedFilters:
    get:
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/FilterParameter'
      - $ref: '#/parameters/SkipParameter'
      - $ref: '#/parameters/MaxPageSizeParameter'
      - $ref: ../../../../../common-types/resource-management/v3/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../common-types/resource-management/v3/types.json#/parameters/ResourceGroupNameParameter
      - $ref: '#/parameters/WorkspaceNameParameter'
      - $ref: ../../../../../common-types/resource-management/v3/types.json#/parameters/ApiVersionParameter
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/SavedFilterPageResponse'
        default:
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
      tags:
      - Saved Filters
      operationId: microsoftAzureSavedfiltersList
      summary: Microsoft Azure Retrieve A List Of Saved Filters For The Provided Search Parameters
      x-ms-examples:
        SavedFilters:
          $ref: ./examples/SavedFilters_List.json
      x-ms-pageable:
        itemName: content
        nextLinkName: nextLink
      description: Needs a more full description created.
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/workspaces/{workspaceName}/savedFilters/{savedFilterName}
  : delete:
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/SavedFilterNameParameter'
      - $ref: ../../../../../common-types/resource-management/v3/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../common-types/resource-management/v3/types.json#/parameters/ResourceGroupNameParameter
      - $ref: '#/parameters/WorkspaceNameParameter'
      - $ref: ../../../../../common-types/resource-management/v3/types.json#/parameters/ApiVersionParameter
      responses:
        '204':
          description: No Content
        default:
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
      tags:
      - Saved Filters
      operationId: microsoftAzureSavedfiltersRemove
      summary: Microsoft Azure Remove A Saved Filter With A Given Savedfiltername
      x-ms-examples:
        SavedFilters:
          $ref: ./examples/SavedFilters_Remove.json
      description: Needs a more full description created.
    get:
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/SavedFilterNameParameter'
      - $ref: ../../../../../common-types/resource-management/v3/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../common-types/resource-management/v3/types.json#/parameters/ResourceGroupNameParameter
      - $ref: '#/parameters/WorkspaceNameParameter'
      - $ref: ../../../../../common-types/resource-management/v3/types.json#/parameters/ApiVersionParameter
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/SavedFilterResponse'
        default:
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
      tags:
      - Saved Filters
      operationId: microsoftAzureSavedfiltersGet
      summary: Microsoft Azure Retrieve A Saved Filter By Savedfiltername
      x-ms-examples:
        SavedFilters:
          $ref: ./examples/SavedFilters_Get.json
      description: Needs a more full description created.
    put:
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/SavedFilterNameParameter'
      - $ref: ../../../../../common-types/resource-management/v3/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../common-types/resource-management/v3/types.json#/parameters/ResourceGroupNameParameter
      - $ref: '#/parameters/WorkspaceNameParameter'
      - $ref: ../../../../../common-types/resource-management/v3/types.json#/parameters/ApiVersionParameter
      - in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/SavedFilterRequest'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/SavedFilterResponse'
        default:
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
      tags:
      - Saved Filters
      operationId: microsoftAzureSavedfiltersPut
      summary: Microsoft Azure Create A Saved Filter With A Given Savedfiltername
      x-ms-examples:
        SavedFilters:
          $ref: ./examples/SavedFilters_Put.json
      description: Needs a more full description created.
  /savedFilters:
    get:
      operationId: microsoftAzureSavedfiltersListsavedfilter
      tags:
      - Saved Filters
      description: Retrieve a list of saved filters for the provided search parameters.
      parameters:
      - $ref: '#/parameters/Azure.Core.Foundations.ApiVersionParameter'
      - $ref: '#/parameters/Azure.Core.FilterQueryParameter'
      - $ref: '#/parameters/Azure.Core.SkipQueryParameter'
      - $ref: '#/parameters/Azure.Core.MaxPageSizeQueryParameter'
      responses:
        '200':
          description: The request has succeeded.
          schema:
            $ref: '#/definitions/PagedSavedFilter'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/Azure.Core.Foundations.ErrorResponse'
          headers:
            x-ms-error-code:
              type: string
              description: String error code indicating what went wrong.
      x-ms-examples:
        SavedFilters_ListSavedFilter:
          $ref: ./examples/SavedFilters_ListSavedFilter_MaximumSet_Gen.json
      x-ms-pageable:
        nextLinkName: nextLink
      summary: Microsoft Azure Get Savedfilters
  /savedFilters/{filterName}:
    get:
      operationId: microsoftAzureSavedfiltersGetsavedfilter
      tags:
      - Saved Filters
      description: Retrieve a saved filter by filterName.
      parameters:
      - $ref: '#/parameters/Azure.Core.Foundations.ApiVersionParameter'
      - name: filterName
        in: path
        description: The caller provided unique name for the resource.
        required: true
        type: string
      responses:
        '200':
          description: The request has succeeded.
          schema:
            $ref: '#/definitions/SavedFilter'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/Azure.Core.Foundations.ErrorResponse'
          headers:
            x-ms-error-code:
              type: string
              description: String error code indicating what went wrong.
      x-ms-examples:
        SavedFilters_GetSavedFilter:
          $ref: ./examples/SavedFilters_GetSavedFilter_MaximumSet_Gen.json
      summary: Microsoft Azure Get Savedfilters Filtername
    put:
      operationId: microsoftAzureSavedfiltersCreateorreplacesavedfilter
      tags:
      - Saved Filters
      description: Create or replace a saved filter with a given filterName.
      parameters:
      - $ref: '#/parameters/Azure.Core.Foundations.ApiVersionParameter'
      - name: filterName
        in: path
        description: The caller provided unique name for the resource.
        required: true
        type: string
      - name: body
        in: body
        required: true
        schema:
          $ref: '#/definitions/SavedFilterData'
      responses:
        '200':
          description: The request has succeeded.
          schema:
            $ref: '#/definitions/SavedFilter'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/Azure.Core.Foundations.ErrorResponse'
          headers:
            x-ms-error-code:
              type: string
              description: String error code indicating what went wrong.
      x-ms-examples:
        SavedFilters_CreateOrReplaceSavedFilter:
          $ref: ./examples/SavedFilters_CreateOrReplaceSavedFilter_MaximumSet_Gen.json
      summary: Microsoft Azure Put Savedfilters Filtername
    delete:
      operationId: microsoftAzureSavedfiltersDeletesavedfilter
      tags:
      - Saved Filters
      description: Delete a saved filter with a given filterName.
      parameters:
      - $ref: '#/parameters/Azure.Core.Foundations.ApiVersionParameter'
      - name: filterName
        in: path
        description: The caller provided unique name for the resource.
        required: true
        type: string
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/Azure.Core.Foundations.ErrorResponse'
          headers:
            x-ms-error-code:
              type: string
              description: String error code indicating what went wrong.
      x-ms-examples:
        SavedFilters_DeleteSavedFilter:
          $ref: ./examples/SavedFilters_DeleteSavedFilter_MaximumSet_Gen.json
      summary: Microsoft Azure Delete Savedfilters Filtername
definitions:
  ErrorDetail:
    description: This is the top-level error object whose code matches the x-ms-error-code response header
    properties:
      code:
        description: This is one of a server-defined set of error codes.
        type: string
      details:
        description: This is an array of details about specific errors that led to this reported error.
        items:
          $ref: '#/definitions/ErrorDetail'
        type: array
      innererror:
        $ref: '#/definitions/InnerError'
      message:
        description: This is a human-readable representation of the error.
        type: string
      target:
        description: This is the error target.
        type: string
    required:
    - code
    - message
    type: object
  PagedSavedFilter:
    type: object
    description: Paged collection of SavedFilter items
    properties:
      value:
        type: array
        description: The SavedFilter items on this page
        items:
          $ref: '#/definitions/SavedFilter'
      nextLink:
        type: string
        format: uri
        description: The link to the next page of items
      totalElements:
        type: integer
        format: int64
        description: The total number of items available in the full result set.
    required:
    - value
  Azure.Core.Foundations.Error:
    type: object
    description: The error object.
    properties:
      code:
        type: string
        description: One of a server-defined set of error codes.
      message:
        type: string
        description: A human-readable representation of the error.
      target:
        type: string
        description: The target of the error.
      details:
        type: array
        description: An array of details about specific errors that led to this reported error.
        items:
          $ref: '#/definitions/Azure.Core.Foundations.Error'
        x-ms-identifiers: []
      innererror:
        $ref: '#/definitions/Azure.Core.Foundations.InnerError'
        description: An object containing more specific information than the current object about the error.
    required:
    - code
    - message
  SavedFilterData:
    type: object
    description: A request body used to create a saved filter.
    properties:
      filter:
        type: string
        description: An expression on the resource type that selects the resources to be returned.
      description:
        type: string
        description: A human readable description of the saved filter.
    required:
    - filter
    - description
  Azure.Core.Foundations.ErrorResponse:
    type: object
    description: A response containing error details.
    properties:
      error:
        $ref: '#/definitions/Azure.Core.Foundations.Error'
        description: The error object.
    required:
    - error
  SavedFilterRequest:
    properties:
      description:
        type: string
      filter:
        type: string
      id:
        type: string
    type: object
  SavedFilterPageResponse:
    properties:
      content:
        items:
          $ref: '#/definitions/SavedFilterResponse'
        type: array
      first:
        type: boolean
      last:
        type: boolean
      nextLink:
        type: string
      number:
        format: int32
        type: integer
      numberOfElements:
        format: int32
        type: integer
      size:
        format: int32
        type: integer
      totalElements:
        format: int64
        type: integer
      totalPages:
        format: int32
        type: integer
    type: object
  SavedFilter:
    type: object
    properties:
      id:
        type: string
        description: The system generated unique id for the resource.
      name:
        type: string
        description: The caller provided unique name for the resource.
        readOnly: true
      displayName:
        type: string
        description: The name that can be used for display purposes.
      filter:
        type: string
      description:
        type: string
    required:
    - name
  SavedFilterResponse:
    properties:
      description:
        type: string
      displayName:
        type: string
      filter:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
  Azure.Core.Foundations.InnerError:
    type: object
    description: An object containing more specific information about the error. As per Microsoft One API guidelines - https://github.com/Microsoft/api-guidelines/blob/vNext/Guidelines.md#7102-error-condition-responses.
    properties:
      code:
        type: string
        description: One of a server-defined set of error codes.
      innererror:
        $ref: '#/definitions/Azure.Core.Foundations.InnerError'
        description: Inner error.
  ErrorResponse:
    properties:
      error:
        $ref: '#/definitions/ErrorDetail'
    required:
    - error
    type: object
  InnerError:
    description: This is an object containing more specific information than the current object about the error.
    properties:
      code:
        description: This is a more specific error code than was provided by the containing error..
        type: string
    type: object
parameters:
  FilterParameter:
    description: An expression on the resource type that selects the resources to be returned.
    in: query
    name: filter
    required: false
    type: string
    x-ms-parameter-location: method
  Azure.Core.FilterQueryParameter:
    name: filter
    in: query
    description: Filter the result list using the given expression.
    required: false
    type: string
    x-ms-parameter-location: method
  SavedFilterNameParameter:
    in: path
    name: savedFilterName
    required: true
    type: string
    x-ms-parameter-location: method
  Azure.Core.MaxPageSizeQueryParameter:
    name: maxpagesize
    in: query
    description: The maximum number of result items per page.
    required: false
    type: integer
    format: int32
    x-ms-parameter-location: method
  MaxPageSizeParameter:
    default: 20
    description: An offset into the collection of the first resource to be returned.
    format: int32
    in: query
    name: maxpagesize
    required: false
    type: integer
    x-ms-parameter-location: method
  Azure.Core.SkipQueryParameter:
    name: skip
    in: query
    description: The number of result items to skip.
    required: false
    type: integer
    format: int32
    default: 0
    x-ms-parameter-location: method
  WorkspaceNameParameter:
    description: The name of the Workspace.
    in: path
    name: workspaceName
    required: true
    type: string
    x-ms-parameter-location: method
  SkipParameter:
    default: 0
    description: An offset into the collection of the first resource to be returned.
    format: int32
    in: query
    name: skip
    required: false
    type: integer
    x-ms-parameter-location: method
  Azure.Core.Foundations.ApiVersionParameter:
    name: api-version
    in: query
    description: The API version to use for this operation.
    required: true
    type: string
    minLength: 1
    x-ms-parameter-location: method
    x-ms-client-name: apiVersion
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
