swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector Relationships API
schemes:
- https
tags:
- name: Relationships
paths:
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.CustomerInsights/hubs/{hubName}/relationships/{relationshipName}
  : put:
      tags:
      - Relationships
      operationId: microsoftAzureRelationshipsCreateorupdate
      x-ms-examples:
        Relationships_CreateOrUpdate:
          $ref: ./examples/RelationshipsCreateOrUpdate.json
      description: Creates a relationship or updates an existing relationship within a hub.
      parameters:
      - name: resourceGroupName
        in: path
        required: true
        type: string
        description: The name of the resource group.
      - name: hubName
        in: path
        required: true
        type: string
        description: The name of the hub.
      - name: relationshipName
        in: path
        required: true
        type: string
        description: The name of the Relationship.
        pattern: ^[a-zA-Z][a-zA-Z0-9_]+$
        minLength: 1
        maxLength: 512
      - name: parameters
        in: body
        required: true
        schema:
          $ref: '#/definitions/RelationshipResourceFormat'
        description: Parameters supplied to the CreateOrUpdate Relationship operation.
      - $ref: '#/parameters/ApiVersionParameter'
      - $ref: '#/parameters/SubscriptionIdParameter'
      responses:
        '200':
          description: OK. Successfully created the relationship.
          schema:
            $ref: '#/definitions/RelationshipResourceFormat'
        '202':
          description: Accepted. The create relationship operation is accepted.
      x-ms-long-running-operation: true
      summary: Microsoft Azure Put Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Customerinsights Hubs Hubname Relationships Relationshipname
    get:
      tags:
      - Relationships
      operationId: microsoftAzureRelationshipsGet
      x-ms-examples:
        Relationships_Get:
          $ref: ./examples/RelationshipsGet.json
      description: Gets information about the specified relationship.
      parameters:
      - name: resourceGroupName
        in: path
        required: true
        type: string
        description: The name of the resource group.
      - name: hubName
        in: path
        required: true
        type: string
        description: The name of the hub.
      - name: relationshipName
        in: path
        required: true
        type: string
        description: The name of the relationship.
      - $ref: '#/parameters/ApiVersionParameter'
      - $ref: '#/parameters/SubscriptionIdParameter'
      responses:
        '200':
          description: OK. Successfully get the relationship.
          schema:
            $ref: '#/definitions/RelationshipResourceFormat'
      summary: Microsoft Azure Get Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Customerinsights Hubs Hubname Relationships Relationshipname
    delete:
      tags:
      - Relationships
      operationId: microsoftAzureRelationshipsDelete
      x-ms-examples:
        Relationships_Delete:
          $ref: ./examples/RelationshipsDelete.json
      description: Deletes a relationship within a hub.
      parameters:
      - name: resourceGroupName
        in: path
        required: true
        type: string
        description: The name of the resource group.
      - name: hubName
        in: path
        required: true
        type: string
        description: The name of the hub.
      - name: relationshipName
        in: path
        required: true
        type: string
        description: The name of the relationship.
      - $ref: '#/parameters/ApiVersionParameter'
      - $ref: '#/parameters/SubscriptionIdParameter'
      responses:
        '200':
          description: OK. The relationship is deleted.
        '202':
          description: Accepted. The delete operation is accepted.
      x-ms-long-running-operation: true
      summary: Microsoft Azure Delete Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Customerinsights Hubs Hubname Relationships Relationshipname
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.CustomerInsights/hubs/{hubName}/relationships
  : get:
      tags:
      - Relationships
      operationId: microsoftAzureRelationshipsListbyhub
      x-ms-examples:
        Relationships_ListByHub:
          $ref: ./examples/RelationshipsListByHub.json
      description: Gets all relationships in the hub.
      parameters:
      - name: resourceGroupName
        in: path
        required: true
        type: string
        description: The name of the resource group.
      - name: hubName
        in: path
        required: true
        type: string
        description: The name of the hub.
      - $ref: '#/parameters/ApiVersionParameter'
      - $ref: '#/parameters/SubscriptionIdParameter'
      responses:
        '200':
          description: OK. Successfully get all the relationships in the hub.
          schema:
            $ref: '#/definitions/RelationshipListResult'
      x-ms-pageable:
        nextLinkName: nextLink
      summary: Microsoft Azure Get Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Customerinsights Hubs Hubname Relationships
definitions:
  ProxyResource:
    properties:
      id:
        readOnly: true
        type: string
        description: Resource ID.
      name:
        readOnly: true
        type: string
        description: Resource name.
      type:
        readOnly: true
        type: string
        description: Resource type.
    x-ms-azure-resource: true
    description: Common properties of proxy resource.
  RelationshipDefinition:
    required:
    - profileType
    - relatedProfileType
    properties:
      cardinality:
        type: string
        enum:
        - OneToOne
        - OneToMany
        - ManyToMany
        x-ms-enum:
          name: CardinalityTypes
          modelAsString: false
        description: The Relationship Cardinality.
      displayName:
        type: object
        additionalProperties:
          type: string
        description: Localized display name for the Relationship.
      description:
        type: object
        additionalProperties:
          type: string
        description: Localized descriptions for the Relationship.
      expiryDateTimeUtc:
        type: string
        format: date-time
        description: The expiry date time in UTC.
      fields:
        type: array
        items:
          $ref: '#/definitions/PropertyDefinition'
        description: The properties of the Relationship.
      lookupMappings:
        type: array
        items:
          $ref: '#/definitions/RelationshipTypeMapping'
        description: Optional property to be used to map fields in profile to their strong ids in related profile.
      profileType:
        type: string
        description: Profile type.
      provisioningState:
        $ref: '#/definitions/ProvisioningState'
        readOnly: true
        description: Provisioning state.
      relationshipName:
        type: string
        readOnly: true
        description: The Relationship name.
      relatedProfileType:
        type: string
        description: Related profile being referenced.
      relationshipGuidId:
        type: string
        readOnly: true
        description: The relationship guid id.
      tenantId:
        type: string
        readOnly: true
        description: The hub name.
    description: The definition of Relationship.
  RelationshipTypeMapping:
    required:
    - fieldMappings
    properties:
      fieldMappings:
        type: array
        items:
          $ref: '#/definitions/RelationshipTypeFieldMapping'
        description: Maps a profile property with the StrongId of related profile. This is an array to support StrongIds that are composite key as well.
    description: Maps fields in Profile to their corresponding StrongIds in Related Profile.
  ProvisioningState:
    type: string
    enum:
    - Provisioning
    - Succeeded
    - Expiring
    - Deleting
    - HumanIntervention
    - Failed
    x-ms-enum:
      name: ProvisioningStates
      modelAsString: true
    description: Provisioning state.
  RelationshipResourceFormat:
    description: The relationship resource format.
    properties:
      properties:
        x-ms-client-flatten: true
        $ref: '#/definitions/RelationshipDefinition'
    allOf:
    - $ref: '#/definitions/ProxyResource'
  PropertyDefinition:
    required:
    - fieldName
    - fieldType
    properties:
      arrayValueSeparator:
        type: string
        description: Array value separator for properties with isArray set.
      enumValidValues:
        type: array
        items:
          $ref: '#/definitions/ProfileEnumValidValuesFormat'
        description: Describes valid values for an enum property.
      fieldName:
        type: string
        description: Name of the property.
      fieldType:
        type: string
        description: Type of the property.
      isArray:
        type: boolean
        description: Indicates if the property is actually an array of the fieldType above on the data api.
      isEnum:
        type: boolean
        description: Indicates if the property is an enum.
      isFlagEnum:
        type: boolean
        description: Indicates if the property is an flag enum.
      isImage:
        type: boolean
        description: Whether the property is an Image.
      isLocalizedString:
        type: boolean
        description: Whether the property is a localized string.
      isName:
        type: boolean
        description: Whether the property is a name or a part of name.
      isRequired:
        type: boolean
        description: Whether property value is required on instances, IsRequired field only for Interaction. Profile Instance will not check for required field.
      propertyId:
        type: string
        description: The ID associated with the property.
      schemaItemPropLink:
        type: string
        description: URL encoded schema.org item prop link for the property.
      maxLength:
        type: integer
        description: Max length of string. Used only if type is string.
      isAvailableInGraph:
        type: boolean
        description: Whether property is available in graph or not.
      dataSourcePrecedenceRules:
        type: array
        items:
          $ref: '#/definitions/DataSourcePrecedence'
        readOnly: true
        description: This is specific to interactions modeled as activities. Data sources are used to determine where data is stored and also in precedence rules.
    description: Property definition.
  DataSource:
    properties:
      name:
        type: string
        readOnly: true
        description: The data source name
      dataSourceType:
        type: string
        enum:
        - Connector
        - LinkInteraction
        - SystemDefault
        x-ms-enum:
          name: DataSourceType
          modelAsString: true
        readOnly: true
        description: The data source type.
      status:
        type: string
        enum:
        - None
        - Active
        - Deleted
        x-ms-enum:
          name: Status
          modelAsString: true
        readOnly: true
        description: The data source status.
      id:
        type: integer
        readOnly: true
        description: The data source ID.
      dataSourceReferenceId:
        type: string
        readOnly: true
        description: The data source reference id.
    description: Data Source is a way for us to know the source of instances. A single type can have data coming in from multiple places. In activities we use this to determine precedence rules.
  DataSourcePrecedence:
    properties:
      dataSource:
        x-ms-client-flatten: true
        $ref: '#/definitions/DataSource'
      precedence:
        type: integer
        description: the precedence value.
    description: The data source precedence is a way to know the precedence of each data source.
  RelationshipListResult:
    properties:
      value:
        type: array
        items:
          $ref: '#/definitions/RelationshipResourceFormat'
        description: Results of the list operation.
      nextLink:
        type: string
        description: Link to the next set of results.
    description: The response of list relationship operation.
  RelationshipTypeFieldMapping:
    required:
    - profileFieldName
    - relatedProfileKeyProperty
    properties:
      profileFieldName:
        type: string
        description: Specifies the fieldName in profile.
      relatedProfileKeyProperty:
        type: string
        description: Specifies the KeyProperty (from StrongId) of the related profile.
    description: Map a field of profile to its corresponding StrongId in Related Profile.
  ProfileEnumValidValuesFormat:
    properties:
      value:
        type: integer
        description: The integer value of the enum member.
      localizedValueNames:
        type: object
        additionalProperties:
          type: string
        description: Localized names of the enum member.
    description: Valid enum values in case of an enum property.
parameters:
  ApiVersionParameter:
    name: api-version
    in: query
    required: true
    type: string
    description: Client Api Version.
  SubscriptionIdParameter:
    name: subscriptionId
    in: path
    required: true
    type: string
    description: Gets subscription credentials which uniquely identify Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
