swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector ApplyUpdate API
schemes:
- https
tags:
- name: ApplyUpdate
paths:
  /subscriptions/{subscriptionId}/providers/Microsoft.Maintenance/applyUpdates:
    get:
      tags:
      - ApplyUpdate
      summary: Microsoft Azure Get Configuration Records Within A Subscription
      operationId: microsoftAzureApplyupdatesList
      consumes: []
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/SubscriptionIdParameter'
      - $ref: '#/parameters/ApiVersionParameter'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ListApplyUpdate'
        default:
          description: BadRequest
          schema:
            $ref: '#/definitions/MaintenanceError'
      x-ms-pageable:
        nextLinkName: null
      x-ms-examples:
        ApplyUpdates_List:
          $ref: ./examples/ApplyUpdates_List.json
      description: Needs a more full description created.
  /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Maintenance/applyUpdates:
    get:
      tags:
      - ApplyUpdate
      summary: Microsoft Azure Get Configuration Records Within A Subscription And Resource Group
      operationId: microsoftAzureApplyupdateforresourcegroupList
      consumes: []
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/SubscriptionIdParameter'
      - name: resourceGroupName
        in: path
        description: Resource Group Name
        required: true
        type: string
      - $ref: '#/parameters/ApiVersionParameter'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ListApplyUpdate'
        default:
          description: BadRequest
          schema:
            $ref: '#/definitions/MaintenanceError'
      x-ms-pageable:
        nextLinkName: null
      x-ms-examples:
        ApplyUpdatesResourceGroup_List:
          $ref: ./examples/ApplyUpdatesResourceGroup_List.json
      description: Needs a more full description created.
definitions:
  Resource:
    description: Definition of a Resource
    type: object
    properties:
      id:
        description: Fully qualified identifier of the resource
        type: string
        readOnly: true
      name:
        description: Name of the resource
        type: string
        readOnly: true
      type:
        description: Type of the resource
        type: string
        readOnly: true
      systemData:
        readOnly: true
        type: object
        description: Azure Resource Manager metadata containing createdBy and modifiedBy information.
        $ref: ../../../../../common-types/resource-management/v2/types.json#/definitions/systemData
    x-ms-azure-resource: true
  ListApplyUpdate:
    description: Response for ApplyUpdate list
    type: object
    properties:
      value:
        description: The list of apply updates
        type: array
        items:
          $ref: '#/definitions/ApplyUpdate'
  ErrorDetails:
    description: An error response details received from the Azure Maintenance service.
    type: object
    properties:
      code:
        description: Service-defined error code. This code serves as a sub-status for the HTTP error code specified in the response.
        type: string
      message:
        description: Human-readable representation of the error.
        type: string
  ApplyUpdate:
    description: Apply Update request
    type: object
    allOf:
    - $ref: '#/definitions/Resource'
    properties:
      properties:
        $ref: '#/definitions/ApplyUpdateProperties'
        description: Properties of the apply update
        x-ms-client-flatten: true
  MaintenanceError:
    description: An error response received from the Azure Maintenance service.
    type: object
    properties:
      error:
        $ref: '#/definitions/ErrorDetails'
        description: Details of the error
  ApplyUpdateProperties:
    description: Properties for apply update
    type: object
    properties:
      status:
        description: The status
        enum:
        - Pending
        - InProgress
        - Completed
        - RetryNow
        - RetryLater
        - NoUpdatesPending
        - Cancel
        - Cancelled
        type: string
        x-ms-enum:
          name: UpdateStatus
          modelAsString: true
          values:
          - value: Pending
            description: There are pending updates to be installed.
          - value: InProgress
            description: Updates installation are in progress.
          - value: Completed
            description: All updates are successfully applied.
          - value: RetryNow
            description: Updates installation failed but are ready to retry again.
          - value: RetryLater
            description: Updates installation failed and should be retried later.
          - value: NoUpdatesPending
            description: No updates are pending.
          - value: Cancel
            description: Cancel the schedule and stop creating PMR for resources part of it. Applicable to Maintenance Configuration resource type only.
          - value: Cancelled
            description: Send the Cancelled response to the user if request came to cancel the schedule. Applicable to Maintenance Configuration resource type only.
      resourceId:
        description: The resourceId
        type: string
      lastUpdateTime:
        format: date-time
        description: Last Update time
        type: string
parameters:
  ApiVersionParameter:
    name: api-version
    in: query
    description: Version of the API to be used with the client request.
    required: true
    type: string
    x-ms-parameter-location: client
  SubscriptionIdParameter:
    name: subscriptionId
    in: path
    description: Subscription credentials that uniquely identify a Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.
    required: true
    type: string
    x-ms-parameter-location: client
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
