swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector EmailGetSendStatus API
schemes:
- https
tags:
- name: EmailGetSendStatus
paths:
  /emails/{messageId}/status:
    get:
      tags:
      - EmailGetSendStatus
      summary: Microsoft Azure Gets The Status Of A Message Sent Previously
      operationId: microsoftAzureEmailGetsendstatus
      produces:
      - application/json
      consumes:
      - application/json
      parameters:
      - in: path
        name: messageId
        description: System generated message id (GUID) returned from a previous call to send email
        required: true
        type: string
      - $ref: '#/parameters/ApiVersionParameter'
      responses:
        '200':
          description: Message status was successfully retrieved.
          headers:
            Retry-After:
              description: 'Amount of time client should wait before retrying the request, specified in seconds '
              type: integer
          schema:
            $ref: '#/definitions/SendStatusResult'
        default:
          description: Error
          headers:
            x-ms-error-code:
              description: Error code - this will be the same as the code in the error property in the response body.
              type: string
          schema:
            $ref: ../../../Common/stable/2021-03-07/common.json#/definitions/CommunicationErrorResponse
      x-ms-examples:
        Get Message Status:
          $ref: ./examples/GetSendStatus.json
      description: Needs a more full description created.
definitions:
  SendStatus:
    description: The type indicating the status of a request.
    enum:
    - queued
    - outForDelivery
    - dropped
    type: string
    x-ms-enum:
      name: SendStatus
      modelAsString: true
      values:
      - value: queued
        description: The message has passed basic validations and has been queued to be processed further.
      - value: outForDelivery
        description: The message has been processed and is now out for delivery.
      - value: dropped
        description: The message could not be processed and was dropped.
  SendStatusResult:
    description: Status of an email message that was sent previously.
    type: object
    required:
    - messageId
    - status
    properties:
      messageId:
        description: System generated id of an email message sent.
        type: string
        example: F9168C5E-CEB2-4faa-B6BF-329BF39FA1E4
      status:
        $ref: '#/definitions/SendStatus'
parameters:
  ApiVersionParameter:
    in: query
    name: api-version
    description: Version of API to invoke.
    required: true
    enum:
    - 2021-10-01-preview
    type: string
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
