swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector JitRequests API
schemes:
- https
tags:
- name: JitRequests
paths:
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Solutions/jitRequests/{jitRequestName}
  : get:
      tags:
      - JitRequests
      operationId: microsoftAzureJitrequestsGet
      description: Gets the JIT request.
      x-ms-examples:
        Gets the jit request:
          $ref: ./examples/getJitRequest.json
      parameters:
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/ResourceGroupNameParameter
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/ApiVersionParameter
      - $ref: '#/parameters/JitRequestNameParameter'
      responses:
        '200':
          description: OK - Returns the JIT request
          schema:
            $ref: '#/definitions/JitRequestDefinition'
        '404':
          description: NotFound.
          x-ms-error-response: false
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: ../../../../../common-types/resource-management/v2/types.json#/definitions/ErrorResponse
      summary: Microsoft Azure Get Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Solutions Jitrequests Jitrequestname
    put:
      tags:
      - JitRequests
      operationId: microsoftAzureJitrequestsCreateorupdate
      description: Creates or updates the JIT request.
      x-ms-examples:
        Create or update jit request:
          $ref: ./examples/createOrUpdateJitRequest.json
      parameters:
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/ResourceGroupNameParameter
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/ApiVersionParameter
      - $ref: '#/parameters/JitRequestNameParameter'
      - name: parameters
        in: body
        required: true
        schema:
          $ref: '#/definitions/JitRequestDefinition'
        description: Parameters supplied to the update JIT request.
      responses:
        '200':
          description: OK - Returns information about the JIT request.
          schema:
            $ref: '#/definitions/JitRequestDefinition'
        '201':
          description: Created - Returns information about the JIT request.
          schema:
            $ref: '#/definitions/JitRequestDefinition'
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: ../../../../../common-types/resource-management/v2/types.json#/definitions/ErrorResponse
      x-ms-long-running-operation: true
      x-ms-long-running-operation-options:
        final-state-via: azure-async-operation
      summary: Microsoft Azure Put Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Solutions Jitrequests Jitrequestname
    patch:
      tags:
      - JitRequests
      operationId: microsoftAzureJitrequestsUpdate
      description: Updates the JIT request.
      x-ms-examples:
        Update jit request:
          $ref: ./examples/updateJitRequest.json
      parameters:
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/ResourceGroupNameParameter
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/ApiVersionParameter
      - $ref: '#/parameters/JitRequestNameParameter'
      - name: parameters
        in: body
        required: true
        schema:
          $ref: '#/definitions/JitRequestPatchable'
        description: Parameters supplied to the update JIT request.
      responses:
        '200':
          description: Ok - Returns information about the JIT request.
          schema:
            $ref: '#/definitions/JitRequestDefinition'
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: ../../../../../common-types/resource-management/v2/types.json#/definitions/ErrorResponse
      summary: Microsoft Azure Patch Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Solutions Jitrequests Jitrequestname
    delete:
      tags:
      - JitRequests
      operationId: microsoftAzureJitrequestsDelete
      description: Deletes the JIT request.
      x-ms-examples:
        Delete jit request:
          $ref: ./examples/deleteJitRequest.json
      parameters:
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/ResourceGroupNameParameter
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/ApiVersionParameter
      - $ref: '#/parameters/JitRequestNameParameter'
      responses:
        '200':
          description: OK
        '204':
          description: NoContent
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: ../../../../../common-types/resource-management/v2/types.json#/definitions/ErrorResponse
      summary: Microsoft Azure Delete Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Solutions Jitrequests Jitrequestname
  /subscriptions/{subscriptionId}/providers/Microsoft.Solutions/jitRequests:
    get:
      tags:
      - JitRequests
      operationId: microsoftAzureJitrequestsListbysubscription
      description: Lists all JIT requests within the subscription.
      x-ms-examples:
        Lists all JIT requests within the subscription:
          $ref: ./examples/listJitRequestsByResourceGroup.json
      parameters:
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/ApiVersionParameter
      responses:
        '200':
          description: OK - Returns an array of JIT requests.
          schema:
            $ref: '#/definitions/JitRequestDefinitionListResult'
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: ../../../../../common-types/resource-management/v2/types.json#/definitions/ErrorResponse
      summary: Microsoft Azure Get Subscriptions Subscriptionid Providers Microsoft Solutions Jitrequests
  /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Solutions/jitRequests:
    get:
      tags:
      - JitRequests
      operationId: microsoftAzureJitrequestsListbyresourcegroup
      description: Lists all JIT requests within the resource group.
      x-ms-examples:
        Lists all JIT requests within the resource group:
          $ref: ./examples/listJitRequestsByResourceGroup.json
      parameters:
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/ResourceGroupNameParameter
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/ApiVersionParameter
      responses:
        '200':
          description: OK - Returns an array of JIT requests.
          schema:
            $ref: '#/definitions/JitRequestDefinitionListResult'
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: ../../../../../common-types/resource-management/v2/types.json#/definitions/ErrorResponse
      summary: Microsoft Azure Get Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Solutions Jitrequests
definitions:
  JitRequestProperties:
    type: object
    properties:
      applicationResourceId:
        type: string
        description: The parent application id.
      publisherTenantId:
        readOnly: true
        type: string
        description: The publisher tenant id.
      jitAuthorizationPolicies:
        description: The JIT authorization policies.
        type: array
        items:
          $ref: '#/definitions/JitAuthorizationPolicies'
        x-ms-identifiers:
        - principalId
        - roleDefinitionId
      jitSchedulingPolicy:
        $ref: '#/definitions/JitSchedulingPolicy'
        description: The JIT request properties.
      provisioningState:
        readOnly: true
        $ref: '#/definitions/ProvisioningState'
        description: The JIT request provisioning state.
      jitRequestState:
        readOnly: true
        $ref: '#/definitions/JitRequestState'
        description: The JIT request state.
      createdBy:
        readOnly: true
        $ref: '#/definitions/ApplicationClientDetails'
        description: The client entity that created the JIT request.
      updatedBy:
        readOnly: true
        $ref: '#/definitions/ApplicationClientDetails'
        description: The client entity that last updated the JIT request.
    required:
    - applicationResourceId
    - jitAuthorizationPolicies
    - jitSchedulingPolicy
    description: Information about JIT request properties
  JitRequestDefinitionListResult:
    type: object
    properties:
      value:
        type: array
        items:
          $ref: '#/definitions/JitRequestDefinition'
        description: The array of Jit request definition.
      nextLink:
        type: string
        description: The URL to use for getting the next set of results.
    description: List of JIT requests.
  Resource:
    type: object
    properties:
      id:
        readOnly: true
        type: string
        description: Resource ID
      name:
        readOnly: true
        type: string
        description: Resource name
      type:
        readOnly: true
        type: string
        description: Resource type
      location:
        type: string
        description: Resource location
      tags:
        type: object
        additionalProperties:
          type: string
        description: Resource tags
      systemData:
        $ref: ../../../../../common-types/resource-management/v2/types.json#/definitions/systemData
        readOnly: true
    description: Resource information.
    x-ms-azure-resource: true
  JitRequestDefinition:
    type: object
    properties:
      properties:
        x-ms-client-flatten: true
        $ref: '#/definitions/JitRequestProperties'
        description: The JIT request properties.
    allOf:
    - $ref: '#/definitions/Resource'
    description: Information about JIT request definition.
  ApplicationClientDetails:
    type: object
    readOnly: true
    properties:
      oid:
        type: string
        description: The client Oid.
      puid:
        type: string
        description: The client Puid
      applicationId:
        type: string
        description: The client application Id.
    description: The application client details to track the entity creating/updating the managed app resource.
  ProvisioningState:
    description: Provisioning status of the managed application.
    readOnly: true
    enum:
    - NotSpecified
    - Accepted
    - Running
    - Deleting
    - Deleted
    - Canceled
    - Failed
    - Succeeded
    - Updating
    type: string
    x-ms-enum:
      name: ProvisioningState
      modelAsString: true
  JitSchedulingType:
    description: The JIT request scheduling type.
    enum:
    - NotSpecified
    - Once
    - Recurring
    type: string
    x-ms-enum:
      name: JitSchedulingType
      modelAsString: true
  JitRequestPatchable:
    type: object
    properties:
      tags:
        type: object
        additionalProperties:
          type: string
        description: Jit request tags
    description: Information about JIT request.
  JitAuthorizationPolicies:
    type: object
    properties:
      principalId:
        type: string
        description: The the principal id that will be granted JIT access.
      roleDefinitionId:
        type: string
        description: The role definition id that will be granted to the Principal.
    required:
    - principalId
    - roleDefinitionId
    description: The JIT authorization policies.
  JitSchedulingPolicy:
    type: object
    properties:
      type:
        $ref: '#/definitions/JitSchedulingType'
        description: The type of JIT schedule.
      duration:
        type: string
        format: duration
        title: The required duration of the JIT request.
      startTime:
        type: string
        format: date-time
        description: The start time of the request.
    required:
    - type
    - duration
    - startTime
    description: The JIT scheduling policies.
  JitRequestState:
    description: The JIT request state.
    readOnly: true
    enum:
    - NotSpecified
    - Pending
    - Approved
    - Denied
    - Failed
    - Canceled
    - Expired
    - Timeout
    type: string
    x-ms-enum:
      name: JitRequestState
      modelAsString: true
parameters:
  JitRequestNameParameter:
    name: jitRequestName
    in: path
    required: true
    type: string
    description: The name of the JIT request.
    x-ms-parameter-location: method
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
