swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector IngestionStatus API
schemes:
- https
tags:
- name: IngestionStatus
paths:
  /dataFeeds/{dataFeedId}/ingestionStatus/query:
    post:
      tags:
      - IngestionStatus
      summary: Microsoft Azure Get Data Ingestion Status By Data Feed
      operationId: microsoftAzureGetdatafeedingestionstatus
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: path
        name: dataFeedId
        description: The data feed unique id
        required: true
        type: string
        format: uuid
      - in: query
        name: $skip
        description: for paging, skipped number
        type: integer
        format: int32
      - in: query
        name: $maxpagesize
        description: the maximum number of items in one page
        type: integer
        format: int32
      - in: body
        name: body
        description: The query time range
        required: true
        schema:
          $ref: '#/definitions/IngestionStatusQueryOptions'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/IngestionStatusList'
        default:
          description: Client error or server error (4xx or 5xx)
          schema:
            $ref: '#/definitions/ErrorCode'
      x-ms-pageable:
        nextLinkName: '@nextLink'
      x-ms-examples:
        Get data ingestion status by data feed:
          $ref: ./examples/getDataFeedIngestionStatus.json
      description: Needs a more full description created.
  /dataFeeds/{dataFeedId}/ingestionProgress/reset:
    post:
      tags:
      - IngestionStatus
      summary: Microsoft Azure Reset Data Ingestion Status By Data Feed To Backfill Data
      operationId: microsoftAzureResetdatafeedingestionstatus
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: path
        name: dataFeedId
        description: The data feed unique id
        required: true
        type: string
        format: uuid
      - in: body
        name: body
        description: The backfill time range
        required: true
        schema:
          $ref: '#/definitions/IngestionProgressResetOptions'
      responses:
        '204':
          description: Success
        default:
          description: Client error or server error (4xx or 5xx)
          schema:
            $ref: '#/definitions/ErrorCode'
      x-ms-examples:
        Reset data ingestion status by data feed to backfill data:
          $ref: ./examples/resetDataFeedIngestionStatus.json
      description: Needs a more full description created.
  /dataFeeds/{dataFeedId}/ingestionProgress:
    get:
      tags:
      - IngestionStatus
      summary: Microsoft Azure Get Data Last Success Ingestion Job Timestamp By Data Feed
      operationId: microsoftAzureGetingestionprogress
      produces:
      - application/json
      parameters:
      - in: path
        name: dataFeedId
        description: The data feed unique id
        required: true
        type: string
        format: uuid
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/DataFeedIngestionProgress'
        default:
          description: Client error or server error (4xx or 5xx)
          schema:
            $ref: '#/definitions/ErrorCode'
      x-ms-examples:
        Get data last success ingestion job timestamp by data feed:
          $ref: ./examples/getIngestionProgress.json
      description: Needs a more full description created.
definitions:
  IngestionStatus:
    type: object
    properties:
      timestamp:
        format: date-time
        description: data slice timestamp.
        type: string
        readOnly: true
      status:
        description: latest ingestion task status for this data slice.
        enum:
        - NotStarted
        - Scheduled
        - Running
        - Succeeded
        - Failed
        - NoData
        - Error
        - Paused
        type: string
        readOnly: true
        x-ms-enum:
          name: IngestionStatusType
          modelAsString: true
      message:
        description: the trimmed message of last ingestion job.
        type: string
        readOnly: true
  IngestionStatusQueryOptions:
    required:
    - endTime
    - startTime
    type: object
    properties:
      startTime:
        format: date-time
        description: the start point of time range to query data ingestion status.
        type: string
      endTime:
        format: date-time
        description: the end point of time range to query data ingestion status.
        type: string
    example:
      startTime: '2020-01-01T00:00:00Z'
      endTime: '2020-02-01T00:00:00Z'
  ErrorCode:
    type: object
    properties:
      message:
        type: string
      code:
        type: string
  IngestionProgressResetOptions:
    required:
    - endTime
    - startTime
    type: object
    properties:
      startTime:
        format: date-time
        description: the start point of time range to reset data ingestion status.
        type: string
      endTime:
        format: date-time
        description: the end point of time range to reset data ingestion status.
        type: string
    example:
      startTime: '2020-01-01T00:00:00Z'
      endTime: '2020-02-01T00:00:00Z'
  DataFeedIngestionProgress:
    type: object
    properties:
      latestSuccessTimestamp:
        format: date-time
        description: "the timestamp of latest success ingestion job.\r\nnull indicates not available"
        type: string
        readOnly: true
      latestActiveTimestamp:
        format: date-time
        description: "the timestamp of latest ingestion job with status update.\r\nnull indicates not available"
        type: string
        readOnly: true
  IngestionStatusList:
    type: object
    properties:
      '@nextLink':
        type: string
        readOnly: true
      value:
        type: array
        items:
          $ref: '#/definitions/IngestionStatus'
        readOnly: true
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
