swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector SolutionsController API
schemes:
- https
tags:
- name: SolutionsController
paths:
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Migrate/migrateProjects/{migrateProjectName}/solutions/{solutionName}
  : get:
      tags:
      - SolutionsController
      summary: Microsoft Azure Gets A Solution In The Migrate Project
      operationId: microsoftAzureSolutionscontrollerGetsolution
      parameters:
      - $ref: ../../../../../../common-types/resource-management/v3/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../../common-types/resource-management/v3/types.json#/parameters/ResourceGroupNameParameter
      - $ref: '#/parameters/migrateProjectName'
      - $ref: '#/parameters/solutionName'
      - $ref: ../../../../../../common-types/resource-management/v3/types.json#/parameters/ApiVersionParameter
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Solution'
        default:
          description: An unexpected error response.
          schema:
            $ref: ../../../../../../common-types/resource-management/v3/types.json#/definitions/ErrorResponse
      deprecated: false
      x-ms-examples:
        SolutionsController_GetSolution_MaximumSet_Gen:
          $ref: ./examples/SolutionsController_GetSolution_MaximumSet_Gen.json
        SolutionsController_GetSolution_MinimumSet_Gen:
          $ref: ./examples/SolutionsController_GetSolution_MinimumSet_Gen.json
      description: Needs a more full description created.
    put:
      tags:
      - SolutionsController
      summary: Microsoft Azure Creates A Solution In The Migrate Project
      operationId: microsoftAzureSolutionscontrollerCreate
      parameters:
      - $ref: ../../../../../../common-types/resource-management/v3/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../../common-types/resource-management/v3/types.json#/parameters/ResourceGroupNameParameter
      - $ref: '#/parameters/migrateProjectName'
      - $ref: '#/parameters/solutionName'
      - $ref: ../../../../../../common-types/resource-management/v3/types.json#/parameters/ApiVersionParameter
      - name: solutionInput
        in: body
        description: The input for the solution.
        required: true
        schema:
          $ref: '#/definitions/Solution'
      responses:
        '200':
          description: ARM create or update operation completed successfully.
          schema:
            $ref: '#/definitions/Solution'
        '201':
          description: ARM create or update operation completed successfully.
          headers:
            Retry-After:
              description: The Retry-After header can indicate how long the client should wait before polling the operation status.
              type: integer
              format: int32
          schema:
            $ref: '#/definitions/Solution'
        default:
          description: An unexpected error response.
          schema:
            $ref: ../../../../../../common-types/resource-management/v3/types.json#/definitions/ErrorResponse
      deprecated: false
      x-ms-examples:
        SolutionsController_Create_MaximumSet_Gen:
          $ref: ./examples/SolutionsController_Create_MaximumSet_Gen.json
        SolutionsController_Create_MinimumSet_Gen:
          $ref: ./examples/SolutionsController_Create_MinimumSet_Gen.json
      description: Needs a more full description created.
    patch:
      tags:
      - SolutionsController
      summary: Microsoft Azure Update Solution
      description: Update a solution with specified name. Supports partial updates, for example only tags can be provided.
      operationId: microsoftAzureSolutionscontrollerUpdate
      parameters:
      - $ref: ../../../../../../common-types/resource-management/v3/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../../common-types/resource-management/v3/types.json#/parameters/ResourceGroupNameParameter
      - $ref: '#/parameters/migrateProjectName'
      - $ref: '#/parameters/solutionName'
      - $ref: ../../../../../../common-types/resource-management/v3/types.json#/parameters/ApiVersionParameter
      - name: solutionInput
        in: body
        description: The input for the solution.
        required: true
        schema:
          $ref: '#/definitions/Solution'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Solution'
        default:
          description: An unexpected error response.
          schema:
            $ref: ../../../../../../common-types/resource-management/v3/types.json#/definitions/ErrorResponse
      deprecated: false
      x-ms-examples:
        SolutionsController_Update_MaximumSet_Gen:
          $ref: ./examples/SolutionsController_Update_MaximumSet_Gen.json
        SolutionsController_Update_MinimumSet_Gen:
          $ref: ./examples/SolutionsController_Update_MinimumSet_Gen.json
    delete:
      tags:
      - SolutionsController
      summary: Microsoft Azure Delete The Solution
      description: Delete the solution. Deleting non-existent project is a no-operation.
      operationId: microsoftAzureSolutionscontrollerDeletesolution
      parameters:
      - $ref: ../../../../../../common-types/resource-management/v3/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../../common-types/resource-management/v3/types.json#/parameters/ResourceGroupNameParameter
      - $ref: '#/parameters/migrateProjectName'
      - $ref: '#/parameters/solutionName'
      - $ref: ../../../../../../common-types/resource-management/v3/types.json#/parameters/ApiVersionParameter
      responses:
        '200':
          description: Resource deleted successfully.
          schema:
            $ref: '#/definitions/Object'
        '204':
          description: Resource deleted successfully.
          schema:
            $ref: '#/definitions/Object'
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: ../../../../../../common-types/resource-management/v3/types.json#/definitions/ErrorResponse
      deprecated: false
      x-ms-examples:
        SolutionsController_DeleteSolution_MaximumSet_Gen:
          $ref: ./examples/SolutionsController_DeleteSolution_MaximumSet_Gen.json
        SolutionsController_DeleteSolution_MinimumSet_Gen:
          $ref: ./examples/SolutionsController_DeleteSolution_MinimumSet_Gen.json
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Migrate/migrateProjects/{migrateProjectName}/solutions
  : get:
      tags:
      - SolutionsController
      summary: Microsoft Azure Gets The List Of Solutions In The Migrate Project
      operationId: microsoftAzureSolutionscontrollerListsolutions
      parameters:
      - $ref: ../../../../../../common-types/resource-management/v3/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../../common-types/resource-management/v3/types.json#/parameters/ResourceGroupNameParameter
      - $ref: '#/parameters/migrateProjectName'
      - $ref: ../../../../../../common-types/resource-management/v3/types.json#/parameters/ApiVersionParameter
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/SolutionsCollection'
        default:
          description: An unexpected error response.
          schema:
            $ref: ../../../../../../common-types/resource-management/v3/types.json#/definitions/ErrorResponse
      deprecated: false
      x-ms-pageable:
        nextLinkName: nextLink
      x-ms-examples:
        SolutionsController_ListSolutions_MaximumSet_Gen:
          $ref: ./examples/SolutionsController_ListSolutions_MaximumSet_Gen.json
        SolutionsController_ListSolutions_MinimumSet_Gen:
          $ref: ./examples/SolutionsController_ListSolutions_MinimumSet_Gen.json
      description: Needs a more full description created.
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Migrate/migrateProjects/{migrateProjectName}/solutions/{solutionName}/getConfig
  : post:
      tags:
      - SolutionsController
      summary: Microsoft Azure Gets The Config For The Solution In The Migrate Project
      operationId: microsoftAzureSolutionscontrollerGetconfig
      parameters:
      - $ref: ../../../../../../common-types/resource-management/v3/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../../common-types/resource-management/v3/types.json#/parameters/ResourceGroupNameParameter
      - $ref: '#/parameters/migrateProjectName'
      - $ref: '#/parameters/solutionName'
      - $ref: ../../../../../../common-types/resource-management/v3/types.json#/parameters/ApiVersionParameter
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/SolutionConfig'
        default:
          description: An unexpected error response.
          schema:
            $ref: ../../../../../../common-types/resource-management/v3/types.json#/definitions/ErrorResponse
      deprecated: false
      x-ms-examples:
        SolutionsController_GetConfig_MaximumSet_Gen:
          $ref: ./examples/SolutionsController_GetConfig_MaximumSet_Gen.json
        SolutionsController_GetConfig_MinimumSet_Gen:
          $ref: ./examples/SolutionsController_GetConfig_MinimumSet_Gen.json
      description: Needs a more full description created.
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Migrate/migrateProjects/{migrateProjectName}/solutions/{solutionName}/cleanupData
  : post:
      tags:
      - SolutionsController
      summary: Microsoft Azure Cleanup The Solution Data In The Migrate Project
      operationId: microsoftAzureSolutionscontrollerCleanupdata
      parameters:
      - $ref: ../../../../../../common-types/resource-management/v3/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../../common-types/resource-management/v3/types.json#/parameters/ResourceGroupNameParameter
      - $ref: '#/parameters/migrateProjectName'
      - $ref: '#/parameters/solutionName'
      - $ref: ../../../../../../common-types/resource-management/v3/types.json#/parameters/ApiVersionParameter
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Object'
        default:
          description: An unexpected error response.
          schema:
            $ref: ../../../../../../common-types/resource-management/v3/types.json#/definitions/ErrorResponse
      deprecated: false
      x-ms-examples:
        SolutionsController_CleanupData_MaximumSet_Gen:
          $ref: ./examples/SolutionsController_CleanupData_MaximumSet_Gen.json
        SolutionsController_CleanupData_MinimumSet_Gen:
          $ref: ./examples/SolutionsController_CleanupData_MinimumSet_Gen.json
      description: Needs a more full description created.
definitions:
  SolutionDetails:
    description: Class representing the details of the solution.
    type: object
    properties:
      groupCount:
        format: int32
        description: Gets or sets the count of groups reported by the solution.
        type: integer
      assessmentCount:
        format: int32
        description: Gets or sets the count of assessments reported by the solution.
        type: integer
      extendedDetails:
        description: Gets or sets the extended details reported by the solution.
        type: object
        additionalProperties:
          type: string
  SolutionsCollection:
    description: Collection of solutions.
    type: object
    properties:
      value:
        description: Gets or sets the list of solutions.
        type: array
        items:
          $ref: '#/definitions/Solution'
      nextLink:
        description: Gets or sets the value of next link.
        type: string
  SolutionSummary:
    description: The solution summary class.
    type: object
    properties:
      instanceType:
        description: Gets the Instance type.
        type: string
        required:
        - value
        readOnly: true
  Solution:
    description: Solution REST Resource.
    x-ms-azure-resource: true
    type: object
    properties:
      id:
        description: Gets the relative URL to get to this REST resource.
        type: string
        readOnly: true
      name:
        description: Gets the name of this REST resource.
        type: string
        readOnly: true
      type:
        description: Gets the type of this REST resource.
        type: string
        readOnly: true
      etag:
        description: Gets or sets the ETAG for optimistic concurrency control.
        type: string
      properties:
        $ref: '#/definitions/SolutionProperties'
        description: Gets or sets the properties of the solution.
  Object:
    description: Defines generic object.
    type: object
    properties: {}
  SolutionConfig:
    description: Class representing the config for the solution in the migrate project.
    type: object
    properties:
      publisherSasUri:
        description: Gets or sets the publisher sas uri for the solution.
        type: string
  SolutionProperties:
    description: Class for solution properties.
    type: object
    properties:
      tool:
        description: Gets or sets the tool being used in the solution.
        enum:
        - ServerDiscovery
        - ServerAssessment
        - ServerMigration
        - Cloudamize
        - Turbonomic
        - Zerto
        - CorentTech
        - ServerAssessmentV1
        - ServerMigration_Replication
        - Carbonite
        - DataMigrationAssistant
        - DatabaseMigrationService
        - Device42
        - JetStream
        - RackWare
        - UnifyCloud
        - Flexera
        - ServerDiscovery_Import
        - Lakeside
        - AppServiceMigrationAssistant
        - Movere
        - CloudSphere
        - Modernization
        - ServerMigration_DataReplication
        - Unknown
        x-ms-enum:
          name: tool
          modelAsString: true
        type: string
      purpose:
        description: Gets or sets the purpose of the solution.
        enum:
        - Discovery
        - Assessment
        - Migration
        x-ms-enum:
          name: purpose
          modelAsString: true
        type: string
      goal:
        description: Gets or sets the goal of the solution.
        enum:
        - Servers
        - Databases
        - DesktopVirtualization
        - WebApplications
        - DataCenter
        x-ms-enum:
          name: goal
          modelAsString: true
        type: string
      status:
        description: Gets or sets the current status of the solution.
        enum:
        - Inactive
        - Active
        x-ms-enum:
          name: status
          modelAsString: true
        type: string
      cleanupState:
        description: Gets or sets the cleanup state of the solution.
        enum:
        - None
        - Started
        - InProgress
        - Completed
        - Failed
        x-ms-enum:
          name: cleanupState
          modelAsString: true
        type: string
      summary:
        $ref: '#/definitions/SolutionSummary'
        description: Gets or sets the summary of the solution.
      details:
        $ref: '#/definitions/SolutionDetails'
        description: Gets or sets the details of the solution.
parameters:
  solutionName:
    name: solutionName
    description: Unique name of a migration solution within a migrate project.
    type: string
    in: path
    x-ms-parameter-location: method
    required: true
    pattern: ^[a-zA-Z0-9-]{3,24}$
  migrateProjectName:
    name: migrateProjectName
    description: Name of the Azure Migrate project.
    type: string
    in: path
    x-ms-parameter-location: method
    required: true
    pattern: ^[a-zA-Z0-9-]{3,24}$
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
