swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector ConfigurationProfileAssignments API
schemes:
- https
tags:
- name: ConfigurationProfileAssignments
paths:
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/virtualMachines/{vmName}/providers/Microsoft.Automanage/configurationProfileAssignments/{configurationProfileAssignmentName}
  : put:
      tags:
      - ConfigurationProfileAssignments
      operationId: microsoftAzureConfigurationprofileassignmentsCreateorupdate
      description: Creates an association between a VM and Automanage configuration profile
      x-ms-examples:
        Create or update configuration profile assignment:
          $ref: ./examples/createOrUpdateConfigurationProfileAssignment.json
      parameters:
      - name: configurationProfileAssignmentName
        in: path
        required: true
        type: string
        description: Name of the configuration profile assignment. Only default is supported.
      - name: parameters
        in: body
        required: true
        schema:
          $ref: '#/definitions/ConfigurationProfileAssignment'
        description: Parameters supplied to the create or update configuration profile assignment.
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/ResourceGroupNameParameter
      - $ref: '#/parameters/VmNameParameter'
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/ApiVersionParameter
      responses:
        '200':
          description: OK. The configuration profile assignment for the VM was updated successfully.
          schema:
            $ref: '#/definitions/ConfigurationProfileAssignment'
        '201':
          description: Created. The Automanage configuration profile assignment for the VM was created successfully.
          schema:
            $ref: '#/definitions/ConfigurationProfileAssignment'
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: ../../../../../common-types/resource-management/v2/types.json#/definitions/ErrorResponse
      x-ms-long-running-operation: false
      produces:
      - application/json
      consumes:
      - application/json
      summary: Microsoft Azure Put Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Compute Virtualmachines Vmname Providers Microsoft Automanage Configurationprofileassignments Configurationprofileassignmentname
    get:
      tags:
      - ConfigurationProfileAssignments
      operationId: microsoftAzureConfigurationprofileassignmentsGet
      description: Get information about a configuration profile assignment
      x-ms-examples:
        Get a configuration profile assignment:
          $ref: ./examples/getConfigurationProfileAssignment.json
      parameters:
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/ResourceGroupNameParameter
      - name: configurationProfileAssignmentName
        in: path
        required: true
        type: string
        description: The configuration profile assignment name.
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/SubscriptionIdParameter
      - $ref: '#/parameters/VmNameParameter'
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/ApiVersionParameter
      responses:
        '200':
          description: OK. The configuration profile assignment was returned successfully.
          schema:
            $ref: '#/definitions/ConfigurationProfileAssignment'
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: ../../../../../common-types/resource-management/v2/types.json#/definitions/ErrorResponse
      produces:
      - application/json
      consumes:
      - application/json
      summary: Microsoft Azure Get Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Compute Virtualmachines Vmname Providers Microsoft Automanage Configurationprofileassignments Configurationprofileassignmentname
    delete:
      tags:
      - ConfigurationProfileAssignments
      operationId: microsoftAzureConfigurationprofileassignmentsDelete
      description: Delete a configuration profile assignment
      x-ms-examples:
        Delete an configuration profile assignment:
          $ref: ./examples/deleteConfigurationProfileAssignment.json
      parameters:
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/ResourceGroupNameParameter
      - name: configurationProfileAssignmentName
        in: path
        required: true
        type: string
        description: Name of the configuration profile assignment
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/SubscriptionIdParameter
      - $ref: '#/parameters/VmNameParameter'
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/ApiVersionParameter
      responses:
        '200':
          description: OK
        '204':
          description: OK
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: ../../../../../common-types/resource-management/v2/types.json#/definitions/ErrorResponse
      x-ms-long-running-operation: false
      produces:
      - application/json
      consumes:
      - application/json
      summary: Microsoft Azure Delete Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Compute Virtualmachines Vmname Providers Microsoft Automanage Configurationprofileassignments Configurationprofileassignmentname
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/virtualMachines/{vmName}/providers/Microsoft.Automanage/configurationProfileAssignments
  : get:
      tags:
      - ConfigurationProfileAssignments
      operationId: microsoftAzureConfigurationprofileassignmentsListbyvirtualmachines
      description: Get list of configuration profile assignments
      x-ms-examples:
        List configuration profile assignments by resourceGroup and virtual machine:
          $ref: ./examples/listConfigurationProfileAssignmentsByVirtualMachines.json
      parameters:
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/ResourceGroupNameParameter
      - $ref: '#/parameters/VmNameParameter'
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/ApiVersionParameter
      responses:
        '200':
          description: OK. The list of configuration profile assignments were returned successfully.
          schema:
            $ref: '#/definitions/ConfigurationProfileAssignmentList'
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: ../../../../../common-types/resource-management/v2/types.json#/definitions/ErrorResponse
      x-ms-pageable:
        nextLinkName: null
      produces:
      - application/json
      consumes:
      - application/json
      summary: Microsoft Azure Get Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Compute Virtualmachines Vmname Providers Microsoft Automanage Configurationprofileassignments
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Automanage/configurationProfileAssignments
  : get:
      tags:
      - ConfigurationProfileAssignments
      operationId: microsoftAzureConfigurationprofileassignmentsList
      description: Get list of configuration profile assignments
      x-ms-examples:
        List configuration profile assignments by resourceGroup:
          $ref: ./examples/listConfigurationProfileAssignmentsByResourceGroup.json
      parameters:
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/ResourceGroupNameParameter
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/ApiVersionParameter
      responses:
        '200':
          description: OK. The list of configuration profile assignments were returned successfully.
          schema:
            $ref: '#/definitions/ConfigurationProfileAssignmentList'
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: ../../../../../common-types/resource-management/v2/types.json#/definitions/ErrorResponse
      x-ms-pageable:
        nextLinkName: null
      produces:
      - application/json
      consumes:
      - application/json
      summary: Microsoft Azure Get Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Automanage Configurationprofileassignments
  /subscriptions/{subscriptionId}/providers/Microsoft.Automanage/configurationProfileAssignments:
    get:
      tags:
      - ConfigurationProfileAssignments
      operationId: microsoftAzureConfigurationprofileassignmentsListbysubscription
      description: Get list of configuration profile assignments under a given subscription
      x-ms-examples:
        List configuration profile assignments by subscription:
          $ref: ./examples/listConfigurationProfileAssignmentsBySubscription.json
      parameters:
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/ApiVersionParameter
      responses:
        '200':
          description: OK. The list of configuration profile assignments were returned successfully.
          schema:
            $ref: '#/definitions/ConfigurationProfileAssignmentList'
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: ../../../../../common-types/resource-management/v2/types.json#/definitions/ErrorResponse
      x-ms-pageable:
        nextLinkName: null
      produces:
      - application/json
      consumes:
      - application/json
      summary: Microsoft Azure Get Subscriptions Subscriptionid Providers Microsoft Automanage Configurationprofileassignments
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.HybridCompute/machines/{machineName}/providers/Microsoft.Automanage/configurationProfileAssignments
  : get:
      tags:
      - ConfigurationProfileAssignments
      operationId: microsoftAzureConfigurationprofileassignmentsListbymachinename
      description: Get list of configuration profile assignments
      x-ms-examples:
        List configuration profile assignments by resourceGroup and machine:
          $ref: ./examples/listConfigurationProfileAssignmentsByMachineName.json
      parameters:
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/ResourceGroupNameParameter
      - $ref: '#/parameters/MachineNameParameter'
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/ApiVersionParameter
      responses:
        '200':
          description: OK. The list of configuration profile assignments were returned successfully.
          schema:
            $ref: '#/definitions/ConfigurationProfileAssignmentList'
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: ../../../../../common-types/resource-management/v2/types.json#/definitions/ErrorResponse
      x-ms-pageable:
        nextLinkName: null
      produces:
      - application/json
      consumes:
      - application/json
      summary: Microsoft Azure Get Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Hybridcompute Machines Machinename Providers Microsoft Automanage Configurationprofileassignments
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.AzureStackHci/clusters/{clusterName}/providers/Microsoft.Automanage/configurationProfileAssignments
  : get:
      tags:
      - ConfigurationProfileAssignments
      operationId: microsoftAzureConfigurationprofileassignmentsListbyclustername
      description: Get list of configuration profile assignments
      x-ms-examples:
        List configuration profile assignments by resourceGroup and cluster:
          $ref: ./examples/listConfigurationProfileAssignmentsByClusterName.json
      parameters:
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/ResourceGroupNameParameter
      - $ref: '#/parameters/ClusterNameParameter'
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/ApiVersionParameter
      responses:
        '200':
          description: OK. The list of configuration profile assignments were returned successfully.
          schema:
            $ref: '#/definitions/ConfigurationProfileAssignmentList'
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: ../../../../../common-types/resource-management/v2/types.json#/definitions/ErrorResponse
      x-ms-pageable:
        nextLinkName: null
      produces:
      - application/json
      consumes:
      - application/json
      summary: Get Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Azurestackhci Clusters Clustername Providers Microsoft Automanage Configurationprofileassignments
definitions:
  ConfigurationProfileAssignmentList:
    description: The response of the list configuration profile assignment operation.
    type: object
    properties:
      value:
        type: array
        items:
          $ref: '#/definitions/ConfigurationProfileAssignment'
        description: Result of the list configuration profile assignment operation.
  ConfigurationProfileAssignmentProperties:
    description: Automanage configuration profile assignment properties.
    type: object
    properties:
      configurationProfile:
        type: string
        description: The Automanage configurationProfile ARM Resource URI.
      targetId:
        type: string
        description: The target VM resource URI
        readOnly: true
      status:
        type: string
        readOnly: true
        description: The status of onboarding, which only appears in the response.
      profileOverrides:
        $ref: '#/definitions/ConfigurationProfileAssignmentProfileOverrides'
        description: The profileOverrides setting for the configuration profile assignment.
  ConfigurationProfileAssignment:
    description: Configuration profile assignment is an association between a VM and automanage profile configuration.
    type: object
    properties:
      properties:
        x-ms-client-flatten: false
        $ref: '#/definitions/ConfigurationProfileAssignmentProperties'
        description: Properties of the configuration profile assignment.
      systemData:
        $ref: ../../../../../common-types/resource-management/v2/types.json#/definitions/systemData
        readOnly: true
        description: Azure Resource Manager metadata containing createdBy and modifiedBy information.
    allOf:
    - $ref: ../../../../../common-types/resource-management/v2/types.json#/definitions/ProxyResource
  ConfigurationProfileAssignmentProfileOverrides:
    description: Data related to configuration profile assignment profile overrides.
    type: object
    additionalProperties:
      type: object
parameters:
  MachineNameParameter:
    name: machineName
    in: path
    required: true
    type: string
    description: The name of the Arc machine.
    x-ms-parameter-location: method
  VmNameParameter:
    name: vmName
    in: path
    required: true
    type: string
    description: The name of the virtual machine.
    x-ms-parameter-location: method
  ClusterNameParameter:
    name: clusterName
    in: path
    required: true
    type: string
    description: The name of the Arc machine.
    x-ms-parameter-location: method
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
