swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector NetworkSecurityPerimeters API
schemes:
- https
tags:
- name: NetworkSecurityPerimeters
paths:
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/networkSecurityPerimeters/{networkSecurityPerimeterName}
  : parameters:
    - $ref: ./network.json#/parameters/SubscriptionIdParameter
    - $ref: '#/parameters/ResourceGroupNameParameter'
    - $ref: '#/parameters/NetworkSecurityPerimeterNameParameter'
    - $ref: ./network.json#/parameters/ApiVersionParameter
    get:
      tags:
      - NetworkSecurityPerimeters
      operationId: microsoftAzureNetworksecurityperimetersGet
      description: Gets the specified network security perimeter by the name.
      responses:
        '200':
          description: Request is successful. Returns the resulting network security perimeter resource.
          schema:
            $ref: '#/definitions/NetworkSecurityPerimeter'
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: ./network.json#/definitions/CloudError
      x-ms-examples:
        NetworkSecurityPerimeterGet:
          $ref: ./examples/NetworkSecurityPerimeterGet.json
      summary: Microsoft Azure Get Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Network Networksecurityperimeters Networksecurityperimetername
    put:
      tags:
      - NetworkSecurityPerimeters
      operationId: microsoftAzureNetworksecurityperimetersCreateorupdate
      description: Creates or updates a Network Security Perimeter.
      parameters:
      - name: parameters
        in: body
        required: true
        schema:
          $ref: '#/definitions/NetworkSecurityPerimeter'
        description: Parameter supplied to create or update the network security perimeter.
      responses:
        '200':
          description: Resource Updated. Returns the network security perimeter.
          schema:
            $ref: '#/definitions/NetworkSecurityPerimeter'
        '201':
          description: Resource Created. Returns the network security perimeter.
          schema:
            $ref: '#/definitions/NetworkSecurityPerimeter'
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: ./network.json#/definitions/CloudError
      x-ms-examples:
        Put Network Security Perimeter:
          $ref: ./examples/NetworkSecurityPerimeterPut.json
      summary: Microsoft Azure Put Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Network Networksecurityperimeters Networksecurityperimetername
    delete:
      tags:
      - NetworkSecurityPerimeters
      operationId: microsoftAzureNetworksecurityperimetersDelete
      description: Deletes a network security perimeter.
      responses:
        '200':
          description: Delete Succeed.
        '204':
          description: Request successful. The resource does not exist.
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: ./network.json#/definitions/CloudError
      x-ms-examples:
        NetworkSecurityPerimeterDelete:
          $ref: ./examples/NetworkSecurityPerimeterDelete.json
      summary: Microsoft Azure Delete Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Network Networksecurityperimeters Networksecurityperimetername
    patch:
      tags:
      - NetworkSecurityPerimeters
      operationId: microsoftAzureNetworksecurityperimetersPatch
      description: Patch Tags for a Network Security Perimeter.
      parameters:
      - name: parameters
        in: body
        required: true
        schema:
          $ref: '#/definitions/UpdateTagsRequest'
        description: Parameter supplied to the network security perimeter.
      responses:
        '200':
          description: Request is successful. Returns the resulting network security perimeter resource.
          schema:
            $ref: '#/definitions/NetworkSecurityPerimeter'
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: ./network.json#/definitions/CloudError
      x-ms-examples:
        Patch Network Security Perimeter:
          $ref: ./examples/NetworkSecurityPerimeterPatch.json
      summary: Microsoft Azure Patch Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Network Networksecurityperimeters Networksecurityperimetername
  /subscriptions/{subscriptionId}/providers/Microsoft.Network/networkSecurityPerimeters:
    get:
      tags:
      - NetworkSecurityPerimeters
      operationId: microsoftAzureNetworksecurityperimetersListbysubscription
      description: List all network security perimeters in a subscription.
      parameters:
      - $ref: ./network.json#/parameters/SubscriptionIdParameter
      - $ref: ./network.json#/parameters/ApiVersionParameter
      - $ref: '#/parameters/ListTopParameter'
      - $ref: '#/parameters/ListSkipTokenParameter'
      responses:
        '200':
          description: Request is successful. Returns the list of the network security perimeters.
          schema:
            $ref: '#/definitions/NetworkSecurityPerimeterListResult'
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: ./network.json#/definitions/CloudError
      x-ms-pageable:
        nextLinkName: nextLink
      x-ms-examples:
        NetworkSecurityPerimetersList:
          $ref: ./examples/NetworkSecurityPerimeterListAll.json
      summary: Microsoft Azure Get Subscriptions Subscriptionid Providers Microsoft Network Networksecurityperimeters
  /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/networkSecurityPerimeters:
    get:
      tags:
      - NetworkSecurityPerimeters
      operationId: microsoftAzureNetworksecurityperimetersList
      description: List network security perimeters in a resource group.
      x-ms-pageable:
        nextLinkName: nextLink
      parameters:
      - $ref: ./network.json#/parameters/SubscriptionIdParameter
      - $ref: '#/parameters/ResourceGroupNameParameter'
      - $ref: ./network.json#/parameters/ApiVersionParameter
      - $ref: '#/parameters/ListTopParameter'
      - $ref: '#/parameters/ListSkipTokenParameter'
      responses:
        '200':
          description: Request is successful. Returns a list of network security perimeters.
          schema:
            $ref: '#/definitions/NetworkSecurityPerimeterListResult'
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: ./network.json#/definitions/CloudError
      x-ms-examples:
        List Network Security Perimeter:
          $ref: ./examples/NetworkSecurityPerimeterList.json
      summary: Microsoft Azure Get Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Network Networksecurityperimeters
definitions:
  NSPProvisioningState:
    type: string
    readOnly: true
    description: The current provisioning state.
    enum:
    - Succeeded
    - Creating
    - Updating
    - Deleting
    - Accepted
    - Failed
    x-ms-enum:
      name: nspProvisioningState
      modelAsString: true
  NetworkSecurityPerimeterListResult:
    type: object
    properties:
      value:
        type: array
        items:
          $ref: '#/definitions/NetworkSecurityPerimeter'
        description: Gets a page of NetworkSecurityPerimeter
      nextLink:
        type: string
        description: Gets the URL to get the next page of results.
    description: Result of the request to list NetworkSecurityPerimeter. It contains a list of network security perimeters and a URL link to get the next set of results.
  NetworkSecurityPerimeter:
    type: object
    properties:
      properties:
        x-ms-client-flatten: true
        $ref: '#/definitions/NetworkSecurityPerimeterProperties'
        description: The network security perimeter properties
      location:
        type: string
        description: The location in which NSP is created.
      name:
        type: string
        description: The name of the resource that is unique within a resource group. This name can be used to access the resource.
      id:
        readOnly: true
        type: string
        description: Network security perimeter identifier.
      type:
        readOnly: true
        type: string
        description: Resource type.
    allOf:
    - $ref: ./network.json#/definitions/Resource
    description: The Network Security Perimeter resource
  NetworkSecurityPerimeterProperties:
    type: object
    properties:
      provisioningState:
        readOnly: true
        $ref: '#/definitions/NSPProvisioningState'
        description: The provisioning state of the scope assignment resource.
      perimeterGuid:
        readOnly: true
        type: string
        description: perimeter guid of the network security perimeter.
    description: Properties of network security perimeter.
  UpdateTagsRequest:
    type: object
    properties:
      id:
        readOnly: true
        type: string
        description: Network security perimeter identifier.
      tags:
        type: object
        additionalProperties:
          type: string
        description: List of tags for Network Security Perimeter
    description: Update tags request.
parameters:
  ResourceGroupNameParameter:
    name: resourceGroupName
    in: path
    required: true
    type: string
    description: The name of the resource group.
    x-ms-parameter-location: method
  ListTopParameter:
    name: $top
    description: An optional query parameter which specifies the maximum number of records to be returned by the server.
    in: query
    required: false
    type: integer
    format: int32
    minimum: 1
    maximum: 20
    x-ms-parameter-location: method
  NetworkSecurityPerimeterNameParameter:
    name: networkSecurityPerimeterName
    in: path
    required: true
    type: string
    description: The name of the network security perimeter.
    x-ms-parameter-location: method
  ListSkipTokenParameter:
    name: $skipToken
    description: SkipToken is only used if a previous operation returned a partial result. If a previous response contains a nextLink element, the value of the nextLink element will include a skipToken parameter that specifies a starting point to use for subsequent calls.
    in: query
    required: false
    type: string
    x-ms-parameter-location: method
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
