openapi: 3.2.0
info:
  title: Microsoft Azure ARG Query Generation API
  version: 2023-09-01-preview
  x-typespec-generated:
  - emitter: '@azure-tools/typespec-autorest'
tags:
- name: QueryGeneration
paths:
  /providers/Microsoft.ResourceGraph/generateQuery:
    post:
      operationId: microsoftAzureQueryGeneratequery
      tags:
      - QueryGeneration
      description: Generates ARG query for a given user prompt.
      parameters:
      - $ref: '#/components/parameters/ApiVersionParameter'
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryGenerationResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      x-ms-examples:
        Succeeded ARG Query Generation:
          $ref: ./examples/ResourcesGenerateQuery.json
        Failed ARG Query Generation:
          $ref: ./examples/ResourcesGenerateQueryNoGeneration.json
        ARG Query Generation with history:
          $ref: ./examples/ResourcesGenerateQueryWithHistory.json
      summary: Microsoft Azure Post Providers Microsoft Resourcegraph Generatequery
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryGenerationRequest'
        required: true
components:
  schemas:
    QueryGenerationRequest:
      type: object
      description: Query Generation Request
      properties:
        history:
          type: array
          description: A collection of chat history to provide context in query generation
          items:
            $ref: '#/components/schemas/HistoryContext'
          x-ms-identifiers: []
        prompt:
          type: string
          description: Prompt text from user
      required:
      - prompt
    StatusResponse:
      type: object
      description: Status
      properties:
        category:
          $ref: '#/components/schemas/StatusCategory'
          description: Status category for query generation result
        message:
          type: string
          description: Status message for query generation result
      required:
      - category
      - message
    QueryGenerationResponse:
      type: object
      description: Query Generation Response
      properties:
        query:
          type: string
          description: Query generated for a given user prompt text
        status:
          $ref: '#/components/schemas/StatusResponse'
          description: Status for the query generation result
      required:
      - query
      - status
    Role:
      type: string
      description: The role which generates a specific message. Restricted to the user or assistant role.
      enum:
      - user
      - assistant
      - system
      x-ms-enum:
        name: Role
        modelAsString: true
        values:
        - name: user
          value: user
          description: If a message was generated by a human, the role should be assigned user
        - name: assistant
          value: assistant
          description: If a message was generated by ARG Query Generation service, then the role should be assistant
        - name: system
          value: system
          description: If a message provides high level instructions for the query generation, then the role should be system
    Error:
      title: Error info.
      type: object
      description: Error details.
      properties:
        code:
          type: string
          description: Error code identifying the specific error.
        message:
          type: string
          description: A human readable error message.
        details:
          type: array
          description: Error details
          items:
            $ref: '#/components/schemas/ErrorDetails'
      required:
      - code
      - message
    ErrorResponse:
      title: Error response.
      type: object
      description: An error response from the API.
      properties:
        error:
          $ref: '#/components/schemas/Error'
          description: Error information.
      required:
      - error
    HistoryContext:
      type: object
      description: History content generated by a user, assistant or system role
      properties:
        content:
          type: string
          description: Content generated by a given role
        role:
          $ref: '#/components/schemas/Role'
          description: Role which generates the content e.g., user, assistant or system
      required:
      - content
      - role
    StatusCategory:
      type: string
      description: Status Category
      enum:
      - Succeeded
      - Failed
      x-ms-enum:
        name: StatusCategory
        modelAsString: true
        values:
        - name: Succeeded
          value: Succeeded
          description: Succeeded when query was generated successfully
        - name: Failed
          value: Failed
          description: Failed when query was not generated
    ErrorDetails:
      title: Error details.
      type: object
      properties:
        code:
          type: string
          description: Error code identifying the specific error.
        message:
          type: string
          description: A human readable error message.
      additionalProperties:
        type: object
      required:
      - code
      - message
  parameters:
    ApiVersionParameter:
      name: api-version
      in: query
      required: true
      description: Api Version.
      schema:
        type: string
