swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector DedicatedCloudServices API
schemes:
- https
tags:
- name: DedicatedCloudServices
paths:
  /subscriptions/{subscriptionId}/providers/Microsoft.VMwareCloudSimple/dedicatedCloudServices:
    get:
      description: Returns list of dedicated cloud services within a subscription
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - DedicatedCloudServices
      summary: Microsoft Azure Implements List Of Dedicatedcloudservice Objects Within Subscription Method
      operationId: microsoftAzureDedicatedcloudservicesListbysubscription
      parameters:
      - $ref: '#/parameters/subscriptionId'
      - $ref: '#/parameters/api-version'
      - type: string
        description: The filter to apply on the list operation
        name: $filter
        in: query
      - type: integer
        format: int32
        description: The maximum number of record sets to return
        name: $top
        in: query
      - type: string
        description: to be used by nextLink implementation
        name: $skipToken
        in: query
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/DedicatedCloudServiceListResponse'
        default:
          description: General Error
          schema:
            $ref: '#/definitions/CSRPError'
      x-ms-examples:
        ListDedicatedCloudServices:
          $ref: ./examples/ListDedicatedCloudServices.json
      x-ms-pageable:
        nextLinkName: nextLink
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.VMwareCloudSimple/dedicatedCloudServices
  : get:
      description: Returns list of dedicated cloud services within a resource group
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - DedicatedCloudServices
      summary: Microsoft Azure Implements List Of Dedicatedcloudservice Objects Within Rg Method
      operationId: microsoftAzureDedicatedcloudservicesListbyresourcegroup
      parameters:
      - $ref: '#/parameters/subscriptionId'
      - $ref: '#/parameters/resourceGroupName'
      - $ref: '#/parameters/api-version'
      - type: string
        description: The filter to apply on the list operation
        name: $filter
        in: query
      - type: integer
        format: int32
        description: The maximum number of record sets to return
        name: $top
        in: query
      - type: string
        description: to be used by nextLink implementation
        name: $skipToken
        in: query
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/DedicatedCloudServiceListResponse'
        default:
          description: General Error
          schema:
            $ref: '#/definitions/CSRPError'
      x-ms-examples:
        ListRGDedicatedCloudServices:
          $ref: ./examples/ListRGDedicatedCloudServices.json
      x-ms-pageable:
        nextLinkName: nextLink
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.VMwareCloudSimple/dedicatedCloudServices/{dedicatedCloudServiceName}
  : get:
      description: Returns Dedicate Cloud Service
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - DedicatedCloudServices
      summary: Microsoft Azure Implements Dedicatedcloudservice Get Method
      operationId: microsoftAzureDedicatedcloudservicesGet
      parameters:
      - $ref: '#/parameters/subscriptionId'
      - $ref: '#/parameters/resourceGroupName'
      - type: string
        description: dedicated cloud Service name
        name: dedicatedCloudServiceName
        in: path
        required: true
      - $ref: '#/parameters/api-version'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/DedicatedCloudService'
        default:
          description: General Error
          schema:
            $ref: '#/definitions/CSRPError'
      x-ms-examples:
        GetDedicatedCloudService:
          $ref: ./examples/GetDedicatedCloudService.json
    put:
      description: Create dedicate cloud service
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - DedicatedCloudServices
      summary: Microsoft Azure Implements Dedicated Cloud Service Put Method
      operationId: microsoftAzureDedicatedcloudservicesCreateorupdate
      parameters:
      - $ref: '#/parameters/subscriptionId'
      - $ref: '#/parameters/resourceGroupName'
      - pattern: ^[a-zA-Z0-9]([-_.a-zA-Z0-9]*[a-zA-Z0-9])?$
        type: string
        description: dedicated cloud Service name
        name: dedicatedCloudServiceName
        in: path
        required: true
      - description: Create Dedicated Cloud Service request
        name: dedicatedCloudServiceRequest
        in: body
        required: true
        schema:
          $ref: '#/definitions/DedicatedCloudService'
      - $ref: '#/parameters/api-version'
      responses:
        '200':
          description: If resource is created or updated successfully, 200 should be returned
          schema:
            $ref: '#/definitions/DedicatedCloudService'
        default:
          description: General Error
          schema:
            $ref: '#/definitions/CSRPError'
      x-ms-examples:
        CreateDedicatedCloudService:
          $ref: ./examples/CreateDedicatedCloudService.json
    delete:
      description: Delete dedicate cloud service
      consumes:
      - application/json
      tags:
      - DedicatedCloudServices
      summary: Microsoft Azure Implements Dedicatedcloudservice Delete Method
      operationId: microsoftAzureDedicatedcloudservicesDelete
      parameters:
      - $ref: '#/parameters/subscriptionId'
      - $ref: '#/parameters/resourceGroupName'
      - type: string
        description: dedicated cloud service name
        name: dedicatedCloudServiceName
        in: path
        required: true
      - $ref: '#/parameters/api-version'
      responses:
        '204':
          description: no content. resource does not exist and the request is well formed
        default:
          description: General Error
          schema:
            $ref: '#/definitions/CSRPError'
          headers:
            Content-Type:
              type: string
              default: application/json
      x-ms-examples:
        DeleteDedicatedCloudService:
          $ref: ./examples/DeleteDedicatedCloudService.json
      x-ms-long-running-operation: true
    patch:
      description: Patch dedicated cloud service's properties
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - DedicatedCloudServices
      summary: Microsoft Azure Implements Dedicatedcloudservice Patch Method
      operationId: microsoftAzureDedicatedcloudservicesUpdate
      parameters:
      - $ref: '#/parameters/subscriptionId'
      - $ref: '#/parameters/resourceGroupName'
      - type: string
        description: dedicated cloud service name
        name: dedicatedCloudServiceName
        in: path
        required: true
      - description: Patch Dedicated Cloud Service request
        name: dedicatedCloudServiceRequest
        in: body
        required: true
        schema:
          $ref: '#/definitions/PatchPayload'
      - $ref: '#/parameters/api-version'
      responses:
        '200':
          description: If resource is created or updated successfully, 200 should be returned
          schema:
            $ref: '#/definitions/DedicatedCloudService'
        default:
          description: General Error
          schema:
            $ref: '#/definitions/CSRPError'
      x-ms-examples:
        PatchDedicatedService:
          $ref: ./examples/PatchDedicatedService.json
definitions:
  Tags:
    description: Tags model
    additionalProperties:
      type: string
  DedicatedCloudServiceListResponse:
    description: List of dedicated cloud services
    properties:
      nextLink:
        description: Link for next list of DedicatedCloudNode
        type: string
      value:
        description: Results of the DedicatedCloudService list
        type: array
        items:
          $ref: '#/definitions/DedicatedCloudService'
  DedicatedCloudService:
    description: Dedicated cloud service model
    required:
    - location
    properties:
      id:
        description: /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/dedicatedCloudServices/{dedicatedCloudServiceName}
        type: string
        readOnly: true
      location:
        description: Azure region
        type: string
        x-ms-mutability:
        - read
        - create
      name:
        description: '{dedicatedCloudServiceName}'
        type: string
        pattern: ^[a-zA-Z0-9]([-_.a-zA-Z0-9]*[a-zA-Z0-9])?$
        readOnly: true
      properties:
        description: The properties of Dedicated Node Service
        x-ms-client-flatten: true
        $ref: '#/definitions/DedicatedCloudServiceProperties'
      tags:
        description: The list of tags
        $ref: '#/definitions/Tags'
      type:
        description: '{resourceProviderNamespace}/{resourceType}'
        type: string
        readOnly: true
    x-ms-azure-resource: true
  CSRPError:
    description: General error model
    properties:
      error:
        description: Error's body
        $ref: '#/definitions/CSRPErrorBody'
  PatchPayload:
    description: General patch payload modal
    properties:
      tags:
        description: The tags key:value pairs
        $ref: '#/definitions/Tags'
  CSRPErrorBody:
    description: Error properties
    properties:
      code:
        description: Error's code
        type: string
        readOnly: true
      details:
        description: Error's details
        type: array
        items:
          $ref: '#/definitions/CSRPErrorBody'
        x-ms-identifiers: []
        readOnly: true
      message:
        description: Error's message
        type: string
        readOnly: true
      target:
        description: Error's target
        type: string
  DedicatedCloudServiceProperties:
    description: Properties of dedicated cloud service
    required:
    - gatewaySubnet
    properties:
      gatewaySubnet:
        description: gateway Subnet for the account. It will collect the subnet address and always treat it as /28
        type: string
      isAccountOnboarded:
        description: indicates whether account onboarded or not in a given region
        type: string
        enum:
        - notOnBoarded
        - onBoarded
        - onBoardingFailed
        - onBoarding
        x-ms-enum:
          modelAsString: false
          name: OnboardingStatus
        readOnly: true
      nodes:
        description: total nodes purchased
        type: integer
        readOnly: true
      serviceURL:
        description: link to a service management web portal
        type: string
        readOnly: true
parameters:
  resourceGroupName:
    type: string
    x-ms-parameter-location: method
    description: The name of the resource group
    name: resourceGroupName
    in: path
    required: true
  subscriptionId:
    type: string
    description: The subscription ID.
    name: subscriptionId
    in: path
    required: true
  api-version:
    type: string
    description: Client API version.
    name: api-version
    in: query
    required: true
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
