swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector RunMetrics API
schemes:
- https
tags:
- name: RunMetrics
paths:
  ? /history/v1.0/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.MachineLearningServices/workspaces/{workspaceName}/experiments/{experimentName}/runs/{runId}/metrics
  : post:
      tags:
      - RunMetrics
      summary: Microsoft Azure Post Metric To A Run
      description: Post a Metric to a specific Run Id.
      operationId: microsoftAzureRunmetricsPost
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/subscriptionIdParameter'
      - $ref: '#/parameters/resourceGroupNameParameter'
      - $ref: '#/parameters/workspaceNameParameter'
      - name: experimentName
        in: path
        description: The experiment name.
        required: true
        type: string
      - name: runId
        in: path
        description: The identifier for a run.
        required: true
        type: string
      - name: metricDto
        in: body
        description: Details of the metric which will be added to the Run Id.
        required: false
        schema:
          $ref: '#/definitions/Metric'
      responses:
        '200':
          description: The Run Metric is posted successfully.
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: '#/definitions/ErrorResponse'
  ? /history/v1.0/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.MachineLearningServices/workspaces/{workspaceName}/experiments/{experimentName}/runs/{runId}/batch/metrics
  : post:
      tags:
      - RunMetrics
      summary: Microsoft Azure Post Metrics To A Run
      description: Post Metrics to a specific Run Id.
      operationId: microsoftAzureRunmetricsBatchpost
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/subscriptionIdParameter'
      - $ref: '#/parameters/resourceGroupNameParameter'
      - $ref: '#/parameters/workspaceNameParameter'
      - name: experimentName
        in: path
        description: The experiment name.
        required: true
        type: string
      - name: runId
        in: path
        description: The identifier for a run.
        required: true
        type: string
      - name: batchMetricDto
        in: body
        description: Details of the Metrics which will be added to the Run Id.
        required: false
        schema:
          $ref: '#/definitions/BatchMetric'
      responses:
        '200':
          description: The Run Metrics are posted successfully.
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: '#/definitions/ErrorResponse'
  ? /history/v1.0/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.MachineLearningServices/workspaces/{workspaceName}/experiments/{experimentName}/metrics/{metricId}
  : get:
      tags:
      - RunMetrics
      summary: Microsoft Azure Get Metric Details
      description: Get Metric details for a specific Metric Id.
      operationId: microsoftAzureRunmetricsGet
      consumes: []
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/subscriptionIdParameter'
      - $ref: '#/parameters/resourceGroupNameParameter'
      - $ref: '#/parameters/workspaceNameParameter'
      - name: experimentName
        in: path
        description: The experiment name.
        required: true
        type: string
      - name: metricId
        in: path
        description: The identifier for a Metric.
        required: true
        type: string
        format: uuid
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/RunMetric'
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: '#/definitions/ErrorResponse'
  ? /history/v1.0/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.MachineLearningServices/workspaces/{workspaceName}/experiments/{experimentName}/metrics:query
  : post:
      tags:
      - RunMetrics
      summary: Microsoft Azure Get All Run Metrics For The Specific Experiment
      description: Get all Run Metrics for the specific Experiment with the specified query filters.
      operationId: microsoftAzureRunmetricsGetbyquery
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/subscriptionIdParameter'
      - $ref: '#/parameters/resourceGroupNameParameter'
      - $ref: '#/parameters/workspaceNameParameter'
      - name: experimentName
        in: path
        description: The experiment name.
        required: true
        type: string
      - name: queryParams
        in: body
        description: Query Parameters for data sorting and filtering.
        required: false
        schema:
          $ref: '#/definitions/QueryParams'
      - name: MergeStrategyType
        in: query
        description: "The type of merge strategy. Currently supported strategies are:\r\nNone - all logged values are returned as individual metrics.\r\nMergeToVector - merges multiple values into a vector of values.\r\nDefault - the system determines the behavior."
        required: false
        type: string
        enum:
        - Default
        - None
        - MergeToVector
      - name: MergeStrategyOptions
        in: query
        description: Controls behavior of the merge strategy in certain cases; e.g. when a metric is not merged.
        required: false
        type: string
        enum:
        - None
        - ReportUnmergedMetricsValues
      - name: MergeStrategySettings.Version
        in: query
        description: The strategy settings version.
        required: false
        type: string
      - name: MergeStrategySettings.SelectMetrics
        in: query
        description: Defines how to select metrics when merging them together.
        required: false
        type: string
        enum:
        - SelectAll
        - SelectByFirstValueSchema
        - SelectByFirstValueSchemaMergeNumericValues
      responses:
        '200':
          description: The Run Metrics are returned successfully.
          schema:
            $ref: '#/definitions/PaginatedRunMetricList'
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: '#/definitions/ErrorResponse'
      x-ms-pageable:
        nextLinkName: nextLink
definitions:
  ErrorResponse:
    description: The error response.
    type: object
    properties:
      error:
        $ref: '#/definitions/RootError'
        description: The top level error that occurred.
      correlation:
        description: Dictionary containing correlation details for the error.
        type: object
        additionalProperties:
          type: string
      environment:
        description: The hosting environment.
        type: string
      location:
        description: The Azure region.
        type: string
      time:
        format: date-time
        description: The time in UTC.
        type: string
  MetricSchemaProperty:
    type: object
    properties:
      propertyId:
        type: string
      name:
        type: string
      type:
        type: string
  MetricSchema:
    type: object
    properties:
      numProperties:
        format: int32
        type: integer
      properties:
        uniqueItems: false
        type: array
        items:
          $ref: '#/definitions/MetricSchemaProperty'
  QueryParams:
    description: The set of supported filters.
    type: object
    properties:
      filter:
        description: "Allows for filtering the collection of resources.\r\nThe expression specified is evaluated for each resource in the collection, and only items where the expression evaluates to true are included in the response.\r\nSee https://docs.microsoft.com/en-us/azure/search/query-odata-filter-orderby-syntax for details on the expression syntax."
        type: string
      continuationToken:
        description: The continuation token to use for getting the next set of resources.
        type: string
      orderBy:
        description: "The comma separated list of resource properties to use for sorting the requested resources.\r\nOptionally, can be followed by either 'asc' or 'desc'"
        type: string
        example: Color, Size desc
      top:
        format: int32
        description: "The maximum number of items in the resource collection to be included in the result.\r\nIf not specified, all items are returned."
        type: integer
  ErrorDetails:
    description: The error details.
    type: object
    properties:
      code:
        description: The error code.
        type: string
      message:
        description: The error message.
        type: string
      target:
        description: The target of the error (e.g., the name of the property in error).
        type: string
  Metric:
    type: object
    properties:
      metricId:
        format: uuid
        type: string
      dataContainerId:
        type: string
      metricType:
        type: string
      createdUtc:
        format: date-time
        type: string
      name:
        type: string
      description:
        type: string
      label:
        type: string
      numCells:
        format: int32
        type: integer
      dataLocation:
        type: string
      cells:
        uniqueItems: false
        type: array
        items:
          type: object
          additionalProperties:
            type: object
      schema:
        $ref: '#/definitions/MetricSchema'
  BatchMetric:
    type: object
    properties:
      values:
        uniqueItems: false
        type: array
        items:
          $ref: '#/definitions/Metric'
  RootError:
    description: The root error.
    type: object
    properties:
      code:
        description: 'The service-defined error code. Supported error codes: ServiceError, UserError, ValidationError, AzureStorageError, TransientError, RequestThrottled.'
        type: string
      message:
        description: A human-readable representation of the error.
        type: string
      target:
        description: The target of the error (e.g., the name of the property in error).
        type: string
      details:
        description: The related errors that occurred during the request.
        uniqueItems: false
        type: array
        items:
          $ref: '#/definitions/ErrorDetails'
      innerError:
        $ref: '#/definitions/InnerErrorResponse'
        description: A nested list of inner errors. When evaluating errors, clients MUST traverse through all of the nested “innerErrors” and choose the deepest one that they understand.
  InnerErrorResponse:
    description: A nested structure of errors.
    type: object
    properties:
      code:
        description: The error code.
        type: string
      innerError:
        $ref: '#/definitions/InnerErrorResponse'
        description: A nested list of inner errors. When evaluating errors, clients MUST traverse through all of the nested “innerErrors” and choose the deepest one that they understand.
  PaginatedRunMetricList:
    description: A paginated list of RunMetrics.
    type: object
    properties:
      value:
        description: An array of objects of type RunMetric.
        uniqueItems: false
        type: array
        items:
          $ref: '#/definitions/RunMetric'
      continuationToken:
        description: The token used in retrieving the next page.  If null, there are no additional pages.
        type: string
      nextLink:
        description: The link to the next page constructed using the continuationToken.  If null, there are no additional pages.
        type: string
  RunMetric:
    type: object
    properties:
      runId:
        type: string
      metricId:
        format: uuid
        type: string
      dataContainerId:
        type: string
      metricType:
        type: string
      createdUtc:
        format: date-time
        type: string
      name:
        type: string
      description:
        type: string
      label:
        type: string
      numCells:
        format: int32
        type: integer
      dataLocation:
        type: string
      cells:
        uniqueItems: false
        type: array
        items:
          type: object
          additionalProperties:
            type: object
      schema:
        $ref: '#/definitions/MetricSchema'
parameters:
  workspaceNameParameter:
    name: workspaceName
    in: path
    description: The name of the workspace.
    required: true
    type: string
    x-ms-parameter-location: method
  subscriptionIdParameter:
    name: subscriptionId
    in: path
    description: The Azure Subscription ID.
    required: true
    type: string
    format: uuid
    x-ms-parameter-location: method
  resourceGroupNameParameter:
    name: resourceGroupName
    in: path
    description: The Name of the resource group in which the workspace is located.
    required: true
    type: string
    x-ms-parameter-location: method
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
