swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector PrivateLinkAssociation API
schemes:
- https
tags:
- name: PrivateLinkAssociation
paths:
  ? /providers/Microsoft.Management/managementGroups/{groupId}/providers/Microsoft.Authorization/privateLinkAssociations/{plaId}
  : put:
      tags:
      - PrivateLinkAssociation
      operationId: microsoftAzurePrivatelinkassociationPut
      description: Create a PrivateLinkAssociation
      parameters:
      - $ref: '#/parameters/ApiVersionParameter'
      - $ref: '#/parameters/GroupIdParameter'
      - $ref: '#/parameters/PrivateLinkAssociationIdParameter'
      - name: parameters
        in: body
        required: true
        schema:
          $ref: '#/definitions/PrivateLinkAssociationObject'
        description: Parameters supplied to create the private link association.
      responses:
        '200':
          description: Ok - Returns information about the new private link association.
          schema:
            $ref: '#/definitions/PrivateLinkAssociation'
        '201':
          description: Created - Returns information about the new private link association.
          schema:
            $ref: '#/definitions/PrivateLinkAssociation'
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: '#/definitions/CloudError'
      x-ms-examples:
        Create a private link association, associate scope to rmpl.:
          $ref: ./examples/PutPrivateLinkAssociation.json
      summary: Microsoft Azure Put Providers Microsoft Management Managementgroups Groupid Providers Microsoft Authorization Privatelinkassociations Plaid
    get:
      tags:
      - PrivateLinkAssociation
      operationId: microsoftAzurePrivatelinkassociationGet
      description: Get a single private link association
      parameters:
      - $ref: '#/parameters/ApiVersionParameter'
      - $ref: '#/parameters/GroupIdParameter'
      - $ref: '#/parameters/PrivateLinkAssociationIdParameter'
      responses:
        '200':
          description: Ok. The request has succeeded
          schema:
            $ref: '#/definitions/PrivateLinkAssociation'
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: '#/definitions/CloudError'
      x-ms-examples:
        Get a single private link association.:
          $ref: ./examples/GetPrivateLinkAssociation.json
      summary: Microsoft Azure Get Providers Microsoft Management Managementgroups Groupid Providers Microsoft Authorization Privatelinkassociations Plaid
    delete:
      tags:
      - PrivateLinkAssociation
      operationId: microsoftAzurePrivatelinkassociationDelete
      description: Delete a PrivateLinkAssociation
      parameters:
      - $ref: '#/parameters/ApiVersionParameter'
      - $ref: '#/parameters/GroupIdParameter'
      - $ref: '#/parameters/PrivateLinkAssociationIdParameter'
      responses:
        '200':
          description: OK
        '204':
          description: ''
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: '#/definitions/CloudError'
      x-ms-examples:
        Delete a private link association.:
          $ref: ./examples/DeletePrivateLinkAssociation.json
      summary: Microsoft Azure Delete Providers Microsoft Management Managementgroups Groupid Providers Microsoft Authorization Privatelinkassociations Plaid
  /providers/Microsoft.Management/managementGroups/{groupId}/providers/Microsoft.Authorization/privateLinkAssociations:
    get:
      tags:
      - PrivateLinkAssociation
      operationId: microsoftAzurePrivatelinkassociationList
      description: Get a private link association for a management group scope
      parameters:
      - $ref: '#/parameters/ApiVersionParameter'
      - $ref: '#/parameters/GroupIdParameter'
      responses:
        '200':
          description: Ok. The request has succeeded
          schema:
            $ref: '#/definitions/PrivateLinkAssociationGetResult'
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: '#/definitions/CloudError'
      x-ms-examples:
        Get a private link association for a MG scope.:
          $ref: ./examples/ListPrivateLinkAssociation.json
      summary: Microsoft Azure Get Providers Microsoft Management Managementgroups Groupid Providers Microsoft Authorization Privatelinkassociations
definitions:
  PrivateLinkAssociationObject:
    type: object
    properties:
      properties:
        $ref: '#/definitions/PrivateLinkAssociationProperties'
        description: The properties of the PrivateLinkAssociation.
  PrivateLinkAssociationProperties:
    type: object
    properties:
      privateLink:
        type: string
        description: The rmpl Resource ID.
      publicNetworkAccess:
        type: string
        enum:
        - Enabled
        - Disabled
        x-ms-enum:
          name: publicNetworkAccessOptions
          modelAsString: true
  PrivateLinkAssociationGetResult:
    description: 'Result of the request to get PLA for a MG scope. '
    type: object
    properties:
      value:
        type: array
        items:
          $ref: '#/definitions/PrivateLinkAssociation'
        description: private link association information.
  PrivateLinkAssociationPropertiesExpanded:
    type: object
    properties:
      privateLink:
        type: string
        description: The rmpl Resource ID.
      publicNetworkAccess:
        type: string
        enum:
        - Enabled
        - Disabled
        x-ms-enum:
          name: publicNetworkAccessOptions
          modelAsString: true
      tenantID:
        type: string
        description: The TenantID.
      scope:
        type: string
        description: The scope of the private link association.
    description: Private Link Association Properties.
  CloudError:
    x-ms-external: true
    properties:
      error:
        $ref: ../../../../../common-types/resource-management/v1/types.json#/definitions/ErrorResponse
    description: An error response for a resource management request.
  PrivateLinkAssociation:
    type: object
    properties:
      properties:
        $ref: '#/definitions/PrivateLinkAssociationPropertiesExpanded'
        description: The private link association properties.
      id:
        readOnly: true
        type: string
        description: The plaResourceID.
      type:
        readOnly: true
        type: string
        description: The operation type.
      name:
        readOnly: true
        type: string
        description: The pla name.
    x-ms-azure-resource: true
parameters:
  PrivateLinkAssociationIdParameter:
    name: plaId
    in: path
    required: true
    type: string
    description: The ID of the PLA
    x-ms-parameter-location: method
  ApiVersionParameter:
    name: api-version
    in: query
    required: true
    type: string
    description: The API version to use for this operation.
  GroupIdParameter:
    name: groupId
    in: path
    required: true
    type: string
    description: The management group ID.
    x-ms-parameter-location: method
    minLength: 1
    maxLength: 90
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
