swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector GlobalDomainRegistration API
schemes:
- https
tags:
- name: GlobalDomainRegistration
paths:
  /subscriptions/{subscriptionId}/providers/Microsoft.DomainRegistration/domains:
    get:
      tags:
      - GlobalDomainRegistration
      summary: Microsoft Azure Lists All Domains In A Subscription
      operationId: microsoftAzureGlobaldomainregistrationGetalldomains
      consumes: []
      produces:
      - application/json
      - text/json
      parameters:
      - $ref: '#/parameters/subscriptionIdParameter'
      - $ref: '#/parameters/apiVersionParameter'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/DomainCollection'
      deprecated: false
      x-ms-pageable:
        nextLinkName: nextLink
      description: Needs a more full description created.
  /subscriptions/{subscriptionId}/providers/Microsoft.DomainRegistration/generateSsoRequest:
    post:
      tags:
      - GlobalDomainRegistration
      summary: Microsoft Azure Generates A Single Sign On Request For Domain Management Portal
      operationId: microsoftAzureGlobaldomainregistrationGetdomaincontrolcenterssorequest
      consumes: []
      produces:
      - application/json
      - text/json
      - application/xml
      - text/xml
      parameters:
      - $ref: '#/parameters/subscriptionIdParameter'
      - $ref: '#/parameters/apiVersionParameter'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/DomainControlCenterSsoRequest'
      deprecated: false
      description: Needs a more full description created.
  /subscriptions/{subscriptionId}/providers/Microsoft.DomainRegistration/validateDomainRegistrationInformation:
    post:
      tags:
      - GlobalDomainRegistration
      summary: Microsoft Azure Validates Domain Registration Information
      operationId: microsoftAzureGlobaldomainregistrationValidatedomainpurchaseinformation
      consumes:
      - application/json
      - text/json
      - application/xml
      - text/xml
      - application/x-www-form-urlencoded
      produces:
      - application/json
      - text/json
      - application/xml
      - text/xml
      parameters:
      - name: domainRegistrationInput
        in: body
        description: Domain registration information
        required: true
        schema:
          $ref: '#/definitions/DomainRegistrationInput'
      - $ref: '#/parameters/subscriptionIdParameter'
      - $ref: '#/parameters/apiVersionParameter'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Object'
      deprecated: false
      description: Needs a more full description created.
  /subscriptions/{subscriptionId}/providers/Microsoft.DomainRegistration/checkDomainAvailability:
    post:
      tags:
      - GlobalDomainRegistration
      summary: Microsoft Azure Checks If A Domain Is Available For Registration
      operationId: microsoftAzureGlobaldomainregistrationCheckdomainavailability
      consumes:
      - application/json
      - text/json
      - application/xml
      - text/xml
      - application/x-www-form-urlencoded
      produces:
      - application/json
      - text/json
      - application/xml
      - text/xml
      parameters:
      - name: identifier
        in: body
        description: Name of the domain
        required: true
        schema:
          $ref: '#/definitions/NameIdentifier'
      - $ref: '#/parameters/subscriptionIdParameter'
      - $ref: '#/parameters/apiVersionParameter'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/DomainAvailablilityCheckResult'
      deprecated: false
      description: Needs a more full description created.
  /subscriptions/{subscriptionId}/providers/Microsoft.DomainRegistration/listDomainRecommendations:
    post:
      tags:
      - GlobalDomainRegistration
      summary: Microsoft Azure Lists Domain Recommendations Based On Keywords
      operationId: microsoftAzureGlobaldomainregistrationListdomainrecommendations
      consumes:
      - application/json
      - text/json
      - application/xml
      - text/xml
      - application/x-www-form-urlencoded
      produces:
      - application/json
      - text/json
      parameters:
      - name: parameters
        in: body
        description: Domain recommendation search parameters
        required: true
        schema:
          $ref: '#/definitions/DomainRecommendationSearchParameters'
      - $ref: '#/parameters/subscriptionIdParameter'
      - $ref: '#/parameters/apiVersionParameter'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/NameIdentifierCollection'
      deprecated: false
      x-ms-pageable:
        nextLinkName: nextLink
      description: Needs a more full description created.
definitions:
  Address:
    description: Address information for domain registration
    type: object
    properties:
      address1:
        description: Address 1
        type: string
      address2:
        description: Address 2
        type: string
      city:
        description: City
        type: string
      country:
        description: Country
        type: string
      postalCode:
        description: Postal code
        type: string
      state:
        description: State
        type: string
  NameIdentifierCollection:
    description: Collection of domain name identifiers
    type: object
    properties:
      value:
        description: Collection of resources
        type: array
        items:
          $ref: '#/definitions/NameIdentifier'
      nextLink:
        description: Link to next page of resources
        type: string
  DomainRegistrationInput:
    description: Domain registration input for validation Api
    type: object
    allOf:
    - $ref: '#/definitions/Resource'
    properties:
      properties:
        properties:
          name:
            description: Name of the domain
            type: string
          contactAdmin:
            $ref: '#/definitions/Contact'
            description: Admin contact information
          contactBilling:
            $ref: '#/definitions/Contact'
            description: Billing contact information
          contactRegistrant:
            $ref: '#/definitions/Contact'
            description: Registrant contact information
          contactTech:
            $ref: '#/definitions/Contact'
            description: Technical contact information
          registrationStatus:
            description: Domain registration status
            enum:
            - Active
            - Awaiting
            - Cancelled
            - Confiscated
            - Disabled
            - Excluded
            - Expired
            - Failed
            - Held
            - Locked
            - Parked
            - Pending
            - Reserved
            - Reverted
            - Suspended
            - Transferred
            - Unknown
            - Unlocked
            - Unparked
            - Updated
            - JsonConverterFailed
            type: string
            x-ms-enum:
              name: DomainStatus
              modelAsString: false
          provisioningState:
            description: Domain provisioning state
            enum:
            - Succeeded
            - Failed
            - Canceled
            - InProgress
            - Deleting
            type: string
            x-ms-enum:
              name: ProvisioningState
              modelAsString: false
          nameServers:
            description: Name servers
            type: array
            items:
              type: string
          privacy:
            description: If true then domain privacy is enabled for this domain
            type: boolean
          createdTime:
            format: date-time
            description: Domain creation timestamp
            type: string
          expirationTime:
            format: date-time
            description: Domain expiration timestamp
            type: string
          lastRenewedTime:
            format: date-time
            description: Timestamp when the domain was renewed last time
            type: string
          autoRenew:
            description: If true then domain will renewed automatically
            type: boolean
          readyForDnsRecordManagement:
            description: If true then Azure can assign this domain to Web Apps. This value will be true if domain registration status is active and it is hosted on name servers Azure has programmatic access to
            type: boolean
          managedHostNames:
            description: All hostnames derived from the domain and assigned to Azure resources
            type: array
            items:
              $ref: '#/definitions/HostName'
          consent:
            $ref: '#/definitions/DomainPurchaseConsent'
            description: Legal agreement consent
          domainNotRenewableReasons:
            description: Reasons why domain is not renewable
            type: array
            items:
              enum:
              - RegistrationStatusNotSupportedForRenewal
              - ExpirationNotInRenewalTimeRange
              - SubscriptionNotActive
              type: string
        x-ms-client-flatten: true
  Resource:
    required:
    - location
    properties:
      id:
        description: Resource Id
        type: string
      name:
        description: Resource Name
        type: string
      kind:
        description: Kind of resource
        type: string
      location:
        description: Resource Location
        type: string
      type:
        description: Resource type
        type: string
      tags:
        description: Resource tags
        type: object
        additionalProperties:
          type: string
    x-ms-azure-resource: true
  DomainCollection:
    description: Collection of domains
    type: object
    properties:
      value:
        description: Collection of resources
        type: array
        items:
          $ref: '#/definitions/Domain'
      nextLink:
        description: Link to next page of resources
        type: string
  Domain:
    description: Represents a domain
    type: object
    allOf:
    - $ref: '#/definitions/Resource'
    properties:
      properties:
        properties:
          contactAdmin:
            $ref: '#/definitions/Contact'
            description: Admin contact information
          contactBilling:
            $ref: '#/definitions/Contact'
            description: Billing contact information
          contactRegistrant:
            $ref: '#/definitions/Contact'
            description: Registrant contact information
          contactTech:
            $ref: '#/definitions/Contact'
            description: Technical contact information
          registrationStatus:
            description: Domain registration status
            enum:
            - Active
            - Awaiting
            - Cancelled
            - Confiscated
            - Disabled
            - Excluded
            - Expired
            - Failed
            - Held
            - Locked
            - Parked
            - Pending
            - Reserved
            - Reverted
            - Suspended
            - Transferred
            - Unknown
            - Unlocked
            - Unparked
            - Updated
            - JsonConverterFailed
            type: string
            x-ms-enum:
              name: DomainStatus
              modelAsString: false
          provisioningState:
            description: Domain provisioning state
            enum:
            - Succeeded
            - Failed
            - Canceled
            - InProgress
            - Deleting
            type: string
            x-ms-enum:
              name: ProvisioningState
              modelAsString: false
          nameServers:
            description: Name servers
            type: array
            items:
              type: string
          privacy:
            description: If true then domain privacy is enabled for this domain
            type: boolean
          createdTime:
            format: date-time
            description: Domain creation timestamp
            type: string
          expirationTime:
            format: date-time
            description: Domain expiration timestamp
            type: string
          lastRenewedTime:
            format: date-time
            description: Timestamp when the domain was renewed last time
            type: string
          autoRenew:
            description: If true then domain will renewed automatically
            type: boolean
          readyForDnsRecordManagement:
            description: If true then Azure can assign this domain to Web Apps. This value will be true if domain registration status is active and it is hosted on name servers Azure has programmatic access to
            type: boolean
          managedHostNames:
            description: All hostnames derived from the domain and assigned to Azure resources
            type: array
            items:
              $ref: '#/definitions/HostName'
          consent:
            $ref: '#/definitions/DomainPurchaseConsent'
            description: Legal agreement consent
          domainNotRenewableReasons:
            description: Reasons why domain is not renewable
            type: array
            items:
              enum:
              - RegistrationStatusNotSupportedForRenewal
              - ExpirationNotInRenewalTimeRange
              - SubscriptionNotActive
              type: string
        x-ms-client-flatten: true
  DomainPurchaseConsent:
    description: Domain purchase consent object representing acceptance of applicable legal agreements
    type: object
    properties:
      agreementKeys:
        description: List of applicable legal agreement keys. This list can be retrieved using ListLegalAgreements Api under TopLevelDomain resource
        type: array
        items:
          type: string
      agreedBy:
        description: Client IP address
        type: string
      agreedAt:
        format: date-time
        description: Timestamp when the agreements were accepted
        type: string
  Object:
    type: object
    properties: {}
  DomainAvailablilityCheckResult:
    description: Domain availablility check result
    type: object
    properties:
      name:
        description: Name of the domain
        type: string
      available:
        description: If true then domain can be purchased using CreateDomain Api
        type: boolean
      domainType:
        description: Domain type
        enum:
        - Regular
        - SoftDeleted
        type: string
        x-ms-enum:
          name: DomainType
          modelAsString: false
  Contact:
    description: Contact information for domain registration. If 'Domain Privacy' option is not selected then the contact information will be made publicly available through the Whois directories as per ICANN requirements.
    type: object
    properties:
      addressMailing:
        $ref: '#/definitions/Address'
        description: Mailing address
      email:
        description: Email address
        type: string
      fax:
        description: Fax number
        type: string
      jobTitle:
        description: Job title
        type: string
      nameFirst:
        description: First name
        type: string
      nameLast:
        description: Last name
        type: string
      nameMiddle:
        description: Middle name
        type: string
      organization:
        description: Organization
        type: string
      phone:
        description: Phone number
        type: string
  DomainControlCenterSsoRequest:
    description: Single sign on request information for domain management
    type: object
    properties:
      url:
        description: Url where the single sign on request is to be made
        type: string
      postParameterKey:
        description: Post parameter key
        type: string
      postParameterValue:
        description: Post parameter value. Client should use 'application/x-www-form-urlencoded' encoding for this value.
        type: string
  HostName:
    description: Details of a hostname derived from a domain
    type: object
    properties:
      name:
        description: Name of the hostname
        type: string
      siteNames:
        description: List of sites the hostname is assigned to. This list will have more than one site only if the hostname is pointing to a Traffic Manager
        type: array
        items:
          type: string
      azureResourceName:
        description: Name of the Azure resource the hostname is assigned to. If it is assigned to a traffic manager then it will be the traffic manager name otherwise it will be the website name
        type: string
      azureResourceType:
        description: Type of the Azure resource the hostname is assigned to
        enum:
        - Website
        - TrafficManager
        type: string
        x-ms-enum:
          name: AzureResourceType
          modelAsString: false
      customHostNameDnsRecordType:
        description: Type of the Dns record
        enum:
        - CName
        - A
        type: string
        x-ms-enum:
          name: CustomHostNameDnsRecordType
          modelAsString: false
      hostNameType:
        description: Type of the hostname
        enum:
        - Verified
        - Managed
        type: string
        x-ms-enum:
          name: HostNameType
          modelAsString: false
  DomainRecommendationSearchParameters:
    description: Domain recommendation search parameters
    type: object
    properties:
      keywords:
        description: Keywords to be used for generating domain recommendations
        type: string
      maxDomainRecommendations:
        format: int32
        description: Maximum number of recommendations
        type: integer
  NameIdentifier:
    description: Identifies an object
    type: object
    properties:
      name:
        description: Name of the object
        type: string
parameters:
  subscriptionIdParameter:
    name: subscriptionId
    in: path
    description: Subscription Id
    required: true
    type: string
  apiVersionParameter:
    name: api-version
    in: query
    description: API Version
    required: true
    type: string
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
