swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector HCIReports API
schemes:
- https
tags:
- name: HCIReports
paths:
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.AzureStackHci/clusters/{clusterName}/providers/Microsoft.Automanage/configurationProfileAssignments/{configurationProfileAssignmentName}/reports/{reportName}
  : get:
      tags:
      - HCIReports
      operationId: microsoftAzureHcireportsGet
      description: Get information about a report associated with a configuration profile assignment run
      x-ms-examples:
        Get a report for a HCI configuration profile assignment:
          $ref: ./examples/getHCIReport.json
      parameters:
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/ResourceGroupNameParameter
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/SubscriptionIdParameter
      - $ref: '#/parameters/ClusterNameParameter'
      - name: configurationProfileAssignmentName
        in: path
        required: true
        type: string
        description: The configuration profile assignment name.
      - name: reportName
        in: path
        required: true
        type: string
        description: The report name.
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/ApiVersionParameter
      responses:
        '200':
          description: OK. The report was returned successfully.
          schema:
            $ref: '#/definitions/Report'
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: ../../../../../common-types/resource-management/v2/types.json#/definitions/ErrorResponse
      produces:
      - application/json
      consumes:
      - application/json
      summary: Get Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Azurestackhci Clusters Clustername Providers Microsoft Automanage Configurationprofileassignments Configurationprofileassignmentname Reports Reportname
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.AzureStackHci/clusters/{clusterName}/providers/Microsoft.Automanage/configurationProfileAssignments/{configurationProfileAssignmentName}/reports
  : get:
      tags:
      - HCIReports
      operationId: microsoftAzureHcireportsListbyconfigurationprofileassignments
      description: Retrieve a list of reports within a given configuration profile assignment
      x-ms-examples:
        List reports by HCI configuration profiles assignment:
          $ref: ./examples/listReportsByconfigurationProfileHCIAssignment.json
      parameters:
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/ResourceGroupNameParameter
      - $ref: '#/parameters/ClusterNameParameter'
      - name: configurationProfileAssignmentName
        in: path
        required: true
        type: string
        description: The configuration profile assignment name.
      - $ref: ../../../../../common-types/resource-management/v2/types.json#/parameters/ApiVersionParameter
      responses:
        '200':
          description: OK. List of reports.
          schema:
            $ref: '#/definitions/ReportList'
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: ../../../../../common-types/resource-management/v2/types.json#/definitions/ErrorResponse
      x-ms-pageable:
        nextLinkName: null
      produces:
      - application/json
      consumes:
      - application/json
      summary: Get Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Azurestackhci Clusters Clustername Providers Microsoft Automanage Configurationprofileassignments Configurationprofileassignmentname Reports
definitions:
  ReportResource:
    description: Details about the resource processed by the configuration profile assignment
    type: object
    properties:
      name:
        type: string
        readOnly: true
        description: Name of the resource.
      id:
        type: string
        readOnly: true
        description: ARM id of the resource.
      type:
        type: string
        readOnly: true
        description: Type of the resource.
      status:
        type: string
        readOnly: true
        description: Status of the resource.
      error:
        $ref: ../../../../../common-types/resource-management/v2/types.json#/definitions/ErrorDetail
        readOnly: true
        description: Error message, if any, returned when deploying the resource.
  Report:
    description: Definition of the report.
    type: object
    properties:
      properties:
        title: Properties
        x-ms-client-flatten: true
        $ref: '#/definitions/AssignmentReportProperties'
        description: The properties for the report.
      systemData:
        $ref: ../../../../../common-types/resource-management/v2/types.json#/definitions/systemData
        readOnly: true
        description: Azure Resource Manager metadata containing createdBy and modifiedBy information.
    allOf:
    - $ref: ../../../../../common-types/resource-management/v2/types.json#/definitions/ProxyResource
  AssignmentReportProperties:
    description: Data related to the report detail.
    type: object
    properties:
      startTime:
        type: string
        description: Start time of the configuration profile assignment processing.
      endTime:
        type: string
        description: End time of the configuration profile assignment processing.
      lastModifiedTime:
        type: string
        readOnly: true
        description: Last modified time of the configuration profile assignment processing.
      duration:
        type: string
        readOnly: true
        description: Duration of the configuration profile assignment processing.
      type:
        type: string
        readOnly: true
        description: Type of the configuration profile assignment processing (Initial/Consistency).
      status:
        type: string
        readOnly: true
        description: The status of the configuration profile assignment.
      configurationProfile:
        type: string
        readOnly: true
        description: The configurationProfile linked to the assignment.
      resources:
        type: array
        readOnly: true
        items:
          $ref: '#/definitions/ReportResource'
        description: List of resources processed by the configuration profile assignment.
      error:
        $ref: ../../../../../common-types/resource-management/v2/types.json#/definitions/ErrorDetail
        readOnly: true
        description: Error message, if any, returned by the configuration profile assignment processing.
      reportFormatVersion:
        type: string
        readOnly: true
        description: Version of the report format
  ReportList:
    description: The response of the list report operation.
    type: object
    properties:
      value:
        type: array
        items:
          $ref: '#/definitions/Report'
        description: Result of the list report operation.
parameters:
  ClusterNameParameter:
    name: clusterName
    in: path
    required: true
    type: string
    description: The name of the Arc machine.
    x-ms-parameter-location: method
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
