swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector ResourcePools API
schemes:
- https
tags:
- name: ResourcePools
paths:
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ConnectedVMwarevSphere/resourcePools/{resourcePoolName}
  : put:
      tags:
      - ResourcePools
      operationId: microsoftAzureResourcepoolsCreate
      description: Create Or Update resourcePool.
      summary: Microsoft Azure Implements Resourcepool Put Method
      x-ms-examples:
        CreateResourcePool:
          $ref: ./examples/CreateResourcePool.json
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/subscriptionId'
      - $ref: '#/parameters/resourceGroupName'
      - in: path
        name: resourcePoolName
        required: true
        type: string
        description: Name of the resourcePool.
      - $ref: '#/parameters/api-version'
      - in: body
        name: body
        description: Request payload.
        schema:
          $ref: '#/definitions/ResourcePool'
      responses:
        '200':
          description: Arm resource update successful.
          schema:
            $ref: '#/definitions/ResourcePool'
        '201':
          description: Created
          schema:
            $ref: '#/definitions/ResourcePool'
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: ../../../../../common-types/resource-management/v3/types.json#/definitions/ErrorResponse
      x-ms-long-running-operation: true
      x-ms-long-running-operation-options:
        final-state-via: azure-async-operation
    get:
      tags:
      - ResourcePools
      operationId: microsoftAzureResourcepoolsGet
      summary: Microsoft Azure Gets A Resourcepool
      description: Implements resourcePool GET method.
      x-ms-examples:
        GetResourcePool:
          $ref: ./examples/GetResourcePool.json
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/subscriptionId'
      - $ref: '#/parameters/resourceGroupName'
      - in: path
        name: resourcePoolName
        description: Name of the resourcePool.
        required: true
        type: string
      - $ref: '#/parameters/api-version'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/ResourcePool'
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: ../../../../../common-types/resource-management/v3/types.json#/definitions/ErrorResponse
    patch:
      tags:
      - ResourcePools
      operationId: microsoftAzureResourcepoolsUpdate
      summary: Microsoft Azure Updates A Resourcepool
      description: API to update certain properties of the resourcePool resource.
      x-ms-examples:
        UpdateResourcePool:
          $ref: ./examples/UpdateResourcePool.json
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/subscriptionId'
      - $ref: '#/parameters/resourceGroupName'
      - in: path
        name: resourcePoolName
        required: true
        type: string
        description: Name of the resourcePool.
      - $ref: '#/parameters/api-version'
      - in: body
        name: body
        description: Resource properties to update.
        schema:
          $ref: '#/definitions/ResourcePatch'
      responses:
        '200':
          description: Arm resource update successful.
          schema:
            $ref: '#/definitions/ResourcePool'
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: ../../../../../common-types/resource-management/v3/types.json#/definitions/ErrorResponse
    delete:
      tags:
      - ResourcePools
      operationId: microsoftAzureResourcepoolsDelete
      summary: Microsoft Azure Deletes An Resourcepool
      description: Implements resourcePool DELETE method.
      x-ms-examples:
        DeleteResourcePool:
          $ref: ./examples/DeleteResourcePool.json
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/subscriptionId'
      - $ref: '#/parameters/resourceGroupName'
      - in: path
        name: resourcePoolName
        description: Name of the resourcePool.
        required: true
        type: string
      - $ref: '#/parameters/api-version'
      - in: query
        name: force
        description: Whether force delete was specified.
        required: false
        type: boolean
      responses:
        '200':
          description: Success
        '202':
          description: Accepted
          headers:
            Location:
              type: string
        '204':
          description: No Content
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: ../../../../../common-types/resource-management/v3/types.json#/definitions/ErrorResponse
      x-ms-long-running-operation: true
  /subscriptions/{subscriptionId}/providers/Microsoft.ConnectedVMwarevSphere/resourcePools:
    get:
      tags:
      - ResourcePools
      operationId: microsoftAzureResourcepoolsList
      summary: Microsoft Azure Implements Get Resourcepools In A Subscription
      description: List of resourcePools in a subscription.
      x-ms-examples:
        ListResourcePools:
          $ref: ./examples/ListResourcePools.json
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/subscriptionId'
      - $ref: '#/parameters/api-version'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/ResourcePoolsList'
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: ../../../../../common-types/resource-management/v3/types.json#/definitions/ErrorResponse
      x-ms-pageable:
        nextLinkName: nextLink
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ConnectedVMwarevSphere/resourcePools
  : get:
      tags:
      - ResourcePools
      operationId: microsoftAzureResourcepoolsListbyresourcegroup
      summary: Microsoft Azure Implements Get Resourcepools In A Resource Group
      description: List of resourcePools in a resource group.
      x-ms-examples:
        ListResourcePoolsByResourceGroup:
          $ref: ./examples/ListResourcePoolsByResourceGroup.json
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/subscriptionId'
      - $ref: '#/parameters/resourceGroupName'
      - $ref: '#/parameters/api-version'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/ResourcePoolsList'
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: ../../../../../common-types/resource-management/v3/types.json#/definitions/ErrorResponse
      x-ms-pageable:
        nextLinkName: nextLink
  ? /subscriptions/{subscriptionId}/providers/Microsoft.VMwareCloudSimple/locations/{regionId}/privateClouds/{pcName}/resourcePools
  : get:
      description: Returns list of resource pools in region for private cloud
      produces:
      - application/json
      tags:
      - ResourcePools
      summary: Microsoft Azure Implements Get Of Resource Pools List
      operationId: microsoftAzureResourcepoolsList
      parameters:
      - $ref: '#/parameters/subscriptionId_2'
      - $ref: '#/parameters/regionId'
      - $ref: '#/parameters/pcName'
      - $ref: '#/parameters/api-version_2'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/ResourcePoolsListResponse'
        default:
          description: General Error
          schema:
            $ref: '#/definitions/CSRPError'
      x-ms-examples:
        ListResourcePools:
          $ref: ./examples/ListResourcePools.json
      x-ms-pageable:
        nextLinkName: nextLink
  ? /subscriptions/{subscriptionId}/providers/Microsoft.VMwareCloudSimple/locations/{regionId}/privateClouds/{pcName}/resourcePools/{resourcePoolName}
  : get:
      description: Returns resource pool templates by its name
      produces:
      - application/json
      tags:
      - ResourcePools
      summary: Microsoft Azure Implements Get Of Resource Pool
      operationId: microsoftAzureResourcepoolsGet
      parameters:
      - $ref: '#/parameters/subscriptionId_2'
      - $ref: '#/parameters/api-version_2'
      - $ref: '#/parameters/regionId'
      - $ref: '#/parameters/pcName'
      - type: string
        description: resource pool id (vsphereId)
        name: resourcePoolName
        in: path
        required: true
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/ResourcePool_2'
        default:
          description: General Error
          schema:
            $ref: '#/definitions/CSRPError'
      x-ms-examples:
        GetResourcePool:
          $ref: ./examples/GetResourcePool.json
definitions:
  ResourcePool:
    description: Define the resourcePool.
    required:
    - location
    - properties
    type: object
    x-ms-azure-resource: true
    properties:
      properties:
        x-ms-client-flatten: true
        description: Resource properties.
        $ref: '#/definitions/ResourcePoolProperties'
      location:
        description: Gets or sets the location.
        type: string
        x-ms-mutability:
        - read
        - create
      extendedLocation:
        $ref: '#/definitions/ExtendedLocation'
        description: Gets or sets the extended location.
      systemData:
        $ref: ../../../../../common-types/resource-management/v2/types.json#/definitions/systemData
        description: The system data.
      tags:
        description: Gets or sets the Resource tags.
        type: object
        additionalProperties:
          type: string
      name:
        description: Gets or sets the name.
        type: string
        readOnly: true
      id:
        description: Gets or sets the Id.
        type: string
        readOnly: true
      type:
        description: Gets or sets the type of the resource.
        type: string
        readOnly: true
      kind:
        type: string
        description: Metadata used by portal/tooling/etc to render different UX experiences for resources of the same type; e.g. ApiApps are a kind of Microsoft.Web/sites type.  If supported, the resource provider must validate and persist this value.
  ExtendedLocation:
    type: object
    description: The extended location.
    properties:
      type:
        type: string
        description: The extended location type.
      name:
        type: string
        description: The extended location name.
  CSRPErrorBody:
    description: Error properties
    properties:
      code:
        description: Error's code
        type: string
        readOnly: true
      details:
        description: Error's details
        type: array
        items:
          $ref: '#/definitions/CSRPErrorBody'
        x-ms-identifiers: []
        readOnly: true
      message:
        description: Error's message
        type: string
        readOnly: true
      target:
        description: Error's target
        type: string
  ResourcePoolProperties_2:
    description: Properties of resource pool
    properties:
      fullName:
        description: Hierarchical resource pool name
        type: string
        readOnly: true
  ResourceProvisioningState:
    type: string
    description: The current deployment state of resource.
    enum:
    - Succeeded
    - Failed
    - Canceled
    - Provisioning
    - Updating
    - Deleting
    - Accepted
    - Created
    x-ms-enum:
      name: ProvisioningState
      modelAsString: true
  ResourcePoolsList:
    description: List of ResourcePools.
    type: object
    properties:
      nextLink:
        description: Url to follow for getting next page of ResourcePools.
        type: string
      value:
        description: Array of ResourcePools
        type: array
        items:
          $ref: '#/definitions/ResourcePool'
    required:
    - value
  CSRPError:
    description: General error model
    properties:
      error:
        description: Error's body
        $ref: '#/definitions/CSRPErrorBody'
  ResourceStatus:
    description: The resource status information.
    type: object
    properties:
      type:
        description: The type of the condition.
        type: string
        readOnly: true
      status:
        description: Status of the condition.
        type: string
        readOnly: true
      reason:
        description: The reason for the condition's status.
        type: string
        readOnly: true
      message:
        description: A human readable message indicating details about the status.
        type: string
        readOnly: true
      severity:
        description: Severity with which to treat failures of this type of condition.
        type: string
        readOnly: true
      lastUpdatedAt:
        description: The last update time for this condition.
        type: string
        format: date-time
        readOnly: true
  ResourcePoolsListResponse:
    description: List of resource pools response model
    properties:
      nextLink:
        description: Link for next list of ResourcePoolsList
        type: string
      value:
        description: Results of the Resource pools list
        type: array
        items:
          $ref: '#/definitions/ResourcePool_2'
  ResourcePatch:
    type: object
    properties:
      tags:
        type: object
        additionalProperties:
          type: string
        description: Resource tags.
    description: Object containing updates for patch operations.
  ResourcePool_2:
    description: Resource pool model
    required:
    - id
    properties:
      id:
        description: resource pool id (privateCloudId:vsphereId)
        type: string
      location:
        description: Azure region
        type: string
        readOnly: true
      name:
        description: '{ResourcePoolName}'
        type: string
        readOnly: true
      privateCloudId:
        description: The Private Cloud Id
        type: string
        readOnly: true
      properties:
        description: Resource pool properties
        x-ms-client-flatten: true
        $ref: '#/definitions/ResourcePoolProperties_2'
      type:
        description: '{resourceProviderNamespace}/{resourceType}'
        type: string
        readOnly: true
  ResourcePoolProperties:
    description: Describes the properties of a Resource Pool.
    type: object
    properties:
      uuid:
        description: Gets or sets a unique identifier for this resource.
        type: string
        readOnly: true
      vCenterId:
        description: Gets or sets the ARM Id of the vCenter resource in which this resource pool resides.
        type: string
      moRefId:
        description: Gets or sets the vCenter MoRef (Managed Object Reference) ID for the resource pool.
        type: string
      inventoryItemId:
        description: Gets or sets the inventory Item ID for the resource pool.
        type: string
      moName:
        description: Gets or sets the vCenter Managed Object name for the resource pool.
        type: string
        readOnly: true
      cpuSharesLevel:
        description: "Gets or sets CPUSharesLevel which specifies the CPU allocation level for this pool.\r\nThis property is used in relative allocation between resource consumers."
        type: string
        readOnly: true
      cpuReservationMHz:
        format: int64
        description: "Gets or sets CPUReservationMHz which specifies the CPU size in MHz that is guaranteed\r\nto be available."
        type: integer
        readOnly: true
      cpuLimitMHz:
        format: int64
        description: "Gets or sets CPULimitMHz which specifies a CPU usage limit in MHz.\r\nUtilization will not exceed this limit even if there are available resources."
        type: integer
        readOnly: true
      memSharesLevel:
        description: "Gets or sets CPUSharesLevel which specifies the memory allocation level for this pool.\r\nThis property is used in relative allocation between resource consumers."
        type: string
        readOnly: true
      memReservationMB:
        format: int64
        description: "Gets or sets MemReservationMB which specifies the guaranteed available memory in\r\nmegabytes."
        type: integer
        readOnly: true
      memLimitMB:
        format: int64
        description: "Gets or sets MemLimitMB specifies a memory usage limit in megabytes.\r\nUtilization will not exceed the specified limit even if there are available resources."
        type: integer
        readOnly: true
      memOverallUsageGB:
        format: int64
        description: Gets the used physical memory on the pool in GB.
        type: integer
        readOnly: true
      memCapacityGB:
        format: int64
        description: Gets the total amount of physical memory on the pool in GB.
        type: integer
        readOnly: true
      cpuOverallUsageMHz:
        format: int64
        description: Gets the used CPU usage across all cores on the pool in MHz.
        type: integer
        readOnly: true
      cpuCapacityMHz:
        format: int64
        description: Gets the max CPU usage across all cores on the pool in MHz.
        type: integer
        readOnly: true
      customResourceName:
        description: Gets the name of the corresponding resource in Kubernetes.
        type: string
        readOnly: true
      datastoreIds:
        description: Gets the datastore ARM ids.
        type: array
        items:
          type: string
        readOnly: true
      networkIds:
        description: Gets the network ARM ids.
        type: array
        items:
          type: string
        readOnly: true
      statuses:
        description: The resource status information.
        readOnly: true
        type: array
        items:
          $ref: '#/definitions/ResourceStatus'
        x-ms-identifiers:
        - type
      provisioningState:
        $ref: '#/definitions/ResourceProvisioningState'
        description: Gets the provisioning state.
        readOnly: true
parameters:
  pcName:
    type: string
    x-ms-parameter-location: method
    description: The private cloud name
    name: pcName
    in: path
    required: true
  resourceGroupName:
    in: path
    name: resourceGroupName
    description: The Resource Group Name.
    required: true
    type: string
    x-ms-parameter-location: method
  api-version:
    in: query
    name: api-version
    description: Client Api Version.
    required: true
    type: string
  subscriptionId:
    in: path
    name: subscriptionId
    description: The Subscription ID.
    required: true
    type: string
  regionId:
    type: string
    x-ms-parameter-location: method
    description: The region Id (westus, eastus)
    name: regionId
    in: path
    required: true
  api-version_2:
    type: string
    description: Client API version.
    name: api-version
    in: query
    required: true
  subscriptionId_2:
    type: string
    description: The subscription ID.
    name: subscriptionId
    in: path
    required: true
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
