swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector EventRoutes API
schemes:
- https
tags:
- name: EventRoutes
paths:
  /eventroutes:
    parameters:
    - $ref: '#/parameters/traceparent'
    - $ref: '#/parameters/tracestate'
    get:
      tags:
      - EventRoutes
      description: Retrieves all event routes.<br>Status codes:<br>* 200 OK
      operationId: microsoftAzureEventroutesList
      x-ms-examples:
        List event routes:
          $ref: ./examples/EventRoutesList.json
      parameters:
      - $ref: '#/parameters/max-items-per-page'
      - $ref: '#/parameters/api-version'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/EventRouteCollection'
        default:
          description: Default response.
          schema:
            $ref: '#/definitions/ErrorResponse'
      x-ms-pageable:
        nextLinkName: nextLink
      summary: Microsoft Azure Get Eventroutes
  /eventroutes/{id}:
    parameters:
    - $ref: '#/parameters/traceparent'
    - $ref: '#/parameters/tracestate'
    get:
      tags:
      - EventRoutes
      description: Retrieves an event route.<br>Status codes:<br>* 200 OK<br>* 404 Not Found<br>  * EventRouteNotFound - The event route was not found.
      operationId: microsoftAzureEventroutesGetbyid
      x-ms-examples:
        Get an event route by id:
          $ref: ./examples/EventRouteGet.json
      parameters:
      - $ref: '#/parameters/eventRouteId'
      - $ref: '#/parameters/api-version'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/EventRoute'
        default:
          description: Default response.
          schema:
            $ref: '#/definitions/ErrorResponse'
      summary: Microsoft Azure Get Eventroutes Id
    put:
      tags:
      - EventRoutes
      description: Adds or replaces an event route.<br>Status codes:<br>* 204 No Content<br>* 400 Bad Request<br>  * EventRouteEndpointInvalid - The endpoint provided does not exist or is not active.<br>  * EventRouteFilterInvalid - The event route filter is invalid.<br>  * EventRouteIdInvalid - The event route id is invalid.<br>  * LimitExceeded - The maximum number of event routes allowed has been reached.
      operationId: microsoftAzureEventroutesAdd
      x-ms-examples:
        Add an event route:
          $ref: ./examples/EventRoutePut.json
        Add an event route (with filter):
          $ref: ./examples/EventRoutePutWithFilter.json
      parameters:
      - $ref: '#/parameters/eventRouteId'
      - name: eventRoute
        description: The event route data
        in: body
        required: true
        schema:
          $ref: '#/definitions/EventRoute'
      - $ref: '#/parameters/api-version'
      responses:
        '204':
          description: Success
        default:
          description: Default response.
          schema:
            $ref: '#/definitions/ErrorResponse'
      summary: Microsoft Azure Put Eventroutes Id
    delete:
      tags:
      - EventRoutes
      description: Deletes an event route.<br>Status codes:<br>* 204 No Content<br>* 404 Not Found<br>  * EventRouteNotFound - The event route was not found.
      operationId: microsoftAzureEventroutesDelete
      x-ms-examples:
        Delete an event route:
          $ref: ./examples/EventRouteDelete.json
      parameters:
      - $ref: '#/parameters/eventRouteId'
      - $ref: '#/parameters/api-version'
      responses:
        '204':
          description: Success
        default:
          description: Default response.
          schema:
            $ref: '#/definitions/ErrorResponse'
      summary: Microsoft Azure Delete Eventroutes Id
definitions:
  ErrorResponse:
    description: Error response.
    required:
    - error
    properties:
      error:
        $ref: '#/definitions/Error'
        description: The error details.
  EventRoute:
    description: A route which directs notification and telemetry events to an endpoint. Endpoints are a destination outside of Azure Digital Twins such as an EventHub.
    type: object
    required:
    - endpointName
    - filter
    properties:
      id:
        description: The id of the event route.
        type: string
        readOnly: true
      endpointName:
        description: The name of the endpoint this event route is bound to.
        type: string
      filter:
        description: An expression which describes the events which are routed to the endpoint.
        type: string
  InnerError:
    description: A more specific error description than was provided by the containing error.
    properties:
      code:
        description: A more specific error code than was provided by the containing error.
        type: string
      innererror:
        description: An object containing more specific information than the current object about the error.
        $ref: '#/definitions/InnerError'
  EventRouteCollection:
    description: A collection of EventRoute objects.
    type: object
    required:
    - value
    properties:
      value:
        description: The EventRoute objects.
        type: array
        items:
          $ref: '#/definitions/EventRoute'
      nextLink:
        description: A URI to retrieve the next page of results.
        type: string
  Error:
    description: Error definition.
    properties:
      code:
        description: Service specific error code which serves as the substatus for the HTTP error code.
        type: string
        readOnly: true
      message:
        description: A human-readable representation of the error.
        type: string
        readOnly: true
      details:
        description: Internal error details.
        type: array
        items:
          $ref: '#/definitions/Error'
        readOnly: true
      innererror:
        description: An object containing more specific information than the current object about the error.
        $ref: '#/definitions/InnerError'
parameters:
  tracestate:
    name: tracestate
    in: header
    description: Provides vendor-specific trace identification information and is a companion to traceparent.
    required: false
    type: string
    x-ms-parameter-location: method
    x-ms-parameter-grouping:
      postfix: Options
  traceparent:
    name: traceparent
    in: header
    description: Identifies the request in a distributed tracing system.
    required: false
    type: string
    x-ms-parameter-location: method
    x-ms-parameter-grouping:
      postfix: Options
  max-items-per-page:
    name: max-items-per-page
    in: header
    description: The maximum number of items to retrieve per request. The server may choose to return less than the requested number.
    required: false
    type: integer
    x-ms-client-name: MaxItemsPerPage
    x-ms-parameter-location: method
    x-ms-parameter-grouping:
      postfix: Options
  eventRouteId:
    name: id
    in: path
    required: true
    type: string
    description: The id for an event route. The id is unique within event routes and case sensitive.
    x-ms-parameter-location: method
  api-version:
    name: api-version
    in: query
    description: The requested API version.
    required: true
    type: string
    minLength: 1
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
