swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector Volumes OnPrem Migration API
schemes:
- https
tags:
- name: Volumes OnPrem Migration
paths:
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.NetApp/netAppAccounts/{accountName}/capacityPools/{poolName}/volumes/{volumeName}/peerClusterForOnPremMigration
  : post:
      summary: Microsoft Azure Start Cluster Peering
      description: Starts peering the cluster for this migration volume
      tags:
      - Volumes OnPrem Migration
      operationId: microsoftAzureVolumesPeerclusterforonpremmigration
      parameters:
      - $ref: ../../../../../common-types/resource-management/v5/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../common-types/resource-management/v5/types.json#/parameters/ResourceGroupNameParameter
      - $ref: '#/parameters/AccountName'
      - $ref: '#/parameters/PoolName'
      - $ref: '#/parameters/VolumeName'
      - $ref: ../../../../../common-types/resource-management/v5/types.json#/parameters/ApiVersionParameter
      - name: body
        description: Cluster peer request object supplied in the body of the operation.
        in: body
        required: true
        schema:
          $ref: '#/definitions/peerClusterForVolumeMigrationRequest'
      x-ms-long-running-operation: true
      x-ms-long-running-operation-options:
        final-state-via: location
        final-state-schema: '#/definitions/clusterPeerCommandResponse'
      x-ms-examples:
        Volumes_PeerClusterForOnPremMigration:
          $ref: examples/Volumes_PeerClusterForOnPremMigration.json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/clusterPeerCommandResponse'
        '202':
          description: Accepted
          headers:
            Location:
              type: string
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: ../../../../../common-types/resource-management/v5/types.json#/definitions/ErrorResponse
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.NetApp/netAppAccounts/{accountName}/capacityPools/{poolName}/volumes/{volumeName}/createOnPremMigrationReplication
  : post:
      summary: Microsoft Azure Start Migration Process
      description: Starts SVM peering and returns a command to be run on the external ONTAP to accept it.  Once the SVMs have been peered a SnapMirror will be created
      tags:
      - Volumes OnPrem Migration
      operationId: microsoftAzureVolumesCreateonpremmigrationreplication
      parameters:
      - $ref: ../../../../../common-types/resource-management/v5/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../common-types/resource-management/v5/types.json#/parameters/ResourceGroupNameParameter
      - $ref: '#/parameters/AccountName'
      - $ref: '#/parameters/PoolName'
      - $ref: '#/parameters/VolumeName'
      - $ref: ../../../../../common-types/resource-management/v5/types.json#/parameters/ApiVersionParameter
      x-ms-long-running-operation: true
      x-ms-long-running-operation-options:
        final-state-via: location
        final-state-schema: '#/definitions/svmPeerCommandResponse'
      x-ms-examples:
        Volumes_CreateOnPremMigrationReplication:
          $ref: examples/Volumes_CreateOnPremMigrationReplication.json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/svmPeerCommandResponse'
        '202':
          description: Accepted
          headers:
            Location:
              type: string
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: ../../../../../common-types/resource-management/v5/types.json#/definitions/ErrorResponse
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.NetApp/netAppAccounts/{accountName}/capacityPools/{poolName}/volumes/{volumeName}/performReplicationTransfer
  : post:
      tags:
      - Volumes OnPrem Migration
      summary: Microsoft Azure Perform A Replication Transfer
      description: Performs an adhoc replication transfer on a volume with volumeType Migration
      operationId: microsoftAzureVolumesPerformreplicationtransfer
      parameters:
      - $ref: ../../../../../common-types/resource-management/v5/types.json#/parameters/SubscriptionIdParameter
      - $ref: ../../../../../common-types/resource-management/v5/types.json#/parameters/ResourceGroupNameParameter
      - $ref: '#/parameters/AccountName'
      - $ref: '#/parameters/PoolName'
      - $ref: '#/parameters/VolumeName'
      - $ref: ../../../../../common-types/resource-management/v5/types.json#/parameters/ApiVersionParameter
      responses:
        '202':
          description: Accepted
          headers:
            Location:
              type: string
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: ../../../../../common-types/resource-management/v5/types.json#/definitions/ErrorResponse
      x-ms-long-running-operation: true
      x-ms-long-running-operation-options:
        final-state-via: location
      x-ms-examples:
        Volumes_PerformReplicationTransfer:
          $ref: examples/Volumes_PerformReplicationTransfer.json
definitions:
  remotePath:
    description: The full path to a volume that is to be migrated into ANF. Required for Migration volumes
    type: object
    required:
    - externalHostName
    - serverName
    - volumeName
    properties:
      externalHostName:
        type: string
        description: The Path to a ONTAP Host
      serverName:
        type: string
        description: The name of a server on the ONTAP Host
      volumeName:
        type: string
        description: The name of a volume on the server
  peerClusterForVolumeMigrationRequest:
    description: Source cluster properties for a cluster peer request
    type: object
    required:
    - peerAddresses
    properties:
      peerAddresses:
        type: array
        minItems: 1
        description: A list of IC-LIF IPs that can be used to connect to the on-prem cluster
        example:
        - 0.0.0.1
        - 0.0.0.2
        - 0.0.0.3
        - 0.0.0.4
        - 0.0.0.5
        - 0.0.0.6
        items:
          type: string
      remotePath:
        description: The full path to a volume that is to be migrated into ANF. Required for Migration volumes
        type: object
        $ref: '#/definitions/remotePath'
        x-ms-mutability:
        - read
        - create
  clusterPeerCommandResponse:
    description: Information about cluster peering process
    type: object
    properties:
      peerAcceptCommand:
        description: A command that needs to be run on the external ONTAP to accept cluster peering.  Will only be present if <code>clusterPeeringStatus</code> is <code>pending</code>
        type: string
  svmPeerCommandResponse:
    description: Information about SVM peering process
    type: object
    properties:
      svmPeeringCommand:
        description: A command that needs to be run on the external ONTAP to accept SVM peering.  Will only be present if <code>svmPeeringStatus</code> is <code>pending</code>
        type: string
parameters:
  AccountName:
    name: accountName
    type: string
    pattern: ^[a-zA-Z0-9][a-zA-Z0-9\-_]{0,127}$
    in: path
    required: true
    description: The name of the NetApp account
    x-ms-parameter-location: method
  PoolName:
    name: poolName
    type: string
    in: path
    required: true
    pattern: ^[a-zA-Z0-9][a-zA-Z0-9\-_]{0,63}$
    minLength: 1
    maxLength: 64
    description: The name of the capacity pool
    x-ms-parameter-location: method
  VolumeName:
    name: volumeName
    type: string
    in: path
    required: true
    pattern: ^[a-zA-Z][a-zA-Z0-9\-_]{0,63}$
    minLength: 1
    maxLength: 64
    description: The name of the volume
    x-ms-parameter-location: method
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
