swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector ListManagementTerm API
schemes:
- https
tags:
- name: ListManagementTerm
paths:
  /contentmoderator/lists/v1.0/termlists/{listId}/terms/{term}:
    post:
      tags:
      - ListManagementTerm
      operationId: microsoftAzureListmanagementtermAddterm
      description: Adds a term to the term list with listId equal to the passed list ID.
      parameters:
      - $ref: '#/parameters/listId'
      - $ref: '#/parameters/term'
      - $ref: '#/parameters/language'
      consumes:
      - application/json
      responses:
        '201':
          description: Created.
        default:
          description: Error response.
          schema:
            $ref: '#/definitions/APIError'
      x-ms-examples:
        Add Term request:
          $ref: ../v1.0/examples/AddTermResource.JSON
      produces:
      - application/json
      summary: Microsoft Azure Post Contentmoderator Lists 0 Termlists Listid Terms Term
    delete:
      tags:
      - ListManagementTerm
      operationId: microsoftAzureListmanagementtermDeleteterm
      description: Deletes a term from the list with listId equal to the passed list ID.
      parameters:
      - $ref: '#/parameters/listId'
      - $ref: '#/parameters/term'
      - $ref: '#/parameters/language'
      responses:
        '204':
          description: No content.
          schema:
            type: string
        default:
          description: Error response.
          schema:
            $ref: '#/definitions/APIError'
      x-ms-examples:
        Delete Term request:
          $ref: ../v1.0/examples/DeleteTermResource.JSON
      produces:
      - application/json
      summary: Microsoft Azure Delete Contentmoderator Lists 0 Termlists Listid Terms Term
  /contentmoderator/lists/v1.0/termlists/{listId}/terms:
    get:
      tags:
      - ListManagementTerm
      operationId: microsoftAzureListmanagementtermGetallterms
      description: Gets all terms from the list with listId equal to the passed list ID.
      parameters:
      - $ref: '#/parameters/listId'
      - $ref: '#/parameters/language'
      - name: offset
        in: query
        description: Pagination start index.
        required: false
        type: integer
      - name: limit
        in: query
        description: Maximum number.
        required: false
        type: integer
      responses:
        '200':
          description: OK.
          schema:
            $ref: '#/definitions/Terms'
        default:
          description: Error response.
          schema:
            $ref: '#/definitions/APIError'
      x-ms-examples:
        Get All Terms request:
          $ref: ../v1.0/examples/GetAllTermsResource.JSON
      produces:
      - application/json
      summary: Microsoft Azure Get Contentmoderator Lists 0 Termlists Listid Terms
    delete:
      tags:
      - ListManagementTerm
      operationId: microsoftAzureListmanagementtermDeleteallterms
      description: Deletes all terms from the list with listId equal to the passed list ID.
      parameters:
      - $ref: '#/parameters/listId'
      - $ref: '#/parameters/language'
      responses:
        '204':
          description: No content.
          schema:
            type: string
        default:
          description: Error response.
          schema:
            $ref: '#/definitions/APIError'
      x-ms-examples:
        Delete AllTerms request:
          $ref: ../v1.0/examples/DeleteAllTermsResource.JSON
      produces:
      - application/json
      summary: Microsoft Azure Delete Contentmoderator Lists 0 Termlists Listid Terms
definitions:
  APIError:
    type: object
    description: Error information that the API returns.
    properties:
      Error:
        $ref: '#/definitions/Error'
  Terms:
    description: Term properties.
    properties:
      Data:
        description: Term data details.
        $ref: '#/definitions/TermsData'
      Paging:
        description: Paging details.
        properties:
          Total:
            description: Total details.
            type: integer
          Limit:
            description: Limit details.
            type: integer
          Offset:
            description: Offset details.
            type: integer
          Returned:
            description: Returned text details.
            type: integer
  TermsData:
    description: All term ID response properties.
    properties:
      Language:
        description: Language of the terms.
        type: string
      Terms:
        description: List of terms.
        type: array
        items:
          $ref: '#/definitions/TermsInList'
      Status:
        description: Term status.
        type: object
        $ref: '#/definitions/Status'
      TrackingId:
        description: Tracking ID.
        type: string
  Status:
    description: Status properties.
    properties:
      Code:
        description: Status code.
        type: integer
      Description:
        description: Status description.
        type: string
      Exception:
        description: Exception status.
        type: string
  TermsInList:
    description: Terms in the passed list ID.
    properties:
      Term:
        description: Added term details.
        type: string
  Error:
    type: object
    description: Error body.
    properties:
      Code:
        type: string
      Message:
        type: string
parameters:
  term:
    name: term
    in: path
    description: Term to be deleted
    required: true
    type: string
    x-ms-parameter-location: method
  language:
    name: language
    in: query
    description: Language of the terms.
    required: true
    type: string
    x-ms-parameter-location: method
  listId:
    name: listId
    in: path
    description: List ID of the image list.
    required: true
    type: string
    x-ms-parameter-location: method
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
