openapi: 3.2.0
info:
  title: Microsoft Azure AttestationClient OpenID Metadata Discovery…
  description: Describes the interface for the per-tenant enclave service.
  version: 2022-09-01-preview
tags:
- name: OpenID Metadata Discovery
paths:
  /certs:
    get:
      tags:
      - OpenID Metadata Discovery
      summary: Microsoft Azure Retrieves The Attestation Signing Keys In Use By The…
      description: Retrieves metadata signing certificates in use by the attestation service
      operationId: microsoftAzureSigningcertificatesGet
      responses:
        '200':
          description: Success
          content:
            application/jwk+json:
              schema:
                $ref: ../../../../../common-types/rfcs/rfc7517.json#/definitions/JSONWebKeySet
            application/json:
              schema:
                $ref: ../../../../../common-types/rfcs/rfc7517.json#/definitions/JSONWebKeySet
        default:
          description: Error response describing why the operation failed
          content:
            application/jwk+json:
              schema:
                $ref: '#/components/schemas/CloudError'
            application/json:
              schema:
                $ref: '#/components/schemas/CloudError'
      x-ms-examples:
        Get Token Signing Certificates:
          $ref: ./examples/Get_Certs.json
  /.well-known/openid-configuration:
    get:
      tags:
      - OpenID Metadata Discovery
      summary: Microsoft Azure Retrieves The Openid Configuration Data For The Azure…
      description: Retrieves metadata about the attestation signing keys in use by the attestation service
      operationId: microsoftAzureMetadataconfigurationGet
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenIDConfigurationResponse'
        default:
          description: Error response describing why the operation failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CloudError'
      x-ms-examples:
        Get OpenID Metadata:
          $ref: ./examples/Get_MetadataConfiguration.json
components:
  schemas:
    CloudError:
      x-ms-external: true
      properties:
        error:
          $ref: '#/components/schemas/CloudErrorBody'
      description: An error response from Attestation.
    CloudErrorBody:
      x-ms-external: true
      properties:
        code:
          type: string
          description: An identifier for the error. Codes are invariant and are intended to be consumed programmatically.
        message:
          type: string
          description: A message describing the error, intended to be suitable for displaying in a user interface.
      description: An error response from Attestation.
    OpenIDConfigurationResponse:
      type: object
      description: The response to the OpenID metadata description document API
      properties:
        response_types_supported:
          description: Types supported in the OpenID metadata API
          type: array
          items:
            type: string
        id_token_signing_alg_values_supported:
          description: List of the supported signing algorithms
          type: array
          items:
            type: string
        revocation_endpoint:
          description: Revocation endpoint
          type: string
        issuer:
          description: Issuer tenant base endpoint
          type: string
        jwks_uri:
          description: The URI to retrieve the signing keys
          type: string
        claims_supported:
          description: Set of claims supported by the OpenID metadata endpoint
          type: array
          items:
            type: string
  securitySchemes:
    azure_auth:
      type: oauth2
      flows:
        implicit:
          scopes:
            user_impersonation: impersonate your user account
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
      description: Azure Active Directory OAuth2 Flow
x-ms-parameterized-host:
  hostTemplate: '{instanceUrl}'
  useSchemePrefix: false
  parameters:
  - name: instanceUrl
    x-ms-parameter-location: client
    description: The attestation instance base URI, for example https://mytenant.attest.azure.net.
    required: true
    type: string
    in: path
    x-ms-skip-url-encoding: true
